### ISSUE TITLE
Group 节点自定义properties 子属性为对象时拖拽group 节点报错

### ISSUE THREAD

**Issue by TTTTTTTZL** [didi/LogicFlow#1003]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
    Group 节点自定义属性properties 中初始化一个属性对象
`
properties: {
 b: { b: 1 }
}
`
2. 期望的表现
 不会在控制台报错，且group 节点缩放过程中其边上的锚点正常跟随
3. 实际的表现
<img width="506" alt="image" src="https://user-images.githubusercontent.com/23022134/215996304-8d991f41-9be9-4012-b9c8-778a5e6a86fa.png">

**最简复现demo**  
demo：
链接：https://codesandbox.io/s/confident-https-pjh964?file=/src/components/HelloWorld.vue

步骤：
1. 两个节点相连接
2. 缩放group 节点
3. 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/23022134/215997084-51f01677-b37a-4e0e-a11a-70c25c30324c.png">

**Comment by towersxu** [comment]
目前看起来是LogicFlow的示例不能直接赋值给vue3中的ref.value。参考[https://github.com/didi/LogicFlow/issues/837#issuecomment-1421934654](https://github.com/didi/LogicFlow/issues/837#issuecomment-1421934654)中的解决办法，可以使用`toRaw(lf.value).render`解决这个问题。
