### ISSUE TITLE
同时选中分组和分组内部的节点，会出现分组内部的节点移动距离错误的问题

### ISSUE THREAD

**Issue by chengjiashuai** [didi/LogicFlow#1004]

**Comment by towersxu** [comment]
目前我们这边没有复现这个问题，请提供在线示例方便我们定位问题。

**Comment by chengjiashuai** [comment]
在官方示例中复现了
复现步骤：
1.配置多选按键multipleSelectKey: "alt"
2.通过多选按键，选中分组内的节点和分组
3.移动选区

在线示例
https://codesandbox.io/s/logicflow-base24-forked-0mxqwj?file=/step_24_group/index.js

**Comment by chengjiashuai** [comment]
> 目前我们这边没有复现这个问题，请提供在线示例方便我们定位问题。

在官网示例中就可以复现

**Comment by towersxu** [comment]
感谢，复现了。同时选中分组和分组内部的节点，会出现分组内部的节点移动距离错乱的问题。这个问题我们下个版本修复。

**Comment by towersxu** [comment]
已在[1.2.0-next.3](https://www.npmjs.com/package/@logicflow/core/v/1.2.0-next.3)版本修复
