### ISSUE TITLE
README内容有误

### ISSUE THREAD

**Issue by yyISACoder** [didi/LogicFlow#1005]
**问题描述**  
路径：master/packages/core/src/README.md，该文档存在内容错误

期望的表现
`packages/core` 帮助我们快速构建流程图编辑器
实际的表现
`packages/core` 帮助我们快速快建流程图编辑器

很小的一个问题，想着还是提一个issue吧，哈哈

**Comment by towersxu** [comment]
哈哈哈，很小的问题也算问题，欢迎直接PR。

**Comment by yyISACoder** [comment]
嗯嗯，好的
