### ISSUE TITLE
[设置"bezier" 类型的edge，连接两个node后，随意拖动节点，edge不会主动吸附node上的锚点]

### ISSUE THREAD

**Issue by xingzilong** [didi/LogicFlow#1010]
vue3+ts环境
问题：设置"bezier" 类型的edge，连接两个node后，随意拖动节点，edge不会主动吸附node上的锚点，而且报错！
               设置其他类型的edge后，edge会主动吸附node上的锚点

![屏幕截图 2023-02-11 004653](https://user-images.githubusercontent.com/71997098/218148388-706d4657-bc5c-456d-a6ec-9c19338ebf11.png)

上述问题如是我代码不当引起的，非常抱歉，因此打扰。
如问题确实存在是属于正常还是非正常呢？

**Comment by scoolor** [comment]
我也遇到了，看起来是bug，换成 LineEdge 就不报错了

**Comment by towersxu** [comment]
@xingzilong @scoolor 可以参考这里的解决办法https://github.com/didi/LogicFlow/issues/837#issuecomment-1421934654

**Comment by xingzilong** [comment]
> @xingzilong @scoolor 可以参考这里的解决办法[#837 （评论）](https://github.com/didi/LogicFlow/issues/837#issuecomment-1421934654)

多谢，问题得到了解决，只是具体是什么原因导致了此问题呢？
