### ISSUE TITLE
[Bug report]  InsertNodeInPolyline 在多条件的节点后插入节点 ，targetId未完全更新

### ISSUE THREAD

**Issue by sswflingling** [didi/LogicFlow#1013]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
![19ac83f38864a59307347a561028840](https://user-images.githubusercontent.com/44767675/219327466-43a04de4-65af-4236-9219-7faa94b69df3.png)
![image](https://user-images.githubusercontent.com/44767675/219327577-f96f5785-31cb-4db2-be3d-1bdb99a20a32.png)

InsertNodeInPolyline方法在多条件的节点后插入节点 ，左侧的三个节点targetId目前还是指向结束节点id, 正常要指向新增节点的id。
2. 期望的表现
左侧的三个节点连接线targetId要指向新增节点的id。
3. 实际的表现
左侧的三个节点连接线 只有一条线更新了targetId

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 在任意在线编码平台，编写示例如[codesanbox](https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js)。将其保存到自己空间，然后贴上链接。
2. 在自己github中创建一个最简单的示例，然后贴上github链接。
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by towersxu** [comment]
我想了一下，此问题暂时不修复了。如果允许节点插入连线时出现同时插入多根连线，可能并不是用户的预期行为。你可以改成交互优化来解决这个问题，例如当节点插入连线后，将这个节点连线的前后连线展示动画。这样也能给用户提示出只插入了一条连线。
