### ISSUE TITLE
通过selectElementById方法选中节点，默认会将节点置顶，包括分组节点，如何避免分组节点的置顶处理

### ISSUE THREAD

**Issue by chengjiashuai** [didi/LogicFlow#1016]

**Comment by towersxu** [comment]
selectElementById这个API是不会触发节点置顶的。目前分组会在选中时放置到其他分组上面，但是保持在所有非分组节点后面，包括属于其他分组的节点。

**Comment by chengjiashuai** [comment]
@towersxu 我当前使用版本是1.1.31，看到的selectElementById这个API是有toFront参数的，并且默认为true，我必须手动传入false才行

**Comment by towersxu** [comment]
确实，是我看错地方了。那你手动传入false能解决你的问题吗？

**Comment by chengjiashuai** [comment]
@towersxu 目前解决了，只是需要我对分组节点做一下判断处理，所以看看后续能不能再优化一下

**Comment by towersxu** [comment]
这个API这里不会优化，因为正常情况下就是需要将选中的节点设置为顶部。如果你不想要这种聚合的功能，可以使用`lf.graphModel.selectElementById` @chengjiashuai
