### ISSUE TITLE
关于virtual 虚拟节点的问题

### ISSUE THREAD

**Issue by Waym1ng** [didi/LogicFlow#1022]
在这个示例中 
![a022edcdf58ca6c59eb54f4e67ecfcb](https://user-images.githubusercontent.com/49272616/221521091-c22a262d-9729-4f33-92bb-6edff5395ee3.png)
导出的数据：
![f13539d7d92b7be48d0ffb9c3301cc3](https://user-images.githubusercontent.com/49272616/221521183-d05bc39c-bb00-48a9-bf42-fdd4a8708264.png)

描述：
这里把三个文本的virtual设为true了，在导出的数据中，nodes数组里确实没有了这三个文本元素，但是在children里还会有它们的id，似乎没有考虑到分组子节点是不是虚拟节点。

**Comment by towersxu** [comment]
这里确实是一个BUG，分组的children不应该包括虚拟节点

**Comment by towersxu** [comment]
感谢提出，已在1.2.3版本修复。
