### ISSUE TITLE
锚点事件

### ISSUE THREAD

**Issue by xingzilong** [didi/LogicFlow#1024]
场景：我在node节点右键的自定义菜单上设置了一个选项”连线“，点击这个”连线“，可以从node的锚点上扯出一条edge去连接其他node。

实际上，现在node上的锚点可以点击进行拖拽连线。我想以上述的场景实现从node的锚点扯出一条edge来。我想问一下是存在相对应的锚点的点击事件吗？
（实际上我现已经实现了上述的场景，是使用addEdge()做到的，但是有点生硬，并且没有和使用锚点拖拽一样的动画，一条edge是被立刻渲染出来的）

**Comment by towersxu** [comment]
你想要实现的是bpmn-js中的那种通过点击箭头出现连线的交互吗？我们目前确实不支持。这种交互的问题是点击后鼠标已经松开，而在目前大多数流程图的产品中，就是通过鼠标松开来 **确认连接**，所以我们并没有支持前者的交互。但是由于LogicFlow的插件机制开放了操作DOM的权限，理论上svg能实现的功能，都可以通过自定义插件来实现。如果你一定想要实现类似的交互，可以从自定义插件入手，自己利用svg来实现。

**Comment by xingzilong** [comment]
感谢解答，我描述的场景的确和bpmn-js中的那种通过点击箭头出现连线的交互非常相似（或者说就是那样的），接下来我会尝试着使用插件的方式去实现。
（这是我通过node:click和addEdge()方法实现的，总感觉不是那么的优雅）

https://user-images.githubusercontent.com/71997098/222040915-c433836f-e677-42af-9112-f62ee1e9ad1b.mp4

**Comment by towersxu** [comment]
看了你的效果，感觉确实在节点不希望把锚点显示出来的情况下，使用bpmn-js这种交互确实更好。由于我这边精力问题，所以没时间弄这个插件，如果你那边做出来了，欢迎给我们PR。
