### ISSUE TITLE
[Bug report]  官方文档未更新、有些实例方法无法调用

### ISSUE THREAD

**Issue by zhang122622623** [didi/LogicFlow#1026]
官网提供的文档，没有及时更新，使用的最新版本，lf实例上有有些方法都没法使用，比如：

1、getNodeModel  无效=》  使用 [getNodeModelById](url)
2、removeEdge 无效 =》 使用 deleteEdge
3、getGraphData 无效 =》 使用 getGraphRawData
4、自定义edge颜色动态切换， this.stroke = "#f00" 无效 =>   this.style.stroke = "#f00"

使用版本：
    "@logicflow/core": "^1.1.31",
    "@logicflow/extension": "^1.1.31",

![1677811721413](https://user-images.githubusercontent.com/15811546/222619444-d4af22db-60e5-42c8-bb72-b8d1fa2f281c.png)
![1677811895827](https://user-images.githubusercontent.com/15811546/222619459-72bb9f6d-0de2-448e-882b-0e6267379edb.png)

期望能更新文档、方便使用~

**Comment by towersxu** [comment]
你这个文档是哪里看到的？目前最新文档地址为https://docs.logic-flow.cn/docs/#/zh/api/logicFlowApi
