### ISSUE TITLE
[Bug report]框选移动元素，线路不能追随

### ISSUE THREAD

**Issue by Oliwans** [didi/LogicFlow#1027]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 步骤描述：拖拽4个不同的节点到画布中，给其中2个连线，用框选功能框住其中2个移动
2. 期望：线路能够追随
3. 问题：线路不能追随

**最简复现demo**  
官方MVP版本即可复现
http://logic-flow.org/mvp/index.html

贴图
![image](https://user-images.githubusercontent.com/9619555/222681466-367eb7a7-bd85-4017-be0c-23ae8a56bf34.png)
![image](https://user-images.githubusercontent.com/9619555/222681357-787351c2-2e8e-49a9-8c38-aa419f9f1ec1.png)

**Comment by towersxu** [comment]
感谢提出，这个问题应该只是mvp示例的问题，目前的logicflow最新版本已经没有这个问题。mvp示例问题我们稍后修复，你仍然可以先正常使用logicflow。

**Comment by Oliwans** [comment]
> 感谢提出，这个问题应该只是mvp示例的问题，目前的logicflow最新版本已经没有这个问题。mvp示例问题我们稍后修复，你仍然可以先正常使用logicflow。

我在本地使用的1.2.0-next4版本，本地可以线路追随，但是打包发布到线上还是有同样的问题，不知道是否是我这边打包的问题

**Comment by towersxu** [comment]
目前没有排查到哪里的问题，你可以先试试改成script方式引入插件。

**Comment by towersxu** [comment]
感谢提出，已在1.2.3版本修复。
