### ISSUE TITLE
[Bug report] 选择React自定义节点，按下 Backspace 键无法删除节点

### ISSUE THREAD

**Issue by eryoutu** [didi/LogicFlow#1029]
**问题描述**  
1. 问题触发的条件
- 版本：`"react": "^17.0.2"` + `"@logicflow/core": "^1.1.31"`
- 步骤：
  - 添加多个自定义React节点、开启快捷键
  - 进入页面，点击**第一个节点**选中，按下Backspace 键，节点**不会被删除**【应该是`container`的`keydown`事件未响应】
- 注：
  - 前`n-1`节点第一次进入都是这样的表现，且**节点的`outline`也是亮一下又灭了**。最后一个节点是正常的
  - 如果点击之后，重复再点击一次，恢复正常

3. 期望的表现
节点都能够正常删除

5. 实际的表现
节点不会被删除
![image](https://user-images.githubusercontent.com/43194472/223083075-4e8a28eb-3af4-4655-9b10-ba26c092c1f7.png)

**最简复现demo**  
https://codesandbox.io/s/react-html-node-keydown-lcl1yc?file=/src/App.js

**Comment by towersxu** [comment]
此问题将在1.2.0-next.5版本修复。
