### ISSUE TITLE
根据官方提供的实现BPMN边界事件节点操作中发现，功能只能在面板没有开启网格可以正常使用，开启网格就失效了

### ISSUE THREAD

**Issue by xiongyachuan** [didi/LogicFlow#1031]
根据官方提供的实现BPMN边界事件节点操作中发现，功能只能在面板没有开启网格可以正常使用，开启网格就失效了
**问题描述** 
1. 开启网格显示就会功能就会失效

**最简复现demo**  
我会把项目打包上传，在LF.vue 文件中搜索 开启网格功能 注释  将那几行代码注释解开，就会导出两个图元叠加失去效果，我上传的是功能可以正常实现，麻烦你们运行之后把我注释的解开 看问题点

正常的效果

![1678257859457](https://user-images.githubusercontent.com/91184124/223639014-5a2838e4-c329-4a09-84ae-47c516278822.jpg)

失败的案例，开启网格之后功能就失效了

![1678257987847](https://user-images.githubusercontent.com/91184124/223639410-7d031db8-8730-48dc-9597-39eed43bd272.jpg)

代码位置：

![1678258054904](https://user-images.githubusercontent.com/91184124/223639713-ee44bb48-5935-49a7-89b5-c35868abde8b.jpg)

包已上传
[logicflow_vue_demo-master.zip](https://github.com/didi/LogicFlow/files/10918023/logicflow_vue_demo-master.zip)

**Comment by towersxu** [comment]
这个是因为grid默认是20，所以会保持所有的节点在放下的时候中心点在格子上。而示例中是通过边界事件节点的位置是否与节点边的距离小于10来判断是否可以吸附。在grid为20的时候就会出现永远不可能为10。有两种修改办法，一种办法是将grid大小改成10；另一种办法是将距离小于10的改成15或者更大。
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/4093984/223653125-7d2861b4-5567-410b-a054-b46c718028a1.png">
