### ISSUE TITLE
Error: <path> attribute d: Expected number, "… 265.5-10\n      L507 255.5 z".

### ISSUE THREAD

**Issue by 15738848982** [didi/LogicFlow#1032]
使用该组件时控制台会报异常，但是不知道是什么原因
![image](https://user-images.githubusercontent.com/117069643/223943156-0b179d9b-51f0-462c-9315-61c7c576a206.png)

**Comment by towersxu** [comment]
这个问题不好排查，有可能是坐标问题，你看看传入render的数据是否有小数点。

**Comment by 15738848982** [comment]
x、y轴坐标是有小数点的

**Comment by towersxu** [comment]
目前LogicFlow产生的数据应该都是整数形式，你是用的历史数据转换给LogicFlow渲染的吗？如果是，请先将这些数字取整。如果不是，请告知如何参数小数格式的数据。

**Comment by 15738848982** [comment]
已解决，将小数点取整就好了
