### ISSUE TITLE
[官网例子--基于 React 组件自定义边]没有内置箭头，重写getArrow方法也不行

### ISSUE THREAD

**Issue by xiaolanzi** [didi/LogicFlow#1033]
![image](https://user-images.githubusercontent.com/16741869/224245901-601f327a-a927-4b44-a02c-1c4e3b15fe6c.png)

建议如果不重写getArrow方法，可以默认在边的终点提供箭头指向，目前重写getArrow方法也不生效，下面是自己重写案例，
如果是我写的有问题，麻烦给个正确getArrow的写法
  getArrow() {   //官网提供的自定义的箭头例子
    const pathAttr = {
      stroke: 'red',
      strokeWidth: 2,
    };
    return h('g', {}, [
      h('path', {
        ...pathAttr,
        d: 'M 0 0 -10 -5 -10 5 z',
      }),
    ]);
  }，

**Comment by towersxu** [comment]
示例写得有点问题，现在已经更新文档了。不需要getArrow，而是要自定义边的时候，将model中的arrowConfig作为属性传给边。

```js
h("line", { ...lineData, ...edgeStyle, ...arrowConfig }),
```
