### ISSUE TITLE
[Bug report]当节点非常窄时，折线与长边会自动平行

### ISSUE THREAD

**Issue by xieqifei** [didi/LogicFlow#1035]
**问题描述**  
当节点非常窄时，折线与长边会自动平行。：
期望，在窄节点上折线不会自动与长边对齐。
是否有导出的函数可以直接修改这个属性？我尝试修改了edge的offset，无法实现我的期望目标。

![dcbba78eea111f0bdda14d2820445fb](https://user-images.githubusercontent.com/50683502/224446218-e613e77f-5f00-481e-84ae-0f047961560e.png)

**Comment by towersxu** [comment]
我记得有修复这个问题，你是用的多少版本？升级最新的试试
