### ISSUE TITLE
[基于 React 组件自定义边]官网例子继承了line自定义边，能否提供折线自定义边案例

### ISSUE THREAD

**Issue by xiaolanzi** [didi/LogicFlow#1036]
使用场景：节点自连，如果使用基于React组件自定义边，边为line的话，那么react组件的边文本就会非常靠近当前节点，并被覆盖一部分，建议支持折线，通过adjustEdge配置为true，可以让边文本和自连节点可以自动调整距离

如何改造getEdge方法画出polyline
class CustomEdgeView extends PolylineEdge{
       getEdge() {
             return h("g", {}, [
                 h("line")  //这里如何画出polyline
             ]
        }
}

疑问：自定义边文本是否能支持通过edgeTextDraggable配置实现拖拽，目前好像不支持

期待效果图：
![image](https://user-images.githubusercontent.com/16741869/224592372-c0512720-3d8e-4876-a464-07d2486cc445.png)

**Comment by towersxu** [comment]
自定义边需要了解一定的svg相关知识，你可以直接参考svg的polyline来做。model中有提供属性去控制文本是否可以拖动。
