### ISSUE TITLE
LogicFlow 实例不能存储在recoil原子中

### ISSUE THREAD

**Issue by xianyulli** [didi/LogicFlow#1038]
**问题描述**  
LogicFlow 实例不能存储在recoil原子中
1. 问题触发的条件
  初始化 
  
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/73095124/224664359-ba4c013b-b279-4899-8fa7-e960c0876b9e.png">

地址： https://codesandbox.io/s/exciting-zeh-d4qj35?file=/src/App.tsx

2. 期望的表现
  能否正常被存储
3. 实际的表现
  不能存储

**Comment by towersxu** [comment]
我对recoil不了解，请问为什么需要将LogicFlow实例存储到recoil原子中？我看注释掉也是可以运行的。https://codesandbox.io/s/confident-cloud-29fv6i?file=/src/App.tsx

**Comment by xianyulli** [comment]
> 
项目使用recoil来做状态管理，方便在其他组件中使用logicflow实例

**Comment by towersxu** [comment]
参考这个[Recoil#406](https://github.com/facebookexperimental/Recoil/issues/406)，可以使用`dangerouslyAllowMutability`来解决这个问题。https://codesandbox.io/s/confident-cloud-29fv6i?file=/src/store/store.ts
