### ISSUE TITLE
是否支持自定义折线的拐点？

### ISSUE THREAD

**Issue by zhanglei518** [didi/LogicFlow#1043]
**问题描述**：自定义锚点在手动连线创建边的时候监听  anchor:drop 事件，成功后先删除原有边，然后调用addEdge方法生成新的边，传参中根据业务规则自定义pointsList（数组中写了多个拐点），
**期望结果**：根据自订的pointsList中的点渲染边
**实际结果**：无效。。。

在自定义边中通过getData方式修改pointsList同样无效。。版本为1.1.31，所以是否支持自定义拐点？

**Comment by towersxu** [comment]
请带上示例，在addEdge的时候，传入pointsList、startPoint、endPoint应该是可以的。

**Comment by zhanglei518** [comment]
> 请带上示例，在addEdge的时候，传入pointsList、startPoint、endPoint应该是可以的。

eventCenter.on('anchor:drop', async ({ data, edgeModel }) => {
    // 删除旧边
    state.lf?.deleteEdge(edgeModel.id);
    // 生成新pointsList，
    const newPointsList = [
      edgeModel.startPoint,
      {
        x: edgeModel.startPoint.x + 50,
        y: edgeModel.startPoint.y,
      },
      {
        x: edgeModel.endPoint.x - 50,
        y: edgeModel.endPoint.y,
      },
      edgeModel.endPoint,
    ];
    // 添加边
    state.lf?.addEdge({
      type: edgeModel.type,
      sourceNodeId: edgeModel.sourceNodeId,
      targetNodeId: edgeModel.targetNodeId,
      sourceAnchorId: edgeModel.sourceAnchorId,
      targetAnchorId: edgeModel.targetAnchorId,
      startPoint: edgeModel.startPoint,
      endPoint: edgeModel.endPoint,
      pointsList: newPointsList,
    });
  });
如上，我理解的也很简单，但是实现起来就是 不行，并且控制台报错如图：
![image](https://user-images.githubusercontent.com/21114634/225222720-1255c99a-9863-41f3-bc93-805dd4a68b6c.png)
我也检查了坐标应该都是整数

**Comment by HTML110** [comment]
> 请带上示例，在addEdge的时候，传入pointsList、startPoint、endPoint应该是可以的。

大哥 我看官网上没有说pointsList 这个参数啊
