### ISSUE TITLE
[Bug report] 节点双击偶现不触发node:dbclick事件

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#1045]
在双击节点时，正常会触发node:dbclick事件。最近扩充画布上节点的数量后，发现双击极少情况下没触发dbclick事件（不确定是不是画布节点数量太多导致的）。

``` javascript
  handleClick = (e: MouseEvent) => {
    // 节点拖拽进画布之后，不触发click事件相关emit
    // 点拖拽进画布没有触发mousedown事件，没有startTime，用这个值做区分
    if (!this.startTime) return;
    const time = new Date().getTime() - this.startTime;
    if (time > 200) return; // 事件大于200ms，认为是拖拽, 不触发click事件。
    const { model, graphModel } = this.props;
    // 节点数据，多为事件对象数据抛出
    const nodeData = model.getData();
    const position = graphModel.getPointByClient({
      x: e.clientX,
      y: e.clientY,
    });
```

节点的点击事件有上面的处理逻辑，handleClick中可能会emit node:dbclick事件。但是会有if (time > 200) return; 限制。
经调试，发现偶尔双击会出现time > 200的情况出现，导致没触发node:dbclick事件。但是直接监听节点对应html元素的dbclick事件，是能触发的。

请问这里的node:dbclick为啥不是监听<g class="lf-node"/>元素的dbclick，而是在click中去处理呢？

**Comment by towersxu** [comment]
dbclick和click一起处理是为了避免双击触发两次单击。

**Comment by wangzhengbo** [comment]
> dbclick和click一起处理是为了避免双击触发两次单击。

这个我觉得可以优化下。因为从用户的角度来看，双击了但没有效果，会认为是有bug。而且原生的dbclick事件实际上已经触发。
