### ISSUE TITLE
期望可以内置一个支持画布一键【全屏】的功能。

### ISSUE THREAD

**Issue by ZhangChongLing** [didi/LogicFlow#1049]
期望可以内置一个支持画布一键【全屏】的功能。

**Comment by towersxu** [comment]
【全屏】功能目前没打算内置，因为如果节点面板是自定义在画布之外的话，全屏功能可能无法包括这部分。建议参考[MDN 全屏API](https://developer.mozilla.org/zh-CN/docs/web/api/fullscreen_api)自定义即可。

**Comment by ZhangChongLing** [comment]
请放心，您的邮件已收到。
