### ISSUE TITLE
如何在BPMN插件中创建新的组件呢？

### ISSUE THREAD

**Issue by leeggco** [didi/LogicFlow#1050]
BPMN 默认只有互斥网关，我希望增加个并行网关，但是没有头绪，有文档可以参考吗？

**Comment by towersxu** [comment]
我们建议在实际业务中完全自定义BPMN插件，而不是使用LogicFlow内置的bpmn插件。所以你可以参考[bpmn插件源码](https://github.com/didi/LogicFlow/tree/master/packages/extension/src/bpmn),
[bpmn数据适配器源码](https://github.com/didi/LogicFlow/tree/master/packages/extension/src/bpmn-adapter)，将上面的代码复制到你们本地项目中进行开发。这样的好处是所有的bpmn相关的业务逻辑都可以在项目中体验，以后有任何扩展也可以满足。
