### ISSUE TITLE
Typescript类型问题

### ISSUE THREAD

**Issue by HodgeWen** [didi/LogicFlow#1052]
**问题描述**  
在配置主题时, 使用@logicflow/core/types/constant/DefaultTheme文件中导出的Theme类型作为注解, 该类型中包含了一些可以改变图形大小的属性, 这与文档并不相符, 实测也并不生效

这是rect类型的定义:

![image](https://user-images.githubusercontent.com/30290407/227172765-d740f111-58e4-4fcb-96e0-69e794585173.png)

**Comment by towersxu** [comment]
感谢提出，已在1.2.2版本修复
