### ISSUE TITLE
[Bug report] 版本1.1.31，静默模式下，连线可以拖动锚点重连

### ISSUE THREAD

**Issue by chg122345** [didi/LogicFlow#1055]
**问题描述**  
版本1.1.31，静默模式下，连线可以拖动锚点重连

**Comment by muyuanshan** [comment]
1. 在初始化过程中，静默模式开始，并且`adjustEdgeStartAndEnd` 为`true`，线的锚点是可以拖动的。因为在静默模式下可以单独开启某些功能，如果不想要开启，不配置这个功能对应的字段即可，删除`adjustEdgeStartAndEnd` 或该字段置为`false`。
2. 如果你的`isSilentMode`是`isSilentMode: flag`这种用变量控制的，`adjustEdgeStartAndEnd: !flag` 也能实现。
希望可以帮到你
