### ISSUE TITLE
在重写连接线样式后，Vue3自定义组件相连后，拖动组件连接线不会跟随。

### ISSUE THREAD

**Issue by psrheartache** [didi/LogicFlow#1056]
**问题描述**  
在FlowLink.ts重写连接线样式后，Vue3自定义组件相连后，拖动组件连接线不会跟随。
问题截图：（重写连接线样式后）
<img width="990" alt="image" src="https://user-images.githubusercontent.com/13062319/228112561-a4c9eb36-fc6e-4108-8b3d-d17f807600dd.png">

注册挂载：
<img width="586" alt="image" src="https://user-images.githubusercontent.com/13062319/228112690-6b232c1d-66a9-4eab-a6b8-ade378a7385d.png">

初始连接：
![image](https://user-images.githubusercontent.com/13062319/228112305-b5d67276-aa7a-4140-9e25-c7f6051645ff.png)

拖拽组件后：
![image](https://user-images.githubusercontent.com/13062319/228112357-fb2dd269-182d-4525-84a3-2247f0e3da27.png)

期望效果：（连击后拖拽组件自动跟随）

初始连接：
![image](https://user-images.githubusercontent.com/13062319/228112016-51fec00f-121e-428d-8ace-b79339d8941b.png)

拖拽组件后：
![image](https://user-images.githubusercontent.com/13062319/228111912-5bae9257-91c1-4150-b82e-630c3406a77c.png)

**最简复现demo**  
[MvpDemo地址：](https://github.com/psrheartache/didi-Logic-Flow-Demo-Vue3-Ts)

**Comment by 15738848982** [comment]
请问大佬解决了嘛？

**Comment by towersxu** [comment]
最近事情有点多，明天再看~

**Comment by psrheartache** [comment]
> 请问大佬解决了嘛？

没时间看LF库源码，copy的官网red3示例代码， 那个里面是好的，
我这个mvp demo里面有问题， 你也遇到了吗？

**Comment by psrheartache** [comment]
> 

麻烦大佬了。

**Comment by psrheartache** [comment]
> 最近事情有点多，明天再看~

麻烦大佬了。

**Comment by towersxu** [comment]
@psrheartache @15738848982 参考https://github.com/didi/LogicFlow/issues/837 ，目前LogicFlow bezier曲线和vue3兼容有点问题，这里需要先调用vue的`toRow`然后再`render`。

**Comment by psrheartache** [comment]
> 

感谢🙏 已解决。

**Comment by psrheartache** [comment]
> 请问大佬解决了嘛？

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/13062319/229088227-8fedc2cf-d5dc-4212-8d4e-eff32665f673.png">

import { toRaw } from 'vue'

lfRaw = toRaw(lf.value)
lfRaw.render()

解决。
