### ISSUE TITLE
页面初始化时报错

### ISSUE THREAD

**Issue by 15738848982** [didi/LogicFlow#1057]
页面初始化报错，因为是组件库里面的代码所以找起来比较麻烦。目前使用版本是1.1.30版本
![image](https://user-images.githubusercontent.com/117069643/228147794-250f703d-1d41-4788-ba67-cce8aee09d61.png)
![1679984972114](https://user-images.githubusercontent.com/117069643/228147882-0ed98ba7-24f3-46c2-8c67-6d8530142701.jpg)

**Comment by towersxu** [comment]
你好，能提供可运行示例代码吗？目前我们这边没有复现这个问题。

**Comment by 15738848982** [comment]
这个是页面初始化代码
![image](https://user-images.githubusercontent.com/117069643/228149708-503b4ceb-5fd4-43c9-9c70-7df0d7b869ed.png)
初始化结束之后获取数据然后给render赋值
![image](https://user-images.githubusercontent.com/117069643/228149989-3910d2e6-86d5-4558-90be-57c49c7da822.png)

**Comment by 15738848982** [comment]
这个是我注册动态节点的代码
![image](https://user-images.githubusercontent.com/117069643/228151479-9c8cf337-37be-4803-867f-eb0d076fbe37.png)

**Comment by 15738848982** [comment]
请问大佬，有办法解决嘛
