### ISSUE TITLE
如果把流程的内容转成规则有什么好的解决方案吗？

### ISSUE THREAD

**Issue by zixiaomuzhen** [didi/LogicFlow#1060]
目前规则引擎我们用的是drools，但是没有可视化的规则配置界面，所以想用logicflow。
想用logicflow生成规则文件，有没有豪的解决方案？有现成的代码可以参考或者插件吗？

**Comment by towersxu** [comment]
这个需要你自己实现logicflow格式与drools格式的相互转换。可以参考这个https://github.com/logic-flow/turbo-client，实现了logicflow与另一款开源引擎的数据转换。

**Comment by zixiaomuzhen** [comment]
> 这个需要你自己实现logicflow格式与drools格式的相互转换。可以参考这个https://github.com/logic-flow/turbo-client ，实现了logicflow与另一款开源引擎的数据转换。

感谢，我研究一下
