### ISSUE TITLE
[Bug report]isSilentMode静默模式不可用

### ISSUE THREAD

**Issue by wxpftd** [didi/LogicFlow#1061]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
https://docs.logic-flow.cn/docs/#/zh/guide/basic/silent-mode?id=%e9%9d%99%e9%bb%98%e6%a8%a1%e5%bc%8f
官方文档里给的在线示例，打开静默模式之后，也是可以编辑文字内容的

**Comment by towersxu** [comment]
感谢提出，示例有问题，已修复。
