### ISSUE TITLE
[ report]logicFlow是否能供 工作流BPMN设计中令牌模拟运行的功能 ?

### ISSUE THREAD

**Issue by pikachuWorld** [didi/LogicFlow#1062]
**问题描述**  
  1、   logicFlow是否能供 工作流BPMN设计中令牌模拟运行的功能   插件是npm install bpmn-js-token-simulation1. 
2.
官网并没有看到相关文档
 我看了一篇’揭秘 LogicFlow 的拓展机制文章 ：
LogicFlow 自己只是一个单纯的流程图编辑器，不带有业务属性。为了更好的易用性，咱们提供了 Bpmn-js 插件，让使用 bpmn-js 的项目可以快速替换。有了 Bpmn 插件后，直接经过 LogicFlow 装载 bpmn 插件，这个页面就表现成为 bpmn-js 了。
 import LogicFlow from '@logicflow/core';
import { Bpmn } from '@logicflow/extension';
LogicFlow.use(Bpmn);

我自己vue代码试看看效果，结果报错
![image](https://user-images.githubusercontent.com/21151422/228722563-0cae0f6f-f6d0-489c-ab62-08dc6b4138fc.png)
![image](https://user-images.githubusercontent.com/21151422/228722575-e21479b2-d706-45d9-80a5-64796fe04b8d.png)
![image](https://user-images.githubusercontent.com/21151422/228722758-95bf1992-9ca6-4a06-b0c4-1ba62e7c3333.png)

期望能实现工作流BPMN设计中令牌模拟运行的功能

**Comment by towersxu** [comment]
我们建议在实际业务中完全自定义BPMN插件，而不是使用LogicFlow内置的bpmn插件。所以你可以参考[bpmn插件源码](https://github.com/didi/LogicFlow/tree/master/packages/extension/src/bpmn),
[bpmn数据适配器源码](https://github.com/didi/LogicFlow/tree/master/packages/extension/src/bpmn-adapter)，将上面的代码复制到你们本地项目中进行开发。这样的好处是所有的bpmn相关的业务逻辑都可以在项目中体验，以后有任何扩展也可以满足。

**Comment by pikachuWorld** [comment]
> 我们建议在实际业务中完全自定义BPMN插件，而不是使用LogicFlow内置的bpmn插件。所以你可以参考[bpmn插件源码](https://github.com/didi/LogicFlow/tree/master/packages/extension/src/bpmn), [bpmn数据适配器源码](https://github.com/didi/LogicFlow/tree/master/packages/extension/src/bpmn-adapter)，将上面的代码复制到你们本地项目中进行开发。这样的好处是所有的bpmn相关的业务逻辑都可以在项目中体验，以后有任何扩展也可以满足。



> 我们建议在实际业务中完全自定义BPMN插件，而不是使用LogicFlow内置的bpmn插件。所以你可以参考[bpmn插件源码](https://github.com/didi/LogicFlow/tree/master/packages/extension/src/bpmn), [bpmn数据适配器源码](https://github.com/didi/LogicFlow/tree/master/packages/extension/src/bpmn-adapter)，将上面的代码复制到你们本地项目中进行开发。这样的好处是所有的bpmn相关的业务逻辑都可以在项目中体验，以后有任何扩展也可以满足。

好的，谢谢！
