### ISSUE TITLE
[Bug report] text文本节点清空内容后，不能选中、编辑和删除

### ISSUE THREAD

**Issue by zqy233** [didi/LogicFlow#1067]
**问题描述**  
1. 问题触发的条件
拖拽text node文本节点，清空文本节点内容
2. 期望的表现
可以再次选中节点，编辑或者删除
3. 实际的表现
节点文本清空后，不能再次选中（无论是选择框还是点击），所以不能编辑文本和删除节点
**最简复现demo**  
https://docs.logic-flow.cn/demo/dist/mvp/
官方demo中拖拽文本节点，删除文本节点内容
![image](https://user-images.githubusercontent.com/57588553/229408453-4a1cbf59-349f-4752-bc15-a8de3848dee6.png)

**Comment by towersxu** [comment]
此问题已修复，请使用1.2.6版本
