### ISSUE TITLE
[Bug report] lfXml2Json 方法转换结果存在问题

### ISSUE THREAD

**Issue by cpf23333** [didi/LogicFlow#1068]
[vue-project.zip](https://github.com/didi/LogicFlow/files/11135563/vue-project.zip)
实际代码在app.vue里
问题：usertTask中有一个bpmn:multiInstanceLoopCharacteristics标签，是空标签
但是import { lfXml2Json } from "@logicflow/extension";
lfXml2Json 方法转换出的对象里，userTask对象里只有id，没有这个标签

**Comment by wumail** [comment]
该问题在最新的版本中被修复了
