### ISSUE TITLE
[Bug report] node:click 事件在笔记本触摸板上不生效

### ISSUE THREAD

**Issue by jiangyuhao1996** [didi/LogicFlow#1071]
我按照官网注册了节点点击事件并打印结果，lf.on('node:click', e => {console.log(e)}),但是这个单机事件在笔记本触摸板上不触发，只在笔记本触摸板上双击事件才响应
![image](https://user-images.githubusercontent.com/75724231/229470730-3c71349b-5d26-4850-8e0a-8684b0d45518.png)

**Comment by boyongjiong** [comment]
#1465 已发版修复
