### ISSUE TITLE
建议-希望有操作画布的 api 

### ISSUE THREAD

**Issue by duansheli** [didi/LogicFlow#1075]
默认是 按住左键可以移动画布 

想要添加一些动作 
WASD 或者上下左右的方向键 可以移动画布 
按住 小键盘的 加号 减号  可以对画布进行 大小缩放 

目前最新版本 1.2.3 
文档中 有介绍 对节点进行  拓展 缩放的操作 
但没看到有 对画布的操作入口

**Comment by towersxu** [comment]
这个是支持的，对画布的放大缩小和移动属于[transformModel](https://docs.logic-flow.cn/docs/#/en/api/transformModelApi). 您可以通过`lf.graphModel.transformModel`获取到。
