### ISSUE TITLE
[图片导出]：当节点中有图片时，使用getSnapshot导出图片，图片节点为空

### ISSUE THREAD

**Issue by love666** [didi/LogicFlow#1076]
**问题描述**  
场景： 当节点中有图片时，使用getSnapshot导出图片，图片节点为空
如图：

![image](https://user-images.githubusercontent.com/34014343/230577322-cb4b1777-8c28-467f-9fc9-2987c6e8d3e5.png)

希望修复~

**Comment by love666** [comment]
目前图片使用base64确实可以，但是当流程图很复杂时，base64超级长，还是希望支持url模式

**Comment by towersxu** [comment]
目前没有好的办法解决这个问题，欢迎PR。此issue与 #477 重复，先关闭这个。
