### ISSUE TITLE
边上插入节点时是否可以应用自定义的连线规则

### ISSUE THREAD

**Issue by hongliangsam** [didi/LogicFlow#1078]
边上插入节点时，目前任意节点都能插入连线，定义了该节点的连线规则如getConnectedSourceRules、getConnectedTargetRules等在插入连线时并不做校验，这样给了用户出错的机会，是否可以优化

**Comment by hongliangsam** [comment]
@muyuanshan 在[1.2.5]更新中：修复了在边上插入节点未触发两边节点校验规则的问题。
该修改导致以下问题：
当定义节点校验规则为，只能允许一条连线输入，一条连线输出：
![image](https://github.com/didi/LogicFlow/assets/50320208/b57d0494-2ff3-44de-915f-9e930b3c6f66)

现在校验连线前后节点，在插入时，将触发连线前后节点校验规则，此时必定插入失败。逻辑上应该是插入成功的，因为插入后每个节点都是一进一出：
![image](https://github.com/didi/LogicFlow/assets/50320208/f2e5d859-aa26-418b-9d4b-1e99447aa012)

期望表现：
应该判断插入后的连线符合节点连线规则，就允许插入。手动使用锚点连线时表现一致。

**Comment by hongliangsam** [comment]
![image](https://github.com/didi/LogicFlow/assets/50320208/ad9a5c59-ec9d-4d17-aa2b-802e1488f24c)
项目地址：https://github.com/hongliangsam/logicflow_vue_insert_demo
@muyuanshan 请查看，谢谢

**Comment by wbccb** [comment]
这个bug能够再提供多些描述信息？是说`物料释放`无法连线插入到`物料输出`？ @hongliangsam

**Comment by boyongjiong** [comment]
因长时间未回复，先将本 issue 关闭处理，如仍有问题，可提供所需信息并重新打开

**Comment by hongliangsam** [comment]
> 这个bug能够再提供多些描述信息？是说`物料释放`无法连线插入到`物料输出`？ @hongliangsam

是【物料输出】无法插入到【获取物料】和【物料释放】之间。因为触发了【物料释放】节点的校验（但符合连线规则，应该可以插入才对）。
可复现项目如下，【酶标仪】之间插入两个【酶标仪】连线之间，正常期望是插入成功，但因为触发【酶标仪】节点校验，插入失败。项目地址：https://github.com/hongliangsam/logicflow_vue_insert_demo，烦请查看，非常感谢！
![image](https://github.com/didi/LogicFlow/assets/50320208/18169e61-4bdc-4469-bf09-46a10a307afb)

**Comment by wbccb** [comment]
😓[https://github.com/didi/LogicFlow/pull/1152](https://github.com/didi/LogicFlow/pull/1152)已经修复了这个问题，最新版本不会出现插入失败的情况
