### ISSUE TITLE
[Bug report] 在Vue3下, 当启用SelectionSelect时, 框选两个或以上的Node进行拖拽时, Edge会出现断连的情况

### ISSUE THREAD

**Issue by ZHBingo** [didi/LogicFlow#1080]
**问题描述**  
在Vue3下, 当启用SelectionSelect时, 框选两个或以上的Node进行拖拽时, Edge会出现断连的情况
在Vue2下, 同样的代码并不会出现这个问题

**Comment by towersxu** [comment]
先试试1.2.4版本是否已经解决这个问题。如果没有，可以试试https://github.com/didi/LogicFlow/issues/837

**Comment by ZHBingo** [comment]
更新到1.2.4, 问题解决, Bezier, Polyline都可以正常使用
