### ISSUE TITLE
在很宽的屏幕的电脑上面，浏览器的宽度达到一定程度，DAG画布会很卡，甚至让整个浏览器的TAB出现卡顿

### ISSUE THREAD

**Issue by Daemon1993** [didi/LogicFlow#1082]
**问题描述**  
hello，我这边使用发现一个问题，
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 比较宽的显示器，随着浏览器窗口宽度增加，DAG画布开始卡顿
2. 没有任何log,不知道具体是什么原因导致的卡顿，想请问下  代码逻辑上是否会出现这个情况，

**Comment by towersxu** [comment]
目前我这边并没有很好的复现办法，建议使用logicflow提供的codesandbox示例进行测试，确认一下会不会是项目的问题。若logicflow本身的示例也有问题，请提供示例在线地址、电脑型号，我这边会去寻找相关的设备进行测试。但是短期这种问题应该无法解决。
