### ISSUE TITLE
[Bug report] 两个节点产生连线，会在画布的背景中出现一条斜着的虚线

### ISSUE THREAD

**Issue by humengxiangfeng** [didi/LogicFlow#1083]
**问题描述**  
1. 问题触发的条件：两个节点连线生成边时便会出现
2. 期望的表现：不再出现该线条
3. 实际的表现：如下图所示，画布中有一条斜着的紫色的隔断的虚线
![image](https://user-images.githubusercontent.com/45894885/231038452-2cd505c0-fbba-4e4b-b2dc-4692e0bc9545.png)

**最简复现demo**  
以下为我本地代码，安装依赖后本地运行即可复现：
[bax_flow_rule_engine.zip](https://github.com/didi/LogicFlow/files/11195668/bax_flow_rule_engine.zip)

**Comment by towersxu** [comment]
您好，之前也没遇到过类似的问题，很有可能还是哪里代码有问题。我这边本周事情比较多，本周可能没时间详细排查这个问题。建议先确认一下，如果都不采用自定义节点和自定义连线，是否会出现这个问题；若出现，重新其一个空白项目看看是否会有问题（确认项目中是否有其他内容导致的冲突）；若不出现，则逐步增加自定义元素，缩放定位的范围。

**Comment by humengxiangfeng** [comment]
> 您好，之前也没遇到过类似的问题，很有可能还是哪里代码有问题。我这边本周事情比较多，本周可能没时间详细排查这个问题。建议先确认一下，如果都不采用自定义节点和自定义连线，是否会出现这个问题；若出现，重新其一个空白项目看看是否会有问题（确认项目中是否有其他内容导致的冲突）；若不出现，则逐步增加自定义元素，缩放定位的范围。

感谢回复，目前项目所有的节点均为继承自基础节点的自定义节点。文档示例并没有出现这种情况，我将逐步进行排查，查看是否自定义节点或者其他问题。谢谢

**Comment by humengxiangfeng** [comment]
最近研究发现，当画布背景改为"mesh"之后，虚线消失
由于业务已经修改没有回过头细究这个问题究竟是如何发生的，该问题可关闭，感谢！
