### ISSUE TITLE
建议添加自定义节点锚点文字展示功能

### ISSUE THREAD

**Issue by wxc0730** [didi/LogicFlow#1086]
**问题描述**  
1. 当前api并未提供锚点自定义文字展示功能
2. 期望官方能提供该功能使锚点可以展示文字

**Comment by towersxu** [comment]
LogicFlow提供了自定义锚点形状的功能`getAnchorShape`，理论上你可以在这上面实现仍和svg能实现的内容。你可以试试https://codesandbox.io/embed/logicflow-base15-ou2i0?fontsize=14&hidenavigation=1&theme=dark&view=preview
