### ISSUE TITLE
[Bug report]自定义HTML节点文本编辑框里面的文字看不见

### ISSUE THREAD

**Issue by huzhigao** [didi/LogicFlow#1087]
![image](https://user-images.githubusercontent.com/20855389/231692619-cebe7d48-9c45-4976-a346-f3a839d044f6.png)
![image](https://user-images.githubusercontent.com/20855389/231692902-6d3fce74-edd2-4c52-83da-12b12ccfe5b6.png)
![image](https://user-images.githubusercontent.com/20855389/231693409-e49c34ca-63c5-46f7-827c-211a1842dd2d.png)
双击节点文本，文本颜色是白色的，导致看不见

**Comment by towersxu** [comment]
你可以用css覆盖一下，将文本编辑状态的字体样式设置为其他演示。

**Comment by huzhigao** [comment]
好的 我试一下

**Comment by huzhigao** [comment]
文档里没找到文本编辑状态的字体样式设置的地方，可以具体讲一下吗
