### ISSUE TITLE
vue中删除连线报错

### ISSUE THREAD

**Issue by RandallYin1** [didi/LogicFlow#1088]
**问题描述**  

1. 问题触发的条件
自定义键盘事件["backSpace"]之后，在回调中使用(lf.deleteEdge)和(lf.deleteNode)删除元素
步骤:
先随意创建三个以上的nodes
①node1链接node2；
②node2链接node3；
③node3链接node4;
④然后删除node1与node2之间的连线;
控制台报错，且此时实例中lf.edges中会出现两个相同ID的item
3. 期望的表现
正常删除
4. 实际的表现
删除第一个连线需要按一次BackSpace，删除下一个需要按两次，再删下一个需要按三次，以此类推

![1681373559934](https://user-images.githubusercontent.com/125436292/231696955-864accd7-1376-4670-b342-22eac1eacc66.png)

在删除第一条线之后，lf的数据是下图这个样子，出现了两个相同id的edges item
![1681373766829](https://user-images.githubusercontent.com/125436292/231697801-241df5f3-ed74-4ca6-9fe7-1c894473172e.png)
![1681373788741](https://user-images.githubusercontent.com/125436292/231697921-adfea92b-bbe8-41f2-8ef6-7aaa81eae64d.png)
同时报错
![1681374360626](https://user-images.githubusercontent.com/125436292/231700490-a6e641b7-4c96-4826-ae64-9fc959865dd9.png)

**Comment by towersxu** [comment]
您好，能提供可运行代码吗？这样看不出什么问题。
