### ISSUE TITLE
[Bug report] Error: <g> attribute transform: Expected number, "matrix(1,0,0,1,NaN,NaN)".

### ISSUE THREAD

**Issue by maskTAQ** [didi/LogicFlow#1090]
**问题描述**  
使用自定义组件（基于RectResize）报错：
logic-flow.js:4800 Error: <g> attribute transform: Expected number, "matrix(1,0,0,1,NaN,NaN)".
1. 问题触发的条件
```
//注册节点
class CustomNode extends RectResize.view {}
class CustomNodeModel extends RectResize.model {}
lf.register({
    type: 'start',
    view: CustomNode,
    model: CustomNodeModel,
  });
//渲染数据
lf.render({nodes:[{id:'5',properties:{},styles: {"": undefined},text:"开始",type:'start',x:60,y:60}]});
```
2. 期望的表现
可以渲染支持拖拽的节点
4. 实际的表现
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/19301145/231953307-35a2367b-b35b-4b0b-867a-9c165d5dc8d1.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/19301145/231953346-d81890b3-a24f-49d9-89ed-9d9e2b7d3b1f.png">

**最简复现demo**

**Comment by towersxu** [comment]
您好，我们这边不能复现这个问题，请带上可运行示例，以便我们排查问题。例如https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js

**Comment by cfx1999** [comment]
我也遇到这个问题了，请问怎么解决的呀

**Comment by cfx1999** [comment]
我是自定义了两个节点一个开始一个结束继承的圆形节点，单独回显其中一个节点没问题，回显两个就会出现这个错误

**Comment by wuyounanhai55** [comment]
我也遇到了，解决了吗，麻烦贴一下代码，谢谢，自定义节点，改变节点样式，然后使用translateCenter报上面的错误
