### ISSUE TITLE
鼠标只是经过边，并未做其他任何操作，也会触发画布的history:change事件

### ISSUE THREAD

**Issue by 1263229887** [didi/LogicFlow#1091]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件：鼠标经过边，也会触发画布的history:change事件,这不合理。 只是经过，并没有点击和拖动或者改变数据。
2. 期望的表现：希望鼠标只是悬浮经过边，没有做其他任何操作这种情况下不触发画布的history:change事件。
3. 实际的表现：鼠标经过边，就会实时触发画布的history:change事件，

**Comment by towersxu** [comment]
您好，默认情况下，鼠标经过边是不会触发history:change. 若您出现这种情况，很可能是你在自定义连线的时候，自定义了鼠标经过边的逻辑，更新了edgeModel的properties。若你既想更新properties，又不想将其记录到history中，可以带上可运行示例，我们一起看这种情况如何处理。
