### ISSUE TITLE
lf.graphModel.moveNode这个方法当用上下左右箭头移动后，保存数据，重新进来加载画布数据时候节点文字位置会显示异常

### ISSUE THREAD

**Issue by 1263229887** [didi/LogicFlow#1092]
this.lf.on('node:click', (data) => {
    const _that = this
    if (data) {
      // 在元素库编辑了元素该名后, 使用静默刷新 强制把多节点绑定的同一元素 值保持一样
      document.onkeydown = function (e) {
        let key = window.event.keyCode;
        // 判断上下左右箭头的key之后，执行对应节点移动处理
        if (key === 38) {
          // 上
          _that.lf.graphModel.moveNode(data.data.id, 0, -1, false);
        } else if (key === 40) {
          // 下
          _that.lf.graphModel.moveNode(data.data.id, 0, 1, false);
        } else if (key === 37) {
          // 左
          _that.lf.graphModel.moveNode(data.data.id, -1, 0, false);
        } else if (key === 39) {
          // 右
          _that.lf.graphModel.moveNode(data.data.id, 1, 0, false);
        }
      };
    }
  })

使用这个方法上下左右箭头微调节点位置，在按住箭头不动，上下左右任意调整节点位置后，用getGraphRawData获取流程图数据，保存起来，然后重新进来加载页面，会发现节点的文字不再居中了。节点文字位置开始错乱。

**Comment by towersxu** [comment]
您好，这个问题看起来应该是你通过鼠标移动的距离与grid设置比例不一致导致了。例如你的grid为10，那么当你将节点移动1px到11位置的时候。下次重新渲染logicflow会强制将节点位置重新设置回10。这个时候就会出现节点位置与文本位置错乱的问题。建议你可以改grid设置为1或者把每次键盘按下后的距离设置为grid的值。
