### ISSUE TITLE
无法使用deleteProperty删除节点某个属性

### ISSUE THREAD

**Issue by cimgor** [didi/LogicFlow#1096]
**问题描述**  
使用例如getProperties、setProperties等这些方法时都没问题，唯独使用deleteProperty 就会报错 lf.deleteProperty is not a function at xxxxxx
![image](https://user-images.githubusercontent.com/48891371/232200795-bdc3b2c3-243b-49f4-b17b-b8972ac96aea.png)

**Comment by towersxu** [comment]
请确认您使用的版本，若最新版本仍然不支持此功能。请带上可运行示例，以便我们排查问题。

**Comment by towersxu** [comment]
目前不支持deleteProperty api, 也不支持设置properties为undefined，近期版本会加上。

**Comment by cimgor** [comment]
已解决啦，我把版本升级到最新版后就可以用这个api咯

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
