### ISSUE TITLE
render渲染了保存/初始化的节点数据，不会触发节点的添加事件吗？[Bug report]

### ISSUE THREAD

**Issue by daigang666** [didi/LogicFlow#1098]
**问题描述**  
1.render渲染节点
2. 期望触发节点添加事件
3. 实际不触发事件

**Comment by towersxu** [comment]
不会，render可能会渲染很多节点，触发添加事件不合理。您是有什么特殊需求吗？我们会基于您实际需求评估是否优化这里。
