### ISSUE TITLE
[Bug report]你好，xml不能正确携带扩展元素（extensionElements）如监听器等

### ISSUE THREAD

**Issue by yw738** [didi/LogicFlow#1105]
**问题描述**  
在LogicFlow导入携带监听器的xml，再导出，再导入报错。原因是extensionElements里面的内容没有被正确的转换。

**最简复现demo**  
导入前：
![image](https://user-images.githubusercontent.com/44350921/232958798-7d903e5b-476d-4972-9230-99261e7a5c44.png)
导入后：
![image](https://user-images.githubusercontent.com/44350921/232958845-093bf10d-b537-4a10-afb7-2289125abffd.png)

**Comment by towersxu** [comment]
您好，感谢提出。目前LogicFlow对BPMN数据格式支持不够完善，您可以先将bpmnElement插件和bpmnAdapter源码放到你本地作为插件使用。

**Comment by wumail** [comment]
该问题已在1.2.5版本中被修复，建议升级至最新版本以解决问题
