### ISSUE TITLE
连线的起始点如何与锚点id进行绑定或者如何将计算出来的锚点坐标注入到连线的起始点

### ISSUE THREAD

**Issue by wxc0730** [didi/LogicFlow#1108]
请问一下流程图连线的起点如何跟锚点id来进行绑定？
前的业务是锚点可以动态新增，但是当我新增锚点的时候锚点位置进行重新计算之后连线的起点或终点会跟锚点错位导致连线的两端不在锚点上。

![image](https://user-images.githubusercontent.com/73807995/233008566-927c136e-1537-487d-9661-5c8f0e047c2d.png)

**Comment by towersxu** [comment]
edgeModel中有`updateStartPoint`, `updateEndPoint`和`initPoints`这三个方法，可以这样实现

```js
// edgeModel
    const startPoint = {
      x: sourceAnchor.x,
      y: sourceAnchor.y
    };
    this.updateStartPoint(startPoint);
    const endPoint = {
      x: targetAnchor.x,
      y: targetAnchor.y
    };
    this.updateEndPoint(endPoint);
    // 这里需要将原有的pointsList设置为空，才能触发bezier的自动计算control点。
    this.pointsList = [];
    this.initPoints();
```

详细示例代码地址：https://codesandbox.io/embed/logicflow-base15-ou2i0?fontsize=14&hidenavigation=1&theme=dark&view=preview
