### ISSUE TITLE
[Bug report] 初始化绑定的快捷键事件，在LogicFlow被销毁之后，绑定的事件还存在。

### ISSUE THREAD

**Issue by flyoverGu** [didi/LogicFlow#1110]
**问题描述**  
因为LogicFlow 绑定快捷键用了 mousetrap。 而mousetrap默认事件是绑定到document上。导致LogicFlow虽然被销毁之后，但绑定的事件还存在。

**Comment by flyoverGu** [comment]
同时，如果同一个页面上有两个LogicFlow实例的时候，快捷键绑定的事件会被触发两次。

**Comment by flyoverGu** [comment]
目前我暂时是在节点销毁的时候，手动调用下 `lf.keyboard.mousetrap.reset()`

然后在事件触发的地方加了一个判断 
`if (e.target == this.lf.container) { }`

**Comment by wumail** [comment]
> 目前我暂时是在节点销毁的时候，手动调用下 `lf.keyboard.mousetrap.reset()`
> 
> 然后在事件触发的地方加了一个判断 `if (e.target == this.lf.container) { }`

这些问题在最新的1.2.5版本中得到了修复，现在不再将事件都绑定到document上。与此同时暴露出另外一个问题（**此前，为了解决这个问题将事件都默认绑在了document上**），当使用React(其他的方式可能也有问题)来开发自定义html节点时，可能会出现点击一次html节点再按下快捷键，操作不会生效的问题，需要双击以聚焦该节点再按下快捷键才会触发([issue#942](https://github.com/didi/LogicFlow/issues/942))，这是可能是因为React的某些合成事件导致节点失焦或是阻止了节点聚焦。这个问题将在后面的版本解决，为了能暂时解决问题，可以为该节点设置tabIndex，同时在点击时进行手动聚焦，来确保元素可以被正确地聚焦并接收输入，具体内容可以自行查阅，同时如果有好的想法、好的解法，欢迎提交PR。
