### ISSUE TITLE
[Bug report]监听"node:dnd-add", 默认选中节点, 无法通过backspace直接删除节点,需重新点击才可删除

### ISSUE THREAD

**Issue by JunCxio** [didi/LogicFlow#1114]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
  监听"node:dnd-add", 默认选中节点, 
      lf.selectElementById(nodeId)
      lf.graphModel.eventCenter.emit("node:click", { data });
 
2. 期望的表现
  通过"backspace"按键可直接删除节点 
3. 实际的表现
  无法通过"backspace"按键可直接删除节点 ,,需重新点击才可删除

**Comment by wumail** [comment]
> **问题描述** 请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
> 
> 1. 问题触发的条件
>    监听"node:dnd-add", 默认选中节点,
>    lf.selectElementById(nodeId)
>    lf.graphModel.eventCenter.emit("node:click", { data });
> 2. 期望的表现
>    通过"backspace"按键可直接删除节点
> 3. 实际的表现
>    无法通过"backspace"按键可直接删除节点 ,,需重新点击才可删除

能提供一个最小可复现的实例吗

**Comment by flyoverGu** [comment]
你拖过去之后，把鼠标挪开，就会发现，默认是不选中。你看上去选中只是鼠标hover在上面而已。

**Comment by towersxu** [comment]
您好，目前没有复现这个问题，请确认使用的最新版本。建议带上可运行示例，方便我们排查问题。

**Comment by JunCxio** [comment]
> 您好，目前没有复现这个问题，请确认使用的最新版本。建议带上可运行示例，方便我们排查问题。

升级版本后该问题修复了

**Comment by xqk1** [comment]
@JunCxio 用的什么版本
