### ISSUE TITLE
[Bug report] lfXml2Json 转换错误

### ISSUE THREAD

**Issue by JianGuoHt** [didi/LogicFlow#1130]
## 使用 lfJson2Xml, lfXml2Json 进行数据转换时
通过 `lfJson2Xml `将 `json `数据转换为 `xml`，再通过 `lfXml2Json `将 `xml ` 数据转换回 `json`, 出现数据丢失、格式错问题；
控制台报错： 找不到undefined对应的节点。

## 期望的表现
数据转换正常

## 示例链接
https://codesandbox.io/s/logicflow-base21-forked-xnpozx?file=/step_21_download/index.js

**Comment by wumail** [comment]
目前xml和json互相转换的问题已经提交了几次pr，可以看看现在仓库里的代码是否符合预期

**Comment by towersxu** [comment]
xmlAdapter仅支持bpmnElement中的元素，不支持circle、node这些基础节点。
