### ISSUE TITLE
如何实现 拖拽交换俩节点

### ISSUE THREAD

**Issue by lovecrossyou** [didi/LogicFlow#1135]
## 问题背景

请用简洁的语言描述问题

## 提案

解决方案，最好可以提供有一些伪代码

## 相关信息

一些关于需求的额外信息和截图

**Comment by towersxu** [comment]
可以参考这个项目https://github.com/hsole/S12 ，里面实现了从一个节点拖动到另一个节点实现覆盖。你把实现覆盖后，把原来的节点也改一下应该就能实现您的需求。注意：如果你要实现完整的交换，需要考虑节点连接的边上的sourceNodeId和targetNodeId更新。
