### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by a64224907** [didi/LogicFlow#1136]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 2个html自定义节点，从一个节点点到另一个节点，会导致另一个节点重新渲染，但是如果此时我点的位置是另一个节点里的下拉框，会出现弹出后立马弹回
2. 下拉框弹出后应不弹回
3.  下拉框弹出后立马弹回了

## 最简复现

一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：

1. 在任意在线编码平台如 codesanbox 编写示例。将其保存到自己空间，然后贴上链接。
2. 在自己 github 中创建一个最简单的示例，然后贴上 github 链接。
3. 删除项目中的 node_modules 部分，打包项目，并拖拽到 issue 输入框中上传（或提供远程可下载地址）。

## 相关信息 context

LogicFlow Version:1.2
Node Version:16.19.1
Platform:PC
[front - 副本.zip](https://github.com/didi/LogicFlow/files/11341976/front.-.zip)

**Comment by towersxu** [comment]
您好，我本地运行了你的示例，但是没有复现遇到的问题。建议更详细的描述如何复现您的问题。html节点一般只会在perperties发生变化后触发setHtml. 

https://github.com/didi/LogicFlow/blob/b96ae473095c91d359d822551a9f346836f16b16/packages/core/src/view/node/HtmlNode.tsx#L38-L47
