### ISSUE TITLE
[Bug report]当流程图中边（贝塞尔）的位置超出所有节点范围，使用 getSnapshot 导出图片，图片不完整

### ISSUE THREAD

**Issue by zengguangzhong** [didi/LogicFlow#1147]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题描述：在使用 lf.getSnapshot() 导出图片的时候，如果流程图的边（贝塞尔曲线）的位置在所有节点的矩形框之外，就会出现导出的图片不符的问题。其他情况正常。
如下图：
![企业微信截图_16837087577037](https://github.com/didi/LogicFlow/assets/20290798/a37c1732-500a-4168-9574-1e8326dd64d2)

3. 期望的表现：与上图保持一致
4. 实际的表现：
![image](https://github.com/didi/LogicFlow/assets/20290798/f6dccdc6-4978-4848-bb0a-7d777a8f509a)

 
简单示例：
https://codesandbox.io/s/logicflow-base21-forked-lx7n9e?file=/step_21_download/index.js

LogicFlow Version: 1.2.1

**Comment by towersxu** [comment]
此问题已在1.2.7版本修复。
