### ISSUE TITLE
[Bug report]getVirtualRectSize 方法获取的矩形尺寸未包括所有边的位置

### ISSUE THREAD

**Issue by zengguangzhong** [didi/LogicFlow#1148]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题描述：packages/core/src/model/GraphModel.ts 文件中的 getVirtualRectSize  方法计算矩形尺寸时，仅计算了所有的节点，忽略了边的位置计算。
![image](https://github.com/didi/LogicFlow/assets/20290798/983d3a43-c395-44a5-b3ce-f8d0d967e9bb)

2. 期望的表现：遍历所有的边的位置，函数返回的矩形尺寸应该要能囊括所有的节点和边。
3. 实际的表现：目前仅包括了所有节点的计算
 

LogicFlow Version: 1.2.1
 

2. 期望的表现：遍历所有的边的位置，函数返回的矩形尺寸应该要能囊括所有的节点和边。
3. 实际的表现：目前仅包括了所有节点的计算
 

LogicFlow Version: 1.2.1

**Comment by wumail** [comment]
具体遇到了什么问题，有哪些不符合预期的地方？
![Uploading 7f39ecd4e7bdd8e56febd09d495c0139.png…]()

**Comment by wumail** [comment]
具体遇到什么问题，实际有哪里不符合预期？
![7f39ecd4e7bdd8e56febd09d495c0139](https://github.com/didi/LogicFlow/assets/56008486/f294b195-61a6-4dd3-8a60-81643b2e74c5)
这种情况下，显然不算上边得到的包围盒和fitView结果更加合理

**Comment by wumail** [comment]
具体遇到什么问题，实际应用中哪里不符合预期？
![8ece1cd0f2bb48676535bdb9f089094e](https://github.com/didi/LogicFlow/assets/56008486/1e5197a4-3957-491e-ad81-0b90369d3744)
这种情况下，显然不算上边的包围盒以及fitView的效果更加合理

**Comment by zengguangzhong** [comment]
> ![8ece1cd0f2bb48676535bdb9f089094e](https://user-images.githubusercontent.com/56008486/239181932-1e5197a4-3957-491e-ad81-0b90369d3744.png) 这种情况下，不算上边的包围盒以及translateCenter的效果更加合理。如果有一条比图中的曲线更离谱更高，这条边对包围盒的贡献就会非常大，fitView就会得到一个缩小得很小的图形。一般来说我们会更注意节点一些，所以感觉现在是合理的，具体什么场景中会得到一个不能接受的结果吗？

你好，我的场景是，希望获取到能刚好完全展示整个流程图（含所有的边和节点）的rect大小。然后再配合fitview方法展示1:1的流程图。

**Comment by wumail** [comment]
> > ![8ece1cd0f2bb48676535bdb9f089094e](https://user-images.githubusercontent.com/56008486/239181932-1e5197a4-3957-491e-ad81-0b90369d3744.png) 这种情况下，不算上边的包围盒以及translateCenter的效果更加合理。如果有一条比图中的曲线更离谱更高，这条边对包围盒的贡献就会非常大，fitView就会得到一个缩小得很小的图形。一般来说我们会更注意节点一些，所以感觉现在是合理的，具体什么场景中会得到一个不能接受的结果吗？
> 
> 你好，我的场景是，希望获取到能刚好完全展示整个流程图（含所有的边和节点）的rect大小。然后再配合fitview方法展示1:1的流程图。

这个后续可以考虑优化一下，暂时你可以照着参照[getVirtualRectSize](https://github.com/didi/LogicFlow/blob/master/packages/core/src/model/GraphModel.ts#L1183)这个方法自己去实现完整完整大小的计算

**Comment by zengguangzhong** [comment]
> 

好的 感谢

**Comment by zengguangzhong** [comment]
> > > ![8ece1cd0f2bb48676535bdb9f089094e](https://user-images.githubusercontent.com/56008486/239181932-1e5197a4-3957-491e-ad81-0b90369d3744.png) 这种情况下，不算上边的包围盒以及translateCenter的效果更加合理。如果有一条比图中的曲线更离谱更高，这条边对包围盒的贡献就会非常大，fitView就会得到一个缩小得很小的图形。一般来说我们会更注意节点一些，所以感觉现在是合理的，具体什么场景中会得到一个不能接受的结果吗？
> > 
> > 
> > 你好，我的场景是，希望获取到能刚好完全展示整个流程图（含所有的边和节点）的rect大小。然后再配合fitview方法展示1:1的流程图。
> 
> 考虑优化后续一下，暂时你可以参照[getVirtualRectSize](https://github.com/didi/LogicFlow/blob/master/packages/core/src/model/GraphModel.ts#L1183)这个方法自己去实现完整大小的计算

好的 感谢
