### ISSUE TITLE
[Feature Request]保存折线的转折点最小变化

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#1149]
## 问题背景

在调整完连线后，再去调整节点，这个时候会重新计算所有的连线轨迹。导致之前调整的路径发生变化。

## 提案

连线增加更新连接点的功能，尽量保持之前的轨迹。

**Comment by WinYourX** [comment]
可不可以增加一个自定义调整连线拐点的功能？现在都是确定头尾自动计算，不太灵活。
