### ISSUE TITLE
[Bug report]升级到LogicFlow1.2.5后使用dagre布局进行排列，线条没有跟随节点移动

### ISSUE THREAD

**Issue by hongliangsam** [didi/LogicFlow#1153]
## 问题描述

1. 问题触发的条件，如何复现：
自动布局选项dagre.ts中设置option：
![image](https://github.com/didi/LogicFlow/assets/50320208/634f60c9-fbf4-4c00-ab5a-1a41e1e715c0)
排布后点击“一键美化”：
![image](https://github.com/didi/LogicFlow/assets/50320208/1a05f5f9-c973-4905-84da-988a95843a58)
3. 期望的表现
![image](https://github.com/didi/LogicFlow/assets/50320208/0c57b84c-324d-4119-a338-500a41234fae)
4. 实际的表现
![image](https://github.com/didi/LogicFlow/assets/50320208/c9339109-1abf-4025-8cc8-879ee356f045)
注意，在LogicFlow1.1.27-1.2.3版本都正常，升级到1.2.4-1.2.5就出现以上问题。
## 最简复现
表现正常的项目地址：https://github.com/hongliangsam/layout-lf1.1.27
出现bug的项目地址：https://github.com/hongliangsam/layout-lf1.2.5

## 相关信息 context

LogicFlow Version:1.2.5
Node Version: v14.15.0 (64-bit)
Platform: 版本	Windows 11 家庭中文版
版本	22H2
操作系统版本	22621.1702
浏览器：Google Chrome版本 113.0.5672.93（正式版本） （64 位）

**Comment by towersxu** [comment]
感谢提出，此问题已在1.2.6版本修复。
