### ISSUE TITLE
[Bug report]自定义HTML节点内部动态添加元素，节点的宽度无法更新

### ISSUE THREAD

**Issue by peipeihai** [didi/LogicFlow#1154]
单独拖入一个节点时，点击【添加】，节点宽度能够随着加入的元素不断更新
<img width="691" alt="image" src="https://github.com/didi/LogicFlow/assets/7858692/834b2a37-cc72-43ff-8c17-cf624ae20596">

与其他节点连线后，再点击【添加】，节点宽度不会更新了，打印出来图数据，发现节点宽度已经更新，但是图不会重新渲染更新
<img width="705" alt="image" src="https://github.com/didi/LogicFlow/assets/7858692/adc39c8e-c42f-43d9-a4ac-75a3982276a6">

**Comment by towersxu** [comment]
您好，看起来应该是有地方写错了。您可以请提供可运行示例，我们可以帮你指出错误的地方。

**Comment by peipeihai** [comment]
> 您好，看起来应该是有地方写错了。您可以请提供可运行示例，我们可以帮你指出错误的地方。

@towersxu  您好，表述错误，是使用@antv/hierarchy进行自动布局后，节点的宽度无法再更新。 可运行代码见附件，谢谢！
[logic-flow-app.zip](https://github.com/didi/LogicFlow/files/11474921/logic-flow-app.zip)

**Comment by towersxu** [comment]
@peipeihai 节点的宽度需要自己算，然后去setAttributes中更新。可以参考这个示例，是动态计算节点的高度的。https://codesandbox.io/embed/logicflow-base15-ou2i0?fontsize=14&hidenavigation=1&theme=dark&view=preview
