### ISSUE TITLE
【版本升级】TypeError: Cannot read properties of undefined (reading 'nodes')

### ISSUE THREAD

**Issue by alpschan** [didi/LogicFlow#1155]
## 问题描述
    1、版本由1.2.1 升级到 1.2.5 之后，就会报以上“TypeError: Cannot read properties of undefined (reading 'nodes')”错误；
    2、这仿佛和BpmnXmlAdapter有关，只要是使用了BpmnXmlAdapter插件或者BpmnAdapter插件，都会出现这个错误。

**Comment by towersxu** [comment]
感谢指出，此问题已在1.2.6版本修复。https://codesandbox.io/s/logicflow-base20-forked-4whykv?file=/package.json

**Comment by alpschan** [comment]
请问一下，为什么升级之后。在lf.getGraphData()中，会多出<LogicFlow></LogicFlow>内容？这不符合bpmn的标准了。

**Comment by towersxu** [comment]
感谢指出，确认一下多的内容是指多了个LogicFlow吗？

**Comment by alpschan** [comment]
对的。之前的BpmnXmlAdapter是可以正确转化成bpmn的XML。
升级了之后，会发现XML中多了一层<LogicFlow>……</LogicFlow>包裹着。。。

看了一下源码，是强制加进去的，包括在重新获取渲染数据的时候，也要加上这个才能准确渲染出来。
`function lfJson2Xml(o) {
    var xmlStr = "<LogicFlow>\t\n";
    for (var m in o) {
        xmlStr += toXml(o[m], m, 0);
    }
    return xmlStr + "\t\n</LogicFlow>";
}`

其实是想知道设计如此还是bug？

**Comment by towersxu** [comment]
@alpschan 这个是BUG，将在本周发布新版本修复

**Comment by alpschan** [comment]
👍👍
