### ISSUE TITLE
[Bug report] 方法 renderRawData 渲染节点，节点中指定zindex，渲染出来zindex不生效。

### ISSUE THREAD

**Issue by XM-GO** [didi/LogicFlow#1162]
方法 renderRawData 渲染节点，节点中指定zindex，渲染出来zindex不生效。

**Comment by towersxu** [comment]
@XM-GO zIndex不属于图数据，属于model的属性。如果你需要在图数据中实现控制zIndex，可以选择放到properties中，然后再自定义节点的时候，将这个perperties的zIndex赋值给model的zIndex
