### ISSUE TITLE
为啥切换静默模式，会更改到画布的配置

### ISSUE THREAD

**Issue by Xiexx-97Len** [didi/LogicFlow#1163]
## 切换静默模式，会更改到画布的配置

做了ctrl+滚轮实现缩放，初始化画布时配置了stopScrollGraph：true（禁止鼠标滚动移动画布），然后在某种情况下，使用了updateEditConfig去设置为静默模式，发现禁止鼠标滚动移动画布失效了。

**Comment by towersxu** [comment]
静默模式是一系列配置的集合，其中就包括了stopScrollGraph。你可以不使用静默模式，改用自己配置属性。https://docs.logic-flow.cn/docs/#/zh/guide/basic/silent-mode
