### ISSUE TITLE
[Bug report]  禁用了MultipleSelectTool，同时通过setMenuByType设置了框选区的自定义菜单，在多选节点后，右键时自定义的框选区菜单不会出现，任然显示为节点本身的菜单；

### ISSUE THREAD

**Issue by zhanglei518** [didi/LogicFlow#1164]
禁用了**MultipleSelectTool**，同时通过**setMenuByType**设置了**框选区**的自定义**菜单**，在多选节点后，右键时自定义的框选区菜单**不会出现**，任然显示为节点本身的菜单；
如下图：
![image](https://github.com/didi/LogicFlow/assets/21114634/f3df490a-cec9-4b35-bf25-47a58eec6853)

公司内网项目，无法上传code...

**Comment by towersxu** [comment]
目前这种情况下，不能使用默认菜单了，选区菜单和选区工具是绑定的。如果你想实现你这种功能，只有参考菜单插件，自定义菜单了。
