### ISSUE TITLE
[Bug report]自定义连线两端的箭头getStartArrow无效

### ISSUE THREAD

**Issue by qingshansuiyun** [didi/LogicFlow#1167]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件，如何复现 当在自定义连线两端的箭头时getEndArrow有效，getStartArrow无效
2. 期望的表现 getEndArrow有效，getStartArrow有效
3. 实际的表现 getEndArrow有效，getStartArrow无效

## 最简复现

一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：

1. 在任意在线编码平台如 codesanbox 编写示例。将其保存到自己空间，然后贴上链接。
[最简demo复现](https://codesandbox.io/s/logicflow026-edgeanimation-forked-kgiyjv?file=/examples/026_edgeAnimation/customEdge.js)
3. 在自己 github 中创建一个最简单的示例，然后贴上 github 链接。
4. 删除项目中的 node_modules 部分，打包项目，并拖拽到 issue 输入框中上传（或提供远程可下载地址）。

## 相关信息 context

LogicFlow Version:1.2.5
Node Version:
Platform:

**Comment by wumail** [comment]
> ## 问题描述
> 请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：
> 
> 1. 问题触发的条件，如何复现 当在自定义连线两端的箭头时getEndArrow有效，getStartArrow无效
> 2. 期望的表现 getEndArrow有效，getStartArrow有效
> 3. 实际的表现 getEndArrow有效，getStartArrow无效
> 
> ## 最简复现
> 一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：
> 
> 1. 在任意在线编码平台如 codesanbox 编写示例。将其保存到自己空间，然后贴上链接。
>    [最简demo复现](https://codesandbox.io/s/logicflow026-edgeanimation-forked-kgiyjv?file=/examples/026_edgeAnimation/customEdge.js)
> 2. 在自己 github 中创建一个最简单的示例，然后贴上 github 链接。
> 3. 删除项目中的 node_modules 部分，打包项目，并拖拽到 issue 输入框中上传（或提供远程可下载地址）。
> 
> ## 相关信息 context
> LogicFlow Version:1.2.5 Node Version: Platform:

这个问题将在下一个版本修复
