### ISSUE TITLE
图片导出能自定义增加水印

### ISSUE THREAD

**Issue by HTML110** [didi/LogicFlow#1169]
图片导出能增加一些api嘛
比如：背景水印，时间戳等功能

**Comment by wumail** [comment]
> 我如何使用这个方法啊 getCanvasData，麻烦能再详解一下！ getCanvasData这个不是getSnapshot封装的一个方法嘛？我是要把整个方法都copy过来进行修改嘛？

这个方法确实没暴露出来，可以调整一下。 @towersxu 👀👀

**Comment by HTML110** [comment]
@towersxu

**Comment by towersxu** [comment]
hello, 这个功能已经支持了。https://codesandbox.io/s/logicflow-base21-o3vqi?from-embed=&file=/step_21_download/index.js
