### ISSUE TITLE
[Bug report] node:dnd-add事件拿不到event对像

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#1170]
## 问题描述

1. 1.2.7版本目前不支持获取node:dnd-add的event对象，在1.1.x版本中我有提PR并被合并：https://github.com/didi/LogicFlow/pull/869
2. 期望1.2.x版本能继续支持这个功能

**Comment by towersxu** [comment]
此问题已在1.2.8版本修复。
