### ISSUE TITLE
[Bug report]导出图片 Snapshot，不支持使用了iconfont的svg图标

### ISSUE THREAD

**Issue by zengguangzhong** [didi/LogicFlow#1171]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件，如何复现
当节点里使用了阿里的iconfont svg图标，在使用Snapshot导出图片的时候，svg图标消失了。原因是：
![image](https://github.com/didi/LogicFlow/assets/20290798/19e4c063-c9e6-401f-8631-899c4a139300)
svg.cloneNode 克隆的时候把 shadowDom 忽略了。
          
3. 期望的表现：期望导出如下图
![image](https://github.com/didi/LogicFlow/assets/20290798/a09906b6-9894-4917-b564-181410efcc82)

5. 实际的表现：svg图标不见了
![image](https://github.com/didi/LogicFlow/assets/20290798/24934ef7-c08e-43c8-b1a7-fa9e7aaca689)

demo地址：
https://codesandbox.io/s/logicflow-base7-forked-8zxt5d?file=/step7/index.js

## 相关信息 context

LogicFlow Version: 1.2.7

**Comment by wumail** [comment]
> zengguangzhong

可以考虑先用html2canvas解决问题
