### ISSUE TITLE
[Bug report] 当nodeData.properties.xxx 的值中包含&lt；这类转义符时，会被自动转义为<，如何让程序不执行转义

### ISSUE THREAD

**Issue by wyy159** [didi/LogicFlow#1175]
## 问题描述

1. 当nodeData.properties.xxx 的值中包含&lt；这类转义符时，会被自动转义为<
2. 期望的表现
不执行转义
3. 实际的表现
执行了转义
## 最简复现
可以使用示例中的bpmn示例导入数据，下载数据进行比较。
原始数据
![image](https://github.com/didi/LogicFlow/assets/61811760/50fc0a9e-76fc-490a-b861-6469db683a99)
导入后，点击查看数据
![image](https://github.com/didi/LogicFlow/assets/61811760/7b539201-faf9-4288-9360-d4df9326fdcd)

## 相关信息 context

LogicFlow Version:
Node Version:
Platform:

**Comment by ZhangMingZhao1** [comment]
这样转义有什么影响吗，默认浏览器行为好像也是这样

**Comment by wyy159** [comment]
> 这样转义有什么影响吗，默认浏览器行为好像也是这样

后台处理表达式时会报错

**Comment by wumail** [comment]
> > 这样转义有什么影响吗，默认浏览器行为好像也是这样
> 
> 后台处理表达式时会报错

bpmn插件中使用了DOMParser or ActiveXObject做XML的解析，&gt;此类编码会被转义，是默认行为，你可以通过如下方式解决问题：
1、和后端约定一个方式做表达式的解析，让后端去处理
2、将数据放在CDATA里防止被解析
3、不通过BPMN插件做XML的解析，将XML数据转为字符串，自己对XML数据进行语法解析
