### ISSUE TITLE
同一个页面，两个实例，第二个实例渲染第一个实例getSelectElements(false)数据，箭头会有问题

### ISSUE THREAD

**Issue by radish-angel** [didi/LogicFlow#1190]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件，如何复现
同一个页面有两个lf实例， 从第一个实例中通过getSelectElements(false)获取数据data，第二个实例通过render(data)渲染画布，第二个实例在通过openEdgeAnimation开启边动画，箭头的样式不会改变
![image](https://github.com/didi/LogicFlow/assets/18325438/1b53d352-9ecc-4ee5-af2e-5a40e339b1db)

3. 期望的表现
第二个实例的箭头可以一起变化
5. 实际的表现
第二个实例的箭头样式跟第一实例的箭头一样
## 最简复现

一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：

## 相关信息 context

LogicFlow Version:1.2.8
Node Version:14.21.3
Platform:

**Comment by towersxu** [comment]
@radish-angel 你好，能提供codesandbox示例吗？

**Comment by radish-angel** [comment]
> @radish-angel 你好，能提供codesandbox示例吗？

https://stackblitz.com/edit/stackblitz-starters-k4caqq?file=src%2FApp.tsx

**Comment by wumail** [comment]
https://stackblitz.com/edit/stackblitz-starters-ti14sx?file=src%2FApp.tsx，这样试试，目前LogicFlow里面直接用边的Id拼成字符串来定义和复用marker

**Comment by wumail** [comment]
> > @radish-angel 你好，能提供codesandbox示例吗？
> 
> https://stackblitz.com/edit/stackblitz-starters-k4caqq?file=src%2FApp.tsx

https://stackblitz.com/edit/stackblitz-starters-ti14sx?file=src%2FApp.tsx
这样试试，目前LogicFlow 里直接通过边id组成的字符串来定义和复用marker，后续会考虑优化

**Comment by radish-angel** [comment]
> > > @radish-angel 你好，能提供codesandbox示例吗？
> > 
> > 
> > https://stackblitz.com/edit/stackblitz-starters-k4caqq?file=src%2FApp.tsx
> 
> https://stackblitz.com/edit/stackblitz-starters-ti14sx?file=src%2FApp.tsx 这样试试，目前LogicFlow 里直接通过边id组成的字符串来定义和复用marker，后续会考虑优化

非常感谢
