### ISSUE TITLE
[Bug report]在监听事件中拿不到用useState定义的数据的最新值

### ISSUE THREAD

**Issue by a64224907** [didi/LogicFlow#1192]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 在监听事件中拿不到用useState定义的数据的最新值
2. 期望的表现
3. 实际的表现

## 最简复现

一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：

## 相关信息 context

LogicFlow Version:1.2.8
Node Version:
Platform:
[logicflowapp.zip](https://github.com/didi/LogicFlow/files/11753668/logicflowapp.zip)

**Comment by wumail** [comment]
你代码写的有问题，最简单的方式是用useRef代替useState
`export default function Home() {
  const t = useRef('1')
  useEffect(()=>{
    const lf = new LogicFlow({
      container: document.querySelector("#app"),
      grid: true,
    });
    
    lf.render({
      nodes: [
        {
          id: "1",
          type: "rect",
          x: 100,
          y: 100,
          text: "节点1",
        },
        {
          id: "2",
          type: "circle",
          x: 300,
          y: 200,
          text: "节点2",
        },
      ],
      edges: [
        {
          sourceNodeId: "1",
          targetNodeId: "2",
          type: "polyline",
          text: "连线",
        },
      ],
    });
    lf.on('node:click',()=>{
      console.log(t.current)
    })
  },[])
  return (
    <>
    <button onClick={()=>{t.current = '2'}}>setTest</button>
    <div id='app' style={{height:'100vh'}}></div>
    </>
  )
}`

**Comment by wumail** [comment]
🫥
