### ISSUE TITLE
[Bug report]渲染画布后，通过自制的收缩侧边栏调整了侧边栏宽度，影响了画布宽度，导致全览功能出现问题

### ISSUE THREAD

**Issue by a64224907** [didi/LogicFlow#1198]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题：渲染画布后，通过自制的收缩侧边栏调整了侧边栏宽度，影响了画布宽度，导致全览功能出现问题
2. 期望：以注册画布时的app宽度为全览宽度
3. 实际：未调整宽度

## 最简复现

一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：
![未调整侧边栏时的全览效果](https://github.com/didi/LogicFlow/assets/78522372/09fc3faa-c0ce-40dd-a0ed-3862b95c2acd)
![调整侧边栏宽度后的全览](https://github.com/didi/LogicFlow/assets/78522372/c4949c74-3d78-46cf-84db-cf2342719635)
[logicflowapp.zip](https://github.com/didi/LogicFlow/files/11796646/logicflowapp.zip)

## 相关信息 context

LogicFlow Version:
Node Version:
Platform:

**Comment by wumail** [comment]
你可以试试在调整侧边栏的同时手动设置更新画布的大小

**Comment by a64224907** [comment]
根据你说的，可以实现
