### ISSUE TITLE
[Bug report]Snapshot导出时iconfont图标时白色框框

### ISSUE THREAD

**Issue by Jackprogramer** [didi/LogicFlow#1201]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：
Snapshot导出时iconfont图标时白色框框
1. Snapshot导出
this.$props.lf.getSnapshot();
2. 使用vue组件作为节点渲染
[https://github.com/Jackprogramer/GitResp2/blob/master/TaskNode](url)
3. 注册节点
[https://github.com/Jackprogramer/GitResp2/blob/master/registerTask](url)

## 相关信息 context

LogicFlow Version:1.2.9
Node Version:12.9
Platform:vue2.6.12

**Comment by wumail** [comment]
暂时可以尝试使用html2Canvas看看能否解决问题

**Comment by towersxu** [comment]
目前还不支持导出url图片，可以考虑先转换为base64。参考https://github.com/didi/LogicFlow/issues/477
