### ISSUE TITLE
[Bug report] 自定义html节点，文本的变更不会触发shouldUpdate

### ISSUE THREAD

**Issue by yj-liuzepeng** [didi/LogicFlow#1208]
## 问题描述

1. [demo 仓库地址](https://github.com/yj-liuzepeng/vue-logicflow#vue-logicflow)
2. 使用vue自定义html节点，通过updateText更新节点时，数据修改了，节点视图没有改变

## 最简复现

运行demo，随意点击一个节点，观察控制台输出

**Comment by towersxu** [comment]
HTML节点目前是通过编排properties发生变化来触发组件的更新。https://github.com/didi/LogicFlow/blob/5bf59303a2f8ab34cec7bc4439750bf0a5daf7da/packages/core/src/view/node/HtmlNode.tsx#L37-L62

所以如果直接修改文本，是不会触发这个组件的再次渲染。

@yj-liuzepeng 你的项目有两种办法解决这个问题。
1. 重写`shouldUpdate`
```js
  shouldUpdate() {
    if (this.preProperties &&
     this.preProperties === this.currentProperties &&
     this.preText === this.props.model.text.value
   ) return;
    this.preProperties = this.currentProperties;
    this.preText = this.props.model.text.value
    return true;
  }
```

2. 组件不使用节点的text，而是将你想要显示的文案放到properties中。

**Comment by towersxu** [comment]
文档缺少shouldUpdate相关内容，需要补充。

**Comment by wumail** [comment]
相关内容已补充，https://docs.logic-flow.cn/docs/#/zh/guide/basic/node?id=shouldupdate
