### ISSUE TITLE
[Bug report]节点缩放后连线未跟随锚点移动

### ISSUE THREAD

**Issue by chengjiashuai** [didi/LogicFlow#1209]
## 问题描述
当前使用版本为：1.2.3

节点缩放后，节点会出现偏移，导致连线不在锚点上，此时再次缩放节点，连线则不会跟随锚点移动
1.首次缩放节点后，连线就不在锚点中心了
![image](https://github.com/didi/LogicFlow/assets/28143893/a65368f2-c932-403f-bbdf-3ea5a8d3d71b)
2.之后再次缩放节点，连线位置未更新
![image](https://github.com/didi/LogicFlow/assets/28143893/d444e1c7-c187-4837-b744-137d0d6d78cb)

**Comment by wbccb** [comment]
跟[issues/875](https://github.com/didi/LogicFlow/issues/875)是一样的问题？ @chengjiashuai

**Comment by wumail** [comment]
同 #831

**Comment by wumail** [comment]
即将发版的1.2.10中修复了该问题，烦请升级版本后重试
