### ISSUE TITLE
自定义边每点击一次就会重新出发渲染

### ISSUE THREAD

**Issue by Jackie-llv** [didi/LogicFlow#1210]
## 问题描述
如图一，每点击一次自定义的边就会重新执行getEdge和react渲染，react没有报错，但是vue里面就会有如下警告，如图二

<img width="890" alt="image" src="https://github.com/didi/LogicFlow/assets/28420052/d63be3af-199f-4624-98f7-c2db96169587">

<img width="634" alt="image" src="https://github.com/didi/LogicFlow/assets/28420052/ab04690a-d7e3-4027-9967-ec92707e1805">

## 最简复现
可以自己在你们的代码里面加上log试一下
https://codesandbox.io/embed/affectionate-visvesvaraya-uexl0y?fontsize=14&hidenavigation=1&theme=dark

**Comment by wumail** [comment]
1、"每点击一次自定义的边就会重新执行getEdge和react渲染"是示例的问题

**Comment by wumail** [comment]
在我自己的vue项目中没有发现类似的问题，根据你的描述也看不出是什么问题，最好提供可复现示例。
