### ISSUE TITLE
[Bug report]在自定义边中添加元素，点击该元素第一次不会触发点击事件，之后第二次后才会触发

### ISSUE THREAD

**Issue by Jackie-llv** [didi/LogicFlow#1211]
## 问题描述

在自定义边中添加元素，点击该元素第一次不会触发点击事件，之后第二次后才会触发

## 最简复现

demo: https://codesandbox.io/s/modest-mcclintock-49fs9n?file=/src/CustomEdge.tsx

打开后点击边上的`aaa`
<img width="264" alt="image" src="https://github.com/didi/LogicFlow/assets/28420052/a57df1aa-f838-4015-874c-7bcbf6ddae36">
查看控制台中的打印信息，就会发现第一次的时候111不会打印出来，第二次之后才会

## 相关信息 context

<img width="411" alt="image" src="https://github.com/didi/LogicFlow/assets/28420052/0a5729b8-9fe8-4b09-91a3-8f0c4f1058cf">

**Comment by wumail** [comment]
https://github.com/didi/LogicFlow/issues/1110
