### ISSUE TITLE
如何实现修改边的始末端点，谢谢

### ISSUE THREAD

**Issue by luoyiping250** [didi/LogicFlow#1218]
## 问题背景

假设已有边A->B，现在想通过拖拽边修改为A->C。
当前是否已支持该需求（未找到相关文档介绍）。
谢谢！

**Comment by wumail** [comment]
移步[discussions](https://github.com/didi/LogicFlow/discussions)，或在相关交流群里提问

**Comment by wumail** [comment]
「触发边拖拽事件-->记录原始边和开始位置-->触发[锚点拖拽连线](anchor:dragstart)事件-->触发[锚点拖拽](anchor:drop)事件-->删除记录的原始的边 」可以试试这个思路
