### ISSUE TITLE
[Bug report] 缩放浏览器到80%, 通过导出base64/下载图片, 图片会出现显示不全的情况 

### ISSUE THREAD

**Issue by JunCxio** [didi/LogicFlow#1222]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件，如何复现
  缩放浏览器到80%, 通过getSnapshotBase64导出base64或下载图片

2. 期望的表现
   图片会出现显示完整

3. 实际的表现
  图片会出现显示不全

## 最简复现

![image](https://github.com/didi/LogicFlow/assets/37202266/177fbd0e-dc81-42f3-925c-43f5f94c699e)

![image](https://github.com/didi/LogicFlow/assets/37202266/6b68f387-f193-47ac-9736-ae4bb9e2d033)

![image](https://github.com/didi/LogicFlow/assets/37202266/5ccc637a-1e1d-4ab3-8091-1d39520b52ac)

## 相关信息 context

LogicFlow Version:
Node Version:
Platform:

**Comment by wumail** [comment]
什么版本？

**Comment by JunCxio** [comment]
> 什么版本？

1.2.9

**Comment by boyongjiong** [comment]
@JunCxio 这个你是你用这个 demo 本地更新了版本吗？https://xinxin93.github.io/logicflow_vue_demo/#/

**Comment by JunCxio** [comment]
> @JunCxio 这个你是你用这个 demo 本地更新了版本吗？https://xinxin93.github.io/logicflow_vue_demo/#/

上面我用的是官方的demo演示的, 我们自己的项目用最新的包也存在这个问题

**Comment by wbccb** [comment]
这个还不太好解决，image内部内容是一个svg，svg的大小是固定，目前代码逻辑调试下是不受image影响的，当svg的大小超过`canvas.width`和`canvas.height`本身的大小时，会出现绘制不完全的情况，当缩放浏览器比例时，`window.devicePixelRatio`会跟着降低，从而`canvas.width`和`canvas.height`也变小，从而导致了缩放时的绘制不完全

目前我能想到的解决方法就是: 
- 要么缩放svg的大小跟`canvas.width`和`canvas.height`相同
- 要么调整`canvas.width`和`canvas.height`跟svg的大小相同

-----
相对来说，调整`canvas.width`和`canvas.height`跟svg的大小相同会比较容易实现些，具体做法为：
- 修正下canvas.style.width的大小，跟实际svg大小有点偏差
```js
const svgContent = document
    .querySelector('.lf-canvas-overlay').getElementsByTagName('g')[0];
const svgContentRect = svgContent.getBoundingClientRect();
bboxWidth = svgContentRect.width + 80;
bboxHeight = svgContentRect.height + 80;
```
- 检测到canvas.width小于svg的大小时，也就是canvas.width小于canvas.style.width时，强制转化为相等，因为`canvas.width = bboxWidth * dpr`本质是为了让画出来的东西没有那么模糊（CSS像素填充的物理像素个数符合window.devicePixelRatio的比例），如果`dpr<1`，那么`canvas.width`直接等于`canvas.style.width`应该是没啥问题的
```js
if(bboxWidth*dpr < bboxWidth) {
    canvas.width = bboxWidth;
}
if(bboxHeight*dpr <bboxHeight) {
    canvas.height = bboxHeight;
}
ctx.drawImage(img, 0, 0);
resolve(canvas);
```
不过具体的实现细节还得再思考完善下，上面我这种做法调试下来是能够解决缩放时的导出图片问题

**Comment by wbccb** [comment]
缩放浏览器可以缩放到最低比例，缩放比例时会导致`window.devicePixelRatio`变小，当`window.devicePixelRatio`小到一定程度时，会导致绘制的`canvas.width`<`canvas.style.width`，此时就能复现导出图片出现显示不全的情况 @boyongjiong
