### ISSUE TITLE
[需求] organizer示例想改成vue3+elementplus版本，结果产生了各种问题，求vue3版本的示例

### ISSUE THREAD

**Issue by gyp8735abc** [didi/LogicFlow#1223]
## 问题背景

organizer示例想改成vue3+elementplus版本，结果产生了各种问题，求vue3版本的示例

## 提案

organizer原有的vue2代码在vue3中加载的节点异常

**Comment by psrheartache** [comment]
> ## 问题背景
> organizer示例想改成vue3+elementplus版本，结果产生了各种问题，求vue3版本的示例
> 
> ## 提案
> organizer原有的vue2代码在vue3中加载的节点异常

之前踩坑写了一个Vue3简单的demo，[didi-Logic-Flow-Demo-Vue3-Ts](https://github.com/psrheartache/didi-Logic-Flow-Demo-Vue3-Ts), 可以看看能否满足你的需求。 因为项目原因，很多功能无法开放， 有Vue3的项目问题，可以私信交流。

**Comment by gyp8735abc** [comment]
> > ## 问题背景
> > organizer示例想改成vue3+elementplus版本，结果产生了各种问题，求vue3版本的示例
> > ## 提案
> > organizer原有的vue2代码在vue3中加载的节点异常
> 
> 之前踩坑写了一个Vue3简单的demo，[didi-Logic-Flow-Demo-Vue3-Ts](https://github.com/psrheartache/didi-Logic-Flow-Demo-Vue3-Ts), 可以看看能否满足你的需求。 因为项目原因，很多功能无法开放， 有Vue3的项目问题，可以私信交流。

好的，非常感谢

**Comment by shitou158** [comment]
我也有这个问题，你解决了么，有解决办法吗
