### ISSUE TITLE
[需求] 希望连线可以增加<foreignObject>标签，可以自定义Edge View

### ISSUE THREAD

**Issue by xiaotaokh** [didi/LogicFlow#1226]
## 问题背景
> 希望连线可以增加`<foreignObject>`标签，可以自定义`Edge View`
```
class customEdge extends PolylineEdge {
  // 自定义HTML
}
```
类似节点的`setHtml`一样:
```javascriptt
class userTaskNode extends HtmlNode {
  setHtml(rootEl) {
    // 自定义HTML
  }
}
```

**Comment by boyongjiong** [comment]
有什么场景需要自定义线的 View 呢？

**Comment by towersxu** [comment]
这个功能已经支持，可以参考[自定义连线](https://site.logic-flow.cn/docs/#/zh/guide/basic/edge?id=custom-edges-based-on-react-components)或者[自定义连线文本](https://github.com/Logic-Flow/docs/blob/f2360b4fdf96592064d9bf6f15a79e89450c520f/demo/organizer/src/node/logicLine.js#L102).
