### ISSUE TITLE
[Optimize] polygonLine pointList更新优化

### ISSUE THREAD

**Issue by wumail** [didi/LogicFlow#1227]
每当节点移动时，折线的pointList都会根据新的起始点坐标重新计算，不保证线的最小变化，很多时候不能合预期，也不够优雅
### 现状：
像在走路🚶一样，🤪
![ezgif-1-ae8e16e013](https://github.com/didi/LogicFlow/assets/56008486/1bda6a6d-e48f-44e2-bc4f-98f5da0ea764)
### 预期：
🤵
![ezgif-3-58f527a868](https://github.com/didi/LogicFlow/assets/56008486/5f278d94-4ceb-4b98-bfe6-80ddb04851ac)

**Comment by yabinliu** [comment]
有解决方案吗？
