### ISSUE TITLE
[Bug report]logicflow 更新的时候遇到其内部引用的 bpmn-io/ids 依赖在由 ids 依赖 1.0.3 升级到 1.0.4时，ids 依赖构建失败，导致安装了 logiflow/extension的工程启动失败。

### ISSUE THREAD

**Issue by ZhangChongLing** [didi/LogicFlow#1228]
## 问题描述

logicflow/extension 更新的时候遇到其内部引用的 bpmn-io/ids 依赖在由 ids 依赖 1.0.3 升级到 1.0.4时，ids 依赖构建失败，导致安装了 logiflow/extension的工程启动失败。这是  bpmn-io/ids 1.0.4 构建失败的 bug#8 导致的（ https://github.com/bpmn-io/ids/issues/8 ）。

1. 问题触发的条件，如何复现

新空间 npm i 安装 logicflow，然后启动工程（删除旧依赖和 .lock 重新安装也能复现。）会抛出 logicflow/extension 中找不到 ids 的问题。

![image](https://github.com/didi/LogicFlow/assets/41157476/3ace1e43-790d-4be9-8651-6a40839af652)

![d343af87e2bd409a9071ad282f015ae](https://github.com/didi/LogicFlow/assets/41157476/411e19c8-6170-42ae-ad95-5852d8408dec)

上图是 ids 1.0.4 构建失败，没产生 dist 文件的情形。

3. 期望的表现

新安装的 logicflow 能正常使用。

## 相关信息 context

LogicFlow Version: v1.2.9
Node Version: v14.19.0
Platform: npm/window/webstorm

**Comment by kuizuo** [comment]
<img width="931" alt="image" src="https://github.com/didi/LogicFlow/assets/61005888/439e3c27-8187-4480-a9d6-0f6a2f952fc2">

我也遇到同样的问题，1.0.0 版本构建没问题，因此目前的解决方案是手动安装 ids 并指定版本 1.0.0，即 `pnpm add ids@1.0.0`，如果不行的话可以在 package.json 中添加 overrides 字段如下

```json
  "overrides": {
    "ids": "1.0.0"
  }
```

**Comment by ZhangChongLing** [comment]
请放心，您的邮件已收到。
