### ISSUE TITLE
[Feature Request] 版本能否内置一个连线优化的功能

### ISSUE THREAD

**Issue by psrheartache** [didi/LogicFlow#1230]
## 问题背景

LogicFlow feature版本能否内置一个连线优化的功能，目前的连线方案， 在视图拖拽之后略显呆板。

## 提案

比如现在创建一个连线，如下：

<img width="678" alt="image" src="https://github.com/didi/LogicFlow/assets/13062319/723ca417-e53e-44a0-aa00-b087991ae11b">

拖拽之后现状，如下：

<img width="440" alt="image" src="https://github.com/didi/LogicFlow/assets/13062319/3db4f668-7b36-4b62-869b-199ad3027d38">

期望：

<img width="891" alt="image" src="https://github.com/didi/LogicFlow/assets/13062319/cb0ae412-5d1b-4e81-9c18-de5d40d0dd91">

继续拖动，期望：

<img width="680" alt="image" src="https://github.com/didi/LogicFlow/assets/13062319/7c5f069a-2d8e-4810-8d9a-651ec2b7b397">

位置拖拽后，视图更新希望连接锚点会随着始、末节点的相对位置进行动态优化， 来达到连线更符合用户直觉。

**Comment by wumail** [comment]
可以尝试通过自定义边，重写updatePoints方法，自行决定连线路径

**Comment by psrheartache** [comment]
> 可以尝试通过自定义边，重写updatePoints方法，自行决定连线路径

感谢提供思路，

![image](https://github.com/didi/LogicFlow/assets/13062319/439668e1-4ca3-42bf-81e8-bc565c9006b4)

<img width="550" alt="image" src="https://github.com/didi/LogicFlow/assets/13062319/88fb7d8c-e23d-43f1-996d-771f5c86e44a">

我看了下官方的实现代码， getBezierControlPoints 和 getControls这些都没有办法在继承类中使用，官方npm包中也并没有export出来， 无法使用。   重写updatePoints后， 两个node节点无法连线， 请问有什么解决方案吗？

**Comment by wumail** [comment]
> > 可以尝试通过自定义边，重写updatePoints方法，自行决定连线路径
> 
> 感谢提供思路，
> 
> ![image](https://user-images.githubusercontent.com/13062319/255550637-439668e1-4ca3-42bf-81e8-bc565c9006b4.png)
> 
> <img alt="image" width="550" src="https://user-images.githubusercontent.com/13062319/255551230-88fb7d8c-e23d-43f1-996d-771f5c86e44a.png">
> 我看了下官方的实现代码， getBezierControlPoints 和 getControls这些都没有办法在继承类中使用，官方npm包中也并没有export出来， 无法使用。 重写updatePoints后， 两个node节点无法连线， 请问有什么解决方案吗？

如果是polyline只需要根据自己的规则算出点并赋值给this.pointList就行；getBezierControlPoints 和 getControls是用来 获取beizer曲线控制点的，计算逻辑比较简单，可以直接从源码里复制出来用，也可以按自己的逻辑算出来，可以参考https://juejin.cn/post/6942727734518874142?searchId=20230717155523FF2BD606640B7E05D760#heading-3

**Comment by wumail** [comment]
> > 可以尝试通过自定义边，重写updatePoints方法，自行决定连线路径
> 
> 感谢提供思路，
> 
> ![image](https://user-images.githubusercontent.com/13062319/255550637-439668e1-4ca3-42bf-81e8-bc565c9006b4.png)
> 
> <img alt="image" width="550" src="https://user-images.githubusercontent.com/13062319/255551230-88fb7d8c-e23d-43f1-996d-771f5c86e44a.png">
> 我看了下官方的实现代码， getBezierControlPoints 和 getControls这些都没有办法在继承类中使用，官方npm包中也并没有export出来， 无法使用。 重写updatePoints后， 两个node节点无法连线， 请问有什么解决方案吗？

「重写后无法连线」检查写法是否有问题 👀 https://github.com/didi/LogicFlow/issues/1232
