### ISSUE TITLE
保存图片时，可以根据图片的缩放保存图片吗？

### ISSUE THREAD

**Issue by zhangluluaichimi** [didi/LogicFlow#1233]
## 问题背景

图片有时候会考虑打印出来，如分辨率太小，打印出来是模糊的

**Comment by wumail** [comment]
![image](https://github.com/didi/LogicFlow/assets/56008486/6d5266c9-c852-4336-887c-19554291863a)
图片的大小上根据元素实际的大小确定的，想要元素变大且不模糊，一是把LogicFlow画布中的元素就缩放到理想大小，二是不修改原画布内容，将画布上到svg元素复制一份，通过设置形变将元素放大到理想大小再导出
