### ISSUE TITLE
画布上 内容过多以及数据处理过多，会出现拖拽 双击，刷新渲染等 卡顿问题？

### ISSUE THREAD

**Issue by HTML110** [didi/LogicFlow#1234]
![image](https://github.com/didi/LogicFlow/assets/33749705/0e98ac38-6c7d-49c9-9e0f-e1ab9a30b358)
请问，有没有好的处理方案，或者如何去解决这些问题  给个思路

**Comment by wangzhengbo** [comment]
节点过多，确实有卡顿问题。不知道官方有没有做过性能测试，大概最多能支持多少量的边/节点

**Comment by wumail** [comment]
现在没办法的，渲染出来的都是实实在在的DOM节点

**Comment by HTML110** [comment]
把这些节点放大到一定效果，卡顿的就没那个明显了，但是依然能让你感觉的到， @towersxu

**Comment by wbccb** [comment]
最好提供个在线demo(填充目前展示的大量数据)。我尝试看看能不能优化下

**Comment by wangyong991** [comment]
> ![image](https://private-user-images.githubusercontent.com/33749705/254197663-0e98ac38-6c7d-49c9-9e0f-e1ab9a30b358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzAxMDEsIm5iZiI6MTcwMTkyOTgwMSwicGF0aCI6Ii8zMzc0OTcwNS8yNTQxOTc2NjMtMGU5OGFjMzgtNmM3ZC00OWM5LTllMGYtZTFhYjlhMzBiMzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA2MTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZWMxOTAyYTM3NDcyYzYyZGZlM2EzYWQ0ODMxMDE3ZTM1ZGE1ZjY4NDllNTU2YmIwYzg3YmQ4ZGMxYzg1ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yA8feZKeB5GDx5TIRIWkrSkWLY4fdx0YgXd_fwLhpLc) 请问，有没有好的处理方案，或者如何去解决这些问题 给个思路

我最近也碰到这个问题，我这边排查发现的是，在自定义节点的properties 属性中，有一个属性值是一个ref对象。把这个ref删掉或者unref，缩放和拖拽就不卡了。目前我最多试了70多个节点。你可以参考看看有没有相同的情况，或者删掉自定义的东西，用他原本的节点渲染是否有卡顿。
