### ISSUE TITLE
[Bug report]分组设置isRestrict没有反应

### ISSUE THREAD

**Issue by zhangluluaichimi** [didi/LogicFlow#1239]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件，如何复现:推拽自定义的分组图形，设置了isRestrict为true,并没有效果
2. 期望的表现：分组里面的子组件不能拖拽到分组框外面去
3. 实际的表现：分组里面的子组件能拖拽到分组框外去

## 最简复现

一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：

1. 在任意在线编码平台如 codesanbox 编写示例。将其保存到自己空间，然后贴上链接。
2. 在自己 github 中创建一个最简单的示例，然后贴上 github 链接。
3. 删除项目中的 node_modules 部分，打包项目，并拖拽到 issue 输入框中上传（或提供远程可下载地址）。

## 相关信息 context

LogicFlow Version:
[Group.zip](https://github.com/didi/LogicFlow/files/12104202/Group.zip)

Node Version:
Platform:

**Comment by wbccb** [comment]
提供的Group.zip经过测试，`isRestrict=true`是有效的
# 可能存在的代码问题
你拖拽形成分组元素到网格后，再拖入元素，由于`src/components/Diagram.vue`没有加入`plugins: [Group]`，因此拖入的元素是不会加入到分组的，也造成了`isRestrict=true`无效的错误
```js
const lf = new LogicFlow({
    //...
    plugins: [Group]
})
```

提供的Group.zip中的`src/components/Diagram.vue`加入`plugins: [Group]`代码后，拖入的元素会加入到分组，`isRestrict=true`是有效的

@zhangluluaichimi 如果不是上述原因，可以再进行反馈
