### ISSUE TITLE
LogicFlow使用情况收集有奖问卷

### ISSUE THREAD

**Issue by Serendipity96** [didi/LogicFlow#124]
### 谁在使用 LogicFlow？
感谢正在使用和关注 LogicFlow 的开发者，我们会持续投入，让 LogicFlow 项目和社区更加繁荣。

### 这个 issue 的出发点
- 聆听社区的声音，让 LogicFlow 解决实际的问题
- 吸引更多的开发者参与和贡献
- 更多的了解 LogicFlow 的实际使用场景，以便后续版本的计划

### 我们期待您能提供
参与LogicFlow问卷，问卷地址：[https://wj.qq.com/s2/9588335/2b7b/](https://wj.qq.com/s2/9588335/2b7b/)。我们会每隔一段时间抽出一部分填写问卷的用户，送出LogicFlow纪念T恤。（目前已经送出第一批30名用户）

**Comment by anncwb** [comment]
目前刚刚尝试使用，遇到的问题还是挺多，打包警告，控制台警告，点击延时，函数获取坐标NaN，没提供函数不能动态修改配置。做了一个示例发现了好多小bug，就不一一提issue了，等你们后面稳定在继续完善的示例。

组织：开源后台示例
使用场景：用于流程图示例程序
![image](https://user-images.githubusercontent.com/28132598/115117644-3a993600-9fd2-11eb-91cd-0918718d7dbf.png)

**Comment by jonny201251** [comment]
logicflow中包含BPMN元素，什么时候添加 bpmn:ParallelGateway并行网关、bpmn:Participant泳道？

**Comment by jonny201251** [comment]
logicflow中包含BPMN元素，有计划添加 [bpmn:ParallelGateway并行网关、bpmn:Participant泳道

**Comment by jonny201251** [comment]
logicflow中包含BPMN元素，有计划添加 [bpmn:ParallelGateway并行网关、bpmn:Participant泳道
组织：合肥市惠冉信息科技有限公司
联系方式：jonny201251@163.com
使用场景：开发公司各种日常审批业务

**Comment by JOJO-CPU** [comment]
请问此插件支持ts语法吗

**Comment by LingXin0** [comment]
turbo 什么时候开源，是与LogicFlow无缝对接的吗？

**Comment by javahuang** [comment]
![Jietu20220217-212029@2x](https://user-images.githubusercontent.com/3992393/154490382-25369731-e3fc-4148-9eb7
![Jietu20220217-212348@2x](https://user-images.githubusercontent.com/3992393/154490624-1287232f-4761-40d7-9903-e1935ae5a695.jpg)
-aa72eeddcb1d.jpg)

系统：卷王调查问卷系统
地址：https://surveyking.cn
使用场景：表单工作流

**Comment by zhuqingguang** [comment]
公司内部系统正在使用，感谢开源

**Comment by WangShuXian6** [comment]
组织：哈尔滨消费金融科技前端团队
联系方式： 微信号 airmusic [我已加入官方微信群]
使用场景：风险控制系统拖拽生成决策规则与流程
