### ISSUE TITLE
一个大元素，里面放几个小元素，然后开启框选，起点在大元素里面 大元素里面的小元素不能被选中，

### ISSUE THREAD

**Issue by HTML110** [didi/LogicFlow#1240]
有没有好的解决方案，这个相当于在元素上面放元素了，希望您能理解我的意思
![1689903595036](https://github.com/didi/LogicFlow/assets/33749705/62a6f242-a31e-4b54-8580-fcd3bff37de8)

**Comment by boyongjiong** [comment]
目前这个 issue 的描述信息不全，先关闭，如果能提供一个示例帮助我们确认问题，可以重新打开

**Comment by boyongjiong** [comment]
如果是分组，分组内的小元素目前是不支持被选中的。如果是三个独立的元素，应该是可以选中的
