### ISSUE TITLE
[Feature Request]设置节点锚点id，节点可通过锚点id自动连线

### ISSUE THREAD

**Issue by GM-117** [didi/LogicFlow#1241]
## 问题背景

通过 getDefaultAnchor 设置锚点，能否在数据 edges 中设置 sourceAnchorId 与 targetAnchorId 自动连接对应节点的锚点。
设置 TA0001 节点右锚点 与 TA0002 节点左锚点自动连线

目前查询文档未看到有此功能。
感谢🙇‍
## 相关信息
![image](https://github.com/didi/LogicFlow/assets/48324205/ba857af3-2ef0-439a-93ec-8b599b631a81)
![image](https://github.com/didi/LogicFlow/assets/48324205/faabf970-cf02-4f90-bc53-ac1309326fc0)

**Comment by wumail** [comment]
什么场景需要这么做呢

**Comment by GM-117** [comment]
在绘制层次图中，通过数据的配置，指定 edges 中的 sourceAnchorId 与 targetAnchorId 能够将两个节点 node 对应锚点连接起来。

例如：
指定 TEST01 下边锚点 与 TEST02 & TEST03 左边锚点通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线
而不是通过 pointsList 绘制直角位置坐标来实现。
![image](https://github.com/didi/LogicFlow/assets/48324205/ef863d08-7455-4deb-ba56-918ef90dee0e)

感谢🙇‍

**Comment by wumail** [comment]
> 在绘制层次图中，通过数据的配置，指定 edges 中的 sourceAnchorId 与 targetAnchorId 能够将两个节点 node 对应锚点连接起来。
> 
> 例如： 指定 TEST01 下边锚点 与 TEST02 & TEST03 左边锚点通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现。 ![image](https://user-images.githubusercontent.com/48324205/255516443-ef863d08-7455-4deb-ba56-918ef90dee0e.png)
> 
> 感谢🙇‍

「通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现」没太看懂，如果通过addEdge绘制有哪里不符合预期吗 👀https://docs.logic-flow.cn/docs/#/zh/api/logicFlowApi?id=addedge

**Comment by wumail** [comment]
> > 在绘制层次图中，通过数据的配置，指定 edges 中的 sourceAnchorId 与 targetAnchorId 能够将两个节点 node 对应锚点连接起来。
> > 例如： 指定 TEST01 下边锚点 与 TEST02 & TEST03 左边锚点通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现。 ![image](https://user-images.githubusercontent.com/48324205/255516443-ef863d08-7455-4deb-ba56-918ef90dee0e.png)
> > 感谢🙇‍
> 
> 「通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现」没太看懂，如果通过addEdge绘制有哪里不符合预期吗 👀https://docs.logic-flow.cn/docs/#/zh/api/logicFlowApi?id=addedge 自己算出起始点下锚点和终点左锚点

后续可以支持，可以先尝试这样做

**Comment by GM-117** [comment]
> > 在绘制层次图中，通过数据的配置，指定 edges 中的 sourceAnchorId 与 targetAnchorId 能够将两个节点 node 对应锚点连接起来。
> > 例如： 指定 TEST01 下边锚点 与 TEST02 & TEST03 左边锚点通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现。 ![image](https://user-images.githubusercontent.com/48324205/255516443-ef863d08-7455-4deb-ba56-918ef90dee0e.png)
> > 感谢🙇‍
> 
> 「通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现」没太看懂，如果通过addEdge绘制有哪里不符合预期吗 👀https://docs.logic-flow.cn/docs/#/zh/api/logicFlowApi?id=addedge 自己算出起始点下锚点和终点左锚点

不符合预期
![image](https://github.com/didi/LogicFlow/assets/48324205/97fd6a94-3c0b-4637-87bf-c8923c6a1e46)

**Comment by GM-117** [comment]
例如：https://antv-g6.gitee.io/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper
![image](https://github.com/didi/LogicFlow/assets/48324205/a441fb0c-1562-499e-9eac-d8e9ba3a93e1)

如这种实现，可以在edges中设置节点锚点的值，连线将根据节点锚点进行相连，并且直角绘制不会出现曲折

![image](https://github.com/didi/LogicFlow/assets/48324205/57b8331b-85c1-484b-af5a-247d9fd100a8)

在logicFlow中查阅文档，可以为每个节点上下左右锚点设置对应的id，能否通过 sourceAnchorId 与 targetAnchorId 将两个节点 node 对应锚点连接起来

感谢🙇‍

**Comment by wumail** [comment]
> > > 在绘制层次图中，通过数据的配置，指定 edges 中的 sourceAnchorId 与 targetAnchorId 能够将两个节点 node 对应锚点连接起来。
> > > 例如： 指定 TEST01 下边锚点 与 TEST02 & TEST03 左边锚点通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现。 ![image](https://user-images.githubusercontent.com/48324205/255516443-ef863d08-7455-4deb-ba56-918ef90dee0e.png)
> > > 感谢🙇‍
> > 
> > 
> > 「通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现」没太看懂，如果通过addEdge绘制有哪里不符合预期吗 👀https://docs.logic-flow.cn/docs/#/zh/api/logicFlowApi?id=addedge 自己算出起始点下锚点和终点左锚点
> 
> 不符合预期 ![image](https://user-images.githubusercontent.com/48324205/255526493-97fd6a94-3c0b-4637-87bf-c8923c6a1e46.png)

这里pointsList计算规则最近会改一版，我测试了改版后的应该是符合你预期的。至于通过锚点ID连线的这个问题，后续可以支持

**Comment by GM-117** [comment]
感谢 🙇‍

> > > > 在绘制层次图中，通过数据的配置，指定 edges 中的 sourceAnchorId 与 targetAnchorId 能够将两个节点 node 对应锚点连接起来。
> > > > 例如： 指定 TEST01 下边锚点 与 TEST02 & TEST03 左边锚点通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现。 ![image](https://user-images.githubusercontent.com/48324205/255516443-ef863d08-7455-4deb-ba56-918ef90dee0e.png)
> > > > 感谢🙇‍
> > > 
> > > 
> > > 「通过 edges 中配置的 sourceAnchorId 与 targetAnchorId 绘制直角连线 而不是通过 pointsList 绘制直角位置坐标来实现」没太看懂，如果通过addEdge绘制有哪里不符合预期吗 👀https://docs.logic-flow.cn/docs/#/zh/api/logicFlowApi?id=addedge 自己算出起始点下锚点和终点左锚点
> > 
> > 
> > 不符合预期 ![image](https://user-images.githubusercontent.com/48324205/255526493-97fd6a94-3c0b-4637-87bf-c8923c6a1e46.png)
> 
> 这里pointsList计算规则最近会改一版，我测试了改版后的应该是符合你预期的。至于通过锚点ID连线的这个问题，后续可以支持

感谢🙇‍

**Comment by DymoneLewis** [comment]
> 例如：https://antv-g6.gitee.io/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper ![image](https://private-user-images.githubusercontent.com/48324205/255527405-a441fb0c-1562-499e-9eac-d8e9ba3a93e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDQyOTMsIm5iZiI6MTcxMTAwMzk5MywicGF0aCI6Ii80ODMyNDIwNS8yNTU1Mjc0MDUtYTQ0MWZiMGMtMTU2Mi00OTllLTllYWMtZDhlOWJhM2E5M2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNjkyMWIyOTljYjYzNWFiYTk1N2EwZDhkYTkxZjE0MDNlNDc5NTJmNDY3NWM1ZGFlOGU4YTcwZDFlYWRiZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWTswzifDPHz6TQN0bWb4HDS627BoMH6ne7LRcrgoq4)
> 
> 如这种实现，可以在edges中设置节点锚点的值，连线将根据节点锚点进行相连，并且直角绘制不会出现曲折
> 
> ![image](https://private-user-images.githubusercontent.com/48324205/255527593-57b8331b-85c1-484b-af5a-247d9fd100a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDQyOTMsIm5iZiI6MTcxMTAwMzk5MywicGF0aCI6Ii80ODMyNDIwNS8yNTU1Mjc1OTMtNTdiODMzMWItODVjMS00ODRiLWFmNWEtMjQ3ZDlmZDEwMGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZWMyNTY3Mjk5NTFiZjI5ZTJkN2VhYTM3ODBlZTAxMzRkZjU2NzYzYzcwZDRmY2E4OTlhZTU0ZGM2YWQ3YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yKypoIv034L02f252gaNLwEaFZ5WE9XykaDUg0ZQVUk)
> 
> 在logicFlow中查阅文档，可以为每个节点上下左右锚点设置对应的id，能否通过 sourceAnchorId 与 targetAnchorId 将两个节点 node 对应锚点连接起来，而不是计算节点锚点的位置，通过锚点id就可以连接~
> 
> 感谢🙇‍

该功能已于1.2.23版本支持上了，请试下呢~
