### ISSUE TITLE
[Bug report]react引入snapshot插件就报错

### ISSUE THREAD

**Issue by jasmine-song** [didi/LogicFlow#1243]
## 问题描述

react单纯引入snapshot插件就报错, 没有任何后续操作
报错内容：getBpmnId.js:5:11里的ids_1.default is not a constructor 

如图
```
import { Snapshot } from '@logicflow/extension';
```
![image](https://github.com/didi/LogicFlow/assets/44150070/48fa63e1-1da6-43a7-960d-e6aecba7091d)
![image](https://github.com/didi/LogicFlow/assets/44150070/fa86fbed-02e3-4e14-88ad-2635c52cd926)

## 相关信息 context
 "@types/react": "16.9.25",
 "@types/react-dom": "16.9.5",
 "@logicflow/core": 1.2.8，
 "@logicflow/extension": 1.2.10

Node Version:14.1.0

**Comment by wumail** [comment]
👀 https://github.com/didi/LogicFlow/issues/1228

**Comment by jasmine-song** [comment]
> 👀 #1228 #1229

![image](https://github.com/didi/LogicFlow/assets/44150070/2940e619-7bf2-4803-8300-51fc184a4355)
![image](https://github.com/didi/LogicFlow/assets/44150070/c0190326-859e-44c0-a8c2-17dc6cb6eb67)
![image](https://github.com/didi/LogicFlow/assets/44150070/16586e84-1989-4dac-8326-8d3a21a6db3c)

我认为可能不是一个错误类型，上面是构建失败 报not found，我package-lock中ids版本1.0.5，构建成功ids下是有dist的
![image](https://github.com/didi/LogicFlow/assets/44150070/3ac61bb4-e735-4668-a26b-de8c8461cc42)
并且我无论写死ids依赖未1.0.0还是1.0.3 都会报`ids_1.default is not a constructor`

**Comment by boyongjiong** [comment]
经沟通，该 issue 可能是项目构建配置导致，目前无法提供可复现示例，先关闭 issue

**Comment by jasmine-song** [comment]
是经典的esm和cjs混入问题，引入extension导出的cjs包应该可以复现问题。

源码写了import Ids from 'ids'; 相当于cjs的默认导入，编译后就会变成一个对象的default属性
而引入的ids也作为我的第三方npm包也是编译好的cjs，模块本身导出就是module.exports={}。
直接返回目标模块的 module.exports 对象，所以去找default属性找不到。 应该以别名方式引入ids或者ids作为内嵌包

已解决。总结在此文中 [](https://juejin.cn/spost/7262243685899681851)
