### ISSUE TITLE
[Feature Request]连线过于生硬

### ISSUE THREAD

**Issue by wojiaoxiaomayun** [didi/LogicFlow#1248]
## 问题背景

logicflow已经相当优秀了，支撑了好多项目，但是有时候比较喜欢连线时感觉软软的感觉，感觉挺高大上的，找了个例子，目前连线比较生硬，并且只暴露了设置样式的配置，而且仅支持直线，而且感觉拖拽节点时连线的变化也比较生硬

## 提案
本连线指的是连接时从开始锚点出来的那条线
暴露出自定义连线的接口，或者优化下连线配置

## 相关信息

![bb7534ba72162e4f86c80bfba5589af](https://github.com/didi/LogicFlow/assets/30283623/408d7af3-4ade-41a5-8c5e-0b1bee9b1132)

https://github.com/didi/LogicFlow/assets/30283623/38d3c6d6-58ae-44ba-b12b-f9f2b92df3d7

**Comment by wumail** [comment]
👀 #1354
