### ISSUE TITLE
[Bug report]请问有什么方法可以阻止node双击事件

### ISSUE THREAD

**Issue by ascendQing** [didi/LogicFlow#1251]
## 问题描述

现在监听node双击事件，弹出一个弹窗，需要把框架的编辑node名称的这个功能阻止掉，尝试用data.e.stopPropagation()，但并没有阻止掉

## 最简复现

this.lf.on('node:dbclick', data => {
      data.e.stopPropagation()
    })

## 相关信息 context

LogicFlow Version:
Node Version:
Platform:

**Comment by wumail** [comment]
可以尝试通过lf.eventCenter.off('node:dbclick')清除所有注册的node:dbclick监听事件，再重新注册你自己的。另外，你这个不是bug report。
