### ISSUE TITLE
如何给边添加条件表达式

### ISSUE THREAD

**Issue by cfc3058353263** [didi/LogicFlow#1253]
如何给边添加条件表达式 conditionExpression 
![image](https://github.com/didi/LogicFlow/assets/52273637/dca6f294-4930-40b3-a15d-42bb21505555)

**Comment by wumail** [comment]
下周会发布一个新版本的BPMN插件，可以适配对此类数据的转换。

**Comment by cfc3058353263** [comment]
请问这周是什么时间发布呢

**Comment by wumail** [comment]
> 请问这周是什么时间发布呢

新插件的代码已经合入master分支了，你可以先把bpmn-elements和bpmn-elements-adapter对应的文件取出来放在本地使用
