### ISSUE TITLE
[Feature Request]校验规则message动态

### ISSUE THREAD

**Issue by html5manong** [didi/LogicFlow#1255]
## 问题背景

节点连接规则校验，message可以动态修改吗。比如我想提示xxx节点不能重复连接。xxx是validate中source或者target才可以获取到

## 提案

![image](https://github.com/didi/LogicFlow/assets/20991636/bfc20910-299a-48c1-b45a-22ab1dc2ba16)
## 相关信息

一些关于需求的额外信息和截图

**Comment by wumail** [comment]
写多个规则，判断逻辑不同文案不同就行了吧？
