### ISSUE TITLE
自定义锚点后，连线功能无效了，不能连线 [Bug report]

### ISSUE THREAD

**Issue by woshikey** [didi/LogicFlow#1259]
getAnchorShape(anchorData) {
            const { x, y,type } = anchorData;
            return h(
                "svg",
                {
                  x: x -5,
                  y: y-15,
                  viewBox: '0 0 1024 1024',
                  width: 18,
                  height: 36,
                },
                h("path", {
                  d:"M263.769088 1020.42112l-7.254016-79.542272c400.029696-36.483072 431.11936-352.07168 431.11936-447.927296-0.512-15.511552-17.736704-409.653248-427.492352-409.653248v-79.872c389.047296 0 501.982208 319.379456 507.343872 488.257536 0.02048 234.053632-132.312064 494.865408-503.716864 528.73728z",
                  fill:"#707070"
                })
              );
        }
/

**Comment by jiahuimin99** [comment]
请问这个问题解决了吗
