### ISSUE TITLE
[Bug report]使用bump边框渲染问题

### ISSUE THREAD

**Issue by yuguaa** [didi/LogicFlow#1262]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

初始调用getNodeStyle渲染节点stroke正常，当某个条件出发，重新js调用getNodeStyle渲染节点stroke未成功，代码正常执行了，但是效果没出来

## 相关信息 context

LogicFlow Version:1.1.22
Node Version:
Platform:vue3

**Comment by wumail** [comment]
1.1.12版本？
