### ISSUE TITLE
[Feature Request]分组内的节点连接该分组上的锚点时，箭头指向可否支持从内到外

### ISSUE THREAD

**Issue by xjikun** [didi/LogicFlow#1266]
## 问题背景

分组内的节点连接该分组的锚点时，连接线的箭头指向问题，箭头指向从外指向了内部，期望连接线在内部，箭头指向从分组内指向外部

## 提案

分组内的节点，能否支持箭头指向问题（从内到外）

## 相关信息

一些关于需求的额外信息和截图
![image](https://github.com/didi/LogicFlow/assets/141391682/882fc134-05c8-4e0f-8dab-b485de356b7e)
![image](https://github.com/didi/LogicFlow/assets/141391682/ae570ffa-0e34-4090-ace6-127521bb59c4)
期望得到图二示例，目前该框架是图一展示

**Comment by wumail** [comment]
你的问题应该是如何自定义边的pointsList 
👀 https://github.com/didi/LogicFlow/issues/1232
