### ISSUE TITLE
[Bug report]动态创建节点后，第一次拖动锚点无法创建连接线。

### ISSUE THREAD

**Issue by SCTJRB** [didi/LogicFlow#1272]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

动态创建节点后，第一次拖动锚点，无法拖出连接线，需要重复拖动。动图如下：

![screencast-localhost_9090-2023 08 11-16_04_59](https://github.com/didi/LogicFlow/assets/22992476/d6131393-cf00-4a08-9a78-a10293cbd0b3)

期望：节点创建成功后，锚点只需要拖动一次，就能创建连接线

## 相关信息 context

LogicFlow Version: v1.2.9
Node Version:v16.15.0
Platform:windows 10  chrome

**Comment by boyongjiong** [comment]
你这种场景，如果确定了要连接的两个节点，直接调用 addEdge 自动连线是不是就 OK 了，还可以减少操作步长。

**Comment by SCTJRB** [comment]
这个场景存在多个节点 多个节点之间可以相互连接 所以是无法确定连接的

**Comment by SCTJRB** [comment]
这个场景存在多个节点  节点之间可以相互连接  所以无法确定连接节点
