### ISSUE TITLE
[Bug report]两个节点互相指向线条会重合，hover不到第二条线，被覆盖了

### ISSUE THREAD

**Issue by jasmine-song** [didi/LogicFlow#1275]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

两个节点互相指向线条会重合，一个节点有两个子节点时候，会看不出来哪个子节点指回的父节点，hover高亮线并不会hover到 底下的第二条线，被覆盖了

## 提案
希望能分拆开两条线，或添加属性控制多条线位置重合时如何展示，或者hover时两条线都能hover到

## 最简复现

一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：

https://codesandbox.io/s/logicflow-base7-forked-fhyytp?file=/step7/data.js
![image](https://github.com/didi/LogicFlow/assets/44150070/c58e614d-5e9f-4eb5-bec1-0c7a6c904c60)
![image](https://github.com/didi/LogicFlow/assets/44150070/d532a4e2-d66d-46ff-bd36-331c8dd2a9fe)
![image](https://github.com/didi/LogicFlow/assets/44150070/b3b0fdb3-0c56-4400-9e6a-c6d887b03311)

**Comment by boyongjiong** [comment]
![image](https://github.com/didi/LogicFlow/assets/8553969/ff170715-8c29-46bf-9738-2e487684206e)
codesandbox 里的代码有点问题吧。我把那几行注释了。

你这个场景如果多加几个锚点好不好使呢？如果是两个锚点互相连，直线肯定会有互相遮挡这样的问题。

**Comment by boyongjiong** [comment]
还有一个思路就是自定义连线的时候，参考 https://x6.antv.antgroup.com/zh/examples/edge/connector/#multiple-smooth-edges X6 的这个 demo，如果连线重叠了，自动偏移这种就互相不影响 hover 了。你可以先尝试实现一下？我们后面也补充一下类似场景的示例。
