### ISSUE TITLE
[Bug report]使用lf.changeNodeId();改变节点id后，需要拖动锚点2次才能拖出连接线

### ISSUE THREAD

**Issue by SCTJRB** [didi/LogicFlow#1279]
## 问题描述
因为我们的需求是：创建节点时，需要填写一些相关信息，填写完毕确定保存后，后端会返回一个id，然后我们使用lf.changeNodeId();替换节点默认的id后，就出现这个问题，需要拖动锚点2次才能拖出连接线，之后我先后注释了lf.changeNodeId()这句代码之后的效果如图：

![screencast-nimbus-capture-2023 08 16-11_40_05](https://github.com/didi/LogicFlow/assets/22992476/44f5289c-8481-4fa9-af21-ca6abf04dfbd)

## 期望
一次就能拖出连接线

## 相关信息 context

LogicFlow Version:1.2.9
Node Version:16.15.0
Platform:chrome

**Comment by boyongjiong** [comment]
没注释那行代码之前，等一会再连线也需要拖两次吗？

**Comment by SCTJRB** [comment]
嗯 即使等待之后 还是一样需要拖动两次

**Comment by SCTJRB** [comment]
> 没注释那行代码之前，等一会再连线也需要拖两次吗？

嗯 即使等待之后 还是一样需要拖动两次

**Comment by SCTJRB** [comment]
已解决！！！ 修改节点id后，使用lf.selectElementById();方法选中该节点即可解决该问题。
