### ISSUE TITLE
setProperties无法更新数据

### ISSUE THREAD

**Issue by Oct16th-Lcs** [didi/LogicFlow#1286]
## 问题描述

当调用setProperties方法时,更新对象数据 ,
原数据对象:
properties:{
name: '张三',
userId: '339579392646713355',
userText:'用户'
}

希望更新的数据对象:
properties:{
name: '张三',
userId: '340547697469558799',
userText:'用户'
}

调用lf.setProperties()，userId没有更新还是原来那个

**Comment by wumail** [comment]
你好，我这边没有复现，最好提供个最小复现示例

**Comment by Oct16th-Lcs** [comment]
是vue2更新对象的问题

**Comment by linlinNB** [comment]
@Oct16th-Lcs 请问老哥如何解决的，我这边也出现了同样的问题

**Comment by Oct16th-Lcs** [comment]
@linlinNB 我的是因为异步更新的问题，改成同步就行，原来临时的解决方案是点确定关闭弹窗之后单独给需要更新的字段setProperties一下
