### ISSUE TITLE
[Bug report] vite下样式警告

### ISSUE THREAD

**Issue by anncwb** [didi/LogicFlow#129]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
vite下，代码会出现警告，没在源代码内找到这行，但是是 引入`@logicflow/extension/lib/style/index.css`才出现

![image](https://user-images.githubusercontent.com/28132598/115099366-f6714b80-9f67-11eb-9133-4e373eb08292.png)

2. 期望的表现
警告消失
3. 实际的表现
出现警告

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows) mac
2. 浏览器类型 （chrome80 或者 IE11） 无关

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by M69W** [comment]
样式写法：`to xx`
`background-image: linear-gradient(top,#b2b2b2,#9b9b9b);`
改为
`background-image: linear-gradient(to top,#b2b2b2,#9b9b9b);`
