### ISSUE TITLE
[Bug report]当使用fitView调整画布缩放即使调整之后依然不能全览画面会导致不调整缩放比

### ISSUE THREAD

**Issue by a64224907** [didi/LogicFlow#1295]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 当使用fitView调整画布缩放即使调整之后依然不能全览画面会导致不调整缩放比
2. 期望：调整为最低缩放比
3.实际：依然是调整前的缩放比
[logicflowapp.zip](https://github.com/didi/LogicFlow/files/12393647/logicflowapp.zip)

**Comment by boyongjiong** [comment]
系统中设置的最低缩放比为 0.2，可以通过 setZoomMiniSize 更新最小缩放比。 

先搞个动图看下你页面的效果？

代码搞一个 codesanbox ，我们看起来更方便些

**Comment by wumail** [comment]
通过setZoomMiniSize设置最小缩放比例
