### ISSUE TITLE
[Bug report] Could not resolve "./bpmn-elements-adapter" from "./bpmn-elements-adapter?commonjs-external"  

### ISSUE THREAD

**Issue by alwaysIn-lilijie** [didi/LogicFlow#1296]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

主体框架使用的nuxt3.0，打包方式用的vite，在npm run build的时候提示Could not resolve "./bpmn-elements-adapter" from "./bpmn-elements-adapter?commonjs-external"  ，extension/es下面的文件基本上都会提示找不到

## 最简复现
猜测原因是不支持vite，commonjs，现在不知道怎么解决，dev环境是正常的，打包编译就出错了

## 相关信息 context

LogicFlow Version:1.2.10
Node Version:19
Platform:

**Comment by alwaysIn-lilijie** [comment]
<img width="1065" alt="image" src="https://github.com/didi/LogicFlow/assets/50645844/af06d683-b4b1-4b90-94b8-82ad2bd13b4c">

**Comment by wumail** [comment]
1.2.10?

**Comment by alwaysIn-lilijie** [comment]
@wumail 是的，昨天是1.2.10，刚刚卸载过后安装了最新的版本， "@logicflow/core": "^1.2.12",
    "@logicflow/extension": "^1.2.13",现在报错RollupError: Could not resolve "./bpmn-elements-adapter" from "./bpmn-elements-adapter?commonjs-external"

**Comment by alwaysIn-lilijie** [comment]
找到临时解决办法了。import { Group } from '@logicflow/extension/es/materials/group';import { MiniMap } from '@logicflow/extension/es/components/mini-map';找到准确的路径这样引入就可以了
