### ISSUE TITLE
[Feature Request] 支持点选节点或线

### ISSUE THREAD

**Issue by hipi** [didi/LogicFlow#1297]
## 问题描述

1. 支持按键 `Ctrl` `Command` 点选节点或线
2. 在框选之后的基础上按键点选节点或取消选择

**Comment by hipi** [comment]
#1212 差不多一样的 Feature

**Comment by hipi** [comment]
#1212 差不多一样的 Feature

**Comment by boyongjiong** [comment]
我先关闭这个 issue，后续 #1212 状态更新回同步通知你这边
