### ISSUE TITLE
[Feature Request]可以考虑支持节点方向可以随意变动吗

### ISSUE THREAD

**Issue by zhangluluaichimi** [didi/LogicFlow#1298]
## 问题背景

1；文字拖拽出来，移入到画布中，希望随着鼠标的方向旋转修改方向；
2：矩形的位置是倾斜的，希望可以通过旋转的方式可以改变矩形的位置；

**Comment by boyongjiong** [comment]
矩形倾斜的角度是用户随机调整的呗，能了解下什么业务场景需要这样的功能呢？

**Comment by wumail** [comment]
同 #390

**Comment by zhangluluaichimi** [comment]
> 矩形倾斜的角度是用户随机调整的呗，能了解下什么业务场景需要这样的功能呢？

1：绘制规划图；
2：文字是在绘制规划图的时候，需要不同方向文字的展示；

**Comment by boyongjiong** [comment]
已发版本，可以更新版本尝试一下
