### ISSUE TITLE
[Bug report] 导出图片不成功

### ISSUE THREAD

**Issue by html5manong** [didi/LogicFlow#1310]
## 问题描述

导出图片不成功，控制台报错：
Failed to construct 'MouseEvent': Failed to read the 'view' property from 'UIEventInit': Failed to convert value to 'Window'.
画布内用的是自定义HTML节点，涉及到的图片采用base64方式。
![image](https://github.com/didi/LogicFlow/assets/20991636/55326d29-209c-421e-95a2-23bc64ae6e07)

**Comment by wumail** [comment]
![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b7767374](https://github.com/didi/LogicFlow/assets/56008486/edaf295d-fe7d-4790-ab08-63a4d01f5bb1)

**Comment by wumail** [comment]
由于所提供信息的不充分，该 issue 被暂时关闭了。请修改 issue 以提供[最小可复现示例](https://stackoverflow.com/help/minimal-reproducible-example)(可以通过以下方式：1. 在任意在线编码平台如 codesanbox 编写示例。将其保存到自己空间，然后贴上链接。2. 在自己 github 中创建一个最简单的示例，然后贴上 github 链接。3. 删除项目中的 node_modules 部分，打包项目，并拖拽到 issue 输入框中上传（或提供远程可下载地址）)来重启 issue。
