### ISSUE TITLE
[Bug report]使用插件渲染Menu、MiniMap等会报错(vue3)

### ISSUE THREAD

**Issue by fanwww** [didi/LogicFlow#1311]
## 问题描述

**使用插件渲染Menu、MiniMap等会报错,需要手动刷新才会加载出来**
![image](https://github.com/didi/LogicFlow/assets/98572444/0a348045-484f-4363-8b2b-996464a7efb4)
![image](https://github.com/didi/LogicFlow/assets/98572444/6bcf4a27-9add-499b-97dc-1c2401732495)
![image](https://github.com/didi/LogicFlow/assets/98572444/ec38185b-4b10-483b-b401-73e23f54643b)

## 最简复现
可去这个网站看一下,不过生产环境没有报错信息,上面的报错是开发环境的报错,但是问题依然存在
https://superfan-fan.gitee.io/myweb/#/mindMaping/talking

## 相关信息 context

LogicFlow Version:
    "@logicflow/core": "^1.2.12",
    "@logicflow/extension": "^1.2.13",
Node Version:v16.17.0
Platform:vue3

**Comment by fanwww** [comment]
![image](https://github.com/didi/LogicFlow/assets/98572444/778694a4-f37c-432f-9091-64ddb9c6ad4d)
加个定时器的话就没有问题

**Comment by wumail** [comment]
还是提供一下可复现示例吧，我这里没有问题
![image](https://github.com/didi/LogicFlow/assets/56008486/2373a6cc-a325-43e9-9df3-66a2005463f8)

**Comment by fanwww** [comment]
> 还是提供一下可复现示例吧，我这里没有问题 ![image](https://user-images.githubusercontent.com/56008486/263925130-2373a6cc-a325-43e9-9df3-66a2005463f8.png)

可以拉取一下这个demo  https://github.com/fanwww/logic_flow
在切换路由的时候会出问题
![image](https://github.com/didi/LogicFlow/assets/98572444/9b21fa71-c545-4b33-ab0e-5bf588ede8f7)

**Comment by wbccb** [comment]
是`Suspense`组件导致的问题，把`Suspense`去掉就没问题了，比如下面这样

```js
<router-view v-slot="{ Component,route }">
  <Transition name="fade" mode="out-in">
    <keep-alive :exclude="['logicflow2']">
      <Suspense>
        <!-- 主要内容 -->
        <component :is="Component" :key="route.path" :name="route.name"></component>
        <!-- 加载中状态 -->
        <template #fallback>
          正在加载...
        </template>
      </Suspense>
    </keep-alive>
  </Transition>
</router-view>
```

换成：

```js
<router-view v-slot="{ Component,route }">
  <Transition name="fade" mode="out-in">
    <keep-alive :exclude="['logicflow2']">
      <component :is="Component" :key="route.path" :name="route.name"></component>
    </keep-alive>
  </Transition>
</router-view>
```

至于`Suspense`组件为什么延缓了部分组件的`render()`的执行...这个就不清楚了，调试不出来
