### ISSUE TITLE
BpmnAdapter无法渲染BPMN的xml

### ISSUE THREAD

**Issue by MusicDataFeTeam** [didi/LogicFlow#1314]
## 问题描述

借助于logicFlow的插件BpmnAdapter渲染不出来BPMN的xml？请问是我的写法有误还是？

1. 问题触发的条件，如何复现
本地有一个bpmn的xml文件，借助于BpmnAdapter和BpmnElement插件，调用lf.render，无法渲染该xml

<img width="570" alt="image" src="https://github.com/didi/LogicFlow/assets/139841095/6951bdb1-b704-4492-b394-d81a2fb7271f">

3. 期望的表现
期望可以正常渲染
5. 实际的表现
渲染为空白

## 最简复现

CodeSandBox链接为 https://codesandbox.io/s/nostalgic-snow-939h8s?file=/src/App.js

## 相关信息 context

LogicFlow Version: 1.2.12
Node Version: v17.4
Platform:

**Comment by wumail** [comment]
这个问题我们排查一下，但是推荐你用新的adapter，https://site.logic-flow.cn/docs/#/zh/guide/extension/adapter?id=%e6%96%b0%e7%9a%84bpmnadapter，还是一样的用法，亲测有效

**Comment by MusicDataFeTeam** [comment]
> 这个问题我们排查一下，但是BpmnAdapter后续不会再维护了，推荐使用新的adapter，https://site.logic-flow.cn/docs/#/zh/guide/extension/adapter?id=%e6%96%b0%e7%9a%84bpmnadapter ，还是一样的用法，亲测有效。

这个demo里面没看懂要怎么使用。直接调用lf.render会报错

**Comment by wumail** [comment]
> > 这个问题我们排查一下，但是BpmnAdapter后续不会再维护了，推荐使用新的adapter，https://site.logic-flow.cn/docs/#/zh/guide/extension/adapter?id=%e6%96%b0%e7%9a%84bpmnadapter ，还是一样的用法，亲测有效。
> 
> 这个文档里面没看懂要怎么使用。直接调用lf.render(xml) 会报错

文档里写的不是很清楚，着重介绍了导出，其实使用方式和之前的插件是差不多了，只是多了几个可选的参数。
直接调用lf.render报什么错呢，可以贴出来看下？

**Comment by MusicDataFeTeam** [comment]
> > > 这个问题我们排查一下，但是BpmnAdapter后续不会再维护了，推荐使用新的adapter，https://site.logic-flow.cn/docs/#/zh/guide/extension/adapter?id=%e6%96%b0%e7%9a%84bpmnadapter ，还是一样的用法，亲测有效。
> > 
> > 
> > 这个文档里面没看懂要怎么使用。直接调用lf.render(xml) 会报错
> 
> 文档里写的不是很清楚，只着重介绍了导出，其实使用方式和之前的插件是差不多了，只是多了几个可选的参数。 直接调用lf.render报什么错呢，可以贴出来看下？ 导入的时候还是直接lf.render(XML)就好了，如果对应的节点没有注册确实是会报错的，先确保导入的xml里所有类型的节点都在Logicflow中注册了

那应该是没注册这个节点？
![image](https://github.com/didi/LogicFlow/assets/139841095/4f6c8e5f-ab47-4215-b33f-bded2c34625d)

**Comment by wumail** [comment]
> > > > 这个问题我们排查一下，但是BpmnAdapter后续不会再维护了，推荐使用新的adapter，https://site.logic-flow.cn/docs/#/zh/guide/extension/adapter?id=%e6%96%b0%e7%9a%84bpmnadapter ，还是一样的用法，亲测有效。
> > > 
> > > 
> > > 这个文档里面没看懂要怎么使用。直接调用lf.render(xml) 会报错
> > 
> > 
> > 文档里写的不是很清楚，只着重介绍了导出，其实使用方式和之前的插件是差不多了，只是多了几个可选的参数。 直接调用lf.render报什么错呢，可以贴出来看下？ 导入的时候还是直接lf.render(XML)就好了，如果对应的节点没有注册确实是会报错的，先确保导入的xml里所有类型的节点都在Logicflow中注册了
> 
> 那应该是没注册这个节点？ ![image](https://user-images.githubusercontent.com/139841095/263951119-16fc39aa-c68a-49e5-b1f4-6829c668cbb3.png)


是的，xml的节点想要渲染出来，但是Logicflow里没注册，找不到对应类型的节点，可不就报错
