### ISSUE TITLE
[Bug report] 图片下载 报错 1px线图片不显示线

### ISSUE THREAD

**Issue by jasmine-song** [didi/LogicFlow#1317]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1.图片下载 http下控制台会报错  base64文件连接不安全错误  但还是可以下载图片

![8cbc350fb82bdb33ced0ebc7dc113db](https://github.com/didi/LogicFlow/assets/44150070/3f934837-e4ec-4049-8b13-79428253af88)

2. 下载图片1px线 不显示  2px以上才可以 . normal文字也线条看不太清 加粗才可
 
![1642980c3d29544671948b8d4befb7d](https://github.com/didi/LogicFlow/assets/44150070/9f2f9672-de43-4fb6-9303-fda83356c84a)

![image](https://github.com/didi/LogicFlow/assets/44150070/ff8db245-74ed-44ec-9866-df21865240b2)

## 相关信息 context

LogicFlow Version: 1.2.12
Node Version:
Platform:

**Comment by wbccb** [comment]
1. 能不能给个复线在线链接，塞入下当前模拟的数据

**Comment by boyongjiong** [comment]
因为长时间未回复，先将此 issue 做关闭处理
