### ISSUE TITLE
[Bug report] 使用自定义图片继承RectNewNode，下载时候的时候发现只有连线，并没有自定义图标

### ISSUE THREAD

**Issue by lixing0323** [didi/LogicFlow#1319]
## 问题描述
使用自定义图片，继承RectNewNode，拖拽在画布上正常显示。可是通过lf.getSnapshot() 下载，发现下载的图片只有连线，没有自定义图片。

这3个为自定义图标，继承的是RectResize，跟RectNewNode类似。
<img width="1134" alt="image" src="https://github.com/didi/LogicFlow/assets/19339814/7b3591a0-e7e9-402e-8dd3-90ffd9b2fb56">
然后通过 getSnapshot 方法下载，图片显示为
<img width="747" alt="image" src="https://github.com/didi/LogicFlow/assets/19339814/a0419a17-4a36-4672-a312-c3bc2debb439">

版本如下：
    "@logicflow/core": "^1.2.12",
    "@logicflow/extension": "^1.2.13",
    "vue": "2.6.14",

**Comment by wumail** [comment]
👀 https://github.com/didi/LogicFlow/issues/1076
