### ISSUE TITLE
BPMN节点连线会与文本节点重叠

### ISSUE THREAD

**Issue by MusicDataFeTeam** [didi/LogicFlow#1325]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 在使用BPMNElements插件时，选择开始节点和结束节点连线，线条会穿过文本节点。
2. 期望的表现：希望能和bpmnjs中一样，文本节点能自适应的调整位置使线条和文本不重叠
3. 实际的表现：线条会穿过文本节点

logicFlow中的表现
![image](https://github.com/didi/LogicFlow/assets/139841095/8a5c394e-7072-43f8-9497-b4088c51656c)

bpmnjs中的表现：
![image](https://github.com/didi/LogicFlow/assets/139841095/b45be820-e211-4ad5-9d60-4146de1215a1)

**Comment by boyongjiong** [comment]
我们初衷是提供 BPMN 插件作为示范，用户可以自定义去做细节优化，目前我们不会针对这个功能做优化。故先关闭此 issue
