### ISSUE TITLE
配置 adjustEdgeStartAndEnd 没有生效

### ISSUE THREAD

**Issue by ParadiseWitch** [didi/LogicFlow#1329]
## 问题描述

adjustEdgeStartAndEnd 配置设置为false时，图中圈出来的位置仍然可以拖动调节（图中指针显示拖动指针）：
![A5ZQHJ GF (U7G`~ TZ`BYN](https://github.com/didi/LogicFlow/assets/37146904/34d520a8-02fe-4436-99d5-b6ff8f7c3172)

## 最简复现
https://codesandbox.io/s/logicflow-base2-forked-4sw749?file=/src/index.js:0-429

## 相关信息 context

LogicFlow Version: 1.2.0-next.5
Node Version: v14.21.1
Platform: window10

**Comment by wumail** [comment]
| adjustEdge              | boolean | true   | 允许调整边                                                           |
| adjustEdgeMiddle        | boolean | false  | 只对折线生效，只允许调整边的中间线段，不允许调整与起点终点相连的线段 |
| adjustEdgeStartAndEnd   | boolean | false  | 允许调整边起点/终点  
当adjustEdgeStartAndEnd为true时，连线的起点和终点会有两个点，可以拖拽这两点来调整连线
图中的拖拽调整边的是中间线段，如果希望边不能被调整，设置`adjustEdge: false`
