### ISSUE TITLE
[Bug report]复制分组节点，并没有把组节点内的节点正确复制，且与被复制的组共用了子节点，逻辑错乱

### ISSUE THREAD

**Issue by xjikun** [didi/LogicFlow#1346]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件，如何复现
    分组内存在节点，复制分组时，并没有把组节点内的节点正确复制，且与被复制的组共用了子节点
2. 期望的表现
     复制分组时，正确copy一份完整的分组（与被复制的完全一致）
3. 实际的表现
    复制分组时，并没有把分组节点内的节点正确复制，且与被复制的组共用了子节点，逻辑错乱
4. 产生问题的原因
    应该是复制了当前组及组的children字段，但children中的id并没有发生改变 导致有相同的id ，所有视觉上看到并没有复制子节点，其实是共用了相同Id的子节点，解决方案 根据children字段里的id 找出子节点 进行clone ，且重新生成唯一id避免相同
## 最简复现

一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：

https://codesandbox.io/s/logicflow-base24-forked-sykj28?file=/step_24_group/index.js

1. 在任意在线编码平台如 codesanbox 编写示例。将其保存到自己空间，然后贴上链接。
2. 在自己 github 中创建一个最简单的示例，然后贴上 github 链接。
3. 删除项目中的 node_modules 部分，打包项目，并拖拽到 issue 输入框中上传（或提供远程可下载地址）。

## 相关信息 context

LogicFlow Version:
Node Version:
Platform:

**Comment by xjikun** [comment]
@wumail 你好，近期有计划修复这个bug吗，急需 感谢🙏

**Comment by wumail** [comment]
> @wumail 你好，近期有计划修复这个bug吗，急需 感谢🙏

会修复，但不保证时间，因为还要发版
取决于你需求的紧急程度，你可以尝试先覆盖默认的快捷键回调
```typescript
// 复制
  keyboard.on(['cmd + c', 'ctrl + c'], () => {
    if (!keyboardOptions.enabled) return true;
    if (graph.textEditElement) return true;
    const { guards } = lf.options;
    const elements = graph.getSelectElements(false);
    const enabledClone = guards && guards.beforeClone ? guards.beforeClone(elements) : true;
    if (!enabledClone || (elements.nodes.length === 0 && elements.edges.length === 0)) {
      selected = null;
      return true;
    }
    selected = elements;
    selected.nodes.forEach(node => translationNodeData(node, TRANSLATION_DISTANCE));
    selected.edges.forEach(edge => translationEdgeData(edge, TRANSLATION_DISTANCE));
    return false;
  });
  // 粘贴
  keyboard.on(['cmd + v', 'ctrl + v'], () => {
    if (!keyboardOptions.enabled) return true;
    if (graph.textEditElement) return true;
    if (selected && (selected.nodes || selected.edges)) {
      lf.clearSelectElements();
      const addElements = lf.addElements(selected);
      if (!addElements) return true;
      addElements.nodes.forEach(node => lf.selectElementById(node.id, true));
      addElements.edges.forEach(edge => lf.selectElementById(edge.id, true));
      selected.nodes.forEach(node => translationNodeData(node, TRANSLATION_DISTANCE));
      selected.edges.forEach(edge => translationEdgeData(edge, TRANSLATION_DISTANCE));
    }
    return false;
  });
``` 
复制粘贴的源代码都在这儿了，https://github.com/didi/LogicFlow/blob/master/packages/core/src/keyboard/shortcut.ts

**Comment by xjikun** [comment]
> > @wumail 你好，近期有计划修复这个bug吗，急需 感谢🙏
> 
> 会修复，但不保证时间，因为还要发版 取决于你需求的紧急程度，你可以尝试先覆盖默认的快捷键回调 复制粘贴的源码在这儿，https://github.com/didi/LogicFlow/blob/master/packages/core/src/keyboard/shortcut.ts

你好，十月中旬有计划修复发布吗

**Comment by wumail** [comment]
https://github.com/didi/LogicFlow/commit/e9d0139da4446ec4451ba7c2516a1e440a951fec 可以看下代码，后续有类似的问题可以尝试先重写addElements方法

**Comment by xjikun** [comment]
> [e9d0139](https://github.com/didi/LogicFlow/commit/e9d0139da4446ec4451ba7c2516a1e440a951fec) 可以看下代码，后续有类似的问题可以尝试先重写addElements方法

嗯嗯 看了代码，在1.2.16版本试了一下，存在一下问题
1. 复制的时候 连接线没有进行复制
2. 连续的ctrl + v 出现了子节点位置错乱及与父分组所属关系错乱

https://github.com/didi/LogicFlow/assets/141391682/f8ab0162-91d2-480f-a89d-445ff4128b10

**Comment by wbccb** [comment]
还有一个很麻烦的地方 如果GroupA有连线Group之外的元素，你复制GroupA的时候，是要复制还是不复制这一条连线呢？

**Comment by wumail** [comment]
> 还有一个很麻烦的地方 如果GroupA有连线Group之外的元素，你复制GroupA的时候，是要复制还是不复制这一条连线呢？

应该是选择范围内的*节点*，以及起始节点都在选择范围内的*连线*，上面的代码确实有些欠考虑

**Comment by xjikun** [comment]
> > 还有一个很麻烦的地方 如果GroupA有连线Group之外的元素，你复制GroupA的时候，是要复制还是不复制这一条连线呢？
> 
> 应该是选择范围内的_节点_，以及起始节点都在选择范围内的_连线_，上面的代码确实有些欠考虑

你好 有计划修复这个bug吗？什么时候能发布呢

**Comment by wumail** [comment]
> > > 还有一个很麻烦的地方 如果GroupA有连线Group之外的元素，你复制GroupA的时候，是要复制还是不复制这一条连线呢？
> > 
> > 
> > 应该是选择范围内的_节点_，以及起始节点都在选择范围内的_连线_，上面的代码确实有些欠考虑
> 
> 你好 有计划修复这个bug吗？什么时候能发布呢

处理中，但是不保证时间，还是看你需求的紧急程度，上面的代码里你可以先自己加上边的复制，同时让节点复制的偏移多一点，可以避免连续复制关系错乱的问题

**Comment by az6161311** [comment]
@wumail  你好，按照你当前的思路去更改这个问题的话，那么当Group这个扩展与Menu这个扩展一起使用的时候，是否需要重构右键的复制功能？能否Group中提供一个可供外面调用的方法之类的？

**Comment by wumail** [comment]
> @wumail 你好，按照你当前的思路去更改这个问题的话，那么当Group这个扩展与Menu这个扩展一起使用的时候，是否需要重构右键的复制功能？能否Group中提供一个可供外面调用的方法之类的？

group本质是一个自定义节点，可以看看是否能通过自定义节点的方式解决

**Comment by az6161311** [comment]
> > @wumail 你好，按照你当前的思路去更改这个问题的话，那么当Group这个扩展与Menu这个扩展一起使用的时候，是否需要重构右键的复制功能？能否Group中提供一个可供外面调用的方法之类的？
> 
> group本质是一个自定义节点，可以看看是否能通过自定义节点的方式解决

在目前的这种情况下，如果在logic-flow中能解决是最好的，在自定义节点中去解决的话会比较绕了... 
我在看看配套的使用情况吧,感谢你的回复！

**Comment by wumail** [comment]
> > > @wumail 你好，按照你当前的思路去更改这个问题的话，那么当Group这个扩展与Menu这个扩展一起使用的时候，是否需要重构右键的复制功能？能否Group中提供一个可供外面调用的方法之类的？
> > 
> > 
> > group本质是一个自定义节点，可以看看是否能通过自定义节点的方式解决
> 
> 在目前的这种情况下，如果在logic-flow中能解决是最好的，在自定义节点中去解决的话会比较绕了... 我在看看配套的使用情况吧,感谢你的回复！

近期事情比较多，可能没太多精力处理问题，请谅解
