### ISSUE TITLE
[Bug report]fitView无法将整个视图适应容器大小

### ISSUE THREAD

**Issue by eyea** [didi/LogicFlow#1356]
## 问题描述

期望整个视图缩小到视图可以展示完全

## 最简复现

[codesandbox地址](https://codesandbox.io/s/sleepy-northcutt-vr5lgs?file=/src/index.js)

## 相关信息 context

```js
"@logicflow/core": "^1.2.15",
"@logicflow/extension": "^1.2.16",
```
Node Version: v20.5.0 

Platform: macOs

**Comment by eyea** [comment]
补充期望效果： 
![image](https://github.com/didi/LogicFlow/assets/17020223/2685080c-c9d3-424e-be3c-0d8924835e83)


当前效果：
![image](https://github.com/didi/LogicFlow/assets/17020223/bde15afc-1c0c-49bc-8b9d-79b87bf05f53)

**Comment by eyea** [comment]
可能是我哪里的设置或者api没用对，上面的复现地址 我更新了一个 `logicFitView` 函数，render 数据后，执行该函数达到预期的效果。

居中的话，`piont` 值如 `[0, 0]` 这样的值可能更合理一些~

假期愉快~

:)

**Comment by eyea** [comment]
仔细观察了下，可能是如下报错导致 `fitView` 执行异常，没有实现预期的效果:

![image](https://github.com/didi/LogicFlow/assets/17020223/681528dd-02fd-48a3-b130-8f025682dab6)

再进一步观察，dom 如下:

![image](https://github.com/didi/LogicFlow/assets/17020223/ab18fbe2-d8b3-4338-9a76-3d665ffa8dca)

[具体源码可能是这里](https://github.com/didi/LogicFlow/blob/f5f14b6db86f9f79463bd06749231c4c88e45095/packages/core/src/view/overlay/Grid.tsx#L66)

![image](https://github.com/didi/LogicFlow/assets/17020223/f16ff31a-0920-45fe-9d56-108dc0c2d572)

除了 `SKEW_Y` `SKEW_X` 别的都是 `NaN`

打印 `graphModel`, 证实上述问题:
![image](https://github.com/didi/LogicFlow/assets/17020223/649099fe-58e4-4feb-b6e8-b18bedb23fd8)

可是为什么会存在这种问题呢，代码里[初始化的位置](https://github.com/didi/LogicFlow/blob/36f3f8125799d77419b8579000948154781bb14c/packages/core/src/model/TransformModel.ts#L27)
![image](https://github.com/didi/LogicFlow/assets/17020223/fe1bd9bd-06c9-461c-8cbb-9ad1fe58622e)

两个可能的问题来源：用户和代码版本更新(使用版本如本issue开始描述)

---

先接着看下源码，哪里会有更新这个

**Comment by wumail** [comment]
假期愉快～我们节后排查一下

**Comment by eyea** [comment]
最新发现，我们的接口对 __properties__ 的 __nodeSize__ 进行了处理导致一些参数的丢失，节后我找他们修正下再观察~

**Comment by eyea** [comment]
emmm...  在排除上述可能得错误后，fitView如果在本身元素就在可视区范文内的，使用后会放大栅格，感觉需要个参数做边界判断，能显示完整就不调整?

**Comment by wumail** [comment]
> emmm... 在排除上述可能得错误后，fitView如果在本身元素就在可视区范文内的，使用后会放大栅格，感觉需要个参数做边界判断，能显示完整就不调整?

fitView的预期就是带缩放的，不调整到话有些奇怪，如果只想定位到画布中心可以使用focusOn

**Comment by eyea** [comment]
> > emmm... 在排除上述可能得错误后，fitView如果在本身元素就在可视区范文内的，使用后会放大栅格，感觉需要个参数做边界判断，能显示完整就不调整?
> 
> fitView的预期就是带缩放的，不调整到话有些奇怪，如果只想定位到画布中心可以使用focusOn

你好，我已经将 __data1__ 的可疑有问题的数据清除掉了。

在这个 [例子](https://codesandbox.io/s/sleepy-northcutt-vr5lgs?file=/src/index.js) 中，我做了下 fitView 效果对比，预期是执行 fitView 达到第二行的效果，即可视区全部展示完整。 

![image](https://github.com/didi/LogicFlow/assets/17020223/629f17d2-969e-487c-9e5c-bc9bdf626b42)

第一行展示的效果不是预期，第二行是预期效果。

第二行执行的方法 主要是手动改了 **point** 的 **x/y** 值:

![image](https://github.com/didi/LogicFlow/assets/17020223/21b3b284-dbc9-4aa0-b8a3-06b4e83d679d)


ps: 效果在例子中右侧可看，电脑截屏功能受限，原谅 :)

**Comment by wumail** [comment]
> > > emmm... 在排除上述可能得错误后，fitView如果在本身元素就在可视区范文内的，使用后会放大栅格，感觉需要个参数做边界判断，能显示完整就不调整?
> > 
> > 
> > fitView的预期就是带缩放的，不调整到话有些奇怪，如果只想定位到画布中心可以使用focusOn
> 
> 你好，我已经将 **data1** 的可疑有问题的数据清除掉了。
> 
> 在这个 [例子](https://codesandbox.io/s/sleepy-northcutt-vr5lgs?file=/src/index.js) 中，我做了下 fitView 效果对比，预期是执行 fitView 达到第二行的效果，即可视区全部展示完整。
> 
> ![image](https://user-images.githubusercontent.com/17020223/273367059-629f17d2-969e-487c-9e5c-bc9bdf626b42.png)
> 
> 第一行展示的效果不是预期，第二行是预期效果。
> 
> 第二行执行的方法 主要是手动改了 **point** 的 **x/y** 值:
> 
> ![image](https://user-images.githubusercontent.com/17020223/273367132-21b3b284-dbc9-4aa0-b8a3-06b4e83d679d.png)
> 
> ps: 效果在例子中右侧可看，电脑截屏功能受限，原谅 :)

我看了下，mock数据里面还是存在某些节点nodeSize里的width、height是null的，内部算出来的画布内容的虚拟边界变成了NaN，导致得到的zoom值不对，focusOn也出现了问题

**Comment by eyea** [comment]
> > > > emmm... 在排除上述可能得错误后，fitView如果在本身元素就在可视区范文内的，使用后会放大栅格，感觉需要个参数做边界判断，能显示完整就不调整?
> > > 
> > > 
> > > fitView的预期就是带缩放的，不调整到话有些奇怪，如果只想定位到画布中心可以使用focusOn
> > 
> > 
> > 你好，我已经将 **data1** 的可疑有问题的数据清除掉了。
> > 在这个 [例子](https://codesandbox.io/s/sleepy-northcutt-vr5lgs?file=/src/index.js) 中，我做了下 fitView 效果对比，预期是执行 fitView 达到第二行的效果，即可视区全部展示完整。
> > ![image](https://user-images.githubusercontent.com/17020223/273367059-629f17d2-969e-487c-9e5c-bc9bdf626b42.png)
> > 第一行展示的效果不是预期，第二行是预期效果。
> > 第二行执行的方法 主要是手动改了 **point** 的 **x/y** 值:
> > ![image](https://user-images.githubusercontent.com/17020223/273367132-21b3b284-dbc9-4aa0-b8a3-06b4e83d679d.png)
> > ps: 效果在例子中右侧可看，电脑截屏功能受限，原谅 :)
> 
> 我看了下，mock数据里面还是存在某些节点nodeSize里的width、height是null的，算出来画布内容包围盒长宽变成了NaN，导致得到的zoom值不正确，focusOn也出现了问题

嗯，谢谢~
