### ISSUE TITLE
[Feature Request] 将绘制好的流程图打印到A4纸或者pdf上。

### ISSUE THREAD

**Issue by vsdzgdzvzdgj** [didi/LogicFlow#1361]
## 问题背景

在一些特殊场景下，用户可能更喜欢阅览纸质或者PDF格式的流程图。
特殊场景：需要将材料整理纸张保存入库保存。
我尝试着使用浏览器的print()函数和Canvas但效果不太理想。

## 提案

希望增加导出pdf格式，或者导出图片插件支持图片切割能力。

**Comment by wumail** [comment]
可以使用类似https://github.com/yWorks/svg2pdf.js 的库，你要做的就是拿到你需要的svg dom元素（可以参考 https://github.com/didi/LogicFlow/blob/master/packages/extension/src/tools/snapshot/index.ts ）
