### ISSUE TITLE
导出图片时，节点上自定义的css不生效

### ISSUE THREAD

**Issue by fresh-Ghost** [didi/LogicFlow#1363]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 在项目中，通过css为节点设置样式后，调用getSnapshot方法导出图片，设置的样式未生效。

## 最简复现

1. 主题配置中设置：
`nodeText: { overflowMode: "autoWrap" }`
2. 样式中设置：
```
.lf-node-text--auto-wrap-inner {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
}
```
3. 调用getSnapshot方法导出图片，步骤2中的样式未生效

## 相关信息 context

LogicFlow Version:
Node Version:
Platform:

**Comment by fresh-Ghost** [comment]
测试地址https://github.com/fresh-Ghost/test-mvp.git；
1.拖拽节点到画布上；
2.双击节点添加足够 长的文本，让文本两行显示，文本末尾显示省略号；
3.点击左上角导出；

**Comment by fresh-Ghost** [comment]
![image](https://vip.helloimg.com/images/2023/10/12/ol6NMY.png)

**Comment by boyongjiong** [comment]
@fresh-Ghost 为什么关掉？
