### ISSUE TITLE
[Bug report]safari中滚动画布，子节点不动，只有线和锚点会动

### ISSUE THREAD

**Issue by wangsuipeng** [didi/LogicFlow#1364]
<img width="1213" alt="image" src="https://github.com/didi/LogicFlow/assets/40386639/8a075d19-05b7-462b-8940-ccd5cf7eca13">

**Comment by wbccb** [comment]
[safari下自定义html节点如果css样式设置position:relative等定位属性，将不会跟随画布移动或缩放](https://github.com/didi/LogicFlow/issues/363)是不是跟这个问题一样，设置了`position:relative`?

**Comment by boyongjiong** [comment]
<img width="1440" alt="image" src="https://github.com/didi/LogicFlow/assets/8553969/ab7ff324-f8f9-4c92-9619-63faa88f0ebb">
确认下是否是 css 样式的问题？如果不是，辛苦提供一下一个在线示例看一下
@wangsuipeng

**Comment by boyongjiong** [comment]
官方这个示例中有类似问题的，是因为 position: relative 引起的

**Comment by boyongjiong** [comment]
因为长时间未回复，我们先将该 issue 关闭，如果有问题可以反馈并重新打开

**Comment by wangsuipeng** [comment]
是的，就是设置了position: relative 引起的，这个可以解决嘛？

**Comment by qingtian5266** [comment]
怎么解决啊
