### ISSUE TITLE
[Bug report]框选多个节点后，原本属性为不可拖动的节点，依然被选中并且能拖动的问题。

### ISSUE THREAD

**Issue by SCTJRB** [didi/LogicFlow#1366]
## 问题描述

如图所示，左右两侧分别是自定义节点实现的，节点属性已设置为不可拖动，但是当框选多个节点时，原本不可拖动的节点，也被选中了并且还能被拖动，请问这种情况下我该怎么实现，不可拖动的节点不能被选中和拖动呢？

## 相关信息 context
[
![screenshots](https://github.com/didi/LogicFlow/assets/22992476/f5c90af7-f2a6-4061-a2ec-1cc65e04ba87)
](url)
LogicFlow Version:1.2.9
Node Version:16.15.0
Platform:win10

**Comment by SCTJRB** [comment]
或者说有没有提供根据节点ID取消选中节点的API，我可以自己实现后面的逻辑，因为我查阅文档后发现并没有取消选中某个节点的方法，就很无奈。

**Comment by boyongjiong** [comment]
可以通过 id 找到节点的 model，然后设置 model.isSelected =  false 就可以取消选中
