### ISSUE TITLE
[Bug report]画布事件他有的事件不触发，只触发了鼠标按下和点击

### ISSUE THREAD

**Issue by d-3841609** [didi/LogicFlow#1367]
画布事件他有的事件不触发，只触发了鼠标按下和点击
![QQ图片20231015233458](https://github.com/didi/LogicFlow/assets/80944685/895f7520-f6df-4586-a418-fc1175ad1291)

**Comment by d-3841609** [comment]
我按照官方文档，监听事件，但是只是触发了按下和单击，其他的都不触发，是我写的不对吗？

**Comment by boyongjiong** [comment]
是代码有问题，代码中没有触发这两个事件，我们看一下

**Comment by d-3841609** [comment]
> 是代码有问题，代码中没有触发这两个事件，我们看一下

我是禁用了，画布拖动和缩放后不触发的，因为我要自定义这两个事件。所以把默认的禁用了。

**Comment by d-3841609** [comment]
还有个问题除了默认的画布事件，我怎么自定义画布事件。我想实现通过快捷加鼠标的方式来拖动和缩放

**Comment by wumail** [comment]
> 还有个问题除了默认的画布事件，我怎么自定义画布事件。我想实现通过快捷加鼠标的方式来拖动和缩放

https://github.com/didi/LogicFlow/tree/master/packages/core/src/keyboard + https://site.logic-flow.cn/docs/#/zh/api/eventCenterApi?id=on

**Comment by d-3841609** [comment]
> > 还有一个问题除了默认的最晚事件，我怎么自定义最晚事件。我想实现通过快速加鼠标的方式来拖动和缩放
> 
> https://github.com/didi/LogicFlow/tree/master/packages/core/src/keyboard + https://site.logic-flow.cn/docs/#/zh/api/eventCenterApi?id=on

这个不能自定义画布的事件吧？个是监听node的

**Comment by d-3841609** [comment]
> > 还有一个问题除了默认的最晚事件，我怎么自定义最晚事件。我想实现通过快速加鼠标的方式来拖动和缩放
> 
> https://github.com/didi/LogicFlow/tree/master/packages/core/src/keyboard + https://site.logic-flow.cn/docs/#/zh/api/eventCenterApi?id=on

Can't I customize this canvas event? I know that nodes and connections can be customized
这个不能自定义画布的事件吧？我知道节点和连线是可以自定义的

**Comment by wumail** [comment]
> > > 还有一个问题除了默认的最晚事件，我怎么自定义最晚事件。我想实现通过快速加鼠标的方式来拖动和缩放
> > 
> > 
> > https://github.com/didi/LogicFlow/tree/master/packages/core/src/keyboard + https://site.logic-flow.cn/docs/#/zh/api/eventCenterApi?id=on
> 
> Can't I customize this canvas event? I know that nodes and connections can be customized 这个不能自定义画布的事件吧？我知道节点和连线是可以自定义的

自定义画布事件是说例如自定义一个“custom:click”事件这样吗？

**Comment by d-3841609** [comment]
> > > > 还有一个问题除了默认的最晚事件，我怎么自定义最晚事件。我想实现通过快速加鼠标的方式来拖动和缩放
> > > 
> > > 
> > > https://github.com/didi/LogicFlow/tree/master/packages/core/src/keyboard + https://site.logic-flow.cn/docs/#/zh/api/eventCenterApi?id=on
> > 
> > 
> > 我无法自定义此画布事件吗？我知道节点和连接是可以自定义的这个不能自定义的事件吧？我知道节点和连线是可以自定义的
> 
> 自定义事件是指自定义一个“自定义：点击”事件是这样吗？

对头，不用他默认的。

**Comment by wumail** [comment]
> https://github.com/didi/LogicFlow/tree/master/packages/core/src/keyboard + https://site.logic-flow.cn/docs/#/zh/api/eventCenterApi?id=on

https://github.com/didi/LogicFlow/tree/master/packages/core/src/keyboard + https://site.logic-flow.cn/docs/#/zh/api/eventCenterApi?id=on 就能满足你的要求，就是普通的event bus

**Comment by wumail** [comment]
> > > > > 还有一个问题除了默认的最晚事件，我怎么自定义最晚事件。我想实现通过快速加鼠标的方式来拖动和缩放
> > > > 
> > > > 
> > > > https://github.com/didi/LogicFlow/tree/master/packages/core/src/keyboard + https://site.logic-flow.cn/docs/#/zh/api/eventCenterApi?id=on
> > > 
> > > 
> > > 我无法自定义此画布事件吗？我知道节点和连接是可以自定义的这个不能自定义的事件吧？我知道节点和连线是可以自定义的
> > 
> > 
> > 自定义事件是指自定义一个“自定义：点击”事件是这样吗？
> 
> 对头，不用他默认的。

https://github.com/didi/LogicFlow/tree/master/packages/core/src/keyboard + https://site.logic-flow.cn/docs/#/zh/api/eventCenterApi?id=on 就能满足你的要求，就是普通的event bus
