### ISSUE TITLE
使用历史记录撤销后，节点拖拽事件中x，y并没有更新[Bug report]

### ISSUE THREAD

**Issue by zhangluluaichimi** [didi/LogicFlow#1369]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件，如何复现：使用历史记录，撤销后，节点拖拽事件（node:mousemove）、节点拖拽放开（node:drop）中data中x,y并没有更新
3. 期望的表现：希望不管什么操作节点拖拽事件（node:mousemove）、节点拖拽放开（node:drop），都能及时更新data里面x,y的值
4. 实际的表现：data中的x,y并没有更新，一直保留之前旧的数据

## 最简复现

一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请选择以下方式编写并上传最简复现 demo：

1. 在任意在线编码平台如 codesanbox 编写示例。将其保存到自己空间，然后贴上链接。

3. 在自己 github 中创建一个最简单的示例，然后贴上 github 链接。
4. 删除项目中的 node_modules 部分，打包项目，并拖拽到 issue 输入框中上传（或提供远程可下载地址）。

## 相关信息 context

LogicFlow Version:
Node Version:
Platform:

**Comment by zhangluluaichimi** [comment]
https://codesandbox.io/s/logicflow-selection-forked-dp6h29?file=/index.html（ codesanbox 编写示例）

**Comment by wumail** [comment]
确实是Bug，目前你可以先在事件回调里通过直接获取当前选择的元素来获取更新后的x,y
