### ISSUE TITLE
[Bug report] 画图完坐标数据有问题，有小数，还有异常数据

### ISSUE THREAD

**Issue by minliuhua** [didi/LogicFlow#1371]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件，如何复现
2. 期望的表现
3. 实际的表现

## 最简复现
怎么是整数啊，现在有小数
text xy坐标还怎么是这样的啊

![)T3{JZQQY7@DVAY917 ZMO6](https://github.com/didi/LogicFlow/assets/65475189/dcc2a998-82a3-4dde-b00e-7605d2a87c21)
![DK5UJRMXJG1LM_VC@NTC7Z7](https://github.com/didi/LogicFlow/assets/65475189/501b3a4d-d152-4773-895c-55b1273e7e6c)

## 相关信息 context

LogicFlow Version:
Node Version:
Platform:

**Comment by wumail** [comment]
开局一张图，内容全靠猜

**Comment by wumail** [comment]
> 我看应该是这个节点后面的坐标都有问题了
> 
> ![_XQBDYEB}BM9BF8T2WQ~{}5](https://user-images.githubusercontent.com/65475189/275778934-95cdb8ad-5b47-4e69-b754-0934c80f00e1.png)
> 
> ```
> import { h, PolygonNode, PolygonNodeModel } from '@logicflow/core'
> 
> class SerialModel extends PolygonNodeModel {
>   static extendKey = 'SerialModel';
>   constructor (data, graphModel) {
>     if (!data.text) {
>       data.text = ''
>     }
>     if (data.text && typeof data.text === 'string') {
>       data.text = {
>         value: data.text,
>         x: data.x,
>         y: data.y + 40
>       }
>     }
>     super(data, graphModel)
>     this.points = [
>       [25, 0],
>       [50, 25],
>       [25, 50],
>       [0, 25]
>     ]
>   }
> 
> }
> 
> class SerialView extends PolygonNode {
>   static extendKey = 'SerialNode';
>   getShape () {
>     const { model } = this.props
>     const { x, y, width, height, points } = model
>     const style = model.getNodeStyle()
>     return h(
>       'g',
>       {
>         transform: `matrix(1 0 0 1 ${x - width / 2} ${y - height / 2})`
>       },
>       h('polygon', {
>         ...style,
>         x,
>         y,
>         points
>       }),
>       h('path', {
>         d:
>           'm 16,15 7.42857142857143,9.714285714285715 -7.42857142857143,9.714285714285715 3.428571428571429,0 5.714285714285715,-7.464228571428572 5.714285714285715,7.464228571428572 3.428571428571429,0 -7.42857142857143,-9.714285714285715 7.42857142857143,-9.714285714285715 -3.428571428571429,0 -5.714285714285715,7.464228571428572 -5.714285714285715,-7.464228571428572 -3.428571428571429,0 z',
>         ...style
>       })
>     )
>   }
> }
> 
> export default {
>   type: 'serial',
>   view: SerialView,
>   model: SerialModel
> };
> ```

你说的这个问题我本地没办法复现
![ezgif-4-1e718640b3](https://github.com/didi/LogicFlow/assets/56008486/92966975-d3d6-4b56-a567-be08af698835)

**Comment by minliuhua** [comment]
把我的这个代码放进去试试看

**Comment by minliuhua** [comment]
移动的时候报这个
![image](https://github.com/didi/LogicFlow/assets/65475189/326c8d9d-5cbc-4f85-9ab7-4f9222eed8a8)
![image](https://github.com/didi/LogicFlow/assets/65475189/53facf2c-74e8-48b0-8ab0-b05d076b388f)

**Comment by minliuhua** [comment]
发现断点这两个都没进去
![image](https://github.com/didi/LogicFlow/assets/65475189/8631f2f5-6bdb-48e9-8f5f-b32a22200a6e)
![image](https://github.com/didi/LogicFlow/assets/65475189/3a72927b-c70e-4b15-9798-39ffb4c90325)

**Comment by minliuhua** [comment]
大佬有时间可以帮忙远程看下吗，我搞得工作流，就差这一步了，跪谢

**Comment by wumail** [comment]
> 大佬有时间可以帮忙远程看下吗，我搞得工作流，就差这一步了，跪谢

不可以哦，你可以提供最小可复现示例帮助我们排查这个可能的Bug

**Comment by minliuhua** [comment]
[这是一个demo](https://github.com/minliuhua/demo.git)

1、下载后解压

npm install --registry=https://registry.npmmirror.com

npm run dev

2、跑去来后
登录地址http://localhost:81/index地址，拖动红框中的节点，

![image](https://github.com/didi/LogicFlow/assets/65475189/aa2e2955-b268-4da8-b487-25cc2e701a21)

就能看到报红

![image](https://github.com/didi/LogicFlow/assets/65475189/b0292142-24d9-4ea7-9917-8d32d820e81e)

点击保存，就能看到坐标有问题

![image](https://github.com/didi/LogicFlow/assets/65475189/15d82524-8c27-4aca-b37d-fc1c77bfd831)
![image](https://github.com/didi/LogicFlow/assets/65475189/67a83a1f-185c-4e4c-b8b4-1b4168c6031f)

**Comment by wumail** [comment]
额。。。你把数据里面的x,y从字符串改成数字就好了

**Comment by minliuhua** [comment]
那怎么改啊，这个不是LogicFlow 返回给我的坐标吗
![image](https://github.com/didi/LogicFlow/assets/65475189/bf07c06d-959d-446b-b975-fc45e2394694)

**Comment by wumail** [comment]
> 那怎么改啊，这个不是LogicFlow 返回给我的坐标吗 ![image](https://user-images.githubusercontent.com/65475189/276185502-bf07c06d-959d-446b-b975-fc45e2394694.png)

![image](https://github.com/didi/LogicFlow/assets/56008486/fd182cd4-fdae-42bd-bdf2-ecb3329d4d83)
