### ISSUE TITLE
[Bug report] group复制的相关问题

### ISSUE THREAD

**Issue by wumail** [didi/LogicFlow#1379]
**问题收集中，欢迎补充**

**Comment by wumail** [comment]
![ezgif-3-238a86ac2b](https://github.com/didi/LogicFlow/assets/56008486/932f0526-cc5a-4422-8fdd-55c6844c5422)
@logicflow/extension v1.2.16发布后，经交流群的反馈，目前发现由于重写了addElements导致复制结果中线的位置出现偏移
原因：
![image](https://github.com/didi/LogicFlow/assets/56008486/33b75139-f6f7-4190-a051-3592f636830f)

**其他问题待收集中** 欢迎补充

**Comment by wbccb** [comment]
😅是我疏忽了，是我写出来的bug，group复制的相关问题保证秒修

**Comment by wumail** [comment]
> 😅是我疏忽了，是我写出来的bug，group复制的相关问题保证秒修

别在意别在意
