### ISSUE TITLE
关于是否要兼容 IE 的讨论

### ISSUE THREAD

**Issue by Serendipity96** [didi/LogicFlow#138]
hi，社区的各位小伙伴：

最近 LogicFlow 收到了一些用户反馈，期望 LogicFlow 能兼容 IE 。

如果在你的使用场景中需要在 IE 中使用 LogicFlow，就在此提交一条评论吧，评论内容包括：
- 需要支持的 IE 版本
- 需要支持的原因 / 实际场景案例
- 期望支持的时间

欢迎大家多多反馈交流！
LogicFlow 社区

**Comment by xiaoyinbiao** [comment]
需要支持的 IE 版本：ie11
需要支持的原因: 政府项目自定义审批流程
期望支持的时间：越快越好...

**Comment by a34089871** [comment]
需要支持的 IE 版本： ie11
需要支持的原因 / 实际场景案例： 项目需要
期望支持的时间： 5月

**Comment by towersxu** [comment]
目前0.4版本已兼容IE11

**Comment by itwmike** [comment]
需要支持的 IE 版本： ie11/IE10
需要支持的原因 / 实际场景案例： 当前有多个项目都是用vue2.x开发的，一直在兼容ie10、11，如果因为流程不支持这些浏览器，就会砍掉这个模块了。
期望支持的时间： 3月

**Comment by towersxu** [comment]
0.x版本IE11可以继续使用，需要引入promise polyfill。1.0版本不再兼容IE11。

**Comment by koukoujun** [comment]
希望支持ie11,大部分项目都为政府项目

**Comment by towersxu** [comment]
@lishaoh 你可以拉取代码，然后降低mobx相关的版本，自己重新构建试试。具体要用那些版本，可以参考0.x版本的代码。

**Comment by lishaoh** [comment]
@towersxu 有现成编译包吗

**Comment by lishaoh** [comment]
@itwmike 请问解决兼容IE11问题了吗？

> 需要支持的 IE 版本： ie11/IE10 需要支持的原因 / 实际场景案例： 当前有多个项目都是用vue2.x开发的，一直在兼容ie10、11，如果因为流程不支持这些浏览器，就会砍掉这个模块了。 期望支持的时间： 3月

**Comment by xiaohudie** [comment]
需要支持的 IE 版本： ie11
需要支持的原因 / 实际场景案例： 政府项目
期望支持的时间： 越快越好

**Comment by wumail** [comment]
> 需要支持的 IE 版本： ie11 需要支持的原因 / 实际场景案例： 政府项目 期望支持的时间： 越快越好

#1143
