### ISSUE TITLE
[Bug report] 缩放节点时，图形和连接线发生偏移。

### ISSUE THREAD

**Issue by layverns** [didi/LogicFlow#1384]
## 问题描述
1.缩放可缩放节点，在拖拽缩放结束时，松开鼠标的瞬间整个图形会发生偏移，导致连线也出现偏移。
我的项目中拖拽，把箭头都挡住了。
2.在保存完图形数据到后台，再重新渲染甚至会出现，线连到其他锚点的情况，不缩放好像就不会。

## 最简复现
可以看官方的例子：
https://site.logic-flow.cn/demo/dist/bpmn-vue

![2023-10-24 213953](https://github.com/didi/LogicFlow/assets/7018249/3111d067-5dba-490b-bcb1-8ae4e429863f)

https://github.com/didi/LogicFlow/assets/7018249/b29e1d77-9ead-4c74-91c1-aa4754b80437

**Comment by wumail** [comment]
去掉网格试试，缩放的尺度没有针对网格做近似
