### ISSUE TITLE
BpmnXmlAdapter插件导出xml时，想自定义格式

### ISSUE THREAD

**Issue by small-dots** [didi/LogicFlow#1385]
## 问题背景

想修改下这个前缀，去掉process：，有什么思路呢？
![image](https://github.com/didi/LogicFlow/assets/52172424/9ef14849-40e6-4544-be19-77ef492fe5af)
<img width="411" alt="image" src="https://github.com/didi/LogicFlow/assets/52172424/fdb4614d-15be-4621-b08d-7655732e64ef">

## 提案

解决方案，最好可以提供有一些伪代码

## 相关信息

一些关于需求的额外信息和截图

**Comment by wumail** [comment]
没看懂，重新描述一下吧

**Comment by wumail** [comment]
去交流群问吧，Issue先关闭了
