### ISSUE TITLE
无法回显xml

### ISSUE THREAD

**Issue by small-dots** [didi/LogicFlow#1389]
![image](https://github.com/didi/LogicFlow/assets/52172424/9e7fb32a-b1f6-4253-ab26-352c08552bb6)

xml数据：
<bpmn:definitions id="1698388790268519845" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" targetNamespace="http://logic-flow.org" exporter="logicflow" exporterVersion="1.2.0">	
  <bpmn:process isExecutable="true" id="1698388790268102850" name="默认流程名称">	
    <bpmn:startEvent id="1698388792206759122" name="开始事件">	
      <bpmn:outgoing>0c19ee53-5d3e-4626-baf8-756c8804844b</bpmn:outgoing>	
    </bpmn:startEvent>	
    <bpmn:userTask id="1698388794401788017" name="用户任务" labelColor="#000000" approveTypeLabel="" approveType="">	
      <bpmn:incoming>0c19ee53-5d3e-4626-baf8-756c8804844b</bpmn:incoming>	
    </bpmn:userTask>	
      <bpmn:sequenceFlow id="0c19ee53-5d3e-4626-baf8-756c8804844b" sourceRef="1698388792206759122" targetRef="1698388794401788017" />	
  </bpmn:process>	
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">	
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="1698388790268102850">	
        <bpmndi:BPMNEdge id="0c19ee53-5d3e-4626-baf8-756c8804844b_di" bpmnElement="0c19ee53-5d3e-4626-baf8-756c8804844b">	
            <di:waypoint x="550" y="200" />	
            <di:waypoint x="740" y="200" />	
        </bpmndi:BPMNEdge>	
        <bpmndi:BPMNShape id="1698388792206759122_di" bpmnElement="1698388792206759122">	
          <dc:Bounds x="480" y="180" width="40" height="40" />	
          <bpmndi:BPMNLabel>	
            <dc:Bounds x="480" y="193" width="40" height="14" />	
          </bpmndi:BPMNLabel>	
        </bpmndi:BPMNShape>	
        <bpmndi:BPMNShape id="1698388794401788017_di" bpmnElement="1698388794401788017">	
          <dc:Bounds x="740" y="160" width="100" height="80" />	
          <bpmndi:BPMNLabel>	
            <dc:Bounds x="770" y="193" width="40" height="14" />	
          </bpmndi:BPMNLabel>	
        </bpmndi:BPMNShape>	
    </bpmndi:BPMNPlane>	
  </bpmndi:BPMNDiagram>	
</bpmn:definitions>

**Comment by wumail** [comment]
你把你这段XML放到bpmnjs里也没办法正常回显啊。。。

**Comment by wumail** [comment]
由于缺少更多的信息，该issue已被暂时关闭，提供更多信息以重启issue。
