### ISSUE TITLE
[Feature Request] 主题新增配置 `lf-text-input`

### ISSUE THREAD

**Issue by WangJincheng4869** [didi/LogicFlow#1390]
## 问题背景

我想实现兼容暗色主题，目前发现无法在配置中实现修改 `lf-text-input` 的样式，目前只能使用覆盖样式的做法。但是这样弊端很大，万一哪个版本升级类名被修改，那么的我的样式将会失效。

## 提案

增加  `lf-text-input` 的样式自定义

## 相关信息

![image](https://github.com/didi/LogicFlow/assets/41162158/7259714c-c94d-4bc2-aa84-caa65f7272a2)

**Comment by wumail** [comment]
https://site.logic-flow.cn/docs/#/zh/api/themeApi?id=nodetext 试试这个

**Comment by wumail** [comment]
目前看，样式类名修改的可能性比较小，主题添加配置可行，可以借此机会重新规划一下主题配置，这项工作会在后面进行，所以推荐先用样式覆盖，后续有新的方式会在该issue下告知
