### ISSUE TITLE
初始化创建lf设置禁止画布拖拽，通过updateEditorConfig修改stopMoveGraph属性，无法激活画布拖拽

### ISSUE THREAD

**Issue by j78742** [didi/LogicFlow#1397]
初始化创建lf设置禁止画布拖拽，通过updateEditorConfig修改stopMoveGraph属性，无法激活画布拖拽

**Comment by boyongjiong** [comment]
球球了，给孩子一个可复现示例吧

**Comment by wumail** [comment]
[updateEditConfig](https://site.logic-flow.cn/docs/#/zh/api/editConfigModelApi?id=updateeditconfig)

**Comment by boyongjiong** [comment]
确认下是否用错 api，看下上面 updateEditConfig 是否有效。本 issue 因长时间未回复，先做关闭处理
