### ISSUE TITLE
[Bug report]复制节点过后节点Text和线条锚点定位偏移

### ISSUE THREAD

**Issue by terrowz** [didi/LogicFlow#1398]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. bug描述
  复制功能在单选/多选复制节点后 该节点的文本和对应的线条定位会产生偏移
2. 期望的表现
  使用复制功能复制节点后 节点的文本和线条可以按照原来的排列方式做自适应
3. 实际的表现
  使用复制功能复制节点后 节点的文本和对应的线条定位会产生偏移

## 最简复现
![image](https://github.com/didi/LogicFlow/assets/60601657/3127593f-0a5d-48ed-9dde-b2a4e744db58)
![image](https://github.com/didi/LogicFlow/assets/60601657/e9dec292-b700-490e-98c6-df7230b9ed51)

## 相关信息 context

LogicFlow Version:
Node Version:
Platform:

**Comment by wumail** [comment]
1. logicflow版本？
2. 根据你的描述无法在本地复现问题，提供可复现示例

**Comment by terrowz** [comment]
> 1. logicflow版本？
版本为1.2.17
> 2. 根据你的描述无法在本地复现问题，提供可复现示例
目前已复现问题 在开启网格模式并将网格可见false时会出现此问题 code如下 注释后可解决
望修复 
![sp231101_165805](https://github.com/didi/LogicFlow/assets/60601657/06231079-906c-4e10-aa90-b1ce18e77ee5)

**Comment by wumail** [comment]
> > 1. logicflow版本？
> >    版本为1.2.17
> > 2. 根据你的描述无法在本地复现问题，提供可复现示例
> >    目前已复现问题 在开启网格模式并将网格可见false时会出现此问题 code如下 注释后可解决
> >    望修复
> >    ![sp231101_165805](https://user-images.githubusercontent.com/60601657/279625914-06231079-906c-4e10-aa90-b1ce18e77ee5.png)

gridSize建议设置成能40的因数或者40的整数

**Comment by terrowz** [comment]
已测试修改为40的因数或倍数时不会出现 感谢
