### ISSUE TITLE
[Bug Report]: 分组节点的 getAddableOutlineStyle 方法失效

### ISSUE THREAD

**Issue by Why1092164058** [didi/LogicFlow#1406]
### 发生了什么？

分组节点 进行自定义绘制之后，
getAddableOutlineStyle() 中的样式失效，方法未被出发触发

`class CommonView extends GroupNode.view {
getShape() {
    const { model } = this.props
    const { x, y, width, height, radius } = model
    const style = model.getNodeStyle()
    return h('g', {}, [
      h('rect', {
        ...style,
        x: x - width / 2,
        y: y - height / 2,
        rx: radius,
        ry: radius,
        width,
        height
      }),
      h(
        'text',
        {
          x: x - width / 2 + 5,
          y: y - 60
        },
        ['串行']
      )
    ])
  }
}`

### logicflow/core版本

1.2.17

### logicflow/extension版本

1.2.18

### 浏览器&环境

Chrome

**Comment by wumail** [comment]
getShape是最终渲染节点会执行的，由于你自己重写了getShape，并且没有自行处理AddableOutline的渲染，导致getAddableOutlineStyle方法失效，group节点继承至可缩放节点，在getResizeShape方法中进行了AddableOutline的渲染，而getResizeShape又会在getShape中被调用，详见 https://github.com/didi/LogicFlow/blob/master/packages/extension/src/materials/group/GroupNode.ts#L379
