### ISSUE TITLE
[Feature]: 可以完善 TS 类型导出吗，或者是已经导出了文档中没有提到

### ISSUE THREAD

**Issue by WangJincheng4869** [didi/LogicFlow#1409]
### 背景&目的

我在使用事件的过程中发现回调没有类型导出，用起来不是很方便。比如如下：
![image](https://github.com/didi/LogicFlow/assets/41162158/c79d0756-2cba-485b-95c1-f68ffb87c891)

**Comment by wumail** [comment]
> > 目前绝大部分类型应该都是导出了的，这里具体指的是什么类型没导出？同时我们已经对文档做了大的更新，会找个时间上线
> 
> 事件对象 `data` ，可能不同的事件回调的数据类型不同，会导致该起来复杂，在文档里说明都有哪些属性也可以。
> 
> 其实咱们这个文档写的已经很牛逼了，比其他项目强多了，点赞。

事件回调函数这部分的类型说明做的确实不好，但是不计划对一版代码做修改，可以透露的是，现在我们已经有了一个2.0版本的初版，对类型进行了整理和补全，希望可以帮助大家更好的使用😶‍🌫️
