### ISSUE TITLE
[Bug Report]: 自定义节点内部输入框选中问题

### ISSUE THREAD

**Issue by yyp0716** [didi/LogicFlow#1411]
### 发生了什么？

使用vue自定义节点内部加入输入框，但是在输入框内进行拖拽选中操作时无法实现，会触发整个节点的拖拽事件，导致无法选中输入框内某段文字。
样例:
https://codesandbox.io/s/vue-logic-flow-demo-zkcfkz?file=/src/App.vue

### logicflow/core版本

1.2.15

### logicflow/extension版本

1.2.16

**Comment by boyongjiong** [comment]
@mousemove.stop  input 里面加下这个就可以了
