### ISSUE TITLE
[Feature]: 边自定义动画希望保留原有边，动画覆盖在边上展示。

### ISSUE THREAD

**Issue by WangJincheng4869** [didi/LogicFlow#1420]
### 背景&目的

现在的东湖是覆盖了原有边的样式，无法实现更加自由的动画效果，如果保留原有边效果，动画属于覆盖层，那么可以实现以下效果
![image](https://github.com/didi/LogicFlow/assets/41162158/6cc2da3b-f506-44bf-9629-65a25347c698)

**Comment by wumail** [comment]
我理解你在自定义节点里自行通过字段控制边的样式就能实现你的需求了

**Comment by WangJincheng4869** [comment]
> 我理解你在自定义节点里自行通过字段控制边的样式就能实现你的需求了

但是当我开始动画的时候，会覆盖掉我自定义的样式
![image](https://github.com/didi/LogicFlow/assets/41162158/05572009-ffc0-47b4-a8aa-57b129a73a5c)

```ts
/**
 * 自定义直角折线边
 */
class SpPolylineEdgeModel extends PolylineEdgeModel {
  createId(): string {
    return nanoid();
  }

  setAttributes() {
    this.isAnimation = true;
  }

  getEdgeStyle() {
    const style = super.getEdgeStyle();
    const { properties } = this;
    if (properties.isActived) {
      style.strokeDasharray = '4 4';
    }
    style.stroke = 'orange';
    return style;
  }
}
```

**Comment by wumail** [comment]
> > 我理解你在自定义节点里自行通过字段控制边的样式就能实现你的需求了
> 
> 但是当我开启动画的时候，会覆盖掉我自定义的样式 ![image](https://user-images.githubusercontent.com/41162158/281297921-05572009-ffc0-47b4-a8aa-57b129a73a5c.png)
> 
> ```ts
> /**
>  * 自定义直角折线边
>  */
> class SpPolylineEdgeModel extends PolylineEdgeModel {
>   createId(): string {
>     return nanoid();
>   }
> 
>   setAttributes() {
>     this.isAnimation = true;
>   }
> 
>   getEdgeStyle() {
>     const style = super.getEdgeStyle();
>     const { properties } = this;
>     if (properties.isActived) {
>       style.strokeDasharray = '4 4';
>     }
>     style.stroke = 'orange';
>     return style;
>   }
> }
> ```

动画的样式也可以自定义啊

**Comment by WangJincheng4869** [comment]
> > > 我理解你在自定义节点里自行通过字段控制边的样式就能实现你的需求了
> > 
> > 
> > 但是当我开启动画的时候，会覆盖掉我自定义的样式 ![image](https://user-images.githubusercontent.com/41162158/281297921-05572009-ffc0-47b4-a8aa-57b129a73a5c.png)
> > ```ts
> > /**
> >  * 自定义直角折线边
> >  */
> > class SpPolylineEdgeModel extends PolylineEdgeModel {
> >   createId(): string {
> >     return nanoid();
> >   }
> > 
> >   setAttributes() {
> >     this.isAnimation = true;
> >   }
> > 
> >   getEdgeStyle() {
> >     const style = super.getEdgeStyle();
> >     const { properties } = this;
> >     if (properties.isActived) {
> >       style.strokeDasharray = '4 4';
> >     }
> >     style.stroke = 'orange';
> >     return style;
> >   }
> > }
> > ```
> 
> 动画的样式也可以自定义啊

仅自定义动画没有找到办法实现我想要的效果，因为动画中点的宽度是要比边宽的，是覆盖在边上的动画。
我查了一下 `polyline` 的 API，没有找到合适的办法，目前想到的办法就是动画边和边分离，动画边可以覆盖到边上面。
类似这种效果：
![动画](https://github.com/didi/LogicFlow/assets/41162158/65efc2d1-cc81-40aa-a4d0-a7484c4bfbf5)

**Comment by wumail** [comment]
> > > > 我理解你在自定义节点里自行通过字段控制边的样式就能实现你的需求了
> > > 
> > > 
> > > 但是当我开启动画的时候，会覆盖掉我自定义的样式 ![image](https://user-images.githubusercontent.com/41162158/281297921-05572009-ffc0-47b4-a8aa-57b129a73a5c.png)
> > > ```ts
> > > /**
> > >  * 自定义直角折线边
> > >  */
> > > class SpPolylineEdgeModel extends PolylineEdgeModel {
> > >   createId(): string {
> > >     return nanoid();
> > >   }
> > > 
> > >   setAttributes() {
> > >     this.isAnimation = true;
> > >   }
> > > 
> > >   getEdgeStyle() {
> > >     const style = super.getEdgeStyle();
> > >     const { properties } = this;
> > >     if (properties.isActived) {
> > >       style.strokeDasharray = '4 4';
> > >     }
> > >     style.stroke = 'orange';
> > >     return style;
> > >   }
> > > }
> > > ```
> > 
> > 
> > 动画的样式也可以自定义啊
> 
> 仅自定义动画没有找到办法实现我想要的效果，因为动画中点的宽度是要比边宽的，是覆盖在边上的动画。 我查了一下 `polyline` 的 API，没有找到合适的办法，目前想到的办法就是动画边和边分离，动画边可以覆盖到边上面。 类似这种效果： ![动画](https://user-images.githubusercontent.com/41162158/281686468-65efc2d1-cc81-40aa-a4d0-a7484c4bfbf5.png)

https://developer.mozilla.org/zh-CN/docs/Web/SVG/SVG_animation_with_SMIL SMIL动画应该也可以实现

**Comment by boyongjiong** [comment]
上面提供了解决方案，目前不会就这个功能开发 feature，故先将此 issue 关闭
