### ISSUE TITLE
[Bug Report]: 数据相同时，箭头会消失

### ISSUE THREAD

**Issue by webRambler** [didi/LogicFlow#1424]
### 发生了什么？

当两个页面都出现同一个图时（数据data相同），切换到第二个页面，则图的箭头会消失，变成直线连接了

### logicflow/core版本

1.2.15

### logicflow/extension版本

1.2.16

### logicflow/engine版本

0.0.9

### 浏览器&环境

Chrome

**Comment by wumail** [comment]
麻烦提供可复现示例，箭头是在defs中定义的可复用元素，先排查一下第二个页面里面箭头对应的marker是否正常在defs中定义了

**Comment by Mirrors406** [comment]
> 麻烦提供可复现示例，箭头是在defs中定义的可复用元素，先排查一下第二个页面里面箭头对应的marker是否正常在defs中定义了

我也有同样的问题，看了defs 是没问题的，只要删除页面中的一个实例，另一个就正常显示了，这怎么解
