### ISSUE TITLE
[Bug Report]: 节点旋转后，进行节点缩放问题

### ISSUE THREAD

**Issue by PandaX-Go** [didi/LogicFlow#1428]
### 发生了什么？

节点旋转后，进行节点缩放
1. 旋转小于45度，节点缩放，锚点位置错误
![image](https://github.com/didi/LogicFlow/assets/143163358/41c39d10-34d7-422e-99bf-7d0bd4e79dc0)
2. 旋转大于90度，节点缩放，锚点位置错误，并且拖拽方向与缩放方向相反（严重）。
![image](https://github.com/didi/LogicFlow/assets/143163358/e1afccda-3b7d-41af-90a0-f5fd30b832ed)

### logicflow/core版本

1.2.16

### logicflow/extension版本

1.2.17

### 浏览器&环境

Chrome

**Comment by wumail** [comment]
暂时没有计划修复完善旋转功能，涉及许多基础逻辑，如果在使用旋转的过程中发现奇怪的现象，那么建议是先不使用旋转

**Comment by DymoneLewis** [comment]
您好，这个问题已于最新版本修复，请升级到core 2.0.5版本 extension 2.0.9版本再试一下
