### ISSUE TITLE
[Bug Report]: 文档中自定义事件示例bug

### ISSUE THREAD

**Issue by jhw-cn** [didi/LogicFlow#1435]
### 发生了什么？

在官方文档。核心功能/事件/自定义事件给出的示例中，当存在多个节点时点击任意节点，点击事件得到的数据都是最后一个节点的数据。
```
// data.js
const data = {
  nodes: [
    {
      id: "1",
      type: "button-node",
      x: 300,
      y: 100,
      properties: {
        name: "hello",
        body: "world",
      },
    },
    {
      id: "2",
      type: "button-node",
      x: 300,
      y: 400,
      properties: {
        name: "hello2",
        body: "world2",
      },
    },
  ],
  edges: [],
};

export default data;
```
<img width="631" alt="image" src="https://github.com/didi/LogicFlow/assets/82150819/80a0a554-f6ee-4d09-92ab-7f25a6f1c7a6">
实际情况：
<img width="622" alt="image" src="https://github.com/didi/LogicFlow/assets/82150819/63f79a64-f57e-481b-93c7-e55300678820">

### logicflow/core版本

1.2.16

### logicflow/extension版本

1.2.17

### logicflow/engine版本

0.0.9

**Comment by DymoneLewis** [comment]
hi，请问这个问题解决了吗，没有的话方便贴下demo地址吗

**Comment by DymoneLewis** [comment]
您好，这边测试没有问题，推测或许是因为两个按钮绑定了同一个事件导致的，如果这个问题还需要解决的话，辛苦贴下按钮事件实现逻辑重启issue
