### ISSUE TITLE
[Bug Report]: 连线过短提示信息内容没有显示

### ISSUE THREAD

**Issue by Oct16th-Lcs** [didi/LogicFlow#1436]
### 发生了什么？

如图所示
![285083433-211b6d9a-72d3-48c8-86e6-a6685672c162](https://github.com/didi/LogicFlow/assets/46834744/333048b1-3300-46c3-8354-d28310fe2815)

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
感谢您的反馈，经排查弹出空报错信息的原因是默认报错信息缺失导致，目前已补充上，欢迎升级到最新版本体验
