### ISSUE TITLE
[Bug Report]: 自定义HtmlNode在Chrome浏览器下选中时会有一个outline

### ISSUE THREAD

**Issue by tianyk** [didi/LogicFlow#1437]
### 发生了什么？

自定义HtmlNode在Chrome浏览器下选中时会有一个outline，通过`getOutlineStyle`覆盖和`nodeSelectedOutline: false`都无法解决。

<img width="1035" alt="image" src="https://github.com/didi/LogicFlow/assets/3387702/43f9bca9-f688-4ad8-946e-48e8174163e3">

测试发现此outline为[foreignObject](https://github.com/didi/LogicFlow/blob/6f3764aefe2fa15a2a72302a4e46403141d150c2/packages/core/src/view/node/HtmlNode.tsx#L64)默认样式，通过设置其样式 outline: none 可以隐藏。

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.18

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
所以这个看起来跟 getOutlineStyle覆盖和nodeSelectedOutline: false  没有关系，不是同一个东西。

还是用 outline: none 处理就行。
