### ISSUE TITLE
[Bug Report]: 调用lf.cloneNode后，克隆的节点中的text向上移动了一段距离

### ISSUE THREAD

**Issue by WhyNot0YJ** [didi/LogicFlow#1440]
### 发生了什么？

调用lf.cloneNode后，克隆的节点中的text向上移动了一段距离
![image](https://github.com/didi/LogicFlow/assets/97305649/a16d8dbc-1c4a-4a0f-90c2-051346dbb563)
举个例子：给node加了一个点击事件，点击就克隆
![image](https://github.com/didi/LogicFlow/assets/97305649/b414c4a8-f624-4f46-8166-afa833ea56de)
点击后ke克隆出来的节点如图所示，文字向上移动了

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

**Comment by wumail** [comment]
是一个已知问题，暂时你可以去掉网格（如果需要可以用图片作为网格背景）以解决问题
