### ISSUE TITLE
[Bug Report]: 导出图片时，HTML节点未显示锚点

### ISSUE THREAD

**Issue by MINDOU520** [didi/LogicFlow#1441]
### 发生了什么？

锚点为常显，导出的图片未显示锚点
![image](https://github.com/didi/LogicFlow/assets/33241945/7fe7b5bb-d197-4648-9fff-074d22b85ab6)
![image](https://github.com/didi/LogicFlow/assets/33241945/7e2f8310-6afd-4d9c-b897-65709731a730)

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by wumail** [comment]
目前导出图片的逻辑就是去掉锚点的，如果需要，可以修改代码、利用插件机制实现自己的图片导出插件

**Comment by MINDOU520** [comment]
您好，您的邮件我已收到！
