### ISSUE TITLE
画布的双击事件[Feature]: 

### ISSUE THREAD

**Issue by harry5257** [didi/LogicFlow#1444]
### 背景&目的

单击画布弹出侧边飘窗会很轻易，使用时不小心点击到画布导致画布飘窗一直飘出，影响使用体验，所以想要增加画布双击事件

**Comment by boyongjiong** [comment]
没太看懂这个是什么意思 -。- 

点击画布弹出 Drawer 应该是用户自定义的能力吧，我理解应该可以自定义成双击显示吧

**Comment by HunterHeroHan** [comment]
可是，为啥画布没有双击事件啊...
![blank](https://github.com/user-attachments/assets/78d896d0-b127-4c2e-bde3-d277e3d557f9
