### ISSUE TITLE
[REMIND⚠️]transform相关问题汇总

### ISSUE THREAD

**Issue by wumail** [didi/LogicFlow#1446]
目前缩放、旋转等transform操作存在冲突、设计不合理等问题，暂时关闭相关Issue并在这里进行汇总，后续会针对相关问题进行统一、集中的修复，将缩放作为节点的基础能力实现而不是现在的自定义节点。

- [x] #1442 
- [x] #1440 
- [x] #1428
- [x] #1417 
- [x] #1384 
- [ ] #937 
- [x] #1628

**Comment by wbccb** [comment]
旋转后的缩放逻辑优化了一下计算方式🤔️现在可以实现旋转后缩放了，哪个大佬可以告诉我一下 我要提交pr到master分支还是next分支？
