### ISSUE TITLE
[Bug Report]: 锚点配置最大可连接边数量后，拖动链接边元锚点后无法修改

### ISSUE THREAD

**Issue by zjutlf** [didi/LogicFlow#1449]
### 发生了什么？

当前demo有一个需求，模型in/out锚点类型需要有最大建立链接点的限制如图所示
![image](https://github.com/didi/LogicFlow/assets/39113462/e2ab1d3c-40ed-4b95-b0ac-91be6417d479)
这里控制边的数量是通过edge:add方法触发对prototype中锚点数据的修改
![image](https://github.com/didi/LogicFlow/assets/39113462/96ef008f-0087-4e3e-b9a5-89c80e89b283)
我们对于锚点控制边的计算方法如图
![image](https://github.com/didi/LogicFlow/assets/39113462/389a59da-f4e4-463e-89f9-815936bec2b2)
当我们链接两个节点的锚点后，修改链接边out0->in0为out1->in0，如图所示
![image](https://github.com/didi/LogicFlow/assets/39113462/c3fbd1cd-7fe3-4eca-b167-b85a85417111)
会提示in链接锚点已满
按照正常逻辑来说，同一条线修改为不同的out点连同一个in点，应该可以正常修改

通过console输出，可以看到，边rule的触发早于edge:delete,edge:add,edge:exchange-node的触发，这代表会优先计算当前锚点链接数量是否大于等于最大链接数量，这应该就是无法修改源锚点位置的原因。

请问这是否是bug，或者是否有较好的触发方案？

同时，还有一个问题，如果锚点拖拽因随机拖拽导致锚点未实际链接到锚点上，是否可以恢复到原先的链接上？如图所示
![image](https://github.com/didi/LogicFlow/assets/39113462/da794be8-ea6e-47a2-a1b6-d4983ae5b21d)
我看到这里仅会在console.log中进行错误打印，而不进行恢复处理，是否能够恢复源锚点
![image](https://github.com/didi/LogicFlow/assets/39113462/3ab81ed9-4d42-4021-b053-bda7ae9efeec)

代码如下，因公司网络无法打开codepen等sandbox，故附压缩包代码如下，请谅解
[iotFlowPlatform.zip](https://github.com/didi/LogicFlow/files/13557882/iotFlowPlatform.zip)

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
我看了一下
第一个问题看起来更像是缺陷🤔？目前只有锚点信息的情况下，很难判断出是 同一条边修改起终点的情况 还是 新连接了一条边的情况，我觉得如果能用当前锚点关联边的集合和当前操作的锚点/边的id做比较，应该就能辨别出 该不该触发提示了。validate函数的第五个参数就是edgeId 可以直接获取（注意新建边的情况下会是undefined），获取当前锚点关联的边的能力后面会加上。
第二个问题确实是个bug😄，这个报错阻塞锚点恢复了，目前正在修复中。

**Comment by DymoneLewis** [comment]
hi，这个问题已经在年前发布的版本里修复了，辛苦升版本试下还有没有问题
