### ISSUE TITLE
[Feature]: tooltip

### ISSUE THREAD

**Issue by LiFuHai1106** [didi/LogicFlow#1456]
### 背景&目的

![image](https://github.com/didi/LogicFlow/assets/57932634/08658317-2c3c-47e0-9020-0e9ea315f97a)
logicflow鼠标上移节点有类似echart的tooltip功能吗，如果没有，后续是否可以增加tooltip功能

**Comment by wumail** [comment]
看起来属于业务功能，可以通过自定义节点实现，不打算内置
