### ISSUE TITLE
[Bug Report]: updateEditConfig 切换 isSilentMode 状态，keyboard 失效

### ISSUE THREAD

**Issue by cathats** [didi/LogicFlow#1460]
### 发生了什么？

我是用 keyboard 定义了删除连线(edge)的操作。

初始化时，我将 isSilentMode 设置为 true，同时添加了自定义 keyboard 事件。
当用户点击「编辑按钮」时将其设置为 false(利用了 updateEditConfig)。但是这一操作导致自定义 keyboard 失效。

下面是一个简化的问题代码，其中 setTimeout 模拟了用户点击按钮切换 isSilentMode 的操作。
preview：https://codesandbox.io/p/sandbox/logicflow-demo-1-rttryj

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by wumail** [comment]
![image](https://github.com/didi/LogicFlow/assets/56008486/9ade42e2-b562-4fc4-a483-19ed85b96821)

**Comment by towersxu** [comment]
看起来是有点问题，静默模式应该只禁用内置的快捷键，不禁用自定义的。
https://github.com/didi/LogicFlow/blob/fb4bb27602ca4cb9bd0f085a7421dbfa6049e18e/packages/core/src/LogicFlow.tsx#L134-L140
可以试试手动再调用一次`lf.keyboard.initShortcuts()`，是否能临时解决这个问题。

**Comment by boyongjiong** [comment]
#1491 已发版修复
