### ISSUE TITLE
作为组件外部进行调用时，history:change事件无法触发

### ISSUE THREAD

**Issue by MINDOU520** [didi/LogicFlow#1461]
### 发生了什么？

用官方demo，把LF做为组件，外部调用初始化方法加载，history:change无法触发
![image](https://github.com/didi/LogicFlow/assets/33241945/2d6af46c-0e09-451e-833e-eccb8586ad8b)
![image](https://github.com/didi/LogicFlow/assets/33241945/583e29df-1a54-4975-a48e-5658509927ca)
![image](https://github.com/didi/LogicFlow/assets/33241945/a5fcbac2-2ea6-4558-b71a-e496ff388153)

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
这个还有问题吗？我记得是实例没有销毁？

**Comment by MINDOU520** [comment]
您好，您的邮件我已收到！

**Comment by MINDOU520** [comment]
> 这个还有问题吗？我记得是实例没有销毁？

还存在，刚开始加载LF时，没有render任何数据，点击时才进行渲染，这中情况需要先销毁实例？

**Comment by boyongjiong** [comment]
没办法复现你这个场景呢，麻烦提供一个最小示例的 demo 给到我们看一下？

**Comment by MINDOU520** [comment]
https://gitee.com/mindou0228/logic-flow-test/tree/master 
基于官方示例：https://xinxin93.github.io/logicflow_vue_demo/#/   增加一个MainView,在其中嵌套了LF，界面有点击按钮，点击后，history:change事件不触发
![Uploading 屏幕录制 2024-01-31 153548 00_00_00-00_00_30.gif…]()

**Comment by boyongjiong** [comment]
建议不要描述，直接提供你实现的 demo 给我们看，我们根据你的描述去实现相关 demo，时间成本极高，没时间搞。

**Comment by MINDOU520** [comment]
https://gitee.com/mindou0228/logic-flow-test/tree/master  demo在这呀

**Comment by DymoneLewis** [comment]
demo已收到∠(°ゝ°)，这边排查下

**Comment by DymoneLewis** [comment]
您好，感谢您的反馈，这边调试了您的代码发现事件不触发的原因主要在于触发点击按钮的重新实例化时，Control组件没有跟着一起更新，内部监听的还是上一个实例的事件，导致出现按钮没重置的情况。
推荐您调整一下业务实现逻辑，在Control组件中监听lf变化或者尝试每次重新实例化时一并更新相关组件
如果有问题欢迎再提😊
