### ISSUE TITLE
[Bug Report]: 当xml渲染时 遇到y="0"时 会发生异常 导致转换失败

### ISSUE THREAD

**Issue by parrot-designa** [didi/LogicFlow#1462]
### 发生了什么？

当渲染的xml结构中存在y="0" 即会报错

![image](https://github.com/didi/LogicFlow/assets/77631518/ac4672d1-cae0-4c84-9779-a848dfdb1bc1)

### logicflow/core版本

1.2.16

### logicflow/extension版本

1.2.16

### logicflow/engine版本

1.2.16

**Comment by boyongjiong** [comment]
这样没办法看出来问题，辛苦提供下 demo
