### ISSUE TITLE
[Bug Report]: 导出图片兼容性问题及垂直居中失效

### ISSUE THREAD

**Issue by ijry** [didi/LogicFlow#1466]
### 发生了什么？

在edge/chrome导出正常（下图左侧），在safari17.2(macOS14.2)导出图片不完整（下图右侧），且文字都没有垂直居中。
![a54c6e275d7d4fac2f2a0b20595f636b](https://github.com/didi/LogicFlow/assets/3102798/86860349-29e6-4b10-83c0-b3de132fc067)

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### logicflow/engine版本

1.2.18

### 浏览器&环境

Chrome, Safari, Microsoft Edge

**Comment by boyongjiong** [comment]
自定义节点的导出样式问题可以看下 https://site.logic-flow.cn/docs/#/zh/guide/extension/snapshot?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e4%b8%8b%e8%bd%bd-css 文档

浏览器兼容的问题，我们今年会抽时间做专项解决兼容性问题，目前只能是建议用 chrome

**Comment by blackstar-baba** [comment]
hi，目前有方法解决safari下导出图片部分缺失的问题了不
