### ISSUE TITLE
[Bug Report]: 框选多个节点后无法整体移动

### ISSUE THREAD

**Issue by HanboyLee** [didi/LogicFlow#1468]
### 发生了什么？

![image](https://github.com/didi/LogicFlow/assets/50396232/4d7e87da-cd92-4818-b6d9-d6f2876024b6)
无法拖拽选择框移动
[codesandbox范例](https://codesandbox.io/p/devbox/sleepy-sid-3wjl8k?file=%2Fpackage.json&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr4v5j4m00063575vou7ucgm%2522%252C%2522sizes%2522%253A%255B62.18106995884773%252C37.81893004115227%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr4v5j4m00023575r3dhhn4s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr4v5j4m00033575gu1lidwe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr4v5j4m00053575dtgymbqa%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B51.78549209904193%252C48.21450790095807%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr4v5j4m00023575r3dhhn4s%2522%253A%257B%2522id%2522%253A%2522clr4v5j4m00023575r3dhhn4s%2522%252C%2522activeTabId%2522%253A%2522clr4vexaj0002357571kscaes%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr4v5j4m00013575wmd89ceh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clr4vcixv00c03575x9dt6xw5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr4vexaj0002357571kscaes%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clr4v5j4m00053575dtgymbqa%2522%253A%257B%2522id%2522%253A%2522clr4v5j4m00053575dtgymbqa%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A1234%252C%2522id%2522%253A%2522clr4vnsyy00u43575130g4gst%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr4vnsyy00u43575130g4gst%2522%257D%252C%2522clr4v5j4m00033575gu1lidwe%2522%253A%257B%2522id%2522%253A%2522clr4v5j4m00033575gu1lidwe%2522%252C%2522activeTabId%2522%253A%2522clr4vn0mx00pm3575814ooquy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr4vn0mx00pm3575814ooquy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr4vn0rw0042eggdegdh72gl%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520install%2520%2540logicflow%252Fcore%2540latest%2522%252C%2522id%2522%253A%2522clr4vvms301t935753s7s61xj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A18.19010416666667%257D)

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
hi，请问问题还存在吗，方便重新贴下demo吗

**Comment by DymoneLewis** [comment]
感谢反馈您的反馈，因提供的demo地址无法打开难以定位问题，故关闭该issue，如若问题还存在且需要解决，辛苦带上可访问的demo重新提issue
