### ISSUE TITLE
使用 updateEditConfig 更改配置项 isSilentMode 键盘删除功能存在问题

### ISSUE THREAD

**Issue by liangjiawei1992** [didi/LogicFlow#1470]
### 发生了什么？

[最小可复现示例](https://codesandbox.io/p/devbox/logicflow-updateeditconfig-issilentmode-qr9mws?file=%2Fsrc%2FApp.tsx%3A26%2C19)

如示例代码：
若创建实例时，开启键盘快捷键，
若初始配置  isSilentMode 为 true, 后期更新为false, 则节点不可删除，期望为非静默模式为可删除。
若初始配置  isSilentMode 为 false,  后期更新为true, 则节点可删除，期望为静默模式为不可删除。

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.18

### logicflow/engine版本

0.0.0

### 浏览器&环境

Chrome

**Comment by wbccb** [comment]
跟这个 [https://github.com/didi/LogicFlow/issues/1460](https://github.com/didi/LogicFlow/issues/1460)看起来有点像🤔️又感觉说的不是一回事

**Comment by boyongjiong** [comment]
#1491 已发版修复
