### ISSUE TITLE
[Bug Report]: 页面存在多个实例时，除第一个实例外 Snapshot 导出会不正确。

### ISSUE THREAD

**Issue by xhlsrj** [didi/LogicFlow#1472]
### 发生了什么？

`Snapshot` 的 `getCanvasData` 方法中 `const layout = document.querySelector('.lf-canvas-overlay').getBoundingClientRect();` 没有处理页面存在多个实例的情况。

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by null9999** [comment]
请问你解决了嘛？

**Comment by xhlsrj** [comment]
> 请问你解决了嘛？

改为`this.lf.container.querySelector`就可以了。
