### ISSUE TITLE
[Bug Report]: 节点拉伸的图行设置旋转（allowRotation），旋转过后，再次拉伸会有问题

### ISSUE THREAD

**Issue by zhangluluaichimi** [didi/LogicFlow#1475]
### 发生了什么？

图形设置了旋转，将图形旋转过后，再次拉伸图形，图形拉伸会不正常；只有将图形恢复到最初的样子，拉伸是正常的

https://github.com/didi/LogicFlow/assets/51119207/bbe8335b-1c58-49f5-862b-000569cbb9e0

### logicflow/core版本

1.2.17

### logicflow/extension版本

1.2.18

### logicflow/engine版本

无

**Comment by wumail** [comment]
是个已知问题，今年会对节点变换做重构和优化。如果在使用中如果遇到问题，暂时建议先不要使用包含旋转和缩放的复合功能

**Comment by DymoneLewis** [comment]
您好，这个问题已于最新版本修复，请升级到core 2.0.5版本 extension 2.0.9版本再试一下
