### ISSUE TITLE
[Feature]: 一些功能请求

### ISSUE THREAD

**Issue by hipi** [didi/LogicFlow#1479]
## 1
目前：删除图上的节点, 如果这个节点上有连接线，则同时删除线。
需求：有配置可以配置删除节点不同时删除连线吗

## 2
目前：菜单插件的text 的入参是字符串
需求：能否可以也可以为函数，入参为node或edge , 因为菜单文字可以可以节点或链接状态来修改文字

同时发现按[官网文档自定义菜单](https://site.logic-flow.cn/docs/#/zh/guide/extension/component-menu?id=%e6%8c%87%e5%ae%9a%e4%b8%9a%e5%8a%a1%e7%8a%b6%e6%80%81%e8%ae%be%e7%bd%ae%e8%8f%9c%e5%8d%95)，取不到通过 `lf.extension.menu.addMenuConfig` 添加的菜单，无法在此基础上做追加

**Comment by boyongjiong** [comment]
目前上面的需求 1 在目前的设计下，不可以只删除节点而不删除线，因为线是基于起始节点和结束节点而存在的。

插件的话，如果是拓展功能，建议自定义实现呢。插件的优先级较低，可能会没有人力支持，建议参与共建
