### ISSUE TITLE
[Bug Report]: 选区事件提供的api不能触发

### ISSUE THREAD

**Issue by oym0308** [didi/LogicFlow#1480]
### 发生了什么？

![c13019f3b0ce7710460dcbbb7dadbc6](https://github.com/didi/LogicFlow/assets/20576931/2852ad16-a53c-4236-b4d8-20fc5459144d)
图中红框的方法都不能触发

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
> ### 发生了什么？
> ![c13019f3b0ce7710460dcbbb7dadbc6](https://private-user-images.githubusercontent.com/20576931/298485523-2852ad16-a53c-4236-b4d8-20fc5459144d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTM0NDgsIm5iZiI6MTcxMTk1MzE0OCwicGF0aCI6Ii8yMDU3NjkzMS8yOTg0ODU1MjMtMjg1MmFkMTYtYTUzYy00MjM2LWI0ZDgtMjBmYzU0NTkxNDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2MzIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNjMyMmQwMzlmMzU2YjFmN2VmZmVmYTEyZDcxYTI2YzIyNjM0NWQ1YzExNDM1YTMxYTcxOWUxMGY4ZGY4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9d3kvytwiqXWby6jsBmF-8tiINcQH2jVIYgDCHbvPd8) 图中红框的方法都不能触发
> 
> ### logicflow/core版本
> 1.2.18
> 
> ### logicflow/extension版本
> 1.2.19
> 
> ### logicflow/engine版本
> _No response_
> 
> ### 浏览器&环境
> Chrome

您好，感谢反馈，可能导致选区这几个事件不触发的原因主要有两个：
1. 初始化实例时配置了disabledTools: ['multipleSelect']禁用了多选工具导致无法触发
2. 框选组移动位置大小小于当前设置的网格大小导致没有触发
辛苦自查下是否是两个原因中的某个导致的，如果不是的话请提供一个demo，重启此issue我们排查下
