### ISSUE TITLE
[Bug Report]: lf.updateEditConfig修改stopMoveGraph属性无效

### ISSUE THREAD

**Issue by Litor** [didi/LogicFlow#1482]
### 发生了什么？

初始化时stopMoveGraph为true，通过lf.updateEditConfig动态修改为false；但是画布仍然不能拖动。
![image](https://github.com/didi/LogicFlow/assets/8906885/d1ee0ad1-b839-42de-83ce-987a76bb59fe)

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
我们处理一下

**Comment by boyongjiong** [comment]
#1487 已发版修复
