### ISSUE TITLE
[Bug Report]: 使用bpmn xml初始化后导出为xml时bpmn:process标签的属性丢失

### ISSUE THREAD

**Issue by chengliang4810** [didi/LogicFlow#1488]
### 发生了什么？

使用如图xml无错误的成功初始化画布
![截屏2024-01-25 23 35 43](https://github.com/didi/LogicFlow/assets/118245941/ca8f2289-8b31-47cb-9766-1e0bf78586e2)

通过下图可以观察到 bpmn:process标签的id被替换、name被删除
![截屏2024-01-25 23 39 15](https://github.com/didi/LogicFlow/assets/118245941/81e7143d-e2d2-425f-bf58-3b09f3200289)

我尝试过官方文档中提到的lf.adapterOut来进行处理，发现数据中并不存在bpmn:process相关的内容

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome, NodeJS

**Comment by boyongjiong** [comment]
你目前提供的信息无法确认是什么原因造成的。需要提供更多的信息，比如提供你的 demo
