### ISSUE TITLE
[Bug Report]: nuxt3使用logicflow刷新地址后，报错

### ISSUE THREAD

**Issue by iforgetyounow** [didi/LogicFlow#1489]
### 发生了什么？

首次展示能正常，但是刷新后就异常。
代码：
<template>
    <v-container id="flow-container" class="d-flex mb-6" ref="flow">
    </v-container>
</template>

<script setup>
import {LogicFlow} from "@logicflow/core";

onMounted(() => {
    const lf = new LogicFlow({
        container: document.getElementById("flow-container"),
        grid: true,
        height: 700
    });
    lf.render({
        nodes: [
            {
                id: "1",
                type: "rect",
                x: 100,
                y: 100,
                text: "节点1",
            },
            {
                id: "2",
                type: "circle",
                x: 300,
                y: 100,
                text: "节点2",
            },
        ],
        edges: [
            {
                sourceNodeId: "1",
                targetNodeId: "2",
                type: "polyline",
                text: "连线",
            },
        ],
    });
});
</script>
效果：
1,首次点击展示(正常)：
![image](https://github.com/didi/LogicFlow/assets/41484097/35a539d0-1730-4132-ae92-a797156e6607)
2,直接刷新浏览器地址(异常)：
![image](https://github.com/didi/LogicFlow/assets/41484097/2459a847-4f55-4b5c-9a43-28f139ef5c13)

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
看下如果直接访问 LogicFlow 所在的这个地址，会不会报错呢？

**Comment by boyongjiong** [comment]
补充一下开发工具报错的信息，确认这个是 LogicFlow 报的错吗？我们 Next.js 测试是没有问题的

**Comment by iforgetyounow** [comment]
直接访问不会报错，展示后，刷新地址就会出错，我用的是nuxt.js,不是next.js

**Comment by iforgetyounow** [comment]
直接访问不会报错，展示后，刷新地址就会出错，我用的是nuxt.js,不是next.js，用的这个https://github.com/rekryt/nuxt-vuetify-dashboard demo替换一下界面的内容展示的。

**Comment by iforgetyounow** [comment]
> 看下如果直接访问 LogicFlow 所在的这个地址，会不会报错呢？

直接访问不会报错，正常展示后，刷新地址就会报错。

**Comment by iforgetyounow** [comment]
> 补充一下开发工具报错的信息，确认这个是 LogicFlow 报的错吗？我们 Next.js 测试是没有问题的

用的是nuxt.js,不是next.js，用的这个https://github.com/rekryt/nuxt-vuetify-dashboard 工程，然后找一个界面，把loginflow的demo内容替换一下，点击菜单能正常展示，但是刷新展示的界面就报错了。

**Comment by iforgetyounow** [comment]
> > 补充一下开发工具报错的信息，确认这个是 LogicFlow 报的错吗？我们 Next.js 测试是没有问题的
> 
> 用的是nuxt.js,不是next.js，用的这个https://github.com/rekryt/nuxt-vuetify-dashboard 工程，然后找一个界面，把loginflow的demo内容替换一下，点击菜单能正常展示，但是刷新展示的界面就报错了。
![image](https://github.com/didi/LogicFlow/assets/41484097/76b965d0-4746-4fea-babc-032a106ecea8)

**Comment by iforgetyounow** [comment]
> > > 补充一下开发工具报错的信息，确认这个是 LogicFlow 报的错吗？我们 Next.js 测试是没有问题的
> > 
> > 
> > 用的是nuxt.js,不是next.js，用的这个https://github.com/rekryt/nuxt-vuetify-dashboard 工程，然后找一个界面，把loginflow的demo内容替换一下，点击菜单能正常展示，但是刷新展示的界面就报错了。
> > ![image](https://private-user-images.githubusercontent.com/41484097/301885106-76b965d0-4746-4fea-babc-032a106ecea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODY3NjEsIm5iZiI6MTcwNjg4NjQ2MSwicGF0aCI6Ii80MTQ4NDA5Ny8zMDE4ODUxMDYtNzZiOTY1ZDAtNDc0Ni00ZmVhLWJhYmMtMDMyYTEwNmVjZWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1MDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNjRmZDBhZWQ2Y2U2ZjhhMGQ5OTUwZTgxOTk1MGVkOTNlYWIzODk4YWU0YmE2NGUyNTZmMTZkNmQ5YjZkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vY23fXDPBgooHcBKiyKaGMwEFac3_qcIVXvzI-2AzMQ)

![image](https://github.com/didi/LogicFlow/assets/41484097/00c2d097-0159-448d-8d6c-1dff4d5b99b3)

**Comment by 17347013442** [comment]
> 补充一下开发工具报错的信息，确认这个是 LogicFlow 报的错吗？我们 Next.js 测试是没有问题的

Next.js 使用也发生了window is not defined，代码：  useEffect(() => {
    if (typeof window !== 'undefined') {
      const lf = new LogicFlow({
        container: document.querySelector('#graph') as HTMLElement,
        height: 400,
      });
      lf.render(data);
      lf.translateCenter();
     }
  }, []);
