### ISSUE TITLE
[Bug Report]: 最新的v1.2.20@logicflow/extension本地启动报错。

### ISSUE THREAD

**Issue by ziangtin** [didi/LogicFlow#1495]
### 发生了什么？

![image](https://github.com/didi/LogicFlow/assets/27566264/7f4eb23f-201a-4791-833a-c59b4d4d9744)

### logicflow/core版本

1.2.19

### logicflow/extension版本

1.2.20

### 浏览器&环境

Chrome

**Comment by ziangtin** [comment]
![image](https://github.com/didi/LogicFlow/assets/27566264/1632addb-df4d-4736-b02e-36d4218572ad)
![image](https://github.com/didi/LogicFlow/assets/27566264/3c7fd4fb-384d-4f35-9224-57d768aadcf2)

**Comment by boyongjiong** [comment]
@logicflow/core-1.2.22
@logicflow/extension-1.2.22

.npmignore 文件中配置导致该问题，已重新发包，请更新后试试
