### ISSUE TITLE
[Bug Report]: 自定义节点嵌套 logicflow时，右键菜单事件 怎么区分？

### ISSUE THREAD

**Issue by io-o** [didi/LogicFlow#1496]
### 发生了什么？

<img width="572" alt="image" src="https://github.com/didi/LogicFlow/assets/22197685/983248a7-1f73-4d40-aa21-4693535a6cc0">
如图所以，循环容器是自定义html节点，里面会生成一个新的 logicflow实例，可以往里面拖拽节点，右键菜单，怎么区分。 目前测试，内部节点右键触发不了。

### logicflow/core版本

1.2.16

### logicflow/extension版本

1.2.17

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
补充一下信息，提供一个 demo 我们看下效果

目前字面上理解感觉就是自定义 HTML 内部元素的事件阻止默认事件或阻止冒泡就行，但不确定你是怎么实现的。

**Comment by io-o** [comment]
> 补充一下信息，提供一个 demo 我们看下效果
> 
> 目前字面上理解感觉就是自定义 HTML 内部元素的事件阻止默认事件或阻止冒泡就行，但不确定你是怎么实现的。

自定义HTML 内部元素，阻止了 事件冒泡，外层可以不触发， 但是内部的右键事件一直无法触发。。。

**Comment by io-o** [comment]
已解决
