### ISSUE TITLE
[Feature]: Snapshot 快照插件的getSnapshotBase64方法可以提供配置参数吗

### ISSUE THREAD

**Issue by HeLinSpace** [didi/LogicFlow#1501]
### 背景&目的

我在使用logic flow设计流程图（非bpmn） 在保存时后 列表展示时希望能展示缩略图 但是由于 不同场景的流程图复杂度不一样 导致生成的快照长宽比不一致 展示的时候就比较丑  不知能否 支持在生成快照时 传入图片的长宽或者长宽比 
万分感谢

**Comment by wumail** [comment]
看起来并不复杂，后续可以支持，欢迎共建～

**Comment by wumail** [comment]
欢迎共建，贡献代码说不定可以领到下一次star net的空投

**Comment by boyongjiong** [comment]
2.0 已支持该功能，欢迎升级体验
