### ISSUE TITLE
[Bug Report]: 直接用<script>引入，if.render()渲染json失败，无报错不渲染

### ISSUE THREAD

**Issue by yaoshanli** [didi/LogicFlow#1504]
### 发生了什么？

![微信截图_20240225135238](https://github.com/didi/LogicFlow/assets/33975235/9b9d438d-9e57-4e19-94e8-0f6b89c8eddf)
我使用的是直接用<script>引入方法开发，初始化渲染数据，使用if.render(data)渲染json失败，无报错不渲染

我做的测试程序地址：https://gitee.com/yaoshanli/logicflow.git

### logicflow/core版本

1.2.22

### logicflow/extension版本

1.2.22

### 浏览器&环境

Microsoft Edge

**Comment by boyongjiong** [comment]
最好通过 codesanbox 提供 demo，项目这种的没办法确认。

请确认好是 LogicFlow 的问题再提 issue，目前根据描述看不是 LogicFlow 的问题，暂时先将 issue 关闭

**Comment by wumail** [comment]
用renderRawData试试？

**Comment by yaoshanli** [comment]
> 用renderRawData试试？

对对对，就是这样，可以了，万分感谢。
