### ISSUE TITLE
[Feature]: 画布重新渲染后，undo和redo可以支持编辑吗

### ISSUE THREAD

**Issue by ninjia111** [didi/LogicFlow#1510]
### 背景&目的

已保存的画布数据，重新加载渲染出来后，历史记录里的undo和redo没有数据，希望undo和redo可编辑，能手动把保存前的分析步骤重新写入history里

**Comment by wumail** [comment]
这个我理解你可以把操作历史和图数据一起保存起来，渲染的时候自己还原，我们能做的也是这些
