### ISSUE TITLE
[Feature]: 容器内流程过多，看不明显，不知道下面还有没有内容，怎么加滚动条

### ISSUE THREAD

**Issue by luomings** [didi/LogicFlow#1512]
### 背景&目的

容器内流程过多，看不明显，不知道下面还有没有内容，怎么加滚动条

**Comment by boyongjiong** [comment]
LogicFlow 目前没有滚动条的设计，如果想要加，可以思考一下给自己写的容器加。

非 feature，目前无相关计划，关闭 issue
