### ISSUE TITLE
[Bug Report]: 静默模式下的点击事件触发问题

### ISSUE THREAD

**Issue by AshTshi** [didi/LogicFlow#1516]
### 发生了什么？

设置isSilentMode:true后，node上的node:click和自定义点击事件均无法再触发，但是edge:click可以正常触发

设置为静默模式:
    const lf = new LogicFlow({
      container: refContainer.current,
      grid: true,
      width: 2000,
      height: 600,
      isSilentMode:true
    });

绑定node的自定义点击事件，edge点击事件：
   lf.on("custom:button-click,edge:click", (model) => {
      window.alert('detail msg')
    });

点击node无法触发alert window
点击edge可以触发

![8c00075a306e8bf296e0aca113f45b4](https://github.com/didi/LogicFlow/assets/40843696/0e8f0650-bc42-4489-a67b-5613d6326fdd)

**期望**：希望node在静默模式下仍可以触发点击事件，保持node上的信息展示能力

### logicflow/core版本

1.2.22

### logicflow/extension版本

1.2.22

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
你的custom:button-click触发时机是什么样的呢？我这边试了一下LF内置的节点点击事件node:click是可以正常触发的

**Comment by DymoneLewis** [comment]
您好，感谢您的反馈，如果这个问题还需要解决的话，辛苦贴一下您的custom:button-click事件的触发逻辑并重启此issue，我们排查一下
