### ISSUE TITLE
[Feature]: 可以更新一下官方文档吗？

### ISSUE THREAD

**Issue by ifYouLike-Weirdo** [didi/LogicFlow#1518]
### 背景&目的

API好多都不是最新的，还要对比，希望可以更新一下

**Comment by wumail** [comment]
看看这个，https://beta.logic-flow.cn/

**Comment by ifYouLike-Weirdo** [comment]
> 看看这个，https://beta.logic-flow.cn/

感谢

**Comment by ifYouLike-Weirdo** [comment]
> 看看这个，https://beta.logic-flow.cn/

![image](https://github.com/didi/LogicFlow/assets/55228333/f57b35ff-7da3-4c0c-8f80-9bc7f55db9ee)
又404了，进不去了
