### ISSUE TITLE
[Bug Report]: angular17 ssr的问题

### ISSUE THREAD

**Issue by msx15615634157** [didi/LogicFlow#1523]
### 发生了什么？

我的angular17的项目，而且需要ssr,最近引入logicflow后，ssr失败了。
An unhandled exception occurred: window is not defined

经过排查发现，一直使用的
`   if (判断是浏览器环境) {
      执行浏览器操作
    }else{
      node环境
    }`
    方案失效了
    
    发现，极端的条件下，只要出现了LogicFlow的声明，都会导致window not defined。明明以下的代码不可达，仍然会触发ssr的失败，这让我很苦恼
    ` if (false) {
      console.log(LogicFlow)
    }`

### logicflow/core版本

1.2.22

### logicflow/extension版本

1.2.22

### logicflow/engine版本

1.2.22

### 浏览器&环境

NodeJS

**Comment by msx15615634157** [comment]
[demo-ssr.zip](https://github.com/didi/LogicFlow/files/14622500/demo-ssr.zip)

**Comment by wumail** [comment]
@DymoneLewis cc

**Comment by DymoneLewis** [comment]
重复issue
