### ISSUE TITLE
[Bug Report]: angular17 ssr的问题

### ISSUE THREAD

**Issue by msx15615634157** [didi/LogicFlow#1524]
### What happened?

我的angular17的项目，而且需要ssr,最近引入logicflow后，ssr失败了。
An unhandled exception occurred: window is not defined

经过排查发现，一直使用的
   if (判断是浏览器环境) { 执行浏览器操作 }else{ node环境 }
方案失效了

发现，极端的条件下，只要出现了LogicFlow的声明，都会导致window not defined。明明以下的代码不可达，仍然会触发ssr的失败，这让我很苦恼
` if (false) {
  console.log(LogicFlow)
}`
[demo-ssr.zip](https://github.com/didi/LogicFlow/files/14622505/demo-ssr.zip)

### Core Version

1.2.22

### Extension Version

1.2.22

**Comment by boyongjiong** [comment]
能们定位一下 window is not defined 是哪儿触发的吗，内部一些方法是用到了 window，ssr 预编译的时候可能会导致报错，但我现在看不出来是哪个导致的

**Comment by msx15615634157** [comment]
angular的ssr报错，一言难尽。就像demo里面报的错的一样，就那么一行，其余什么有用信息都没有。不知道vue的ssr会不会有不同

**Comment by boyongjiong** [comment]
你抽空试一下？我今天在一个 utils 中 isIe 方法，我看定义的是变量，它会在初始化的时候执行，会导致报 window is not defined 的错误。

@logicflow/core@2.0.3
