### ISSUE TITLE
[Bug Report]: 自定义节点锚点的连线无法正确回显

### ISSUE THREAD

**Issue by zhangyufen** [didi/LogicFlow#1526]
### 发生了什么？

自定义节点的锚点以后，锚点之间的连线在提供了type,sourceNodeId, targetNodeId, sourceAnchorId 和 targetAnchorId 几个主要参数后，仍旧无法正确回显。测试发现必须存在startPoint 和 endPoint 就正常了 

期待结果
![image](https://github.com/didi/LogicFlow/assets/14355473/2d8883db-f595-494f-b075-72706fb341dc)

实际结果
![image](https://github.com/didi/LogicFlow/assets/14355473/62943b68-ed9b-4a37-a6cc-165538d33e1d)

可复现示例
https://codesandbox.io/p/sandbox/logicflow-base15-forked-m5j52t?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clto6wwru00063b6hynhm9s0c%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clto6wwru00023b6h1ojlomq7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clto6wwru00033b6h16qcmyyq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clto6wwru00053b6h5lku7457%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clto6wwru00023b6h1ojlomq7%2522%253A%257B%2522id%2522%253A%2522clto6wwru00023b6h1ojlomq7%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clto6wwru00053b6h5lku7457%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clto6wwru00043b6hbdko5s3r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clto6wwru00053b6h5lku7457%2522%252C%2522activeTabId%2522%253A%2522clto6wwru00043b6hbdko5s3r%2522%257D%252C%2522clto6wwru00033b6h16qcmyyq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clto6wwru00033b6h16qcmyyq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### logicflow/core版本

1.2.5

### logicflow/extension版本

1.2.5

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
hi，请问回填的时候没带startPoint和endPoint是有什么背景吗，理论上 边数据里是有startPoint和endPoint数据的，回填应该是会带上对应数据的

**Comment by zhangyufen** [comment]
我最开始用自定义节点做了一个类似的效果，测试时发现它的边回显不需要startPoint 和 endPoint，就以为自定义锚点的边应该也是这样的。。。。

**Comment by zhangyufen** [comment]
我有点理解startPoint he endPoint 必须存在的原因了，自定义锚点的位置并不容易内部计算。  如果不是个bug的话，那我把节点位置和边startPoint endPoint都存下来吧
