### ISSUE TITLE
group可变形分组初始化以后，点击子节点，isSelect为true， 但是四个变形控制点都在变现的底层，处于假选中状态[Bug Report]: 

### ISSUE THREAD

**Issue by DavisGYF** [didi/LogicFlow#1535]
### 发生了什么？

https://github.com/didi/LogicFlow/assets/34234187/8583d338-f3a0-4605-98f7-0432422318bf

https://github.com/didi/LogicFlow/assets/34234187/cd06e8d3-1194-445d-b73b-566b7f5203bb

![image](https://github.com/didi/LogicFlow/assets/34234187/2b8918d4-6c14-43ae-afc0-bef196e7be82)

### logicflow/core版本

ex.1.2.18

### logicflow/extension版本

ex.1.2.19

### 浏览器&环境

Chrome

**Comment by wbccb** [comment]
如果方便的话 最好提供一个最小化的可复现示例 这样排查会快一点 @DavisGYF

**Comment by DavisGYF** [comment]
> 如果方便的话 最好提供一个最小化的可复现示例 这样排查会快一点 @DavisGYF

我仔细看了 官方的这个泳道图 就可以复现
https://examples.logic-flow.cn/demo/dist/pool

1 加载之后直接 点击lane组件 四个角的拖拽显示的就不对 就是我说的假选中状态 图片乳腺
![image](https://github.com/didi/LogicFlow/assets/34234187/689fd170-d772-4b58-8697-c30509d5fd31)
2 加载之后 你先点击 pool再点击 lane 就是正确的状态
![image](https://github.com/didi/LogicFlow/assets/34234187/6211d193-dbd2-4d8c-b8c4-a9c4a508edb6)

仔细看上面2个图片的四角 你们可以去实际操作一下 直接看就是很明显 不对 
**重点是 上面第一种假选中状态的时候 你鼠标很不好 选中点击四个点进行拖拽变形**

**Comment by DavisGYF** [comment]
@wbccb 可以直接去实操一下

**Comment by DymoneLewis** [comment]
您好，该问题已修复，辛苦升级到1.2.26版本验证一下😊
