### ISSUE TITLE
[Feature]: 希望增加【节点文本】和【边文本】的修改事件

### ISSUE THREAD

**Issue by WangJincheng4869** [didi/LogicFlow#1538]
### 背景&目的

点击节事件获取到的数据并不是响应式的，所以导致无法获取修改节点文本的最新值，也就无法修改自定义配置面板中关于节点名称的值。（目前暂时禁用修改节点文本解决）

希望增加这两个修改事件，这样就可以自定义处理自定义修改面板中的数据。

**Comment by DymoneLewis** [comment]
您好，文本修改事件已于2.0.0版本中添加，您可以监听
