### ISSUE TITLE
[Bug Report]: 官网部分示例链接失效

### ISSUE THREAD

**Issue by regiondavid** [didi/LogicFlow#1539]
### 发生了什么？

比如https://site.logic-flow.cn/tutorial/extension-insert-node-in-polyline
跳转到了https://site.logic-flow.cn/demo/dist/examples#/extension/InserNodeInPolyline?from=doc
然后404

### logicflow/core版本

xxx

### logicflow/extension版本

xxx

### 浏览器&环境

Chrome

**Comment by wumail** [comment]
@DymoneLewis @sophia502 cc

**Comment by DymoneLewis** [comment]
感谢反馈，问题已修复，请查收ღ( ´･ᴗ･` )
