### ISSUE TITLE
[Bug Report]: Firefox 鼠标滚轮缩放无反应

### ISSUE THREAD

**Issue by colinjiang007** [didi/LogicFlow#1543]
### 发生了什么？

[Bug Report]: Firefox 鼠标滚轮缩放无反应,无法缩放.

### logicflow/core版本

1.2.23

### logicflow/extension版本

1.2.23

### logicflow/engine版本

1.2.23

### 浏览器&环境

Firefox

**Comment by DymoneLewis** [comment]
🤔 stopMoveGraph、stopZoomGraph属性有设置为true吗，这边用firefox没复现

**Comment by DymoneLewis** [comment]
您好，因该issue长期没有回复，所以这边先把issue关闭了，如果仍有问题，欢迎重启issue，提供更多的信息给我们继续排查
PS：LogicFlow 2.0版本已正式发布，欢迎您升级使用，2.0改动一览传送门：https://site.logic-flow.cn/tutorial/update
