### ISSUE TITLE
带text文本的节点menu右键-复制，复制出来节点x,y和文本x,y的位置不一样，text都比节点的xy少10个像素[Bug Report]: 

### ISSUE THREAD

**Issue by DavisGYF** [didi/LogicFlow#1545]
### 发生了什么？

![image](https://github.com/didi/LogicFlow/assets/34234187/54cf3c98-c7e4-4453-9480-fa09d285e6cf)
https://codesandbox.io/embed/dazzling-hypatia-en8s9?fontsize=14&hidenavigation=1&theme=dark&view=preview
这个链接 是官方给的 右键menu示例链接

### logicflow/core版本

ex.1.2.18

### logicflow/extension版本

ex.1.2.19

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
您好，该问题已修复，辛苦升级到1.2.26版本验证一下😊
