### ISSUE TITLE
[Bug Report]: BPMNAdapter 转换 XML 字符串为 js 数据，转换不正确

### ISSUE THREAD

**Issue by hoishing-lam** [didi/LogicFlow#1548]
### 发生了什么？

如题，现在我有一个对象数据：

```js
const graphData = {
  nodes: [
    {
      id: '1',
      type: 'rect',
      x: 100,
      y: 100,
    },
    {
      id: '2',
      type: 'circle',
      x: 300,
      y: 200,
    },
  ],
  edges: [
    {
      id: 'edge1',
      type: 'polyline',
      sourceNodeId: '1',
      targetNodeId: '2',
      startPoint: { x: 150, y: 100 },
      endPoint: { x: 250, y: 200 },
      pointList: [
        { x: 150, y: 100 },
        { x: 200, y: 100 },
        { x: 200, y: 200 },
        { x: 250, y: 200 },
      ],
    },
  ],
};
```

使用 BPMNAdapter，把实例的 XML 字符串转为 js 数据，再与实例本身的 js 数据对比，发现两者对比不上：

```js
// 获取实例 xml 字符串
const xml = lf.getGraphData();

// 转换 xml 字符串为 graphData
const convertedGraphData = lf.adapterIn(xml);

// 获取实例自身 graphData
const selfGraphData = lf.getGraphRawData();
```

问题复现链接：[https://codesandbox.io/p/sandbox/confident-tdd-kpcrsq](https://codesandbox.io/p/sandbox/confident-tdd-kpcrsq)。点击上面复现 demo 的按钮，查看控制台：

![image](https://github.com/didi/LogicFlow/assets/155834675/5ef2e137-1d90-49a6-bd6e-d91409fca3dc)

问题复现链接：[https://codesandbox.io/p/sandbox/confident-tdd-kpcrsq](https://codesandbox.io/p/sandbox/confident-tdd-kpcrsq)

### logicflow/core版本

1.2.23

### logicflow/extension版本

1.2.23

### 浏览器&环境

Chrome

**Comment by hoishing-lam** [comment]
demo 里面还有个问题，`renderRawData` 渲染是没问题，但转换为 xml 字符串后调用 `render` 是出错的：

```js
// it works
lfRef.current.renderRawData(graphData);

// 注释上面一行，而执行以下两行，是会报错的
// const xml = lfRef.current.adapterOut(graphData);
// lfRef.current.render(xml);
```

**Comment by wumail** [comment]
这个问题是这样的，BPMNAdapter只识别BPMN节点，demo里的rect节点和circle节点都不是合法的BPMN节点，所以不被识别和转换，而edge元素bpmn:sequenceFlow 是合法的BPMN节点，所以被识别和转换了
![image](https://github.com/didi/LogicFlow/assets/56008486/354fbe57-0d4e-44a6-9528-246297a29c87)
这就是为什么转换的结果为
```typescript
{
  edges: Array(1),
  nodes: Array(0)
}
```

**Comment by hoishing-lam** [comment]
> 这个问题是这样的，BPMNAdapter只识别BPMN节点，demo里的rect节点和circle节点都不是合法的BPMN节点，所以不被识别和转换，而edge元素会被默认转为 bpmn:sequenceFlow 是合法的BPMN节点，所以被识别和转换了 ![image](https://private-user-images.githubusercontent.com/56008486/320342796-354fbe57-0d4e-44a6-9528-246297a29c87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDYyODcsIm5iZiI6MTcxMjU0NTk4NywicGF0aCI6Ii81NjAwODQ4Ni8zMjAzNDI3OTYtMzU0ZmJlNTctMGQ0ZS00NGE2LTk1MjgtMjQ2Mjk3YTI5Yzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAzMTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjODRjM2VjZjkxNGU2MmEzMzczZDYyYzhkZjI1Y2EyNjEwODkyZDUxZDFiZGYxNmY0ZDRjZWQ5MWY4Yjk4ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SvhZOhBaMxONckQD23BdaEKnpS7gyDO-ZFdHke7RLXQ) 这就是为什么转换的结果为
> 
> ```ts
> {
>   edges: Array(1),
>   nodes: Array(0)
> }
> ```

原来是数据问题，感谢回复。我看[文档](https://site.logic-flow.cn/tutorial/basic-node)说 react 和 circle 是 logicflow 内置的节点，以为是能够转换成 bpmn 节点的。
