### ISSUE TITLE
[Bug Report]: 自定义节点每次拖拽生成会创建两个实例

### ISSUE THREAD

**Issue by yyp0716** [didi/LogicFlow#1556]
### 发生了什么？

![image](https://github.com/didi/LogicFlow/assets/51068965/023c1b30-9aa4-43c0-9e70-3d04af7236d5)
每次拖拽生成会生成两个vue实例，导致vue内监听事件触发多次，且页面html只有一个节点。
https://codesandbox.io/p/sandbox/logicflow-cdfxwc?file=%2Fsrc%2Fcomponents%2Fstart_input.vue%3A45%2C12
拖拽生成开始节点即可查看到mounted触发了两次。

### logicflow/core版本

1.2.17

### logicflow/extension版本

1.2.18

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
目前logicflow内部机制是当一个新的节点拖进画布的时候会先创建一个虚拟节点供用户操作，此时会触发一次（即虚拟节点的setHtml）；用户触发mouseup后才会创建一个真实节点，此时会触发第二次（真实节点的setHtml），所以会触发两次
在您的case里，如果只想触发真实节点的mounted事件的话，可以在SqlNode的setHtml里增加model.virtual的判断逻辑，在为true的时候不触发mounted即可
`
...
if(model.virtual) return;
new Profile().$mount(el);
`

**Comment by DymoneLewis** [comment]
感谢您的反馈，辛苦参考上面评论里的解决方案试一下是否满足诉求，如有问题欢迎再反馈讨论

**Comment by yyp0716** [comment]
完美解决，感谢
