### ISSUE TITLE
与diamond类型节点连接的边，在拖动时必定报错，将下面官网例子的矩形1改成diamond可复现

### ISSUE THREAD

**Issue by knchen-java** [didi/LogicFlow#1562]
官网例子：
<img width="989" alt="image" src="https://github.com/didi/LogicFlow/assets/59496110/44682250-8815-4812-88f5-72250ac92f37">
复现数据：
const data = {
  nodes: [
    {
      id: '1',
      type: 'diamond',
      x: 100,
      y: 100,
      text: '矩形1',
    },
    {
      id: '2',
      type: 'ellipse',
      x: 500,
      y: 100,
      text: '椭圆2',
    },
    {
      id: '3',
      type: 'polygon',
      x: 100,
      y: 250,
      text: '多边形3',
    },
    {
      id: '4',
      type: 'diamond',
      x: 300,
      y: 250,
      text: '菱形4',
    },
  ],
  edges: [
    {
      sourceNodeId: '1',
      targetNodeId: '2',
      startPoint: {
        x: 100,
        y: 60,
      },
      endPoint: {
        x: 500,
        y: 50,
      },
      type: 'polyline',
    },
    {
      sourceNodeId: '2',
      targetNodeId: '3',
      type: 'line',
    },
    // TODO
    {
      sourceNodeId: '2',
      targetNodeId: '4',
      type: 'bezier',
    },
  ],
};

**Comment by DymoneLewis** [comment]
感谢反馈，我们修复一下
