### ISSUE TITLE
[Bug Report]: 在特定版本下，节点缩放 NodeResize不生效。

### ISSUE THREAD

**Issue by destiny516** [didi/LogicFlow#1570]
### 发生了什么？

在版本    "@logicflow/core": "1.2.22",    "@logicflow/extension": "1.1.15",版本下，可以正常显示，但是当有拖拽动作的时候，没有放大缩小效果。
[示例](https://codesandbox.io/p/devbox/logicflow-resize-bug-mg4zqm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluw4sh3v0007356imvvh7mqm%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluw4sh3u0002356ien4djqr5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluw4sh3u0004356ipcua9ipz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluw4sh3v0006356ilzu8zh9h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluw4sh3u0002356ien4djqr5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluw4sh3u0001356igbj95w4l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cluw4sh3u0002356ien4djqr5%2522%252C%2522activeTabId%2522%253A%2522cluw4sh3u0001356igbj95w4l%2522%257D%252C%2522cluw4sh3v0006356ilzu8zh9h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluw4sh3v0005356i6xm7b4av%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluw4sh3v0006356ilzu8zh9h%2522%252C%2522activeTabId%2522%253A%2522cluw4sh3v0005356i6xm7b4av%2522%257D%252C%2522cluw4sh3u0004356ipcua9ipz%2522%253A%257B%2522id%2522%253A%2522cluw4sh3u0004356ipcua9ipz%2522%252C%2522activeTabId%2522%253A%2522cluw9f5he00jk356isoc7mrvs%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluw4sh3u0003356i32jdel6i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%252C%257B%2522id%2522%253A%2522cluw5192500cx356izrvjbgj3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluw5197g001odbhufn8b33eh%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%252C%2522id%2522%253A%2522cluw9f5he00jk356isoc7mrvs%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
![动画 (0)](https://github.com/didi/LogicFlow/assets/45482458/6ce0ab3d-9b08-45ce-a0f7-0efb2da40965)

### logicflow/core版本

1.2.22

### logicflow/extension版本

1.1.15

### 浏览器&环境

Chrome

**Comment by destiny516** [comment]
还有一个问题，当我把最大高或宽与初始高或宽设置成一样的时候，也会失效，  比如
```javascript
initNodeData(data) {
        super.initNodeData(data);
        this.width = 160
        this.height = 20
        this.radius = 5
        this.maxWidth = 300;
        this.maxHeight = 20;
}
```

**Comment by destiny516** [comment]
所以延伸出一个问题，如果我只想宽或高缩放的需求的话怎么办？

**Comment by DymoneLewis** [comment]
您好，这边排查了一下原因应该是core包和extension包版本不一致导致的，辛苦升级下extension版本

**Comment by DymoneLewis** [comment]
> 所以延伸出一个问题，如果我只想宽或高缩放的需求的话怎么办？

对于这个需求，可以设置节点的宽高的min值和max值一致，不过当前最新resizeNode插件中这么设置之后操作起来体验比较差，这两天会发布新版本完全支持上

**Comment by destiny516** [comment]
好的，谢谢

**Comment by destiny516** [comment]
我发现在
    "@logicflow/core": "^1.2.26",
    "@logicflow/extension": "^1.2.26"
    版本下，缩放也是不生效的
[代码示例](https://codesandbox.io/p/devbox/logicflow-resize-bug-mg4zqm?file=%2Fpackage.json%3A13%2C1-14%2C38)

**Comment by DymoneLewis** [comment]
了解，这边看下∠(°ゝ°)

**Comment by destiny516** [comment]
还有一个最低高度的问题，就是高度设置成30以下，是不能缩放的，最小30.

**Comment by DymoneLewis** [comment]
> 还有一个最低高度的问题，就是高度设置成30以下，是不能缩放的，最小30.

因为ResizeNode内部设置了的minHeight（就是30），如果有更小的诉求的话，在自定义的节点里重新设置一下this.minHeight就行
