### ISSUE TITLE
[Bug Report]: groupNode.addChild方法有bug

### ISSUE THREAD

**Issue by DonZZZ668** [didi/LogicFlow#1577]
### 发生了什么？

addNode(groupNode)手动生成一个groupNode,然后通过groupNode.addChild(node.id)将一个节点手动加入，将此节点移出groupNode区域按道理应该这两个节点解除分组关系，但是并没有，还会绑定，除非，手动移动一下node节点才会解除绑定；看了下代码，手动拖入节点到组会触发materials/group/index.js中的appendNodeToGroup方法，此方法会_this.nodeGroupMap.set(data.id,group.id)，移出节点出组会触发appendNodeToGroup(),其中会用到nodeGroupMap。但是groupNode.addChild(node.id)并不会修改nodeGroupMap，所以手动将节点加入组，再将节点移出会触发此bug。
解决方案:在手动加入组groupNode.addChild(node.id)后增加一行代码，lf.extension.group.nodeGroupMap.set(node.id,groupNode.id),我们手动加入这个Map即可。

https://github.com/didi/LogicFlow/assets/61984651/1472fdc8-10d8-4c4b-9597-2f2e07f064a6

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### logicflow/engine版本

null

### 浏览器&环境

Chrome

**Comment by wbccb** [comment]
[https://github.com/didi/LogicFlow/issues/1576](https://github.com/didi/LogicFlow/issues/1576)

已经修复了吧？
