### ISSUE TITLE
[Bug Report]: 右侧panel信息不更新

### ISSUE THREAD

**Issue by ABing1118** [didi/LogicFlow#1578]
### 发生了什么？

![1509ad65a613acd31d76979197d1c35](https://github.com/didi/LogicFlow/assets/103724048/eae64949-4d2a-4696-ad79-7ac8a11ceecf)
![a5fc85f167648a1cfbad021b89bf706](https://github.com/didi/LogicFlow/assets/103724048/b978cb04-e79a-4c0e-a013-41a44ff677c5)
![aafb13804ebcb1e6108881313f7bc14](https://github.com/didi/LogicFlow/assets/103724048/81f6d1bf-c583-4ec2-a239-26fa81ae2961)只有当我点击一个空白处，让右边的panel消失之后再点击白色的圆角长方形右侧才显示正常
![084ba57286c9c0d5b1e6d0120686207](https://github.com/didi/LogicFlow/assets/103724048/35da674a-40ac-43a1-8d17-b81195cf8b43)就是我如果不点击一个空白地方，直接点击另一个节点，他的右边panel始终是一开始的那个而不是最新的

### logicflow/core版本

最新

### logicflow/extension版本

最新

### 浏览器&环境

Microsoft Edge

**Comment by boyongjiong** [comment]
这个应该是示例的 bug，我们这儿不追踪这个的问题哈，感觉应该就是哪儿写的有问题，可以自己 debug 一下
