### ISSUE TITLE
vue3 使用时 切换显示状态 内存一直在增加 没有自动清楚缓存

### ISSUE THREAD

**Issue by shmily-xxx** [didi/LogicFlow#1581]
### What happened?

vue3 使用时 切换显示状态 内存一直在增加 没有自动清楚缓存 这只是例子 实际内容更多 更卡
最开始内存
![1713433395983](https://github.com/didi/LogicFlow/assets/84055095/b08e399b-b57c-4dc2-b63d-f3d53b2c7d59)
切换几次后内存
![1713433159666](https://github.com/didi/LogicFlow/assets/84055095/8e9e7228-62a4-4089-b89f-379a4431c63b)
[logicflow.zip](https://github.com/didi/LogicFlow/files/15022879/logicflow.zip)

### Core Version

1.1.23

### Extension Version

1.1.23

### What browsers are you seeing the problem on?

Chrome

**Comment by shmily-xxx** [comment]
![1713517432925](https://github.com/didi/LogicFlow/assets/84055095/d05f2861-f58b-4fa1-9741-bc3891ea7bb0)
发现新增的这个自定义html节点没有删除 多次操作会一直增加 内存也在增加

**Comment by DymoneLewis** [comment]
感谢反馈，确实有这样的问题，目前正在开发destroy方法，短期比较推荐在FlowChart的beforeDestroy里调用一下lf.clearData()方法清空画布或者使用v-show控制组件的显隐

**Comment by shmily-xxx** [comment]
我尝试了lf.clearData()方法 节点还在 感觉作用不是太大

**Comment by wumail** [comment]
> 我尝试了lf.clearData()方法 节点还在 感觉作用不是太大

我跑了下你给的示例
1、FlowChart组件销毁但是节点内存不释放的问题确实存在，无论是html节点还是一般的节点
![image](https://github.com/didi/LogicFlow/assets/56008486/39cb59a7-174d-4f42-8ea4-969039ba23e5)
![image](https://github.com/didi/LogicFlow/assets/56008486/1469268a-57c0-4400-a7f4-dcadcc39e532)
2、内存的增长情况还好
一开始：
![image](https://github.com/didi/LogicFlow/assets/56008486/84f20cfa-670f-4d03-a075-c8081347b09b)
GC后：
![image](https://github.com/didi/LogicFlow/assets/56008486/feb8b102-7a4e-4e98-a2db-13b7034e751b)
3、尝试做了一些解除引用的动作，有一定作用，但是不影响结论1
![image](https://github.com/didi/LogicFlow/assets/56008486/0b264565-55b8-47cc-868c-419718a683c5)
![image](https://github.com/didi/LogicFlow/assets/56008486/e5a17114-6898-4972-8de5-291f970cc36e)
![image](https://github.com/didi/LogicFlow/assets/56008486/1be67136-d5d0-455c-8843-a9f39251a5ce)
![image](https://github.com/didi/LogicFlow/assets/56008486/5b0d4fce-b629-4f44-a48f-317eb36a6708)

**Comment by shmily-xxx** [comment]
我尝试了你的这种方法 列子里面数据少 我用到项目组作用不大 
这是我用例子跑的 先切换显隐看下是100mb  再切换很多次增加到了200mb，而且 componentWillMount() {
    this.app.unmount()
  }还会有警告
![1714114766777](https://github.com/didi/LogicFlow/assets/84055095/5801cda7-44aa-4e18-9ae1-16999f042c9f)

![1714115064331](https://github.com/didi/LogicFlow/assets/84055095/dc87bbca-3b54-4f7e-8c37-2279d17dd952)
请问下 后期会提供 销毁方法吗？

**Comment by wumail** [comment]
> 我尝试了你的这种方法 列子里面数据少 我用到项目组作用不大 这是我用例子跑的 先切换显隐看下是100mb 再切换很多次增加到了200mb，而且 componentWillMount() { this.app.unmount() }还会有警告 ![1714114766777](https://private-user-images.githubusercontent.com/84055095/325878626-5801cda7-44aa-4e18-9ae1-16999f042c9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTk1OTMsIm5iZiI6MTcxNDExOTI5MywicGF0aCI6Ii84NDA1NTA5NS8zMjU4Nzg2MjYtNTgwMWNkYTctNDRhYS00ZTE4LTlhZTEtMTY5OTlmMDQyYzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA4MTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTdkZWQwMzBlYjhhMTliMzJiYjY4ZThkODcyNjdlNTgzNTg0ZDIzMDIxODdhMzhkYmYwNjFmZjE1M2JiZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jrM56KYfe9JEDyDFaVBWsO16dZTgfR3nfstG-AXc1_c)
> 
> ![1714115064331](https://private-user-images.githubusercontent.com/84055095/325879326-dc87bbca-3b54-4f7e-8c37-2279d17dd952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTk1OTMsIm5iZiI6MTcxNDExOTI5MywicGF0aCI6Ii84NDA1NTA5NS8zMjU4NzkzMjYtZGM4N2JiY2EtM2I1NC00ZjdlLThjMzctMjI3OWQxN2RkOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA4MTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNWY0NDA0MDQ2Mzk2OWJkNDczZWY4OWY3ODI4OWU0MmQyNTBjMmIwMDRmNGM4N2YwOWNhNjc2Mjg1NDVkODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nHiIkTazgDJMdtig7qSfzWWG-lrUeoYinTBTh1O3aNo) 请问下 后期会提供 销毁方法吗？

销毁的方法目前看确实是需要的，内存未释放的问题需要整体看下、排查一下，工作量可能不小

**Comment by wbccb** [comment]
```js
import { createApp } from 'vue';
import Palette from './tools/Palette.vue';
import VueHtmlNode from './nodes/VueHtmlNode';

class NodeRedExtension {
  static pluginName = 'NodeRedExtension'
  constructor ({ lf }) {
    lf.register(VueHtmlNode);
    lf.setDefaultEdgeType('flow-link');
    this.app = createApp(Palette, {
      lf
    })
  }
  render(lf, domOverlay) {
    const node = document.createElement('div')
    node.className = 'node-red-palette'
    domOverlay.appendChild(node)
    this.app.mount(node)
  }
}

export default NodeRedExtension
```

初步看了下，感觉是这个`this.app.mount(node)`没有释放掉，本质还是`destroy方法`需要完善一下，尤其是插件的`destroy方法`

**Comment by wbccb** [comment]
@boyongjiong 没解决没解决 这个内存泄露问题还没解决 不要被我误导了....

**Comment by Java-Xc** [comment]
定时刷新节点和边，内存会一直增加直到浏览器崩掉，我的天啊
