### ISSUE TITLE
[Bug Report]: angular使用logicflow时需要引入preact和mobix这两个库感觉很怪异

### ISSUE THREAD

**Issue by duopu** [didi/LogicFlow#1583]
### 发生了什么？

使用@angular/cli": "12.2.16创建的项目引入logicflow时，

如果不引入"mobx": "^5.15.4","preact": "^10.12.1",这两个库会有编译报错，
其中好像是类型引用的报错，而且还不能引用最新版本的mobix和preact。 感觉很怪异，我一个别的类型的框架为何再额外引用这两个库才能运行，作为一个大厂出品的库我觉得不应该存在这种低级的设计缺陷，新手感觉很懵逼，你内部怎么实现我不管，但是外部使用的时候不应该存在这么多的门槛和坑。

我在预研antd/x6的时候，使用感司就很丝滑，在安装过程中几乎没有什么坑，安装运行就跑起来了。只是后来因为不可抗力的因素选择了 logicflow。

运行logicflow时就一路坎坷，

第一步只安装了这三个库的时候存在的报错：
    "@logicflow/core": "^1.2.26",
    "@logicflow/engine": "0.0.12",
    "@logicflow/extension": "^1.2.26",
![PixPin_2024-04-22_11-09-13](https://github.com/didi/LogicFlow/assets/148187698/c5888b21-6db2-4d85-b479-efa9bb2d7702)

然后按照提示我安装了最新的mobx，然后又报了这个：
![image](https://github.com/didi/LogicFlow/assets/148187698/b0d9d72d-852b-43c2-a8a9-d29266abc0d1)

最终在几经摸索的情况下把 依赖包安装成 "mobx": "^5.15.4","preact": "^10.12.1", 才勉强跑起来，一路跑起来真无语，望改善使用体验

### logicflow/core版本

1.2.26

### logicflow/extension版本

1.2.26

### logicflow/engine版本

0.0.12

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
我们升级了 2.0 版本，能升级 2.0 版本再试一下吗？我们这边都没有 Angular 的经验，所以没有测 Angular 场景
