### ISSUE TITLE
节点右键菜单如何根据节点状态可以实现动态的显隐

### ISSUE THREAD

**Issue by qingfenglailai** [didi/LogicFlow#1587]
### 背景&目的

开发过程中节点node 需要添加右键菜单, 并且根据当前节点的执行状态 要动态的做右键菜单内容的显隐切换

**Comment by wumail** [comment]
可以尝试自己实现哦~ 可以参考https://github.com/didi/LogicFlow/blob/master/packages/extension/src/components/menu/index.ts 虽然从现在来看这样的写法很原始
