### ISSUE TITLE
[Bug Report]: 内置插件小地图miniMap的选中框变成了个蓝点，并且移动蓝点会疯狂报错

### ISSUE THREAD

**Issue by Ljy66** [didi/LogicFlow#1593]
### 发生了什么？

- 在vue3项目中使用logicflow以及内置插件小地图MiniMap，实际渲染效果却是个蓝点，并且拖动蓝点时会报错，如下图

![image](https://github.com/didi/LogicFlow/assets/32189692/ad4def0a-5e46-494b-8131-c320351ee9d7)

- 报错信息【“Error: <g> attribute transform: Expected number, "…atrix(1,0,0,1,0,NaN)".】
![image](https://github.com/didi/LogicFlow/assets/32189692/a270e87c-f2d4-4c2c-b6f8-82fab2da1d8d)

- 效果录屏
![logicflow的bug](https://github.com/didi/LogicFlow/assets/32189692/762127d9-688f-428b-883d-1c61cb938ac2)

- 代码
```
 const handleClick = (e:any)=>{
   const position = lf.value?.getPointByClient(e.x, e.y) as any
   const x = position?.domOverlayPosition.x || 700
   lf.value?.extension.miniMap.show(x - 120, 40)
}
```

### logicflow/core版本

1.2.26

### logicflow/extension版本

1.2.26

### 浏览器&环境

Chrome

**Comment by Gemini-0529** [comment]
这个问题我也有，logicFlow在el-drawer中就会出现这问题

**Comment by boyongjiong** [comment]
你好，我们发布了 2.0 版本，新版本重构了 miniMap 插件，并提供了一些配置项和 api，欢迎升级新版本使用

暂时将该 issue 关闭，如果新版本有问题麻烦再提一个 issue，并关联此 issue
