### ISSUE TITLE
[Bug Report]: 小地图中监听画布位置变化并重新setView中的限流过小，导致拖拽时会每隔300ms顿一下

### ISSUE THREAD

**Issue by philipxiaoxi** [didi/LogicFlow#1596]
### 发生了什么？

小地图中监听画布位置变化并重新setView中的限流过小，导致拖拽时会每隔300ms顿一下。

主要代码是这里：
![image](https://github.com/didi/LogicFlow/assets/52746230/112fb6da-9b4d-4b92-9dc3-fe68513d9a57)

当拖拽时会触发小地图setView，此时限流300ms，如果节点数量较多，本来拖拽是很流畅的，但这里更新setView会顿一下，期望可以支持调整为防抖，可以接收拖拽完毕后再更新小地图或者支持配置限流或防抖以及时间。

感谢~ 看看是否能够采用我的建议来临时优化这个版本的小地图

### logicflow/core版本

1.2.27

### logicflow/extension版本

1.2.27

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
我们 2.0 版本已经发布了，优化了小地图中的逻辑，可以试试我们新版的性能
