### ISSUE TITLE
[Bug Report]: 节点显示非指定坐标

### ISSUE THREAD

**Issue by zhaovincent** [didi/LogicFlow#1599]
### 发生了什么？

节点在画布中显示的坐标非指定坐标，x y都是默认+10的位置 测试代码地址：https://gitee.com/junyue/test-logic-flow

### logicflow/core版本

1.2.27

### logicflow/extension版本

1.2.27

### 浏览器&环境

Microsoft Edge

**Comment by DymoneLewis** [comment]
> ### 发生了什么？
> 节点在画布中显示的坐标非指定坐标，x y都是默认+10的位置 测试代码地址：https://gitee.com/junyue/test-logic-flow
> 
> ### logicflow/core版本
> 1.2.27
> 
> ### logicflow/extension版本
> 1.2.27
> 
> ### logicflow/engine版本
> _No response_
> 
> ### 浏览器&环境
> Microsoft Edge

看了一下你的源码，节点的坐标没有问题，边指向节点有偏差是由初始化数据里给边设置的pointList导致的，注释之后就能正确指到节点上了
