### ISSUE TITLE
[Bug Report]: InsertNodeInPolyline扩展插件个性化配置设置不生效

### ISSUE THREAD

**Issue by smrsmr** [didi/LogicFlow#1601]
### 发生了什么？

问题： 按官方文档对对InsertNodeInPolyline插件个性化设置的时候不生效
期望：能正常对InsertNodeInPolyline插件进行配置

文档地址：https://site.logic-flow.cn/tutorial/extension-insert-node-in-polyline
<img width="1380" alt="image" src="https://github.com/didi/LogicFlow/assets/26588239/e6974d5c-a8f9-4696-b1cf-c4369d297f94">

### logicflow/core版本

1.2.27

### logicflow/extension版本

1.2.27

### 浏览器&环境

Chrome

**Comment by RayJason** [comment]
+1

**Comment by DymoneLewis** [comment]
辛苦提供一个能最小复现问题的demo我们看下呢

**Comment by boyongjiong** [comment]
因长时间未回复，现将此 issue 关闭。如后续仍有类似问题，请提供最小复现 demo，我们追踪处理一下
