### ISSUE TITLE
[Bug Report]: 最新Chrome浏览器在拖拽节点到画布后无法再次选中该节点进行拖拽

### ISSUE THREAD

**Issue by lanbodaniu** [didi/LogicFlow#1609]
### 发生了什么？

https://xinxin93.github.io/logicflow_vue_demo/#/
在这个demo中可以复现拖拽问题
![PixPin_2024-05-21_17-39-27](https://github.com/didi/LogicFlow/assets/56634584/65a0a2ce-2429-4ada-87b2-fd73c2d20ca9)

![PixPin_2024-05-21_17-42-23](https://github.com/didi/LogicFlow/assets/56634584/e5daa8f1-f37b-4866-bb80-e58be9776b67)

自定义的HtmlNode节点
    const html = `
      <div>
        <img width='45px' src='${require('./img/xxx.png')}' />
      </div>
    `;
    const html = `
      <div 
        style="
          width:45px;height:45px;
          background: url(${require('./img/xxx.png')}) no-repeat;
          background-size: 100%;
          ">
      </div>
    `;
使用img时拖拽有bug，使用background拖拽无bug

### logicflow/core版本

1.2.18

### logicflow/extension版本

1.2.19

### 浏览器&环境

Chrome, Microsoft Edge

**Comment by flavour-yang** [comment]
### 浏览器 ### 
125.0.6422.61（正式版本）
### 复现步骤 ### 
同样官方示例, 新加节点连接节点时会拖动节点画布
1. 新加节点
2. 任意节点连接

![cb0fa63a-ff22-48dd-8265-c80478586e4c](https://github.com/didi/LogicFlow/assets/29671223/9268322b-7e9b-4415-91e9-9ec425bcd4f7)

**Comment by ifYouLike-Weirdo** [comment]
遇到的同样问题，求解答

**Comment by ChangeSuger** [comment]
可以参考 #1619 中提供的解决方案

**Comment by JOJO-CPU** [comment]
![Uploading 1721958239850.jpg…]()

**Comment by JOJO-CPU** [comment]
我也出现了同样的问题

**Comment by boyongjiong** [comment]
重复 issue，解决方案参考 #1619
