### ISSUE TITLE
[Feature]: 布局排列方式

### ISSUE THREAD

**Issue by yanzhandong** [didi/LogicFlow#1610]
### 背景&目的

我有一个配置审批流程的需求，在配置数据的时候，我们是竖着配置的，但是在某个场景下需要把数组LTR横着展示，lf有方法能处理吗

**Comment by boyongjiong** [comment]
目前没有内置功能，只能你自己遍历数据，重新更新节点坐标去实现

目前应该也不会支持该功能，暂时将 issue 关闭。如果有足够多的需求，我们可以会考虑一下是否支持
