### ISSUE TITLE
[Bug Report]: 连线命名为纯数字时解析报错

### ISSUE THREAD

**Issue by jinkuiqian** [didi/LogicFlow#1612]
### 发生了什么？

连线命名为纯数字时，getEdgeConfig在解析名称时，解析成number, 造成textVal.split报错

<img width="942" alt="截屏2024-05-25 13 34 58" src="https://github.com/didi/LogicFlow/assets/155619507/0ede0ed7-5106-42a5-abcf-2caaa324a080">

### logicflow/core版本

1.2.27

### logicflow/extension版本

1.2.27

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
已发版 2.0.1，请升级后使用，如有问题再新建 issue 关联此 issue，先关闭本 issue
