### ISSUE TITLE
[Discussion]: 框选插件事件监听问题

### ISSUE THREAD

**Issue by DymoneLewis** [didi/LogicFlow#1614]
### 发生了什么？

【这是一个来自QQ用户群的反馈】
节点框选后，节点内渲染的下拉框组件的滚动事件无法触发了，需要手动移除监听才能用。
问题：
1. 是否需要支持这样的交互
2. 其他模块的鼠标事件是否会有问题

### logicflow/core版本

1.2.27

### logicflow/extension版本

1.2.27

### 浏览器&环境

Chrome

**Comment by ChangeSuger** [comment]
#1534 这个问题应该与这个提交有关，目前的实现会阻塞整个页面的滚轮事件，稍晚这边提个pr修复一下
