### ISSUE TITLE
[Bug Report]: 节点面板拖动失效并报错

### ISSUE THREAD

**Issue by ifYouLike-Weirdo** [didi/LogicFlow#1619]
### 发生了什么？
https://github.com/didi/LogicFlow/issues/1609
**问题同上面的回答**
**本项目使用的是官方示例的模板**：https://xinxin93.github.io/logicflow_vue_demo/#/

> 此模板也有这样的bug

![image](https://github.com/didi/LogicFlow/assets/55228333/ed4b07b0-6a2a-4850-80c4-51a8de28c14d)
![image](https://github.com/didi/LogicFlow/assets/55228333/c53927a9-7872-4be9-8494-94ba045796e6)
基本上第二次拖拽左侧面板到图中就会变成图1这样，会把一整个面板拉动
并且流程图中的节点拖拽和流程图空白处拖拽，以及连接线的连接（按下和拖拽）不生效，在松开的时候节点会跟着鼠标移动然后报错（图2）

> 有时候双击一下节点，拖拽就又不报错了

### logicflow/core版本

1.2.22

### logicflow/extension版本

1.2.22

**Comment by ChangeSuger** [comment]
这边也遇到过与图1类似的问题，测试发现是自行实现的 NodePanel 会有这个问题，但使用官方的 DndPanel 就不会有这个问题，解决方法是在相关的事件处理中增加`prevent`修饰符。

与此问题相关代码：

https://github.com/xinxin93/logicflow_vue_demo/blob/d5e1bcf0b43db8e56475a27ea67fc54916cfbf97/src/components/LFComponents/NodePanel.vue#L1-L13

修改前：

```
@mousedown="$_dragNode(item)"
```

修改后：

```
@mousedown.prevent="$_dragNode(item)"
```

试试看能不能解决您遇到的问题。

**Comment by ifYouLike-Weirdo** [comment]
> 这边也遇到过与图1类似的问题，测试发现是自行实现的 NodePanel 会有这个问题，但使用官方的 DndPanel 就不会有这个问题，解决方法是在相关的事件处理中增加`prevent`修饰符。
> 
> 与此问题相关代码：
> 
> https://github.com/xinxin93/logicflow_vue_demo/blob/d5e1bcf0b43db8e56475a27ea67fc54916cfbf97/src/components/LFComponents/NodePanel.vue#L1-L13
> 
> 修改前：
> 
> ```
> @mousedown="$_dragNode(item)"
> ```
> 
> 修改后：
> 
> ```
> @mousedown.prevent="$_dragNode(item)"
> ```
> 
> 试试看能不能解决您遇到的问题。

感谢您的解答！！！已经没问题了！！！

**Comment by JOJO-CPU** [comment]
感谢解答，已经没有问题，但是希望官网的那个示例demo也修复下，避免更多人踩坑
