### ISSUE TITLE
[Bug Report]: 当触发框选事件后，或者反复移动画布中的节点，或者多次放大缩小画布之后，画布鼠标滚轮的缩小放大变成全屏响应，外面拖拽面板的滚动条都失去响应

### ISSUE THREAD

**Issue by CHENCHAHA** [didi/LogicFlow#1623]
### 发生了什么？

当触发框选事件后，或者反复移动画布中的节点，或者多次放大缩小画布之后，画布鼠标滚轮的缩小放大变成全屏响应，外面拖拽面板的滚动条都是去响应

![_17176664001381](https://github.com/didi/LogicFlow/assets/92902236/d4b5f730-9df2-447e-9658-113f8f339199)

### logicflow/core版本

1.2.27

### logicflow/extension版本

1.2.27

### 浏览器&环境

Chrome

**Comment by Jerryzhengtao** [comment]
同版本，画布添加节点后，鼠标滚轮缩放浏览器失效，只能缩放画布，应该是画布独享了鼠标滚轮事件

**Comment by wangzt-arch** [comment]
同问题，有什么解决方案吗？

**Comment by DymoneLewis** [comment]
@wangzt-arch @Jerryzhengtao 确实存在这个问题，我们在即将发布的2.0版本里优化了框选插件的逻辑也处理了这个bug，可以这个月我们发布2.0后升级版本试试
不升级版本情况下的解决方案可以参考下这个demo
https://codesandbox.io/p/sandbox/selection-bug-resolution-kmwxl5?file=%2Findex.html%3A53%2C27
