### ISSUE TITLE
[Feature]: 拖动画布，为什么画布没有动，只有节点在动。应该要和小地图中移动的效果一样，背景带着节点动，而不是只移动节点，看起来很奇怪

### ISSUE THREAD

**Issue by CHENCHAHA** [didi/LogicFlow#1624]
### 背景&目的

拖动画布，为什么画布没有动，只有节点在动。应该要和小地图中移动的效果一样，背景带着节点动，而不是只移动节点，看起来很奇怪

![11111111111111111117177467033855](https://github.com/didi/LogicFlow/assets/92902236/a14c2e56-216f-48d4-967b-6077c306ba1a)

**Comment by boyongjiong** [comment]
![2024-08-13 19 57 26](https://github.com/user-attachments/assets/6130bbe3-729b-477d-accb-30c3238b3287)
没太懂你的描述，我这边看效果应该就是你描述的这个样子吧

**Comment by Ari1c** [comment]
问一下在拖动画布的时候，画布内有接口轮询，这时候会重新render 画布，就会导致画布重置，这种如何解决在画布拖动的时候有接口轮询。画布也不会被重置

**Comment by Ari1c** [comment]
> ![2024-08-13 19 57 26](https://private-user-images.githubusercontent.com/8553969/357400228-6130bbe3-729b-477d-accb-30c3238b3287.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODkyMzksIm5iZiI6MTcyMzc4ODkzOSwicGF0aCI6Ii84NTUzOTY5LzM1NzQwMDIyOC02MTMwYmJlMy03MjliLTQ3N2QtYWNjYi0zMGMzMjM4YjMyODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDYxNTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGMwOWU4OTlhMDhiZDU1NzQ5YTZkMzk5OWZjZDk4MzAzYjdmMzA3MTFiZWUwOTBjZDg1MWQ2YjdmZjkxMTllNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G2SKP9l8clqZ8SK4r1glv7XKyaq_dHtAAN7X_K9pjiE) [ ![2024-08-13 19 57 26](https://private-user-images.githubusercontent.com/8553969/357400228-6130bbe3-729b-477d-accb-30c3238b3287.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODkyMzksIm5iZiI6MTcyMzc4ODkzOSwicGF0aCI6Ii84NTUzOTY5LzM1NzQwMDIyOC02MTMwYmJlMy03MjliLTQ3N2QtYWNjYi0zMGMzMjM4YjMyODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDYxNTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGMwOWU4OTlhMDhiZDU1NzQ5YTZkMzk5OWZjZDk4MzAzYjdmMzA3MTFiZWUwOTBjZDg1MWQ2YjdmZjkxMTllNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G2SKP9l8clqZ8SK4r1glv7XKyaq_dHtAAN7X_K9pjiE) ](https://private-user-images.githubusercontent.com/8553969/357400228-6130bbe3-729b-477d-accb-30c3238b3287.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODkyMzksIm5iZiI6MTcyMzc4ODkzOSwicGF0aCI6Ii84NTUzOTY5LzM1NzQwMDIyOC02MTMwYmJlMy03MjliLTQ3N2QtYWNjYi0zMGMzMjM4YjMyODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDYxNTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGMwOWU4OTlhMDhiZDU1NzQ5YTZkMzk5OWZjZDk4MzAzYjdmMzA3MTFiZWUwOTBjZDg1MWQ2YjdmZjkxMTllNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G2SKP9l8clqZ8SK4r1glv7XKyaq_dHtAAN7X_K9pjiE) [ ](https://private-user-images.githubusercontent.com/8553969/357400228-6130bbe3-729b-477d-accb-30c3238b3287.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODkyMzksIm5iZiI6MTcyMzc4ODkzOSwicGF0aCI6Ii84NTUzOTY5LzM1NzQwMDIyOC02MTMwYmJlMy03MjliLTQ3N2QtYWNjYi0zMGMzMjM4YjMyODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDYxNTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGMwOWU4OTlhMDhiZDU1NzQ5YTZkMzk5OWZjZDk4MzAzYjdmMzA3MTFiZWUwOTBjZDg1MWQ2YjdmZjkxMTllNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G2SKP9l8clqZ8SK4r1glv7XKyaq_dHtAAN7X_K9pjiE) 没太懂你的描述，我这边看效果应该就是你描述的这个样子吧

问一下在拖动画布的时候，画布内有接口轮询，这时候会重新render 画布，就会导致画布重置，这种如何解决在画布拖动的时候有接口轮询。画布也不会被重置
