### ISSUE TITLE
不同版本的core和extension会导致Group中的自动调整大小失效

### ISSUE THREAD

**Issue by wuyumm** [didi/LogicFlow#1658]
### 发生了什么？

使用的是@logicflow/core@^1.2.26和@logicflow/extension@1.1.3这两个包，会导致Group中的自动调整大小失效，将这两个包都换成1.1.31版本，就可以进行大小调整

### logicflow/core版本

^1.2.22

### logicflow/extension版本

1.1.31

### 浏览器&环境

Chrome

**Comment by ChangeSuger** [comment]
core 包和 extension 包是同步迭代的，在配套使用时推荐使用相同或相近的版本，避免不符合预期的情况发生。
