### ISSUE TITLE
[Feature]: 控制面板图标不显示的问题

### ISSUE THREAD

**Issue by huoyalong** [didi/LogicFlow#1659]
### 背景&目的

![image](https://github.com/didi/LogicFlow/assets/71935611/e6e10b64-61e1-49c1-b0f7-6101fb716adb)

我是按照文档中的demo加了一个导航的控制面板，然后iconClass: "custom-minimap",定义了一个iconClass，但是没有给具体的css怎么写，我这样写之后svg不显示是怎么回事啊

**Comment by ChangeSuger** [comment]
一个示例参考 https://github.com/ChangeSuger/LogicFlow/commit/734d55cc8f6ea19e7de36fdb2f5f9cc05fcdee93

自定义 icon 的类名然后通过 CSS 样式设置背景图片的思路是对的，但从提供的信息里看不出具体原因，这边建议您打开浏览器的开发者工具检查两个点：

1. CSS 样式是否有应用到对应的元素上
2. `url()` 中的字符串是否能正常渲染出 SVG 图像
