### ISSUE TITLE
[Bug Report]: 2.0.0-beta.2 跑不起来，直接报依赖内部错误

### ISSUE THREAD

**Issue by Panweitong** [didi/LogicFlow#1667]
### 发生了什么？

安装2.0.0-beta.2后，项目运行报错，显示内部依赖错误
![微信图片_20240708111504](https://github.com/didi/LogicFlow/assets/24288404/002aedea-8f10-47e5-b0dc-5857cff32eb7)
点击上述报错直接跳转到依赖内部
![微信图片_20240708111511](https://github.com/didi/LogicFlow/assets/24288404/b8256e79-5e19-43db-a64b-525aa64c58de)

节点代码：
`
import { HtmlResize } from "@logicflow/extension";
import $ from "jquery";

class CardModel extends HtmlResize.model {
  initNodeData(data) {
    super.initNodeData(data);
    this.text.editable = false; // 禁止节点文本编辑
    // 设置节点宽高和鼠标移动多少距离后开始缩放节点
    const width =
      data.properties.nodeSize && data.properties.nodeSize.width
        ? data.properties.nodeSize.width
        : 250;
    const height =
      data.properties.nodeSize && data.properties.nodeSize.height
        ? data.properties.nodeSize.height
        : 250;
    // const height = 250
    this.width = width;
    this.height = height;
    this.minWidth = 80;
    this.minHeight = 80;
    this.gridSize = 1;
  }
  setAttributes() {
    if (
      (this.properties.iconRadio == true &&
        this.properties.nodeSize &&
        this.properties.nodeSize.height &&
        parseInt(this.properties.nodeSize.height) <= 80) ||
      (this.properties.iconRadio == true &&
        this.properties.nodeSize &&
        this.properties.nodeSize.width &&
        parseInt(this.properties.nodeSize.width) <= 80)
    ) {
      this.width = 80;
      this.height = 80;
    }
    if (
      (this.properties.iconRadio == false &&
        this.properties.nodeSize &&
        this.properties.nodeSize.height &&
        parseInt(this.properties.nodeSize.height) == 250) ||
      (this.properties.iconRadio == false &&
        this.properties.nodeSize &&
        this.properties.nodeSize.width &&
        parseInt(this.properties.nodeSize.width) == 250)
    ) {
      this.width = 250;
      this.height = 250;
    }
  }
}
class CardNode extends HtmlResize.view {
  setHtml(rootEl) {
    const { id, properties } = this.props.model;
    var color =
      properties.titleColor && properties.titleColor != ""
        ? properties.titleColor
        : "#6266BC";
    const el = document.createElement("div");
    el.className = "uml-wrapper";
    var html = ``;
    el.innerHTML = html;
    rootEl.innerHTML = "";
    rootEl.appendChild(el);
  }
}

export default {
  type: "icon-card",
  view: CardNode,
  model: CardModel,
}
`

### logicflow/core版本

2.0.0-beta.2

### logicflow/extension版本

2.0.0-beta.2

### logicflow/engine版本

无

### 浏览器&环境

Chrome

**Comment by FanSun521** [comment]
先用2.0.0-beta.1吧，2.0.0-beta.2确实有很多问题

**Comment by Panweitong** [comment]
2.0.0-beta.1 我也跑不起来，报setMenuConfig undefined的错

**Comment by Panweitong** [comment]
> 先用2.0.0-beta.1吧，2.0.0-beta.2确实有很多问题

2.0.0-beta.1 我也跑不起来，报setMenuConfig undefined的错

**Comment by FanSun521** [comment]
可以上传个demo看看

**Comment by boyongjiong** [comment]
最新是 2.0.0-beta.5 了，现在还有问题吗

**Comment by Panweitong** [comment]
没有呢，我这边可以正常使用了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 你说呢？ ***@***.***&gt;
发送时间: 2024年7月25日 20:10
收件人: didi/LogicFlow ***@***.***&gt;
抄送: paiweitong ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [didi/LogicFlow] [Bug Report]: 2.0.0-beta.2 跑不起来，直接报依赖内部错误 (Issue #1667)





 
最新是 2.0.0-beta.5 了，现在还有问题吗

**Comment by boyongjiong** [comment]
好的，那我这边先关闭 issue，后续有问题欢迎继续提 issue 交流
