### ISSUE TITLE
[Bug Report]: moveNode方法不能用

### ISSUE THREAD

**Issue by ifYouLike-Weirdo** [didi/LogicFlow#1671]
### 发生了什么？

![image](https://github.com/didi/LogicFlow/assets/55228333/64ff512c-6e4b-4568-a6e9-bd28b189372f)

按照官方文档写的，结果打印后发现根本没有这个方法，代码上边的deleteNode方法没问题
![image](https://github.com/didi/LogicFlow/assets/55228333/19b602fa-65da-4b61-a010-5d14222c250e)
![image](https://github.com/didi/LogicFlow/assets/55228333/b529702e-afaa-4903-bb20-716705ab47ba)

### logicflow/core版本

1.2.22

### logicflow/extension版本

1.2.22

**Comment by boyongjiong** [comment]
兄嘚，
![image](https://github.com/user-attachments/assets/9d8aaca5-c0a5-4dc6-a870-6fd5580f8a6f)
这一行应该是 lf.value.graphModel.moveNode(id, deltaX, deltaY);

**Comment by ifYouLike-Weirdo** [comment]
@boyongjiong 感谢大哥！
