### ISSUE TITLE
[Feature]: logicFlow 工作流手机端回显需求

### ISSUE THREAD

**Issue by kzhzjdyw888** [didi/LogicFlow#1674]
### 背景&目的

1.通过后端返回的 json数据 +历史经过节点数据集合+当前节点高亮集合 能否实现直接new logicflow  不用画布的情况下把数据渲染去生成图片或者base64 实现移动端回显轨迹。
![image](https://github.com/didi/LogicFlow/assets/97489662/a1a9c4a7-879f-493a-bbbb-2669439fbaa0)

**Comment by boyongjiong** [comment]
不行。

即使 getSnapshot 也是需要画布在初始化的情况下使用。

直接在移动端初始化 LogicFlow，设置为静默模式来回显也行吧。LogicFlow 只是不支持移动端交互，渲染是没问题的
