### ISSUE TITLE
[Feature]: 支持nuxt3.0 ssr=true模式

### ISSUE THREAD

**Issue by iforgetyounow** [didi/LogicFlow#1693]
### 背景&目的

#1683 #1668  两个的解决方案互斥，无法使用ssr=true模式，请麻烦内部沟通下，看如何能够使用ssr=true模式。

**Comment by boyongjiong** [comment]
#1683 在这个中看结论

**Comment by iforgetyounow** [comment]
> #1683 在这个中看结论
请看下这个#1668 开启ssr=true，项目是无法启动的。不是说解决方案不行，而是前面已经限制了必须设置ssr=false才能导入lodash-es，不然项目都无法启动
