### ISSUE TITLE
[Bug Report]: nuxt 配置ssr:true,第一次点击路由可以正常展示，刷新后异常

### ISSUE THREAD

**Issue by iforgetyounow** [didi/LogicFlow#1706]
### 发生了什么？

vue:
<template>
  <v-container>
  
      <v-card id="flow-container" style="height: 90dvh">
      </v-card>

  </v-container>
</template>
<script setup lang="ts">
import LogicFlow from "@logicflow/core";
import GraphConfigData from "@logicflow/core";

const lf = ref<LogicFlow>({});
const graphData = ref<GraphConfigData>({
  nodes: [
    {
      id: "node_id_1",
      type: "rect",
      x: 100,
      y: 100,
      text: {x: 100, y: 100, value: '节点1'},
      properties: {}
    },
    {
      id: "node_id_2",
      type: "circle",
      x: 200,
      y: 300,
      text: {x: 300, y: 300, value: '节点2'},
      properties: {}
    }
  ],
  edges: [
    {
      id: "edge_id",
      type: "polyline",
      sourceNodeId: "node_id_1",
      targetNodeId: "node_id_2",
      text: {x: 139, y: 200, value: "连线"},
      startPoint: {x: 100, y: 140},
      endPoint: {x: 200, y: 250},
      pointsList: [{x: 100, y: 140}, {x: 100, y: 200}, {x: 200, y: 200}, {x: 200, y: 250}]
    }
  ]
})
onMounted(() => {
  lf.value = new LogicFlow({
    container: document.getElementById('flow-container'),
    grid: false,
    edgeTextEdit: false,
    nodeTextEdit: false,
  })
  lf.value.render(graphData.value)
})
</script>
nuxt.config:
    ssr: true,
第一次进入：
![image](https://github.com/user-attachments/assets/8ef61a67-ac39-40da-a83a-11c387eabd29)
刷新路由：
![image](https://github.com/user-attachments/assets/3fc06647-fea8-4d13-9a47-203c57e70af6)
使用client-only:
<template>
  <v-container>
    <client-only>
      <v-card id="flow-container" style="height: 90dvh">
      </v-card>
    </client-only>
  </v-container>
</template>
<script setup lang="ts">
import LogicFlow from "@logicflow/core";
import GraphConfigData from "@logicflow/core";

const lf = ref<LogicFlow>({});
const graphData = ref<GraphConfigData>({
  nodes: [
    {
      id: "node_id_1",
      type: "rect",
      x: 100,
      y: 100,
      text: {x: 100, y: 100, value: '节点1'},
      properties: {}
    },
    {
      id: "node_id_2",
      type: "circle",
      x: 200,
      y: 300,
      text: {x: 300, y: 300, value: '节点2'},
      properties: {}
    }
  ],
  edges: [
    {
      id: "edge_id",
      type: "polyline",
      sourceNodeId: "node_id_1",
      targetNodeId: "node_id_2",
      text: {x: 139, y: 200, value: "连线"},
      startPoint: {x: 100, y: 140},
      endPoint: {x: 200, y: 250},
      pointsList: [{x: 100, y: 140}, {x: 100, y: 200}, {x: 200, y: 200}, {x: 200, y: 250}]
    }
  ]
})
onMounted(() => {
  lf.value = new LogicFlow({
    container: document.getElementById('flow-container'),
    grid: false,
    edgeTextEdit: false,
    nodeTextEdit: false,
  })
  lf.value.render(graphData.value)
})
</script>
也不行
![image](https://github.com/user-attachments/assets/66a242b0-3ad0-470f-b734-d7e1e33ce652)

### logicflow/core版本

2.0.0-beta.2

### logicflow/extension版本

2.0.0-beta.2

**Comment by boyongjiong** [comment]
解决了吗？总感觉你这个不是 LogicFlow 的问题，你理解我们的包只能客户端渲染就行了。

建议去搜 nuxt  window is not defined 类似的问题。因为我们初始化是需要 container 的，你服务端渲染的时候没办法提供这个 dom 节点

先关闭此 issue。如果还是有问题，请带着 「可复现 demo（最好是 codesandbox，也可以提供 github 项目）」 重新提 issue
