### ISSUE TITLE
[Bug Report]: Highlight插件针对基于RectNode的节点有问题

### ISSUE THREAD

**Issue by Panweitong** [didi/LogicFlow#1707]
### 发生了什么？

示例视频如下：

https://github.com/user-attachments/assets/a6f16575-f4e7-4958-8746-231541a3842a

有问题的节点代码：
RectNode.js

`import { RectResize } from "@logicflow/extension";
import {
  getShapeStyleFuction,
  getTextStyleFunction,
} from "../getShapeStyleUtil";

// 矩形
class RectNewModel extends RectResize.model {
  setToBottom() {
    this.zIndex = 0;
  }

  getNodeStyle() {
    const style = super.getNodeStyle();
    const properties = this.getProperties();
    return getShapeStyleFuction(style, properties);
  }

  getTextStyle() {
    const style = super.getTextStyle();
    const properties = this.getProperties();
    return getTextStyleFunction(style, properties);
  }
}

export default {
  type: "pro-rect",
  view: RectResize.view,
  model: RectNewModel,
};`

`import { h } from "@logicflow/core";
import RectNode from "RectNode";

// 图片-基础节点
class ImageModel extends RectNode.model {
  initNodeData(data) {
    super.initNodeData(data);
    this.text.editable = false; // 禁止节点文本编辑
    this.width = 100;
    this.height = 100;
  }
}

class ImageNode extends RectNode.view {
  getImageHref() {
    return "https://ccrb.s3.cn-northwest-1.amazonaws.com.cn/%E5%A6%96%E6%80%AA1.png";
  }
  getResizeShape() {
    const { x, y, width, height } = this.props.model;
    const href = this.getImageHref();
    const attrs = {
      x: x - (1 / 2) * width,
      y: y - (1 / 2) * height,
      width,
      height,
      href,
      // 根据宽高缩放
      preserveAspectRatio: "none meet",
    };
    return h("g", {}, [h("image", { ...attrs })]);
  }
}

export default {
  type: "image-node",
  view: ImageNode,
  model: ImageModel,
};
`

### logicflow/core版本

2.0.0-beta.5

### logicflow/extension版本

2.0.0-beta.5

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
没看懂这个 issue 的问题，

Highlight 插件功能是：
鼠标 hover 到节点或边上会高亮与这个节点或边相关的节点和边

节点：高亮这个节点前后相关的所有边和节点

边：高亮这个边指向的节点前后相关的所有边和节点

如果定位到插件逻辑有问题，请提供可复现 demo。目前看视频，感觉好像没有问题

**Comment by Panweitong** [comment]
这个我已经解决了，我代码的问题，在节点内部实现代码中重新获取style，然后赋值就可以了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 你说呢？ ***@***.***&gt;
发送时间: 2024年7月30日 15:50
收件人: didi/LogicFlow ***@***.***&gt;
抄送: paiweitong ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [didi/LogicFlow] [Bug Report]: Highlight插件针对基于RectNode的节点有问题 (Issue #1707)





 
没看懂这个 issue 的问题，
 
Highlight 插件功能是：
 鼠标 hover 到节点或边上会高亮与这个节点或边相关的节点和边
 
节点：高亮这个节点前后相关的所有边和节点
 
边：高亮这个边指向的节点前后相关的所有边和节点
 
如果定位到插件逻辑有问题，请提供可复现 demo。目前看视频，感觉好像没有问题
