### ISSUE TITLE
[Feature]: 如何控制grid的显隐？

### ISSUE THREAD

**Issue by shannonleezjlab** [didi/LogicFlow#1730]
### 背景&目的

在编辑态和不可编辑的时候想通过修改画布的背景来切换编辑模式，看了很多文档发现都没有修改grid显隐或者background的方法。
请问可以修改吗？

**Comment by boyongjiong** [comment]
目前没有，我们后续可以评估一下

**Comment by DymoneLewis** [comment]
你好，我们刚发布的2.0.7版本里支持了动态控制grid显隐的能力，可以升级使用试下，有问题的可以重开issue
