### ISSUE TITLE
[Feature]: 节点选框了以后，拿不到选框区域的长宽和四个顶点吗？

### ISSUE THREAD

**Issue by HanYuanShow** [didi/LogicFlow#1740]
### 背景&目的

节点选框了以后，拿不到选框区域的长宽和四个顶点吗？
![image](https://github.com/user-attachments/assets/b4ef5f5a-fce0-4da6-9046-9505b7e9f7d0)

**Comment by boyongjiong** [comment]
![image](https://github.com/user-attachments/assets/2d1dc04e-2256-4771-8ce4-92361c51d577)
可以，我们更新下文档，回调函数参数是
elements，
leftTopPoint: [x, y]
rightBottomPoint: [x, y]

长宽用坐标去计算就行
