### ISSUE TITLE
[Feature]: 分组组件的 自动扩展 如X6中的这个效果如何实现？

### ISSUE THREAD

**Issue by wfxs2012** [didi/LogicFlow#1750]
### 背景&目的

https://x6.antv.vision/zh/examples/node/group#expand-shrink
请教大佬，自己研究了一下没做出来呀

**Comment by DymoneLewis** [comment]
🤔看起来大概思路就是：
- 监听node:drag事件，触发时取出data.id，调用getNodeModelById获取到对应的nodeModel
- 遍历graphModel.nodes找出是分组节点且children.includes(data.id)的数据(groupModel)做以下操作：
    1. 从nodeModel和groupModel中取出x,y,height,width(groupModel的重命名成：gx,gy,gHeight,gWidth），然后设置一个阈值range
    2. 判断是否满足(x - width/2) <= (gx - gWidth/2 + 10) || (x + width/2) <= (gx + gWidth/2 - 10) || (y - height/2) <= (gy - gHeight/2 + 10) || (y + height/2) <= (gy + gHeight/2 - 10)
    3. 如果满足，分组节点对应的宽/高（x方向满足就做宽度处理，y方向满足条件就做高度处理，如果都满足就宽高都处理）+ range，分组节点的x/y也要相应做加减（如果子节点是在左/上方向移动，x/y要减去range；如果是右/下方向就加range）
    4. 不满足条件就不做处理
