### ISSUE TITLE
[Bug Report]: 全局resize 事件未注销

### ISSUE THREAD

**Issue by dlx2soft** [didi/LogicFlow#1756]
### 发生了什么？

当页面跳转后 注册的全局resize 事件未被注销，会在控制台打印警告

![微信图片_20240812110313](https://github.com/user-attachments/assets/d34003b1-a29e-408b-8406-f488bf805c93)

### logicflow/core版本

2.0

### logicflow/extension版本

2.0

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
已发版 2.0.1，请升级后使用，如有问题再新建 issue 关联此 issue，先关闭本 issue
