### ISSUE TITLE
[Bug Report]: @logicflow/engine 导入 @nyariv/sandboxjs 出错

### ISSUE THREAD

**Issue by zhai-conan** [didi/LogicFlow#1758]
### 发生了什么？

vue：2
node: 16.20.2
import Engine from '@logicflow/engine';
导入出错
![微信截图_20240812110127](https://github.com/user-attachments/assets/f3cacbc5-25d2-490b-816b-1eccc54bcc9c)
![微信截图_20240812110143](https://github.com/user-attachments/assets/fceaa8c7-8dca-407a-b128-0c92da25ba6e)

### logicflow/core版本

1.2.22

### logicflow/extension版本

1.2.22

### logicflow/engine版本

0.1.0, 0.0.12

**Comment by zhai-conan** [comment]
之前使用 @vue/cli-service 出错
改为 使用 vite 后 运行 就可以导入 engine 了
![微信截图_20240812121458](https://github.com/user-attachments/assets/e79e00cd-7437-40ce-9078-6894eee7a1be)

**Comment by boyongjiong** [comment]
项目可以提供一下吗？@vue/cli-service 的

**Comment by boyongjiong** [comment]
因为长时间未回复，暂时将该 issue 关闭，如有需要，请提供可复现 demo 重新提 issue
