### ISSUE TITLE
[Bug Report]: 2.0版本vue自定义节点使用Label组件有报错

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#1759]
### 发生了什么？

2.0版本vue自定义节点使用Label组件有报错
---节点组件代码
`<template>
  <div class="node--wrap">
    <div>{{ percentage }}</div>
  </div>
</template>

<script>
export default {
  name: "progressNode",
  inject: ["getNode", "getGraph"],
  data() {
    return {
      percentage: 80,
    };
  },
  mounted() {
    const node = this.getNode();
    const graph = this.getGraph();
    graph.eventCenter.on("node:properties-change", (eventData) => {
      console.log(eventData);
      if (eventData.id === node.id) {
        this.percentage = eventData.properties.progress;
      }
    });
  },
};
</script>
<style scoped></style>`

---主页面代码
`<template>
  <div>
    <button @click="setAttr">节点赋值</button>
    <button @click="setNodeNameModel">切换节点名称显示模式</button>
    <div class="container" ref="container"></div>
  </div>
</template>

<script>
import LogicFlow, { TextMode } from "@logicflow/core";
import { register } from "@logicflow/vue-node-registry";
import progressNode from "./progressNode";
import { Label } from "@logicflow/extension";
import "@logicflow/core/lib/style/index.css";
export default {
  name: "Container",
  data() {
    return {
      lf: null,
    };
  },
  mounted() {
    this.lf = new LogicFlow({
      container: this.$refs.container,
      grid: true,
      plugins: [Label],
      pluginsOptions: {
        label: {
          isMultiple: false,
          maxCount: 1,
          labelWidth: 80,
          // textOverflowMode -> 'ellipsis' | 'wrap' | 'clip' | 'nowrap' | 'default'
          textOverflowMode: "ellipsis",
        },
      },
    });
    register(
      {
        type: "progress",
        component: progressNode,
      },
      this.lf
    );
    this.lf.render({});
    const node1 = this.lf.addNode({
      id: "vue-node-1",
      type: "progress",
      x: 80,
      y: 80,
      text: "节点名称节点名称节点名称节点名称节点名称节",
      properties: {
        progress: 60,
        width: 60,
        height: 60,
        refY: 60,
      },
    });
    console.log("node1 --->>>", node1);
  },
  methods: {
    setAttr() {
      this.lf.setProperties("vue-node-1", {
        progress: 50,
      });
    },
    setNodeNameModel() {
      const nextLabel = this.lf.extension.label;
      nextLabel.updateTextMode(TextMode.LABEL);
    },
  },
};
</script>

<style scoped>
.container {
  width: 1000px;
  height: 500px;
}
</style>`

结果报
![image](https://github.com/user-attachments/assets/6cedc917-1393-48ed-b8dc-aa6a97f17fa2)
如果去掉以下代码就正常不报错
![image](https://github.com/user-attachments/assets/3a38ebd5-1234-4db6-b3d6-ebd0ac009b48)

还有textOverflowMode -> 'ellipsis' | 'wrap' | 'clip' | 'nowrap' | 'default' ；是否支持超过两行显示...并支持鼠标悬停显示全部

### logicflow/core版本

2.0

### logicflow/extension版本

2.0

### logicflow/engine版本

2.0

**Comment by boyongjiong** [comment]
我看一下

**Comment by zoujpxyz2017** [comment]
上面的是安装了2.0.0-beta.0版本；
我升级到2.0.0版本后，不报错了，但是节点的名称不显示了
![image](https://github.com/user-attachments/assets/3b30c3e7-3162-4138-ae65-2a63f421da06)
![image](https://github.com/user-attachments/assets/89d363c5-5565-40bd-93cf-5643481b9f71)

**Comment by DymoneLewis** [comment]
不展示的问题确实是个bug，我们修复一下

**Comment by boyongjiong** [comment]
已发版 2.0.1，请升级后使用，如有问题再新建 issue 关联此 issue，先关闭本 issue
