### ISSUE TITLE
[Bug Report]: 使用highlight 插件后dndpanel 拖拽添加节点报错！！！

### ISSUE THREAD

**Issue by dlx2soft** [didi/LogicFlow#1764]
### 发生了什么？

使用highlight 插件后dndpanel 拖拽添加节点报错！！！
![微信图片_20240812191536](https://github.com/user-attachments/assets/e9d584f4-efb2-4bda-8133-90b4baee37dc)

### logicflow/core版本

2.0

### logicflow/extension版本

2.0

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
已发版 2.0.1，请升级后使用，如有问题再新建 issue 关联此 issue，先关闭本 issue
