### ISSUE TITLE
[Bug Report]: 动态分组折叠展开报错

### ISSUE THREAD

**Issue by SprASum** [didi/LogicFlow#1767]
### 发生了什么？

动态分组折叠展开报错
![image](https://github.com/user-attachments/assets/989ab1b7-9ac9-4b8f-92f9-ab7f4f01e4ff)
![image](https://github.com/user-attachments/assets/4afc4086-9a51-43ea-a7eb-2b4e2ac9bb40)

### logicflow/core版本

2.0.0

### logicflow/extension版本

2.0.0

### logicflow/engine版本

2.0.0

### 浏览器&环境

Chrome, NodeJS

**Comment by boyongjiong** [comment]
已发版 2.0.1，请升级后使用，如有问题再新建 issue 关联此 issue，先关闭本 issue
