### ISSUE TITLE
[Bug Report]: 2.0版本vue的自定义节点，在缓存组件切换的时候，生成了两份自定义节点

### ISSUE THREAD

**Issue by 121922144** [didi/LogicFlow#1768]
### 发生了什么？

demo：
[vue-cli-vue3-demo.zip](https://github.com/user-attachments/files/16598153/vue-cli-vue3-demo.zip)

<img width="710" alt="iss" src="https://github.com/user-attachments/assets/37e52014-bc32-4573-8c50-359e89a7a1e6">
如图，page1和page2共用一个组件，切换的时候缓存组件，审查元素可以看到vue自定义节点变成了两个

### logicflow/core版本

2.0.0

### logicflow/extension版本

2.0.0

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
最近比较忙，没太抽出时间继续研究，如果你有时间，可以帮忙研究一下原因。可以给我们科普一下
