### ISSUE TITLE
[Feature]: 在使用  pnpm 时会报错无法找到 `tsconfig.json`

### ISSUE THREAD

**Issue by WangJincheng4869** [didi/LogicFlow#1770]
### 背景&目的

当我使用 pnpm 时，会在 `node_modules` 下有这么一个文件，且会触发报错。
`node_modules\.pnpm\@logicflow+core@2.0.0\node_modules\@logicflow\core\tsconfig.json`
![图片](https://github.com/user-attachments/assets/fa361b91-8a03-4565-9870-783dd7e6933b)

目前没有找到合适的解决办法，请问有什么方式可以规避这个错误，本地进行什么配置还是只能在发包的时候忽略这个文件。我看了其他的依赖包中的文件，几乎都没有 `tsconfig.json` 。

**Comment by DymoneLewis** [comment]
使用pnpm做什么操作遇到的呢？

**Comment by WangJincheng4869** [comment]
> 使用pnpm做什么操作遇到的呢？

安装之后在 IDE 中就会报这个错误，重启 TS 服务之后还是有这个错，很是诡异。

**Comment by WangJincheng4869** [comment]
> 使用pnpm做什么操作遇到的呢？

### 我猜测可能时找不到这个文件，我删了报错就没了。

![1723547715923](https://github.com/user-attachments/assets/86071d27-f46b-4603-93da-85ad49b8a892)


### 删除之后重启 TS 服务后消失

![图片](https://github.com/user-attachments/assets/d8b1630e-4fd4-4cbc-a16f-043608414506)

**Comment by DymoneLewis** [comment]
@boyongjiong sir, CC this one please

**Comment by boyongjiong** [comment]
"skipLibCheck": true,  你项目的 tsconfig 中配置这个呢？

报错的现象是你启动自己的项目就报错吗？还是点进这个文件之后报错

**Comment by WangJincheng4869** [comment]
> "skipLibCheck": true, 你项目的 tsconfig 中配置这个呢？
> 
> 报错的现象是你启动自己的项目就报错吗？还是点进这个文件之后报错

尝试了一下，加了之后没有用。直接在控制台里显示有错误，发现有错误才点进去的。

![图片](https://github.com/user-attachments/assets/cce8b8ed-c510-4d2f-bf37-2edf76480315)

**Comment by boyongjiong** [comment]
> > "skipLibCheck": true, 你项目的 tsconfig 中配置这个呢？
> > 报错的现象是你启动自己的项目就报错吗？还是点进这个文件之后报错
> 
> 尝试了一下，加了之后没有用。直接在控制台里显示有错误，发现有错误才点进去的。
> 
> ![图片](https://private-user-images.githubusercontent.com/41162158/357645582-cce8b8ed-c510-4d2f-bf37-2edf76480315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDIyMzIsIm5iZiI6MTcyMzYwMTkzMiwicGF0aCI6Ii80MTE2MjE1OC8zNTc2NDU1ODItY2NlOGI4ZWQtYzUxMC00ZDJmLWJmMzctMmVkZjc2NDgwMzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAyMTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZDM4YjZiZDM0YTIzNjMwMWU5NGRhYmViMGQ3Mjc0ZmY1MTliMWY2NGY4NzFkMTc5YzJjMzRkMzk5MDU4NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qV3xVugW_OxJWcQKEp9Ms036jAuSvzmbFrLhVQXgipI)

正常项目中应该忽略掉 node_modules 吧。你项目中 你的 typeRoots 需要配吗？你在项目tsconfig.json 中按下面第一个解决方案处理下试试

在使用 TypeScript 时，有时会遇到来自 `node_modules` 中包的 `tsconfig.json` 文件报错的情况。这可能是因为 TypeScript 解析到了一些你不希望它去处理的第三方库配置，导致编译时报错。以下是解决这个问题的一些方法：

### 1. **排除 `node_modules` 目录**

默认情况下，TypeScript 会忽略 `node_modules` 目录中的代码，除非显式引用了其中的文件。如果你遇到问题，可以在你的 `tsconfig.json` 中确认或者添加以下配置，确保 TypeScript 编译器不会解析 `node_modules` 下的配置：

```json
{
  "compilerOptions": {
    "skipLibCheck": true, // 跳过类型声明文件的检查
    "exclude": ["node_modules"] // 排除 node_modules 目录
  }
}
```

- `skipLibCheck: true` 会跳过对 `.d.ts` 文件的类型检查，这可以避免很多与类型声明文件相关的问题。
- `exclude: ["node_modules"]` 会明确排除 `node_modules` 目录。

### 2. **设置 `baseUrl` 和 `paths`**

如果你正在处理单个包的 `tsconfig.json` 冲突，可以通过设置 `baseUrl` 和 `paths` 来指定解析模块的位置，以避免冲突：

```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "*": ["node_modules/*"]
    }
  }
}
```

### 3. **使用 `typeRoots` 限制 TypeScript 类型定义文件的解析范围**

通过设置 `typeRoots`，你可以限制 TypeScript 只从特定的目录解析类型定义文件：

```json
{
  "compilerOptions": {
    "typeRoots": ["./types", "./node_modules/@types"]
  }
}
```

这可以避免 TypeScript 解析到 `node_modules` 中不希望它处理的类型文件。

### 4. **排除特定的包**

如果问题仅在某个特定的包上，你可以在 `exclude` 中排除该包：

```json
{
  "compilerOptions": {
    "exclude": [
      "node_modules/some-package"
    ]
  }
}
```

### 5. **使用 `resolutions` (适用于 Yarn)**

如果你使用 Yarn 作为包管理器，并且某些包的依赖项中存在有问题的 `tsconfig.json`，你可以使用 Yarn 的 `resolutions` 功能强制指定某个包的特定版本。

在 `package.json` 中添加：

```json
"resolutions": {
  "**/some-package": "1.2.3"
}
```

然后运行 `yarn install`。

### 6. **升级或降级 TypeScript**

有时，报错可能是由于 TypeScript 版本不兼容导致的。尝试升级或降级 TypeScript 版本，看看问题是否能够解决：

```bash
npm install typescript@latest --save-dev
# 或者
npm install typescript@4.x.x --save-dev
```

### 7. **清理 TypeScript 缓存**

如果你已经排除了所有可能的原因，但错误依然存在，可以尝试清理 TypeScript 缓存或重新启动开发环境：

```bash
tsc --build --clean
npm run clean
npm install
```

通过以上方法，你应该能够解决 `node_modules` 包中 `tsconfig.json` 报错的问题。如果问题仍然存在，请提供更多的错误信息或上下文，我可以进一步帮助你排查。

**Comment by WangJincheng4869** [comment]
@boyongjiong 因为 `typeRoots` 的默认值是 `/node_modules/@types` ，而我需要引入 element 的 声明文件 `element-plus/global` ，因为我想要这个提示，所以才这样配置的。并且我设置了 `types` 选择，应该是仅会加载我配置的这些（英文不好，只能通过翻译，感觉 `types` 应该是这个作用）。

它们是这种包含关系，所以我这里无法将 `node_modules` 从  `typeRoots` 中移除。
![图片](https://github.com/user-attachments/assets/dea2fda0-1819-42a1-a590-e11122f4a8c0)

下面是 TS 官方文档的介绍

![图片](https://github.com/user-attachments/assets/07fe7e09-af33-4766-99cd-7127a9d7f238)

![图片](https://github.com/user-attachments/assets/e37ed015-5646-4e49-b6ba-0a087a4aae70)


我尝试删除 `node_modules` 配置，并重启 TS 服务，发现依旧没有效果。这些配置应该仅仅是影响是否加载 `.d.ts`，感觉这个 tsconfig.json 排除不掉。

![图片](https://github.com/user-attachments/assets/3f1b96bb-27c3-481c-a6a8-8dbf664f5b56)

**Comment by boyongjiong** [comment]
啥情况呀，我说的是这个呀，exclude 也可以只写 exclude: ["node_modules/@logicflow/core"] 这样试试
```
{
  "compilerOptions": {
    "skipLibCheck": true, // 跳过类型声明文件的检查
    "exclude": ["node_modules"] // 排除 node_modules 目录
  }
}
```

再仔细看看上面回复的方法

**Comment by WangJincheng4869** [comment]
> 啥情况呀，我说的是这个呀，exclude 也可以只写 exclude: ["node_modules/@logicflow/core"] 这样试试
> 
> ```
> {
>   "compilerOptions": {
>     "skipLibCheck": true, // 跳过类型声明文件的检查
>     "exclude": ["node_modules"] // 排除 node_modules 目录
>   }
> }
> ```
> 
> 再仔细看看上面回复的方法


呃.... 其实这个 `exclude` 排除选项我在反馈前就试过了，不好使。但是 `compilerOptions` 中写  `exclude` 直接报错。

![图片](https://github.com/user-attachments/assets/0c42e3f5-8672-41c5-9cad-13803df528c5)

**Comment by WangJincheng4869** [comment]
@boyongjiong 找到为什么用下面那个 `exclude` 不生效的原因了。

![图片](https://github.com/user-attachments/assets/c3566117-474e-4529-9de2-b53accaf22de)

**Comment by boyongjiong** [comment]
问题解决了吗？

如果没有解决，需要提供一下可复现示例我们这边看一下。目前我们没有复现这个问题。

**Comment by WangJincheng4869** [comment]
> 问题解决了吗？
> 
> 如果没有解决，需要提供一下可复现示例我们这边看一下。目前我们没有复现这个问题。

我给 [pnpm](https://github.com/pnpm/pnpm/issues/8427) 也提交了一个，我搞了一个复现项目，你可以用这个试试。

**Comment by Ronbb** [comment]
问题还在。在 vscode 中，跳转到 @logicflow/core 或 @logicflow/extension 中的任何文件都会产生这个错误，并且不会消失。

默认情况下，vscode 的 ts 插件只会检查打开的文件，所以需要打开 logicflow 的文件（比如使用转到定义/F12）才会出现这个错误。

可以使用 pnpm patch 删除问题配置：

```diff
diff --git a/tsconfig.json b/tsconfig.json
index d30719e4c69ef59ba1de32f55d9d935db450618e..aa33842581f3d9fc2cdbe047c0725bb9e787153c 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -1,5 +1,4 @@
 {
-  "extends": "../../tsconfig.json",
   "compilerOptions": {
     "allowImportingTsExtensions": false,
     "experimentalDecorators": true,

```

**Comment by WangJincheng4869** [comment]
> 问题还在。在 vscode 中，跳转到 @logicflow/core 或 @logicflow/extension 中的任何文件都会产生这个错误，并且不会消失。
> 
> 默认情况下，vscode 的 ts 插件只会检查打开的文件，所以需要打开 logicflow 的文件（比如使用转到定义/F12）才会出现这个错误。
> 
> 可以使用 pnpm patch 删除问题配置：
> 
> diff --git a/tsconfig.json b/tsconfig.json
> index d30719e4c69ef59ba1de32f55d9d935db450618e..aa33842581f3d9fc2cdbe047c0725bb9e787153c 100644
> --- a/tsconfig.json
> +++ b/tsconfig.json
> @@ -1,5 +1,4 @@
>  {
> -  "extends": "../../tsconfig.json",
>    "compilerOptions": {
>      "allowImportingTsExtensions": false,
>      "experimentalDecorators": true,

我每次升级都会在本地把这行干掉，这样就清净了。
