### ISSUE TITLE
[Bug Report]: 撤销操作会将全部自定义属性 `properties` 清空。

### ISSUE THREAD

**Issue by WangJincheng4869** [didi/LogicFlow#1787]
### 发生了什么？

我编写了一个 BPMN 的 usertask 节点，用到了自定义属性，但是发现撤销操作会将所有节点中的 `properties` 清空，如动图所示：
![动画](https://github.com/user-attachments/assets/0d53e237-fe3d-4266-89d3-92f1228a8d2f)

以下是我为了方便修改属性值自己编写的工具类

```ts
import { cloneDeep, set } from 'lodash-unified';
import type { ActiveLogicFlowData } from '../../types';
import { ACTIVE_LOGIC_FLOW_DATA_SYMBOL, LOGIC_FLOW_SYMBOL } from '../../context';

/**
 * LogicFlow 的操作 hooks
 */
export function useLogicFlow<T extends ActiveLogicFlowData>() {
  // LogicFlow 操作对象
  const lf = useInjectRef(LOGIC_FLOW_SYMBOL);
  // 当前修改的节点/连线对象
  const activeData = useInjectRef<T>(ACTIVE_LOGIC_FLOW_DATA_SYMBOL);

  /**
   * 修改其中一个属性的值（只能在 FlowDesigner 的子组件中使用）
   * @param path 设置值的属性路径
   * @param val 要设置的值
   */
  const setProperty = (path: string, val: any) => {
    if (!lf.value) {
      console.warn(`useLogicFlow.setProperty - LogicFlow 对象为空`);
      return;
    }
    if (!activeData.value) {
      console.warn(`useLogicFlow.setProperty - activeData 对象为空`);
      return;
    }
    if (!activeData.value.id) {
      console.warn(`useLogicFlow.setProperty - activeData 对象 id 为空`);
      return;
    }
    if (!activeData.value.properties) {
      activeData.value.properties = {};
    }
    set(activeData.value.properties, path, val);
    lf.value?.setProperties(activeData.value.id, cloneDeep(activeData.value.properties));
  };

  return {
    lf,
    activeData,
    setProperty,
  };
}

```

### logicflow/core版本

2.0.1

### logicflow/extension版本

2.0.1

### 浏览器&环境

Chrome

**Comment by FanSun521** [comment]
可以把你编写的 demo 提供下吗

**Comment by WangJincheng4869** [comment]
> 可以把你编写的 demo 提供下吗

我得花些时间抽出来，这个是封装在项目里的，用到了不少项目的工具类，不急的话等我几个小时。

**Comment by WangJincheng4869** [comment]
> 可以把你编写的 demo 提供下吗

https://github.com/WangJincheng4869/fanKuiWenJian/tree/main/packages/logic-flow-redo-bug-demo

**Comment by FanSun521** [comment]
你的vue数据流有问题，你的vue数据和logicflow数据不对应，我算了回退步长是没问题的，你改两次propertise数据，就可以回退两次undo，logicFLow是没问题的。
你可以参考vue demo: https://examples.logic-flow.cn/demo/dist/mvp
源码：https://github.com/Logic-Flow/docs/tree/master/demo/mvp
后续还有问题可以再交流～

**Comment by WangJincheng4869** [comment]
@FanSun521 好，我研究研究，虽然你这个demo撤销也有问题，撤销一步需要连续点两次撤销，但是没把全部的属性都清除。

**Comment by FanSun521** [comment]
我没细看这个demo，撤销一步需要连续点两次撤销，我也发现了，发生在点击节点弹出属性面板的时候，这一步可能会有修改properties的操作，所以需要点两次，LogicFlow的undo是没问题的。

**Comment by WangJincheng4869** [comment]
@FanSun521 您看是不是我理解的这样。

## 1. 我将 [候选者类型] 中 [员工] 修改为 [部门]

这里我设置了两次数据（调用了两次 `setProperty` 方法）：
1. 将类型修改为部门
![图片](https://github.com/user-attachments/assets/0ef3ada8-6e8c-40ce-9c61-e9ee228086cc)

3. 将员工集合数据清空
![图片](https://github.com/user-attachments/assets/13c753c5-e86b-4796-a0ae-1061128b10c4)
![图片](https://github.com/user-attachments/assets/0519021c-34ab-4ac5-b37a-d6be0c93a1f1)

## 2. 修改多任务处理方式
![图片](https://github.com/user-attachments/assets/c5bcfb7c-632f-4860-8c59-59d1ee1ce65f)

## 3. 拖入任意一个网关 

也应该算一次操作

## 4. 将网关类型改变
![图片](https://github.com/user-attachments/assets/8c5423a2-769b-4baa-8fc3-fcafa80ac510)
这里我调用了 3 次方法，那么算几步？


目前我不知道撤销的操作是怎么计算的，能大概说明一下吗？我找找思路是哪里出了问题。

**Comment by WangJincheng4869** [comment]
@FanSun521 我现在有点无从下手，如果能知道这个撤销的计算方式，那么应该能有些帮助，麻烦了。

**Comment by FanSun521** [comment]
先吃饭₍˄·͈༝·͈˄*₎◞ ̑̑

在 2024-08-27 12:01:11，"Kirito丶城" ***@***.***> 写道：

@FanSun521 我现在有点无从下手，如果能知道这个撤销的计算方式，那么应该能有些帮助，麻烦了。

**Comment by FanSun521** [comment]
这边计算的撤销逻辑是 GraphData 中有数据变会往undos队列存一次 graphData 画布数据 
源码地址：https://github.com/didi/LogicFlow/blob/master/packages/core/src/history/index.ts

**Comment by WangJincheng4869** [comment]
> 这边计算的撤销逻辑是 GraphData 中有数据变会往undos队列存一次 graphData 画布数据 源码地址：https://github.com/didi/LogicFlow/blob/master/packages/core/src/history/index.ts

请问我如何能debug这个类，从目前的现在看最有可能的就是其没有将 `Properties` 数据加入 `undos` 中。因为目前的现象就是，只要进行一次撤销就会将所有节点的 `Properties` 清除。无论中间间隔多少次操作。

**Comment by FanSun521** [comment]
<sp-flow-designer-control-panel :lf="logicFlow" @undo="activeData = undefined" @redo="activeData = undefined" />
你每次undo都会额外执行activeData = undefine，我觉得你这里会有问题：
@undo="activeData = undefined"

**Comment by WangJincheng4869** [comment]
> <sp-flow-designer-control-panel :lf="logicFlow" @undo="activeData = undefined" @redo="activeData = undefined" /> 你每次undo都会额外执行activeData = undefine，我觉得你这里会有问题： @undo="activeData = undefined"

应该不是这样原因，因为 `activeData` 与 logicFlow 的数据无关，这个是我自己存的数据。我去除了这两个事件问题依旧存在。

**Comment by FanSun521** [comment]
> > <sp-flow-designer-control-panel :lf="logicFlow" @undo="activeData = undefined" @redo="activeData = undefined" /> 你每次undo都会额外执行activeData = undefine，我觉得你这里会有问题： @undo="activeData = undefined"
> 
> 应该不是这样原因，因为 `activeData` 与 logicFlow 的数据无关，这个是我自己存的数据。我去除了这两个事件问题依旧存在。

 lf.value?.setProperties(activeData.value.id, toRaw(activeData.value.properties)); 这样就ok了

**Comment by FanSun521** [comment]
> > > <sp-flow-designer-control-panel :lf="logicFlow" @undo="activeData = undefined" @redo="activeData = undefined" /> 你每次undo都会额外执行activeData = undefine，我觉得你这里会有问题： @undo="activeData = undefined"
> > 
> > 
> > 应该不是这样原因，因为 `activeData` 与 logicFlow 的数据无关，这个是我自己存的数据。我去除了这两个事件问题依旧存在。
> 
> lf.value?.setProperties(activeData.value.id, toRaw(activeData.value.properties)); 这样就ok了，回退次数正常了，剩余的就是处理vue数据了
> 调试我这边也挺麻烦，我去改node_modules代码结果没有效果
> 传vue响应式数据有问题，我也猜想 就是其没有将 Properties 数据加入 undos 中，这个需要后续排查下：传响应式数据 => garphData 对于LogicFLow 来说确实不变，所以没有加入 undos 中，如果是这样，那就需要兼容下传 vue 响应式数据

**Comment by FanSun521** [comment]
> > > > <sp-flow-designer-control-panel :lf="logicFlow" @undo="activeData = undefined" @redo="activeData = undefined" /> 你每次undo都会额外执行activeData = undefine，我觉得你这里会有问题： @undo="activeData = undefined"
> > > 
> > > 
> > > 应该不是这样原因，因为 `activeData` 与 logicFlow 的数据无关，这个是我自己存的数据。我去除了这两个事件问题依旧存在。
> > 
> > 
> > lf.value?.setProperties(activeData.value.id, toRaw(activeData.value.properties)); 这样就ok了，回退次数正常了，剩余的就是处理vue数据了
> > 调试我这边也挺麻烦，我去改node_modules代码结果没有效果
> > 传vue响应式数据有问题，我也猜想 就是其没有将 Properties 数据加入 undos 中，这个需要后续排查下：传响应式数据 => garphData 对于LogicFLow 来说确实 garphData 数据不变，所以没有加入 undos 中，如果是这样，那就需要兼容下传 vue 响应式数据

**Comment by WangJincheng4869** [comment]
## 以下是我通过 `HISTORY_CHANGE` 事件捕捉到的数据
先说问题：
1. 撤销后 `redoAble` 的值依旧是 `false`，这个感觉应该是bug
2. 查看 `undos` 数组中的数据的确是正确的，但不知为何撤销后无法正确还原

下图中最后一个是点击撤销后的数据，倒数第二个则是撤销之前的数据。

![图片](https://github.com/user-attachments/assets/4571e8f5-df4d-47e1-907a-97cdb6ff07f4)

**Comment by WangJincheng4869** [comment]
### 这是刚把用户节点拖进画布的数据，没有任何问题，两个都是竟签、员工
![图片](https://github.com/user-attachments/assets/778de9a7-4c6a-4f88-82d1-8662f76220f2)

### 修改为 部门、并签，数据出问题了
![图片](https://github.com/user-attachments/assets/df02c311-8b75-47b9-8489-51efe613a245)

**Comment by WangJincheng4869** [comment]
### 这个是直接修改为部门，没有设置为并签。这时数据就已经出问题了

![图片](https://github.com/user-attachments/assets/42e4d930-ec7e-45f7-a223-725f53554767)

### 这里的 setProperties 的方法我已经进行了修改，同时加上了 `toRaw` 和 `cloneDeep`

![图片](https://github.com/user-attachments/assets/22c11223-d21f-4e8e-936b-f51880e872cc)

**Comment by WangJincheng4869** [comment]
@FanSun521 大佬，我好像找到原因了，但是不知道怎么解决，您帮我参谋参谋。

原因是我自定义的这个节点，构造函数中会初始化属性值。
![图片](https://github.com/user-attachments/assets/05454b82-6e5d-44c6-8bcf-1e4e4ef61a03)

但是，在撤销时画布会重绘，并且会重新创建这个对象，所以导致被重置了。

我是直接在浏览器里打断点发现的！

![图片](https://github.com/user-attachments/assets/bbc7de12-c066-4f34-b1b9-c903a6439bbc)

直接进来了

![图片](https://github.com/user-attachments/assets/c77b5f52-c155-4474-9a6f-fc3da20b52d2)

**Comment by FanSun521** [comment]
- 我发现 setProperties 会触发UserTaskModel的 construtor 很奇怪
- redo/undo 是基于graphData的，graphData变了就会重新new 节点，执行constructor这个是符合预期的，解决办法：
this.properties = { ...new DefaultUserTaskProperties(), ...this.properties }; new DefaultUserTaskProperties()优先级低一些试一下
- 我现在人晕了，排查不出来问题了

**Comment by WangJincheng4869** [comment]
> * 我发现 setProperties 会触发UserTaskModel的 construtor 很奇怪
> 
>     * redo/undo 是基于graphData的，graphData变了就会重新new 节点，执行constructor这个是符合预期的，解决办法：
>       this.properties = { ...new DefaultUserTaskProperties(), ...this.properties }; new DefaultUserTaskProperties()优先级低一些试一下
> 
>     * 我现在人晕了，排查不出来问题了

非常感谢！的确是个低级错误，改成如下写法就没问题了。

![图片](https://github.com/user-attachments/assets/b72430db-bf06-43d0-8d9f-8e0d8aa4e683)

## 问题原因

在重绘时会将原始的数据通过构造传进来，由于我的错误写法导致将其数据重置。

### 错误的写法

1、这里的 ` this.properties = { ...this.properties, ...UserTaskPropertiesFactory.createDefault() };` 导致将重绘的时候的数据重置

```ts
class UserTaskModel extends RectNodeModel {
  constructor(data: LogicFlow.NodeConfig<UserTaskProperties>, graphModel: GraphModel) {
    super(data, graphModel);
    this.properties = { ...this.properties, ...UserTaskPropertiesFactory.createDefault() };
  }
}
```
### 正确的写法

需要先对 `data.properties` 判断再进行初始化，随后调用父类构造。

```ts
class UserTaskModel extends RectNodeModel {
  constructor(data: LogicFlow.NodeConfig<UserTaskProperties>, graphModel: GraphModel) {
    data.properties ||= UserTaskPropertiesFactory.createDefault();
    super(data, graphModel);
  }
}
```
