### ISSUE TITLE
[Bug Report]: 官网自定义节点demo的节点只能复制一次

### ISSUE THREAD

**Issue by DymoneLewis** [didi/LogicFlow#1791]
### 发生了什么？

第一个节点复制以后，再去选中第二个节点复制，就复制不了
![{B464B1B8-019F-8ECB-D6DD-E7CE888B4F80}](https://github.com/user-attachments/assets/4a42b670-6d9f-4a2d-94bc-466f4e647fbb)

————————————2024.12.11 更新——————————————————
验证了一下，感觉是操作问题，如果没选中节点就复制粘贴的话确实就复制不了了

### logicflow/core版本

1.2.28

### logicflow/extension版本

1.2.28

### 浏览器&环境

Chrome

**Comment by Ari1c** [comment]
@boyongjiong 问一下有没有类似 node 的复制方法，背景是我在编排 html 节点的时候里面可以设置全局变量，我想在用户复制的时候把复制 node 的全局变量也复制一份，这个有办法吗，有没有类似 lf.on("node:xxx(复制)", (node) => {}) 的方法

**Comment by DymoneLewis** [comment]
> @boyongjiong 问一下有没有类似 node 的复制方法，背景是我在编排 html 节点的时候里面可以设置全局变量，我想在用户复制的时候把复制 node 的全局变量也复制一份，这个有办法吗，有没有类似 lf.on("node:xxx(复制)", (node) => {}) 的方法

🤔如果想要实现这样的效果，不用加"node:xxx(复制)"事件也能实现吧，因为cloneNode的逻辑其实就是这样
  ```
const targetNode = this.getNodeModelById(nodeId) // 根据ID找到对应的nodeModel
const data = targetNode?.getData() // 获取节点数据，里面会包括当前节点的id、坐标、文本、properties信息
if (data) {
  data.x += 30 // 设置新节点的坐标位移以错开两个节点
  data.y += 30
  data.id = ''
  if (typeof data.text === 'object' && data.text !== null) { // 如果有文本的话也更新一下文本年代坐标
    data.text.x += 30
    data.text.y += 30
  }
  const nodeModel = this.addNode(data) // 根据上面的数据创建新节点
```
所以如果要复制的话可以在执行cloneNode之前把当前节点的数据和全局变量存下来再复制
