### ISSUE TITLE
[Feature]: 第一次很难找到获取画布数据源的 api，文档可以优化～

### ISSUE THREAD

**Issue by Lzzzs** [didi/LogicFlow#1796]
### 背景&目的

我第一次开发 LF，想要只要获取画布的数据 api 是哪个，找不到地方。还是通过 google 去搜了之后，才知道 api是啥。
![image](https://github.com/user-attachments/assets/0b472e68-478b-4d64-991d-18c485ae2583)
知道 api 是啥，我去文档里面搜才知道在这，感觉不太明显，因为我感觉这个 api 也是比较重要的，可以考虑放到【快速上手】章节？让用户能从这个章节立马知道 渲染图表-> 获取数据 的全流程

**Comment by boyongjiong** [comment]
感谢建议，我们考虑一下

**Comment by FanSun521** [comment]
官网已更新，close 这个 issue 了

**Comment by FanSun521** [comment]
官网已更新，close 这个 issue 了
