### ISSUE TITLE
[Bug Report]: 文档教程有误

### ISSUE THREAD

**Issue by leo-118** [didi/LogicFlow#1798]
### 发生了什么？

![image](https://github.com/user-attachments/assets/3845be94-198d-4ade-91d2-0adcd46f8c07)
路径不对， 2.0.1版本没有style目录

### logicflow/core版本

2.0.1

### logicflow/extension版本

2.0.1

### 浏览器&环境

Microsoft Edge

**Comment by boyongjiong** [comment]
下次麻烦提供完整的文档截图或者文档链接。找到两个插件文档中链接未更新。下个版本会更新文档

你这么引用就可以  import "@logicflow/core/lib/style/index.css"

**Comment by leo-118** [comment]
非常感谢&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月22日(星期四) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [didi/LogicFlow] [Bug Report]: 文档教程有误 (Issue #1798)














 
下次麻烦提供完整的文档截图或者文档链接。找到两个插件文档中链接未更新。下个版本会更新文档
 
你这么引用就可以  import ***@***.***/core/lib/style/index.css"
