### ISSUE TITLE
[Bug Report]: 新插件 NodeSelection 选中后 resize 问题

### ISSUE THREAD

**Issue by miyuesc** [didi/LogicFlow#1800]
### 问题1

![image](https://github.com/user-attachments/assets/350a1256-c658-4d63-bdda-94143d69ab48)
![image](https://github.com/user-attachments/assets/c6ca6182-38b5-422d-8618-39e119c6ea43)
![image](https://github.com/user-attachments/assets/839841d3-1178-486a-ba27-9ee7d7c31f13)

选中元素后调整元素大小，选中框无法同时更新，但是，在进行撤销恢复操作时，则会同步变化。

### 问题2

![image](https://github.com/user-attachments/assets/0565c0e5-83be-49ac-a163-64b8a71b3f81)

选框支持 resize？如果支持的话，个人感觉应该是将内部选中元素进行等比例放大，而不是单纯调整选框大小。并且选框resize 之后，内部元素变化选框会再次恢复到适配选中元素的状态

### logicflow/core版本

2.0.1

### logicflow/extension版本

2.0.1

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
第一个问题辛苦将extension包升级到2.0.6版本试试呢
第二个问题我们排期解决一下，也欢迎提pr给我们
