### ISSUE TITLE
[Bug Report]: 预设的 BPMN 泳道元素 resize 异常

### ISSUE THREAD

**Issue by miyuesc** [didi/LogicFlow#1802]
### 发生了什么？

![image](https://github.com/user-attachments/assets/86ba0dd8-1a3f-4eb1-b223-9bfb6497fa1b)

预设代码中对 node:resize 的监听回调函数参数设置异常。v 2.0 中该事件参数已经修改。

### logicflow/core版本

2.0.1

### logicflow/extension版本

2.0.1

**Comment by DymoneLewis** [comment]
麻烦提供一下你的node:resize回调方法的写法，从截图上看oldNodeSize应该是你的业务变量，看不出从哪个参数上取的值

**Comment by miyuesc** [comment]
> 麻烦提供一下你的node:resize回调方法的写法，从截图上看oldNodeSize应该是你的业务变量，看不出从哪个参数上取的值

@DymoneLewis 这个是官网里面 插件 => nodeResize 里面最后的一个例子

**Comment by DymoneLewis** [comment]
> > 麻烦提供一下你的node:resize回调方法的写法，从截图上看oldNodeSize应该是你的业务变量，看不出从哪个参数上取的值
> 
> https://site.logic-flow.cn/tutorial/extension/node-resize
> 
> ![image](https://private-user-images.githubusercontent.com/50617660/366049671-e9a2b773-1505-42dd-995e-5bc0d3794f0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzM1ODcsIm5iZiI6MTcyNTk3MzI4NywicGF0aCI6Ii81MDYxNzY2MC8zNjYwNDk2NzEtZTlhMmI3NzMtMTUwNS00MmRkLTk5NWUtNWJjMGQzNzk0ZjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDEzMDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNjA3MjI3ZTBiMGI4YzJhYzdkNmRlZDkzNzgxYzdhZGNjYzUzMDlmNTgzZmQ1Y2FkYTdlN2JiOWRiOTA3YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M0JSexqEib4zoma9QXEVeMbqLgKgj9Bua6rohJFzJbY)
> 
> 在 2.0.1 版本的时候，参数是不对上的。实际代码运行中，回调函数参数是我截图中所示的样子。

了解，看了一下确实是版本迭代里把参数名改了：oldNodeSize => preData, newNodeSize => data，可以先把参数名换一下试试，我们本周处理一下这个问题

**Comment by miyuesc** [comment]
看起来不只是回调参数对象的 key 变化了，内部内容也变了很多。希望后面这种改动可以同步更新下文档

**Comment by DymoneLewis** [comment]
已发2.0.7版本，可以升级试一下
