### ISSUE TITLE
[Bug Report]: 先旋转节点，然后进行缩放，锚点有问题

### ISSUE THREAD

**Issue by zxh666a** [didi/LogicFlow#1813]
### 发生了什么？

1、先旋转再缩放，锚点会偏移
2、旋转360度，再缩放，缩放点位会是反方向的，例如右下角往右拖本应该是放大，却是缩小。
![Snipaste_2024-08-23_14-02-20](https://github.com/user-attachments/assets/a9d848f5-6e4c-46ae-be9f-005327c6cbf0)

### logicflow/core版本

2.0.1

### logicflow/extension版本

2.0.1

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
我们正在处理这个问题，请等待下一个版本

**Comment by DymoneLewis** [comment]
您好，这个问题已于最新版本修复，请升级到core 2.0.5版本 extension 2.0.9版本再试一下
