### ISSUE TITLE
[Bug Report]: 升级2.0.2报错

### ISSUE THREAD

**Issue by HunterHeroHan** [didi/LogicFlow#1814]
### 发生了什么？

umi 4.3.15环境，升级到2.0.2版本报错，2.0.1 还是好的
![image](https://github.com/user-attachments/assets/73af97df-b2ef-4b86-844f-773e63fafe86)

### logicflow/core版本

2.0.2

### logicflow/extension版本

2.0.2

### 浏览器&环境

Chrome

**Comment by tank0321** [comment]
我也遇到同样错误

**Comment by boyongjiong** [comment]
或者下次提 issue，带一下 demo，不然我们修复了也没办法验证是否 OK 了。在我们这边的项目中都是 OK 的 o.o

**Comment by tank0321** [comment]
> 升级 2.0.4 试一下呢？之前在 Extension index.ts 中引入了 index.less，好像是有问题的，处理了一下

目前最新release只有2.0.2
