### ISSUE TITLE
[Bug Report]: windows在开发extention包时，执行pnpm run  build:watch报错

### ISSUE THREAD

**Issue by rainnoon** [didi/LogicFlow#1818]
### 发生了什么？

![Snipaste_2024-08-23_17-21-04](https://github.com/user-attachments/assets/fb3886d8-02fd-42e4-8171-b38d901dc592)
执行命令报错

### logicflow/core版本

2.0.2

### logicflow/extension版本

2.0.2

**Comment by boyongjiong** [comment]
"build:watch:esm": "tsc --module esnext --target es6 --outDir ./es --watch" 麻烦试一下改成这样看有没有问题？我这边没有 windows 电脑 0.o
