### ISSUE TITLE
[Bug Report]: 2.0.1以上版本流程保存bpmn格式后再回显时报错Cannot read properties of undefined (reading 'dc:Bounds')

### ISSUE THREAD

**Issue by jisuwoniusxy** [didi/LogicFlow#1823]
### 发生了什么？

vue版本 2.0.1以上版本流程保存bpmn格式后再回显时报错Cannot read properties of undefined (reading 'dc:Bounds')然后只能显示节点，不能显示箭头线。 在官网示例[https://site.logic-flow.cn/zh/examples/showcase/bussiness#bpmn这个页面上画流程后点击下面的保存按钮后再点击上传按钮] 也报同样的错误。 在bpmn网站[上是可以正常回显的](https://demo.bpmn.io/s/start)
示例[https://site.logic-flow.cn/zh/examples/showcase/bussiness#bpmn](示例)

### logicflow/core版本

2.0.1及以上

### logicflow/extension版本

2.0.1及以上

### 浏览器&环境

Chrome, NodeJS

**Comment by boyongjiong** [comment]
已发布 @logicflow/extension@2.0.5，已解决该问题，辛苦升级使用

**Comment by jisuwoniusxy** [comment]
我安装了@logicflow/extension@2.0.5版本  没好使啊  还是报那个错误啊

**Comment by jisuwoniusxy** [comment]
![Snipaste_2024-08-28_10-14-35](https://github.com/user-attachments/assets/e61cbb3d-18a1-453a-bd0a-5db835602087)
