### ISSUE TITLE
[Bug Report]: mvp案例给自定义node添加快捷样式后translateCenter报错

### ISSUE THREAD

**Issue by weiwei02580** [didi/LogicFlow#1830]
### 发生了什么？

![Snipaste_2024-08-28_16-54-13](https://github.com/user-attachments/assets/be2119f9-b74c-4603-a713-8ccb2c06bb34)

### logicflow/core版本

2.0.3

### logicflow/extension版本

2.0.4

**Comment by weiwei02580** [comment]
同之前 #1090的问题

**Comment by boyongjiong** [comment]
给自定义节点添加快捷样式是什么意思。麻烦带可复现 demo 提 issue
