### ISSUE TITLE
[Bug Report]: 画布拖动结束的事件无法监听到

### ISSUE THREAD

**Issue by SprASum** [didi/LogicFlow#1838]
### 发生了什么？

在源码中注册了画布拖拽结束的事件
![image](https://github.com/user-attachments/assets/0c6f71f2-4a1f-4220-b4fe-0863335b7b9f)

但是监听这个事件画布拖拽结束无法正常触发

### logicflow/core版本

2.0.1

### logicflow/extension版本

2.0.1

### logicflow/engine版本

2.0.1

**Comment by boyongjiong** [comment]
![image](https://github.com/user-attachments/assets/3add6151-84ce-448b-8685-51740fce6237)

![image](https://github.com/user-attachments/assets/8b32f678-8c69-4137-9ac3-b8e165273166)


最新版本 2.0.3，我这边测试是没有问题的，可以升级版本再看一下，如果有问题再反馈。
