### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by zxh666a** [didi/LogicFlow#1839]
### 发生了什么？

文字有回车换行的情况下，动态调整文字大小，文字会便宜，文字元素会变得很高。
![image](https://github.com/user-attachments/assets/6bc7e2d1-b645-486e-8b63-d4d0b87aab61)

### logicflow/core版本

2.0.1

### logicflow/extension版本

2.0.1

**Comment by DymoneLewis** [comment]
> > 你好，我想确认一下你的文本用的是原生文本还是Label呢？
> 
> 原生文本，双击编辑的那个。未使用label。
确实有问题，我修复一下

**Comment by DymoneLewis** [comment]
> > 你好，我想确认一下你的文本用的是原生文本还是Label呢？
> 
> 原生文本，双击编辑的那个。未使用label。
确实有问题，我修复一下

**Comment by DymoneLewis** [comment]
下午好，我最近又写了demo review了一下，发现了问题原因疑似是fontSize传入了字符串导致的😅，辛苦fontSize传入number再试下呢
