### ISSUE TITLE
【微信群】自定义连线规则两个节点直接只允许一条边

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#184]

**Comment by towersxu** [comment]
方案：
1. 自己维护一个map去记录那两个节点直接已连接线，然后去获取。
2. 实时去拿所有的边，自己判断。
![1621492137553](https://user-images.githubusercontent.com/4093984/118929964-c1498600-b977-11eb-82a3-9d259e2c7236.jpg)

**Comment by ctrlh985** [comment]
该如何实时获取所有边
