### ISSUE TITLE
[Bug Report]: 测试vue组件，出现“this.vm.$destroy is not a function”错误

### ISSUE THREAD

**Issue by raingend** [didi/LogicFlow#1848]
### 发生了什么？

我在测试vue组件功能的时候遇到问题。我只做了个设计器页面和一个Vue组件的页面，设计器页面我是这样写的
'''
<script>
……
import { register } from '@logicflow/vue-node-registry';
import VueNode from "./vueNode.vue";

export default {
    name: "flowDiagram",
    data() {
        return {
            lf: null,
            drawer: false,
            currentNode: null,
        };
    },

    mounted() {
        //初始化
        this.lf = new LogicFlow({
            container: this.$refs.container,
	    //使用Dnd面板
            plugins: [DndPanel],
        });
	// 注册vue组件
        register(
            {
                type: 'VueNode',
                component: VueNode
            },
            this.lf
        )
        this.lf.extension.dndPanel.setPatternItems(
            [
                {
                    type: 'VueNode',
                    text: 'Vue节点',
                    icon: require('@/assets/img/delete.jpg'),
                },
            ]
        )
	// 默认添加一个节点，并渲染出来
        this.lf.render(
            {
                nodes: [
                    {
                        id: 50,
                        type: 'VueNode',
                        x: 100,
                        y: 150,
                        text: '你好',
                    },
                ],
            }
        );
    },

    methods: {
        handleClose(done) {
            done();
        },
    },
}
</script>
'''

vue组件的代码也很简单
'''
<template>
    <div>
        <img style="width: 60px; height: 60px;" src="@/assets/img/logo.png" />{{ labeltext }}
    </div>
</template>

<script>
export default {
    name: 'VueNode',
    data() {
        return {
            labeltext: "hi there"
        }
    },
    mounted() {
        this.labeltext = this.labeltext + "1"
    }
}
</script>
'''
运行起来后，没问题
![Z@OKG$6B 9_ 9371_{JIU2](https://github.com/user-attachments/assets/7d4ae95f-69b7-47dc-bdd7-82b06adcf3cc)
从Dnd面板拖动组件到设计器中也正常
![XJF(YBPK@FD@EL`5~VW%0GE](https://github.com/user-attachments/assets/8bf039f1-daae-4bbd-bbc1-71b697defe29)
松开鼠标时，报错“this.vm.$destroy is not a function”
![36C441) `49@ {CC%@MCOZR](https://github.com/user-attachments/assets/1ba28e7d-d59f-4838-8c5c-e25b6ae398a5)

### logicflow/core版本

2.0.3

### logicflow/extension版本

2.0.5

### 浏览器&环境

Microsoft Edge

**Comment by DymoneLewis** [comment]
没看懂，所以是怎么触发的这个报错？

**Comment by boyongjiong** [comment]
麻烦提供一下复现 demo，这个描述我们无法定位问题，没有复现 demo 我们会对此 issue 做关闭处理

**Comment by xwatsonmai** [comment]
+1 我也遇到这个bug，就是把vue节点注册到dndPanel里，然后从拖拽面板里把vue节点拖出来的时候就可以复现出这个问题了

**Comment by boyongjiong** [comment]
> +1 我也遇到这个bug，就是把vue节点注册到dndPanel里，然后从拖拽面板里把vue节点拖出来的时候就可以复现出这个问题了
> 
> 更新： 我知道是啥问题了，要按照vue自定义节点里说明的，引入const TeleportContainer = getTeleport()，然后在模板里使用： `<TeleportContainer />` 就能解决这个问题了。。。
> 
> 说时候我觉得这种方法有点奇怪，有一丢丢额外的心智负担，不过能用就好

可以抽空给我们提供个例子看看吗？想了解下前因后果全貌

**Comment by boyongjiong** [comment]
@logicflow/extension@2.0.10 应该已经解决了该问题，可以升级使用 #1895
