### ISSUE TITLE
【微信群】拖拽添加节点报错“不存在id为xx的节点”

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#185]
![1621492284045](https://user-images.githubusercontent.com/4093984/118930272-1f766900-b978-11eb-9258-e7d5899df638.jpg)

**Comment by towersxu** [comment]
这种情况下，一般是因为自己在定义拖拽面板的时候，面板本身有内容可以拖拽导致的。比如拖了一个图片、一个标签之类的。
可以考虑将这些可拖拽的元素设置为不可拖动。
有如下措施：
1. 给图片添加point-events:none属性

**Comment by WangShuXian6** [comment]
我用的是原生drop事件，onDrop的时候

```ts
 dnd.startDrag({
      type: 'UserTask'
    })
```

该怎么办？
会一直报这个错，但不影响使用

**Comment by towersxu** [comment]
dnd只有在mousedown事件后调用，如果希望自定义拖动，不能使用dnd。您可以参考dnd源码，自己在拖动结束后计算出鼠标位置的坐标，手动添加节点到对应的文章。计算坐标可以参考[http://logic-flow.org/api/transformModelApi.html#htmlpointtocanvaspoint](http://logic-flow.org/api/transformModelApi.html#htmlpointtocanvaspoint)
