### ISSUE TITLE
[Feature]:这行日志输出能删掉吗？每次修改都会输出 `console.log('_rootEl', _rootEl)`

### ISSUE THREAD

**Issue by WangJincheng4869** [didi/LogicFlow#1856]
### 背景&目的

![图片](https://github.com/user-attachments/assets/ae4507f0-bd4d-4993-bf50-7decb469eae0)

**Comment by boyongjiong** [comment]
安排

**Comment by DymoneLewis** [comment]
extension包已发2.0.7版本，可以升级试一下
