### ISSUE TITLE
[Bug Report]: @logicflow/extension@2.0.2 子流程的折叠事件源码报错

### ISSUE THREAD

**Issue by small145900** [didi/LogicFlow#1857]
### 发生了什么？

引用了内部子流程，点击折叠icon，源码报错如下图。经过排查，推测是源码的阻止冒泡命令没有断句分号，ts编译成js后没有自动增加断句符号，导致了后续的命令与冒泡命令变成了一条执行语句，从尔报错。
![WechatIMG4935](https://github.com/user-attachments/assets/c9edebe6-142f-43ce-8e6e-fdb3eba87582)
![WechatIMG4938](https://github.com/user-attachments/assets/cb76898e-ff60-49ef-96b0-e6514145189c)

### logicflow/core版本

2.0.2

### logicflow/extension版本

2.0.2

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
extension包已发2.0.7版本，可以升级试一下
