### ISSUE TITLE
[Bug Report]: 拖动react自定义节点组件到画布中，使用Portal 方式渲染，拖拽完成后出现重复创建元素导致的key重复问题，而且在进入画布的时候也会自动添加一个虚拟节点到虚拟dom树中

### ISSUE THREAD

**Issue by jiujiu-123** [didi/LogicFlow#1866]
### 发生了什么？

react中 使用函数式组件定义react自定义节点，并使用Portal 方式渲染组件自定义组件 我将自定义组件通过dnd.startDrag()的方式拖动到画布中 即使我没有松开鼠标 他刚到画布中就会在reactDOM树中保存一个节点，当我松开鼠标时他会同时保存两个id一样的节点且报错key重复，
只要我不用Portal 方式渲染组件就不会存在这个问题 是不是Portal.getProvider()内部的useReducer方法存在问题 

index.js:1  Warning: Encountered two children with the same key, `5a0c618a-3546-4f38-b8c3-fd32c756f2d9`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

这个是拖拽逻辑
  const MouseDown = (e: MouseEvent,item: any) => {
    e.stopPropagation()
    props.flow?.dnd.startDrag({
      type: item.type,
      label: `${(e.target as HTMLElement).textContent}`,
      text: `${(e.target as HTMLElement).textContent}`,
      properties: {
        name: item.type,
        width: item.properties?.width || 100,
        height: item.properties?.height || 100,

        style: {
          width: "100px",
          height: '100px',
          border: '1px solid #000000',
          stroke:"blue",
          strokeLinecap: 'round',
        }
      },
    })
  }

这个是展示画布组件的jsx
export const CanvasContext = createContext<LogicFlow | null>(null);
const LFReactPortalProvider = Portal.getProvider();

    <div className="flex flex-row w-[100%] h-[99vh]">
      <div
        style={{ borderRight: '1px solid #f4f4f4' }}
        className="flex h-[100%] w-[300px] pt-5 bg-[#ffffff]"
      >
        <MaterialList flow={flow} />
      </div>

      <div>
        {/*<CanvasContext.Provider >*/}
          <LFReactPortalProvider />
        {/*</CanvasContext.Provider>*/}
      </div>
      <div className="flex-1" ref={containerFlowRef}></div>

    </div>

这是自定义的react节点
import { ReactNodeProps, ReactNodeView } from '@logicflow/react-node-registry';
import { FC, memo, useContext } from 'react';
import { CanvasContext } from '@/pages/editor';

// 自定义 React 组件
const NodeComponent: FC<ReactNodeProps> = ({ node }) => {
  // const flow = useContext(CanvasContext)
  // if(!flow || !node) return;
  // flow.getDataById(node.id)
  const data = node.getData();
  if (!data.properties) data.properties = {};

  const confirmUpdate = ReactNodeView.prototype.confirmUpdate.bind(node)
  // 重写更新逻辑
  ReactNodeView.prototype.confirmUpdate = ()=>{
    // console.log(13131);
  }
  return (
    <div style={node.getProperties().style} key={new Date().getTime()}>
      <div className="react-algo-node">
        <span>{data.properties.name as string}圆形</span>
      </div>
    </div>
  );
};

export default memo(NodeComponent);

### logicflow/core版本

2.0.3

### logicflow/extension版本

2.0.6

### 浏览器&环境

Chrome

**Comment by gismanli** [comment]
https://github.com/didi/LogicFlow/blob/master/packages/react-node-registry/src/view.ts#L25

这里有BUG，没有针对Portal模式做判断，重复插入了DOM元素
