### ISSUE TITLE
[Bug Report]: 旋转 graph 后，targetNode无法落线形成一个边

### ISSUE THREAD

**Issue by LeeeeeeM** [didi/LogicFlow#1871]
### 发生了什么？

对于旋转后的 graph，部分场景下判断终点是否落在锚点有问题 一直是 false，导致无法在 targetNodeInfo 中获取到anchor，无法进行 edge连线。

![image](https://github.com/user-attachments/assets/9c4d025c-1c8f-450f-8d46-62274fa7a026)

![image](https://github.com/user-attachments/assets/e3e41c72-1fca-470b-a552-159bb46f98d0)

### logicflow/core版本

latest

### logicflow/extension版本

latest

### logicflow/engine版本

latest

### 浏览器&环境

Chrome

**Comment by LeeeeeeM** [comment]
判断 isInNode的方法有问题，可以用叉乘处理判断落点是否在当前多边形内。
可以先简单处理凸多边形的场景。

**Comment by boyongjiong** [comment]
大佬提个 PR 吧
