### ISSUE TITLE
能麻烦支持下，在外部能针对节点新增菜单或者覆盖菜单嘛

### ISSUE THREAD

**Issue by aidening** [didi/LogicFlow#188]
**需求描述**  
#### 1、需求
希望能够在外部 `新增` 节点菜单 或者 `覆盖` 节点菜单，不是到 `model` 内 覆盖 `this.menu`
#### 2、期望的表现
类似 
```
lf.addNodeMenu({
    type: 'nodeType',
    text: '详情',
    callback(node) {}
});

lf.setNodeMenu({
    type: 'nodeType',
    menus: [
        {
            text: '菜单1',
            callback(node) {}
        }
    ]
})
```

**Comment by towersxu** [comment]
已支持，参考[文档](http://logic-flow.org/guide/extension/component-menu.html#%E6%8C%87%E5%AE%9A%E7%B1%BB%E5%9E%8B%E5%85%83%E7%B4%A0%E9%85%8D%E7%BD%AE%E8%8F%9C%E5%8D%95)
