### ISSUE TITLE
[Feature]: edges 直接通过properties 配置线段上的文本颜色等属性。

### ISSUE THREAD

**Issue by leixuesong** [didi/LogicFlow#1880]
### 背景&目的

目前只有两个办法：
1. 重写边的getTextStyle方法，重新定义边文本样式的取值逻辑_
2. 设置主题，初始化传入的配置项style支持通过edgeText字段设置边字体颜色。

希望在定义data数据时，edges 直接通过properties 配置edgeText来设置线段上的文本颜色等属性，这样可以保持和设置主题统一，同时更加灵活和方便。

**Comment by boyongjiong** [comment]
目前的设计，用户可以通过自定义边实现该功能。

因为人力有限，目前可能没有人力实现该功能，这边欢迎你能参与 PR，实现更多类似的功能。共建 LogicFlow

因为暂无计划，所以先将该 issue 关闭，希望能在 PR 区见到你哈哈哈
