### ISSUE TITLE
[Bug Report]: 一键美化功能会连接错误

### ISSUE THREAD

**Issue by NorthWind17** [didi/LogicFlow#1884]
### 发生了什么？

在官网demo 脑图和一键美化、编排器中，如果在右侧的节点去连左边的节点，当执行一键美化时，连线错误，如图
![111](https://github.com/user-attachments/assets/c01e75e7-823b-4232-9adc-9feb1a4074cd)
![2222](https://github.com/user-attachments/assets/de679183-68d0-4fa7-aeaf-789f10ef65fe)

### logicflow/core版本

1.2.28

### logicflow/extension版本

1.2.28

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
这个应该是一键美化使用的 layout 包中重新计算线的路径时，节点的锚点位置获取错误导致的。

但这个包因为功能不完善，暂时不建议使用，建议参考代码自己实现自动美化算法
https://github.com/didi/LogicFlow/tree/v1.2.0/packages/layout   代码是这个
