### ISSUE TITLE
[Bug Report]: resize后画布大小没有重置，可能是什么原因？

### ISSUE THREAD

**Issue by williammyuan** [didi/LogicFlow#1889]
### 发生了什么？

如codesandbox所示，
https://codesandbox.io/p/sandbox/w8rp8x

执行了以上方法，发现画布大小不变，可能是什么原因？

### logicflow/core版本

2.0.4

### logicflow/extension版本

2.0.8

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
你的这个 codesandbox 项目权限有开放吗？我这边打开怎么说 Sandbox not found

**Comment by boyongjiong** [comment]
无法确认你遇到的问题，但我们最近解决了 resize 之后画布未更新的一个 bug，请更新最新版本使用
