### ISSUE TITLE
[Bug Report]: mvp案例-切换选中图形时，右侧的样式并没有跟着切换

### ISSUE THREAD

**Issue by ZMonet** [didi/LogicFlow#1897]
### 发生了什么？

mvp案例-在画布中点击某个图形或线设置了样式之后，再点击到另一个图形或线，右侧弹出的样式并没有跟着变化，需要先点一下空白处再点击目标图形才能实现切换，不方便快速修改各个图形或者线的样式，我本地换成logicflow 2.x版本，仍然有这个问题
![样式视图数据没有实时切换1](https://github.com/user-attachments/assets/dd13e9cb-47f3-48ba-b9e7-71806263705d)
![样式视图数据没有实时切换2](https://github.com/user-attachments/assets/a0793535-17bb-45ab-95c6-a01435cc9a31)

### logicflow/core版本

2.0.3

### logicflow/extension版本

2.0.6

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
MVP demo 项目的 bug 不在这里追踪哈，可以在对应的 GitHub 项目中提，也可以尝试自己处理
