### ISSUE TITLE
[Bug Report]: Vue 自定义节点 在@logicflow/vue-node-registry": "^1.0.7 版本中无法显示

### ISSUE THREAD

**Issue by yourcf** [didi/LogicFlow#1899]
### 发生了什么？
Vue 自定义节点
在以下版本中可以正常显示，
"@logicflow/core": "2.0.5",
"@logicflow/extension": "2.0.9",
"@logicflow/vue-node-registry": "1.0.6",
![af52f5bc51e5e0c2f8bda90cb6365308](https://github.com/user-attachments/assets/c26b7623-de2d-47f1-b23d-4c32c1478102)

但是在2.0.6版本中，无法显示
"@logicflow/core": "^2.0.6",
"@logicflow/extension": "^2.0.10",
 "@logicflow/vue-node-registry": "^1.0.7",
![37c977e5703e6386b872984be939e79a](https://github.com/user-attachments/assets/1d1aca1e-c19d-4b44-a550-3df762b3d9be)

### logicflow/core版本

2.0.6

### logicflow/extension版本

2.0.10

### 浏览器&环境

Microsoft Edge

**Comment by wbccb** [comment]
"@logicflow/vue-node-registry": "1.0.6"升级到"1.0.7"，强制加了一个flowId的传入，看看有没有报错信息或者提供一下demo @yourcf

**Comment by yourcf** [comment]
加了flowId后 已解决

**Comment by boyongjiong** [comment]
> "@logicflow/vue-node-registry": "1.0.6"升级到"1.0.7"，强制加了一个flowId的传入，可以看看有没有报错信息提示"没有传入`flowId`的`props`"，然后参考 [flowId的传入](https://github.com/didi/LogicFlow/blob/master/sites/docs/docs/tutorial/advanced/vue.zh.md) 传入flowId，如果传入了flowId还有问题的话，需要提供一下demo @yourcf , 我排查下

@wbccb 我忘了当时那个 PR 中文档有没有添加这个属性的说明，感觉我们应该在文档中加一下这个 props 的意义，

或者说如果不传，我们是否能生成一个默认的，不至于让它升版本后突然发现节点没了

**Comment by wbccb** [comment]
目前 [https://site.logic-flow.cn/tutorial/advanced/vue](https://site.logic-flow.cn/tutorial/advanced/vue)   就是一个例子而已，所以之前的pr就是在文档上的例子完善了下，没有加特别说明，这个我后面加一下flowId对应的说明

至于说是否设置为`required: false`，其实我之前有想过，要是不传的话，是不是要自己通过`document.querySelector("flow-id")`的模式去取对应的flowId，我的想法是：

------------------------

1.  界面上如果同时存在多个`LogicFlow`对象时，会不知道到底要取哪个，这样自动生成flowId就得思虑很多方面（如何正确取到你`new LogicFlow()`时想要映射到的`<TeleportContainer />`，因为如 [pull/1895](https://github.com/didi/LogicFlow/pull/1895) 所说，这两个东西其实可以写在不同的地方），可能会引入其他意想不到的问题

```
<div flow-id="A"></div>
<div flow-id="B"></div>
```

2. 如果设置为`可选不传`，那开发者绝大部分就不会传（因为大部分人只会稍微看下文档，不会细看），而flowId设置为必传+如果你不传=>会在开发阶段提示`props`缺失，在开发阶段就能解决这个问题，所以设置为可选不传的话，其实就等同于这个参数内部要好好处理，那就会回到第1点，得好好思考下生成flowId到底会产生什么影响...这就是将开发者的成本转移到维护者身上

3. 目前来说，`<TeleportContainer />`确实是有点心智负担，会不知道到底为什么要引入这个东西，而强制让用户传入flowId，可以让他们更加清楚就是跟`<TeleportContainer />`绑定，并且其实也只是增加一丢丢开发成本

4. 最主要我看了下`@logicflow/vue-node-registry`目前总体npm下载量的并不是很多，所以就算是`Break Change`，升版本确实有点问题，但是稍微答疑一下就行了，过了这个"1.0.6"升级到"1.0.7"的阶段就行，我觉得 稍微答疑的花费时间 <<<<<< 思考自动生成flowId要适配的逻辑所花费的时间+后续出问题要不断修复花费的成本 要少很多

我的想法是这样的 @boyongjiong
