### ISSUE TITLE
[Feature]: 希望能更改拖曳用的鼠标按键

### ISSUE THREAD

**Issue by EdwinOlders11** [didi/LogicFlow#1902]
### 背景&目的

希望能设置不仅仅只能用鼠标左键拖曳画布，让右键、中键甚至侧键也能用，在我的一个场景下，希望能用左键进行单个节点的拖动，中键进行节点的框选，同时用右键进行画布的拖动，结果发现既不能让框选与拖动同时启用，也不能更改拖动用的鼠标按键
目前还在研究能否自行实现，但难度感觉很大，希望制作组能看见...

**Comment by ChangeSuger** [comment]
> 希望能设置不仅仅只能用鼠标左键拖曳画布，让右键、中键甚至侧键也能用，在我的一个场景下，希望能用左键进行单个节点的拖动，中键进行节点的框选，同时用右键进行画布的拖动，结果发现既不能让框选与拖动同时启用，也不能更改拖动用的鼠标按键
目前还在研究能否自行实现，但难度感觉很大，希望制作组能看见...

这个其实不建议用右键、中键和侧键来做，右键一般会和菜单功能绑定，中键和侧键的话某些设备可能是不支持的，推荐还是把这些操作收敛到鼠标左键上，这个其实很多流程图产品都有类似的设计可以参考，比如：

- 正常情况下，使用鼠标左键进行选区，被框选的元素会被选中
- 鼠标左键点击被选中元素进行拖拽
- 按住空格键时，可以通过点击画布任意区域进行全局拖拽

以上这个的实现我写了个[示例](https://logicflow.hisoten.xyz/examples/01-cursor-enhance/)，大致上能满足框选、节点拖动、画布拖拽同时启用的需求，可以参考一下~

**Comment by boyongjiong** [comment]
可以参考 @ChangeSuger 的回答和实现，目前建议用户自定义实现，不会内置该功能，故先将此 issue 关闭处理
