### ISSUE TITLE
[Feature]: Label extension can be select and delete by action (like keypress or context menu)

### ISSUE THREAD

**Issue by irelance** [didi/LogicFlow#1909]
### 背景&目的

It just create there and can not find a nature way to remove, when I create multiple labels and after save!
Maybe show a line link between the labels and the node when node is select or overflow.

**Comment by DymoneLewis** [comment]
In the extension package v2.0.12, we support the ability to select the node and delete it by backspace
the contextmenu ability is in development
You can upgrade the version to try it
