### ISSUE TITLE
[Bug Report]: Label extension sometimes can't move

### ISSUE THREAD

**Issue by irelance** [didi/LogicFlow#1910]
### What happened?

The bug happened on your site too
https://site.logic-flow.cn/tutorial/extension/label
Sometimes double click the label will cause this problem

### Core Version

2.0.6

### Extension Version

2.0.10

### Engine Version

no

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

https://github.com/user-attachments/assets/8339457c-3a07-4d9d-8387-c890ec3683df

**Comment by irelance** [comment]
https://github.com/user-attachments/assets/8339457c-3a07-4d9d-8387-c890ec3683df

**Comment by DymoneLewis** [comment]
Hi😀, thank you for your feedback, at present the Label plugin does have some problems, we are optimizing, and it will be synchronized to you after the subsequent fixes.
