### ISSUE TITLE
[Bug Report]: 界面进行过缩放包括使用 lf.fitView() 后，拖动 DynamicGroup 后其内部的节点移动与 group 不同步

### ISSUE THREAD

**Issue by ZivvW** [didi/LogicFlow#1914]
### 发生了什么？

发生了什么：进行过缩放后，拖动 DynamicGroup 后其内部的节点移动与 group 不同步；

期望：group内的节点和group同步移动；

gif: ![chrome-capture-2024-10-17](https://github.com/user-attachments/assets/59e9239e-d185-4e5d-ae03-b4f68b0c13b4)

复现示例：在官网的[demo上](https://site.logic-flow.cn/tutorial/extension/dynamic-group) 点击放大/缩小，再把圆放到group里拖动group即可复现

经测试，使用 logicflow/extension 2.0.10 会出现这个问题，之前的版本是正常的

更新：一开始以为是 lf.fitView() 的问题，后续发现只要进行过缩放就会出现这个问题

### logicflow/core版本

2.0.6

### logicflow/extension版本

2.0.10

### 浏览器&环境

Chrome

**Comment by wbccb** [comment]
按照道理来讲，logicflow/extension 2.0.9应该也有问题才对，logicflow/extension 2.0.9没问题吗？

**Comment by ZivvW** [comment]
> 按照提交记录来看，logicflow/extension 2.0.9应该也有问题才对，logicflow/extension 2.0.9没问题吗？

嗯，我用下面的版本测试发现没这个问题

    "@logicflow/core": "^2.0.5",
    "@logicflow/extension": "^2.0.9",
