### ISSUE TITLE
[Bug Report]: DynamicGroup组件，折叠收起异常

### ISSUE THREAD

**Issue by lele4818** [didi/LogicFlow#1918]
### 发生了什么？

当DynamicGroup中有children时，分组默认是收起状态时（即isCollapsed为true），分组中的子项（下面数据中的rect_2）没有被收起。
lf.render({
  nodes: [
    {
      type: "dynamic-group",
      x: 400,
      y: 400,
      properties: {
        children: ["rect_2"],
        isCollapsed: true,
      }
    },
    {
      id: "rect_2",
      type: "circle",
      x: 400,
      y: 400,
    },
  ],
});

![a3f8a2c70a869d7d75d45d1bfb145cc](https://github.com/user-attachments/assets/dc3e99f5-e24a-4b99-a89f-cf132c6d2984)

### logicflow/core版本

2.0.6

### logicflow/extension版本

2.0.10

### 浏览器&环境

Chrome

**Comment by wbccb** [comment]
初始化状态为isCollapsed=true时，没有正确初始化折叠状态

**Comment by lele4818** [comment]
> 初始化状态为isCollapsed=true时，没有正确初始化折叠状态？

是的，DynamicGroup是被折叠起来了，但是里面的children没有被折叠起来
