### ISSUE TITLE
如何实现异步更新拖入的节点Id

### ISSUE THREAD

**Issue by wjyunn** [didi/LogicFlow#192]
想要生成自定义的唯一id：
  通过调用接口的方式，
  调用失败就不要节点出来（未成功）

目前实现方式：
  在注册节点处加入生成id接口
![image](https://user-images.githubusercontent.com/64448568/119434060-00961f00-bd4a-11eb-9b86-79405d14cfbb.png)

这里从节点拖拽到面板上会走两次上方的代码
![image](https://user-images.githubusercontent.com/64448568/119434159-2fac9080-bd4a-11eb-8f33-d39effb2fcf7.png)

如果我在error的地方进行return处理，节点依然能够出来

 希望有可以自定义id的地方，从文档里没有找到这个功能，生成节点到面板的逻辑也没有弄明白

**Comment by towersxu** [comment]
目前节点拖拽创建都是同步的，异步的体验不太好。手动拖入了节点，要等ajax拿到id后才能显示节点，中间会存在一段空白时间。

建议改成这种交互

1. 拖入的节点，设置节点为灰色，这个时候表示节点还没有完全加入。
2. 监听`node:dnd-add`事件，这个时候再发起ajax请求获取新的id.
3. ajax返回成功，则把刚拖入的节点删除，获取其坐标，在坐标位置用lf实例上的添加节点方法创建一个一样的节点。
4. ajax返回失败，直接把拖入的节点删除就好了。

拖拽添加到面板请参考文档[dnd-panel](http://logic-flow.org/guide/extension/component-dnd-panel.html)
