### ISSUE TITLE
[Bug Report]: 2.0版本打开内置缩放，导致经过边合并

### ISSUE THREAD

**Issue by 0131LWG** [didi/LogicFlow#1926]
### 发生了什么？

2.0版本打开内置缩放allowResize: true时。导致经过边和节点连接处出现合并边的情况

https://github.com/user-attachments/assets/eb24a0f1-9dfb-49b7-b761-14410fa2ab03

示例：https://codesandbox.io/p/devbox/xsl72v

这种情况只出现在lf.render时有数据的情况下并且allowResize设置为true

### logicflow/core版本

2.0.6

### logicflow/extension版本

2.0.10

### 浏览器&环境

Chrome

**Comment by ChangeSuger** [comment]
@boyongjiong ，导致以上问题的代码主要是这个：

https://github.com/didi/LogicFlow/blob/f74b47cf29a5c88b3706ab8faa1d3e6a5b724b3a/packages/core/src/view/Control.tsx#L59-L61

感觉这个逻辑确实多余了，除了导致以上问题外，还会导致 hover 状态下调整节点大小只能缩小不能放大：向内拉不会导致锚点消失，可以正常拖拽，向外拉时因为是按照网格间距触发缩放，网格间距大时鼠标会移出节点，hover 状态消失，然后触发组件卸载，触发 `cancelDrag` 直接取消拖拽。不过也有可能是出于这个原因设置的。

这个处理起来争议可能比较大，就不提 PR 了（我处理基本上就是直接删了这三行😂，实测可以解决以上提到的两个问题，但不确定会不会引入新的问题😥）。

**Comment by 0131LWG** [comment]
> @boyongjiong ，导致以上问题的代码主要是这个：
> 
> https://github.com/didi/LogicFlow/blob/f74b47cf29a5c88b3706ab8faa1d3e6a5b724b3a/packages/core/src/view/Control.tsx#L59-L61
> 
> 感觉这个逻辑确实多余了，除了导致以上问题外，还会导致 hover 状态下调整节点大小只能缩小不能放大：向内拉不会导致锚点消失，可以正常拖拽，向外拉时因为是按照网格间距触发缩放，网格间距大时鼠标会移出节点，hover 状态消失，然后触发组件卸载，触发 `cancelDrag` 直接取消拖拽。不过也有可能是出于这个原因设置的。
> 
> 这个处理起来争议可能比较大，就不提 PR 了（我处理基本上就是直接删了这三行😂，实测可以解决以上提到的两个问题，但不确定会不会引入新的问题😥）。

好的，谢谢，那我就先不使用allowResize来规避这个问题

**Comment by wbccb** [comment]
问题应该是下面代码触发的`onDragEnd()`导致的，更加具体点讲应该是`onDragEnd()`->`updateEdgePointByAnchors()`触发了两个`node`连线`edge`的anchor位置重新计算
```ts
 componentWillUnmount() { 
   this.dragHandler.cancelDrag() 
 } 
cancelDrag = () => {
  const DOC: any = window?.document

  DOC.removeEventListener('mousemove', this.handleMouseMove, false)
  DOC.removeEventListener('mouseup', this.handleMouseUp, false)
  this.onDragEnd({ event: undefined })
  this.isDragging = false
}
updateEdgePointByAnchors = () => {
    const { id, anchors } = this.nodeModel
    const edges = this.getNodeEdges(id)
    // 更新边
    edges.sourceEdges.forEach((item) => {
      const anchorItem = anchors.find(
        (anchor) => anchor.id === item.sourceAnchorId,
      )
      if (anchorItem) {
        item.updateStartPoint({
          x: anchorItem.x,
          y: anchorItem.y,
        })
      }
    })
    edges.targetEdges.forEach((item) => {
      const anchorItem = anchors.find(
        (anchor) => anchor.id === item.targetAnchorId,
      )
      if (anchorItem) {
        item.updateEndPoint({
          x: anchorItem.x,
          y: anchorItem.y,
        })
      }
    })
  }
```

目前有两个路径会触发`onDragEnd()`，一个是组件销毁时触发`onDragEnd()`，一个是拖拽时触发`onDragEnd()`，因此就算删掉下面的代码也无法解决问题，因为你拖拽了还是会导致anchor位置重新计算
```ts
 componentWillUnmount() { 
   this.dragHandler.cancelDrag() 
 } 
```

但是我没有深度研究具体原因是什么？初步看起来，应该是初始化`edge`时，没有传入连接点anchor的id，导致初始化后，实际的anchor坐标跟表现的anchor坐标不一致导致的，也就是
![1926](https://github.com/user-attachments/assets/4f65d5bd-45dd-49a5-9a13-4a8a865ae51b)


------------------------------------------------------------------------------------------------------------
而在`componentWillUnmount()`触发`this.dragHandler.cancelDrag() `并不多余，甚至非常有必要，这个代码主要涉及两个东西，一个是
- 请看[https://github.com/didi/LogicFlow/pull/1835](https://github.com/didi/LogicFlow/pull/1835)的`3.3.2 onDragging 没有销毁注册事件`小点，展示了为什么要添加这段代码的原因，因为有可能会导致滑动异常
- 因为组件可能销毁，但是如果你在销毁时没有触发`this.dragHandler.cancelDrag() `，那么就会发生内存泄露，因为在`drag.ts`中注册了事件监听器`mousemove`和`mouseup`，但是没有正确解绑，在 [https://github.com/didi/LogicFlow/issues/1581](https://github.com/didi/LogicFlow/issues/1581)就算切换为2.0，其实还是无法正常完全释放`LogicFlow`，其实在[#1581](https://github.com/didi/LogicFlow/issues/1581)中没有触发`drag.ts`中注册了事件监听器`mousemove`和`mouseup`的，但是还是无法释放，如果多了这个`drag.ts`的事件监听器`mousemove`和`mouseup`的内存泄露，更加无法释放内存

------------------------------------------------------------------------------------------------------------


而导致了`hover 状态下调整节点大小只能缩小不能放大`这个问题，我个人觉得这个问题应该是：
`根据网格调整位置`跟`hover`之间的冲突问题，而不是`componentWillUnmount()`触发`this.dragHandler.cancelDrag() `的问题，这段代码只是把这个问题显露出来而已，并不是导致`根据网格调整位置，网格间距大时鼠标会移出节点`跟`hover`之间的冲突问题的主要原因，当然`cancelDrag()`触发的内容，比如`cancelDrag()`方法是否不应该触发`this.onDragEnd({ event: undefined })`，这个有待商榷（这个方法也不是我写的=_=）
