### ISSUE TITLE
[Bug Report]: ipad端实际位置和node的位置不重合，偏离大

### ISSUE THREAD

**Issue by AIqcwh** [didi/LogicFlow#1927]
### 发生了什么？

![微信图片_20241022103801](https://github.com/user-attachments/assets/44f13298-1ba6-4cbf-8586-7edd8b4a34e7)

在pc端显示正常，在ipad显示出错，如图所示

### logicflow/core版本

2.0.5

### logicflow/extension版本

2.0.9

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
#1925 重复的 issue，关注这个即可
