### ISSUE TITLE
升级到2.0之后，ANCHOR_DRAGED在没有创建连线的情况下不会触发了

### ISSUE THREAD

**Issue by daydaychen** [didi/LogicFlow#1928]
> 这样做的话，行为与文档不一致啊
> 
> 
> 
> anchor:dragend | 锚点连线结束，不管是否创建连线都会触发。
> 
> 
> 
> 加上这个判断，在没有创建连线的情况下，ANCHOR_DRAGED事件就不会触发了。 

 _Originally posted by @daydaychen in [a68ebc8](https://github.com/didi/LogicFlow/commit/a68ebc8eb392a1c9896e43b2ffbca3d8575bb6c5#r148207291)_

**Comment by boyongjiong** [comment]
你说的很有道理，我处理一下
