### ISSUE TITLE
[Feature]: 为Line PolyLine 也添加getPath方法

### ISSUE THREAD

**Issue by wumail** [didi/LogicFlow#1929]
### 背景&目的

I tried to use logicflow to incorporate some brilliant featrues with custom line, but found that it was not easy to get the path of the line, I hope you can help me, thank you very much.  Love from china❤
something like:
<img width="266" alt="image" src="https://github.com/user-attachments/assets/ee9d8204-81e2-4547-aefd-c348b586b9d9">

**Comment by DymoneLewis** [comment]
Can't you join us to do this? Love from china too🤡
