### ISSUE TITLE
支持鼠标穿透节点

### ISSUE THREAD

**Issue by Mirrors406** [didi/LogicFlow#1930]
### 背景&目的

有一些节点是作为背景存在的（例如作为泳道存在），希望有属性设置，让鼠标能够穿透节点，移动画布

**Comment by EdwinOlders11** [comment]
你可以通过CSS选中对应节点的"g"父元素然后添加pointer-events: none;来实现这个效果
比如你的泳道节点有一个类名叫.lf_swimlanes，那么在你的css中添加
`.lf-node:has(.lf_swimlanes){
    pointer-events: none;
}`
就能实现鼠标穿透的效果，不过:has这个选择器要在比较新的浏览器版本中才支持（chrome/edge 105及以上）
我是这样处理的，希望能帮上忙

**Comment by Mirrors406** [comment]
> 你可以通过CSS选中对应节点的"g"父元素然后添加pointer-events: none;来实现这个效果
> 比如你的泳道节点有一个类名叫.lf_swimlanes，那么在你的css中添加
> `.lf-node:has(.lf_swimlanes){
>     pointer-events: none;
> }`
> 就能实现鼠标穿透的效果，不过:has这个选择器要在比较新的浏览器版本中才支持（chrome/edge 105及以上）
> 我是这样处理的，希望能帮上忙

有用，非常感谢

**Comment by Mirrors406** [comment]
> 你可以通过CSS选中对应节点的"g"父元素然后添加pointer-events: none;来实现这个效果
> 比如你的泳道节点有一个类名叫.lf_swimlanes，那么在你的css中添加
> `.lf-node:has(.lf_swimlanes){
>     pointer-events: none;
> }`
> 就能实现鼠标穿透的效果，不过:has这个选择器要在比较新的浏览器版本中才支持（chrome/edge 105及以上）
> 我是这样处理的，希望能帮上忙

https://github.com/didi/LogicFlow/issues/880 可以直接对 lf-node 添加同层类名，这样就不用 :has 了
