### ISSUE TITLE
[Bug Report]: 开启 allowResize: true，连接线发生重绘

### ISSUE THREAD

**Issue by zhm5921** [didi/LogicFlow#1934]
### 发生了什么？

初始化logflow实例，开启 allowResize: true，会导致目前发现的两个问题：
1、第一次拖动节点到页面，连接线位置改变，点击空白位置，连接线位置发生变化，之后不会；
2、鼠标移出节点后，连接线发生重绘，此时并非移动节点

目前解决办法：allowResize: false
但又另一个问题，有些节点是需要开启allowResize:true；在初始化logflow实例，一旦allowResize: false，即使自定义节点开启allowResize:true也不管用
[logicflow_demo.zip](https://github.com/user-attachments/files/17499835/logicflow_demo.zip)

### logicflow/core版本

2.0.6

### logicflow/extension版本

2.0.10

### logicflow/engine版本

0.1.1

**Comment by wbccb** [comment]
能够提供一个录制视频演示下流程？直接运行[logicflow_demo.zip](https://github.com/user-attachments/files/17499835/logicflow_demo.zip)项目，拖动节点和连线看不出什么问题

**Comment by zhm5921** [comment]
第一次拖动连接线后 点击了空白位置，连接线位置发生变化；
第二次拖动调整连接线后，鼠标移入节点，再移出节点，并没有拖动节点，连接线位置发生变化；
https://github.com/user-attachments/assets/2b0a3c12-cc27-4d3e-81e6-ae6feeee1fa9

**Comment by wbccb** [comment]
好的 我大概知道什么问题了，两个操作所触发的逻辑是一样的，应该也是组件销毁时触发了`this.drag.cancelDrag()`->`onDragEnd`，然后触发了两点之间的线的重新计算所导致的问题😓
