### ISSUE TITLE
[Feature]: 能否为logicflow提供一键美化的功能

### ISSUE THREAD

**Issue by Y-aong** [didi/LogicFlow#1935]
### 背景&目的

当我们使用流程图时，特别是节点比较多的时候，流程图的美化是很费时费力的，很多细节控对于流程图的美化是很在意的，如果调试这些细节会影响很多主体功能的实现。我认为比较好的一键美化应该包括
1、一键美化可以很好的整理流程图，不影响业务功能
2、流程图很多时，不要全部整理到一行，这样不方便查看，要根据当前画布的宽度进行换行
3、对于带有分支的流程图的美化，也要做到可以换行显示

**Comment by gismanli** [comment]
可以用 `@antv/layout` 自行处理下

**Comment by boyongjiong** [comment]
目前提供 https://hsole.github.io/layoutFlow/ 这个示例

代码： https://github.com/hsole/layoutFlow

如有实际的业务需求，建议可以调研 @antv/layout 各种布局算法，实现后也可以给我们 PR
