### ISSUE TITLE
[Bug Report]: 在移动端预览流程图发生的错误

### ISSUE THREAD

**Issue by Atleastyou** [didi/LogicFlow#1937]
### 发生了什么？

目前遇到的问题是：使用插件在基于vue2的H5移动项目中预览流程图的功能，基于目前不支持移动端的移动等手指功能，通过提供的Api,getSnapshotBase64方法把流程图转换成base64数据用图片的形式展示，期望完成展示整个流程图，结果是在安卓系统中能完整展示，而在IOS系统中会发生裁剪的效果，导致展示的图片显示不完成
安卓：
![JPG](https://github.com/user-attachments/assets/1c964073-6483-4d3d-85e1-57f12a59de34)
IOS：
![1](https://github.com/user-attachments/assets/12b5ed57-3050-47c7-93ba-6815b54d6e3c)

### logicflow/core版本

1.2.8

### logicflow/extension版本

1.2.8

**Comment by boyongjiong** [comment]
试试直接用移动端的 chrome 浏览器访问你们的页面有问题吗？

**Comment by Atleastyou** [comment]
> #1925 重复的 issue，关注该 issue 即可



> 试试直接用移动端的 chrome 浏览器访问你们的页面有问题吗？

在PC端用浏览器切换成mobile模式访问是没有问题的
