### ISSUE TITLE
需求：已经走过的流程，能够控制节点、边、节点文本、边文本高亮，支持修改颜色

### ISSUE THREAD

**Issue by aidening** [didi/LogicFlow#195]
1. 问题描述：
       在审批流程进行时，很多场景都会有需要知道当前节点在哪个位置，以及已经走过的节点需要 `高亮显示`，
       目前而言：logicflow 没有提供显式的方法使用

              对于节点和边的高亮，我可以 通过以下方式去设置：
              节点：
                         const nodeModel = lf.getNodeModel(nodeId);
                         nodeModel.updateAttributes({ stroke: 'red' });
               边：
                         const edge = lf.getEdgeModelById(edgeId);
                         edgeModel.updateAttributes({ stroke: 'red' });

               那么 nodeText & edgeText 呢，我查询源码，没有找到可以设置的方式，text 在 model 当中，是通过
                        data.text = {
                                value: 'xxx'
                                x: ...,
                                y: ...
                         }
             进行设置的，并没有可以设置颜色的属性。
             主题theme 有一个 nodeText 对象，这个可以根据 节点类型 设置 文本颜色，但是并不能满足 高亮 需求

2. 期望 & 实际的表现
         希望可以直接通过 lf 对象 设置文本、节点、边的颜色，logicflow 能够暴露出方法，例如

               lf.setNodeStyleById(nodeId, { stroke: 'red', text: { stroke: 'red' } });

               lf.setEdgeStyleById(edgeId, { stroke: 'red', text: { stroke: 'red'  });

**Comment by towersxu** [comment]
这个功能是支持的，稍后我们提供点示例。有两种情况：
1. 控制高亮的是持久化数据
    这种情况下，一般将控制高亮的字段放到proerties中，在自定义节点的时候，判断properties中是否存在这个字段，如果存在，就设置节点的fill为某种颜色。
```ts
const graphData = {
   nodes: [
      {
         id: '1',
         type: 'start',
         x: 100,
         y: 100,
         properties: {
            isActived: 1
         }
      }
   ]
}

class StartEventModel extends CircleNodeModel {
      setAttributes() {
        // 读取数据属性的 properties.color，并根据其值设置样式属性 stroke
        const { properties: { isActived } } = this;
        if (isActived) {
            this.fill = 'red'
        }
      }
}


```   
 
2. 控制高亮的是用户操作，不需要持久化存储。
    这种情况下需要通过lf去控制指定节点和连线的model. 设置其fill.

```ts
lf.getNodeModel(nodeId).updateAttributes({
   fill: 'red'
})
```

**Comment by aidening** [comment]
哈喽，您说的这个是节点的高亮或者填充，还有一种情况是节点文本，边文本的高亮发自我的华为手机-------- 原始邮件 --------发件人： xutao ***@***.***>日期： 2021年5月31日周一 晚上9:30收件人： didi/LogicFlow ***@***.***>抄送： Aiden Xiong ***@***.***>, Author ***@***.***>主    题： Re: [didi/LogicFlow] 需求：已经走过的流程，能够控制节点、边、节点文本、边文本高亮，支持修改颜色 (#195)

这个功能是支持的，稍后我们提供点示例。有两种情况：

控制高亮的是持久化数据

这种情况下，一般将控制高亮的字段放到proerties中，在自定义节点的时候，判断properties中是否存在这个字段，如果存在，就设置节点的fill为某种颜色。

const graphData = {

   nodes: [

      {

         id: '1',

         type: 'start',

         x: 100,

         y: 100,

         properties: {

            isActived: 1

         }

      }

   ]

}



class StartEventModel extends CircleNodeModel {

      setAttributes() {

        // 读取数据属性的 properties.color，并根据其值设置样式属性 stroke

        const { properties: { isActived } } = this;

        if (isActived) {

            this.fill = 'red'

        }

      }

}



控制高亮的是用户操作，不需要持久化存储。

这种情况下需要通过lf去控制指定节点和连线的model. 设置其fill.

lf.getNodeModel(nodeId).updateAttributes({

   fill: 'red'

})

**Comment by towersxu** [comment]
目前已支持基于properties自定义节点和连线文本样式。

```js
class SquareView extends RectNode {
  getTextStyle () {
    const style = super.getTextStyle()
    const {
      model: {
        properties = {},
      },
    } = this.props;
    if (properties.isUsed) {
      style.color = 'red'
    }
    return style
  }
}
```
