### ISSUE TITLE
[Bug Report]: 重新设置lf的options参数，使用render刷新画布，不生效。1.0版本可以

### ISSUE THREAD

**Issue by PandaX-Go** [didi/LogicFlow#1964]
### 发生了什么？

1. 先对lf参数赋值 lf!.options!.background = background
2. 执行画布刷新lf?.render(viewer.lf?.getGraphRawData())

修改的参数未生效。
![image](https://github.com/user-attachments/assets/37b45696-06a6-437c-9ce3-99750f8b89c4)

### logicflow/core版本

2.0

### logicflow/extension版本

2.0

**Comment by DymoneLewis** [comment]
已经开发完了，最早明天，最晚下周发个版修复

**Comment by DymoneLewis** [comment]
你好，在最新版本里支持动态修改background了，调用lf.graphModel.updateBackgroundOptions(backgroundOption)即可，写法可以参考源码demo：https://github.com/didi/LogicFlow/blob/master/examples/feature-examples/src/pages/background/index.tsx
