### ISSUE TITLE
按照官方快速上手教程使用失败，提示“Error: 请检查 container 参数是否有效”

### ISSUE THREAD

**Issue by hanchenxu-cxhan** [didi/LogicFlow#197]
![image](https://user-images.githubusercontent.com/65534690/120136821-9bd53b80-c205-11eb-99d4-df5827a25248.png)
![image](https://user-images.githubusercontent.com/65534690/120136704-53b61900-c205-11eb-9ff6-03af7ef1ab71.png)

**Comment by towersxu** [comment]
因为渲染LogicFlow的时候，container传入的节点还没有被渲染到dom上吧，你setTimeout延迟1秒渲染LogicFlow试试。

**Comment by KeyToLove** [comment]
可以试试在`componentDidMount`生命周期中初始化LogicFlow.
