### ISSUE TITLE
[Bug Report]: logicflow index.min.js中第1行第78870列报错[n is not a function]

### ISSUE THREAD

**Issue by 545340550** [didi/LogicFlow#1975]
### 发生了什么？

logicflow index.min.js中第1行第78870列报错[n is not a function]
![image](https://github.com/user-attachments/assets/25fec256-11d4-4230-8e6d-9212311d24b2)
大概是这段，打包后不清楚原代码在哪里

### logicflow/core版本

2.0.9

### logicflow/extension版本

null

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
请提供可复现 demo，这完全无法定位问题
