### ISSUE TITLE
[Feature]: 需要在polyline上添加一个加号按钮，能够创建节点，如钉钉一样的

### ISSUE THREAD

**Issue by luohaijun123** [didi/LogicFlow#1979]
### 背景&目的

1、怎么自定义polyline，文中只有line的例子。
2、在polyline上添加加号,类似钉钉流程
![2020051213250056](https://github.com/user-attachments/assets/c88bac6d-f892-4c28-a6a0-234eaeb8b87f)

**Comment by DymoneLewis** [comment]
🤔一会儿给你写个

**Comment by DymoneLewis** [comment]
发现现在 编排器 demo里有这样的逻辑，可以参考源码看下

**Comment by luohaijun123** [comment]
谢谢大佬
