### ISSUE TITLE
需求：元素ID生成规则配置化

### ISSUE THREAD

**Issue by huangzheyu** [didi/LogicFlow#199]
**问题描述**  
元素ID希望支持更多的配置方式（比如int型id），否则兼容旧数据需要在拖动元素，复制等情况等多个场景进行转化和绑定。

**Comment by towersxu** [comment]
目前要想改变id的格式，只有在自定义的时候，控制器生成。可以参考https://github.com/didi/LogicFlow/blob/bed5435f381e8146b1e8af8105de7aedb8b5b2f5/packages/extension/src/bpmn/tasks/ServiceTask.ts#L6-L10
