### ISSUE TITLE
[Bug Report]: 设置背景图片后，从新修改背景，删除背景图片，不生效背景还存在。

### ISSUE THREAD

**Issue by PandaX-Go** [didi/LogicFlow#1995]
### 发生了什么？

设置背景图片 生效
background = {
backgroundColor: "#ffffff",
backgroundImage: "url(img/bg-h/bg-h1.jpg)",
backgroundRepeat: "no-repeat",
backgroundSize: "cover",
}
取消背景图片
background = {
backgroundColor: "#ffffff",
}
画布上上一次设置的图片还在，无法消除
![image](https://github.com/user-attachments/assets/5c07d531-9d0f-4ab8-914d-853f67e72a5d)

### logicflow/core版本

2.0.9

### logicflow/extension版本

2.0.13

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
那更新背景是怎么更新的呢，用的updateBackgroundOptions方法吗还是别的？

**Comment by PandaX-Go** [comment]
使用的updateBackgroundOptions方法



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月10日 21:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [didi/LogicFlow] [Bug Report]: 设置背景图片后，从新修改背景，删除背景图片，不生效背景还存在。 (Issue #1995) |

那更新背景是怎么更新的呢，用的updateBackgroundOptions方法吗还是别的？

**Comment by DymoneLewis** [comment]
> 使用的updateBackgroundOptions方法
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年12月10日 21:07 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [didi/LogicFlow] [Bug Report]: 设置背景图片后，从新修改背景，删除背景图片，不生效背景还存在。 (Issue #1995) | 那更新背景是怎么更新的呢，用的updateBackgroundOptions方法吗还是别的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

了解，我看下

**Comment by ChangeSuger** [comment]
https://github.com/didi/LogicFlow/blob/e8bff34f2b880566173c7a91f099614d43e3a02c/packages/core/src/model/GraphModel.ts#L1501-L1515

`updateBackgroundOptions()` 方法是增量更新背景选项的，可以试一下以下方式来实现清除背景：

```js
// 设置背景图片 生效
background = {
  backgroundColor: "#ffffff",
  backgroundImage: "url(img/bg-h/bg-h1.jpg)",
  backgroundRepeat: "no-repeat",
  backgroundSize: "cover",
}

// 取消背景图片
background = {
  backgroundImage: "",
}
```

**Comment by PandaX-Go** [comment]
可以的
