### ISSUE TITLE
[Feature]: 在node节点，设置了input，删除input中的内容时，节点会被删除

### ISSUE THREAD

**Issue by hanChao-IsBigPenisBoy** [didi/LogicFlow#1999]
我的想法是，如果我自定义了其中的内容，能不能把节点的移动，删除，等一些系统的操作，放在头部进行， 在操作框架内置的鼠标事件，或者是键盘事件时，需要先点击头部，然后才能进行操作，这样就不会影响组件内部

[codesandbox 代码地址](https://codesandbox.io/p/devbox/misty-wind-z9zqvv)

![1733720855046](https://github.com/user-attachments/assets/d0dffac0-1c4c-4db6-b8f8-64c08f272be7)

**Comment by hanChao-IsBigPenisBoy** [comment]
我的想法是，如果我自定义了其中的内容，能不能把节点的移动，删除，等一些系统的操作，放在头部进行， 在操作框架内置的鼠标事件，或者是键盘事件时，需要先点击头部，然后才能进行操作，这样就不会影响组件内部
![1733720855046](https://github.com/user-attachments/assets/d0dffac0-1c4c-4db6-b8f8-64c08f272be7)

**Comment by EdwinOlders11** [comment]
你可以在input标签的 _onkeydown_ 事件里使用 _e.stopPropagation();_ 来阻止事件冒泡，这样就节点就不会收到键盘相关事件了，比如删除，但input元素本身没事
你好像用了VUE，那么就是在元素上添加 _v-on:keydown.stop_ 即可，其他的比如拖动等也是类似

**Comment by hanChao-IsBigPenisBoy** [comment]
> 你可以在<input />标签的 _onkeydown_ 事件里使用 _e.stopPropagation();_ 来阻止事件冒泡，这样就节点就不会收到键盘相关事件了，比如删除，但<input />元素本身没事 你好像用了VUE，那么就是在元素上添加 _v-on:keydown.stop_ 即可，其他的比如拖动等也是类似 希望能帮到你

如果我是使用了**Monaco Editor** 这种类型的组件，我是不是可以直接给外面的挂载的div，添加**v-on:keydown.stop** 也能处理这个问题，虽然我没有试过，不知道能不能行

**Comment by hanChao-IsBigPenisBoy** [comment]
> 你可以在<input />标签的 _onkeydown_ 事件里使用 _e.stopPropagation();_ 来阻止事件冒泡，这样就节点就不会收到键盘相关事件了，比如删除，但<input />元素本身没事 你好像用了VUE，那么就是在元素上添加 _v-on:keydown.stop_ 即可，其他的比如拖动等也是类似 希望能帮到你

我好像知道怎么弄了，感谢
