### ISSUE TITLE
文档：优化建议

### ISSUE THREAD

**Issue by sunyongjian** [didi/LogicFlow#2]
目前 LogicFlow 的文档和示例还是有不太完善的地方，大家可以把在使用过程中，遇到的类似 “想实现某个功能但没有相关文档” 的问题记录到该 issue 下，我们会专门对文档和示例做一次优化。
优化建议举例：
- 自定义节点的使用文档不易读，成本高，建议优化成怎么怎么样
- 想实现一个怎么样的常见功能，但是不知道该如何做，希望提供完整的代码示例，希望提供 react/vue 版本的示例
- 哪部分文档有缺失

**Comment by KangZaiLi** [comment]
1.示例 - 审批流程 这里希望提供完整的代码示例，希望提供 vue 版本的示例

**Comment by gongym12138** [comment]
http://logic-flow.org/guide/extension/extension-components.html#%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97

应该将
import '@logicflow/extension/lib/style.css';
改为
import '@logicflow/extension/lib/style/index.css'

另外自定义节点处文档读起来很迷茫，大概用了一个下午才创建出一个自定义节点来
希望可以提供由一个svg文件，快速生成注册节点方法的工具或者方法

**Comment by sunyongjian** [comment]
@gongym12138 收到。自定义节点的优化安排中
文档错误 你可以直接提 PR 哈哈

**Comment by Serendipity96** [comment]
文档 examples 不够清晰，比如：流程图左侧的 panel 使用什么组件生成的，在文档中未找到。

**Comment by Serendipity96** [comment]
期望有一个完整的 playground

**Comment by yhlchao** [comment]
文档的教程按照功能进行编写，现在是将原理、教程、API 掺杂在了一起

**Comment by yangmiao7** [comment]
自定义HTML节点如何修改插入内容文字？

**Comment by duansheli** [comment]
## 示例代码 差点意思

### 没启动成功 
感觉不友好  （主要写后端，前端属于 api boy ）
不能理解 为什么示例代码 需要在根目录执行命令 

Error: missing script: bootstrap

根目录下执行  npm run bootstrap
应该是指 examples  的上级目录 执行了 不行 
又在 examples 目录执行 还是有问题 

前面 npm xxx 后面又是 yarn start 
嗯，还得装个yarn。。。

寻思 这 examples 是和当前的源码有啥关联？？  
示例代码启动失败 很难受 

建议 
1. example 可以是 npm i  加 npm run start 就能启动的 
2. 能提供个docker 版么 ，调试啥的先不说，能先看看运行效果是啥样不
3. 能整个 vue 的版本么 

### 官网文档中 bpmn 的例子 太简陋
说是支持 bpmn 
节点类型太少 

网关分  排他 并行 事件 包容 
还有信号 事件 
任务： 用户任务 服务任务 邮件任务。。。
子流程、信号事件、边界事件。。。

**Comment by shuhuiyu** [comment]
1.希望增加一个官方的泳道配置
2.自己做了个假的节点泳道效果，但是节点的连线在底层，写了z-index的还是不行，有什么解决办法

**Comment by xiamengjun** [comment]
> 1.希望增加一个官方的泳道配置2.自己做了个假的节点泳道效果，但是节点的连线在底层，写了z-index的还是不行，有什么解决办法

你好，可否告知一下，基于现有功能，你是怎么实现这个假的泳道效果的？学习下

**Comment by finalreturn** [comment]
自定义的节点，循环不停的设置properties刷新，会不会内存泄漏？

**Comment by wxdproto** [comment]
默认的画布有点太大，自己设置样式效果也不好
