### ISSUE TITLE
[Feature]: edge支持无终点或无起点

### ISSUE THREAD

**Issue by abuexclusive** [didi/LogicFlow#2000]
### 背景&目的

在一些复杂的业务中，流程中可能只需要展示一部分，这类需求会产生单独出现一条线连接到显示在流程中的节点上即可，而另外一端则可以不显示，此类的应用比较常见，期待能够支持没有终点或起点的edge

**Comment by EdwinOlders11** [comment]
我有类似的需求，我现在的解决方法是用一个半径为0的圆形节点并附其一个不显示的锚点来当作连线，这样用户看不到也无法通过单击选中，缺点是如果用户使用框选时仍可被选中
希望可以帮到你

**Comment by boyongjiong** [comment]
#1011 与该 issue 重复，后续关注该 issue，本 issue 做关闭处理
