### ISSUE TITLE
[Bug Report]: 折线调整过边的位置后，重新渲染时，边的位置被重置成默认状态

### ISSUE THREAD

**Issue by ZivvW** [didi/LogicFlow#2001]
### 发生了什么？

折线调整过边的位置后，重新渲染时，边的位置被重置成默认状态。
如图：
![chrome-capture-2024-12-11](https://github.com/user-attachments/assets/692ac60b-c4f1-437a-af13-cf63f68154a5)

应该是在 [这个提交](https://github.com/didi/LogicFlow/commit/d3d45eff91799c5b8a3217c82a3f6cc3dac1bab6#diff-21fa640acdbfa2d7ffdfdcec755f8611ea83581675c30f518521e3928ac88310R49
) 里, 增加了在初始化的时候校验起点和终点在不在锚点上的逻辑导致的
另外这里`!isEqual(anchor, point)` 的判断可能也有问题，point 初始时不含 id，导致哪怕起点和终点的位置没有修改，只改了中间的点也会被重置。

### logicflow/core版本

2.0.9

### logicflow/extension版本

2.0.13

### 浏览器&环境

Chrome

**Comment by DymoneLewis** [comment]
提了pr，佬有空可以一起看看
https://github.com/didi/LogicFlow/pull/2006

**Comment by lanxiao-fang** [comment]
+1，保存了一份json数据后，拿来做初始化渲染并未按照预期位置渲染，而是默认。
