### ISSUE TITLE
[Bug Report]: grid网格在2.0.10版本下失效

### ISSUE THREAD

**Issue by EdwinOlders11** [didi/LogicFlow#2009]
### 发生了什么？

grid网格在通过cdn使用时2.0.10版本下失效，在2.0.9版本下正常
复现：https://codesandbox.io/p/sandbox/shvsw2

另外在我的项目中小地图组件也更新到2.0.10后位置错误，不显示，在2.0.9版本下正常，但没能在codesandbox中成功复现...还在找是哪里出的问题...QAQ

### logicflow/core版本

2.0.10

### logicflow/extension版本

2.0.14

### 浏览器&环境

Chrome, NodeJS

**Comment by ZivvW** [comment]
网格对齐没了吗？ 2.0.10 改成要用配置项开启了
new LogicFlow 的时候传入 snapGrid: true

**Comment by DymoneLewis** [comment]
如上所说，因为 2.0.10 版本里把网格对齐改成配置项了
在10版本的版本说明了也有，现在在补充文档，下周更新一下官网（心虚目移
https://github.com/didi/LogicFlow/releases/tag/%40logicflow%2Fcore%402.0.10
