### ISSUE TITLE
[Bug Report]: 渐进连线proximity-connect导致出现重复连线

### ISSUE THREAD

**Issue by githubxufeng** [didi/LogicFlow#2026]
### 发生了什么？

使用的官网渐进连线示例，拖拽连线后，会出现两条叠在一起的线，可以拖拽线拉开，就可以看出。

### logicflow/core版本

ex. 2.0.10

### logicflow/extension版本

ex. 2.0.14

### 浏览器&环境

Chrome

**Comment by AlanCai1307** [comment]
连线拖拽到目标节点就会出现重复线
![Image](https://github.com/user-attachments/assets/02625c20-5b5f-4498-bb52-c456bcfc276e)
