### ISSUE TITLE
[Bug report] 撤销重做不会派发事件

### ISSUE THREAD

**Issue by helloworldcyj** [didi/LogicFlow#203]
**问题描述**  
1. 问题触发的条件
开启键盘快捷键，使用快捷键撤销和重做，元素可能被删除或者添加，监听事件不会触发。
2. 期望的表现
触发监听事件
3. 实际的表现
不会触发

**最简复现demo**  

`useEffect(() => {
    const lf = new LogicFlow({
      container: document.querySelector('#graph') as HTMLElement,
      stopScrollGraph: true,
      stopZoomGraph: true,
      grid: {
        size: 10,
        type: 'mesh',
      },
      snapline: true,
      width: 700,
      height: 600,
      keyboard: {
        enabled: true
      },
    });
    lfRef.current = lf;
    lf.on('node:click', (eventObject) => {
      console.log('lalala node click: ', eventObject)
    });
    lf.on('node:delete', (eventObject) => {
      console.log('lalala node delete: ', eventObject)
    });
    lf.on('node:add', (eventObject) => {
      console.log('lalala node add: ', eventObject)
    });
    lf.on('blank:click', (eventObject) => {
      console.log('lalala blank click: ', eventObject)
    });
    lf.on('edge:add', (eventObject) => {
      console.log('lalala edge add: ', eventObject)
    });
    lf.on('edge:delete', (eventObject) => {
      console.log('lalala edge delete: ', eventObject)
    });
    lf.render();
  }, [])
`

**Comment by kaishuige** [comment]
配置i18n 多语言的时候 要刷新页面才会更新语言

**Comment by towersxu** [comment]
@kaishuige i18n需要自己监听语言切换后，自己重新渲染。
