### ISSUE TITLE
vue下如何创建自定义节点？我看都是recat的，没有vue的案例啊.

### ISSUE THREAD

**Issue by smarttang** [didi/LogicFlow#217]
**问题描述**  
我看文档http://logic-flow.org/guide/advance/customEdge.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%9E%E7%BA%BF%E7%9A%84-model
都是react的，没有vue的，这个咋用？

**环境信息描述**  
vue-element-admin

**最简复现demo**  
RT啊，不知如何引入？

**Comment by towersxu** [comment]
https://github.com/xinxin93/logicflow_vue_demo
