### ISSUE TITLE
全局nodeTextDraggable和节点文本draggable属性的问题

### ISSUE THREAD

**Issue by AK36** [didi/LogicFlow#220]
**问题描述**  

1、若nodeTextDraggable设置为true，则节点文本的draggable属性将无任何作用，因为
![image](https://user-images.githubusercontent.com/18526128/123601316-1e174680-d82a-11eb-9a28-4c5106e6f18a.png)

2、若nodeTextDraggable设置为false,则可通过节点文本的draggable属性控制节点文本的拖拽，但存在一个问题是：拖动文本的同时，节点也会跟着产生移动效果，并且不是同步移动

**Comment by towersxu** [comment]
@AK36 
第一点：确实有点问题，但是目前影响不大。一般只想要某种类型的节点文本可以拖动，可以考虑nodeTextDraggable采用默认值false, 然后去单独设置它可以拖动。没有必要去支持先将所有的节点设置为允许拖动，然后在去将某种节点设置为不可以拖动。
```js
class CustomModel extends PolygonNodeModel {
        setAttributes() {
          this.text.draggable = true
        }
      }
```

第二点我测试了一下，不会出现拖动文本的同事节点也会跟着移动。在本文拖动的部分，有判断如果是draggable为true, 会阻止事件冒泡。如果你那边能复现这种情况，能否提供一个可运行的demo ?

**Comment by AK36** [comment]
@towersxu 
下面是我遇到的问题，在自定义节点Model中覆盖setSelected，设置选中时才可以拖动文字就会出现我说的那种情况
如果初始就设置可拖动确实不会有问题
![image](https://user-images.githubusercontent.com/18526128/124563175-62ca5f80-de72-11eb-82ab-0bca46e9ce8f.png)

**Comment by AK36** [comment]
@towersxu  我的问题是默认节点文本都不可移动，只有当选中时才可移动，为的是避免移动节点时有时候鼠标光标时在文本上，导致移动的是节点文本，我的实现方式是在model中覆盖setSelected方法
![image](https://user-images.githubusercontent.com/18526128/124578934-3ff37780-de81-11eb-9037-7d06ed626926.png)

**Comment by towersxu** [comment]
但是不应该有第二点的问题啊，我这边测试第二点是没有问题的

**Comment by AK36** [comment]
@towersxu 你可以试试   初始nodeTextDraggable: false，节点文本draggable默认不可移动（我怀疑是因为文本draggable属性在初始化时只有为true才会进行一些操作，为false不会执行，后期再改为true的话缺少初始化时执行的一些操作导致）
![image](https://user-images.githubusercontent.com/18526128/124694494-f738ce80-df13-11eb-8b97-f8280a823195.png)
同时覆盖 setSelected  看能不能浮现
![image](https://user-images.githubusercontent.com/18526128/124694523-04ee5400-df14-11eb-9037-54f32ca6b259.png)

**Comment by AK36** [comment]
@towersxu 你不能浮现是因为你默认初始化时设置的节点文本draggable为true，而我是需要默认情况不可移动，选中时才可移动，所以我的初始化draggable为false
你的代码：
![image](https://user-images.githubusercontent.com/18526128/124695202-55b27c80-df15-11eb-8084-d167ceadca59.png)
我的代码：
![image](https://user-images.githubusercontent.com/18526128/124695223-5fd47b00-df15-11eb-8fb1-8f5271cd7a9a.png)

**Comment by towersxu** [comment]
这个一开始回复了，可以考虑nodeTextDraggable采用默认值false, 然后去单独设置它可以拖动。

默认true, 单独设置false目前不太好处理，因为draggable这个值的状态目前只有true or false, 没有undefined这种。
