### ISSUE TITLE
[开发环境能右键点击显示菜单]打包到测试环境右键点击没效果

### ISSUE THREAD

**Issue by YangsonHung** [didi/LogicFlow#230]
创建实例代码：
![image](https://user-images.githubusercontent.com/32238889/125712390-13f6fd28-45a5-45a9-a3ec-4abe0cc590bf.png)
![image](https://user-images.githubusercontent.com/32238889/125712430-e0728790-fe05-45e8-83b2-4a962d1f73de.png)

**Comment by towersxu** [comment]
能直接提供在线demo吗？你贴的代码和菜单无关。

另外确认一下开发环境是否有报错。

**Comment by YangsonHung** [comment]
https://codesandbox.io/s/process-sko2y?file=/src/App.js
这是在线代码，代码和项目的差不多。

项目中是这样创建的
```jsx
useEffect(() => {
        // 创建实例
        const lf = new LogicFlow({
            ...constructorConfig,
            container: document.querySelector(`#${containerID}`),
        });

        // 控制面板添加保存按钮
        Control.addItem({
            key: 'save',
            iconClass: 'si si-com_preservation',
            title: '保存',
            text: '保存',
            onClick: () => handleSaveClick(lf),
        });

        // 控制面板添加更新按钮
        Control.addItem({
            key: 'update',
            iconClass: 'si si-com_sync',
            title: '更新',
            text: '更新',
            onClick: handleUpdateClick,
        });

        // 控制面板添加复制按钮
        // Control.addItem({
        //     key: 'copy',
        //     iconClass: 'si si-com_copy2',
        //     title: '复制',
        //     text: '复制',
        //     onClick: () => {},
        // });

        // 添加节点点击事件监听
        lf.on('node:click', e => {
            console.log('当前节点 :>> ', e);
            onClickNode && onClickNode(e);
        });

        // 设置拖拽面板
        lf.setPatternItems(patternItemsConfig);
        lf.setMenuConfig({
            nodeMenu: [
                {
                    text: '删除',
                    callback(node) {
                        lf.deleteNode(node.id);
                    },
                },
            ],
            edgeMenu: [
                {
                    text: '删除',
                    callback(edge) {
                        lf.deleteEdge(edge.id);
                    },
                },
            ],
        });
        // 保存实例
        setLogicflow(lf);

        return () => {
            // 移除掉，防止切换tab时重复添加
            Control.removeItem('save');
            Control.removeItem('update');
            // Control.removeItem('copy');
        };
    }, []);

    useEffect(() => {
        setRenderData(Object.keys(graphData).length > 0 ? graphData : initGraphData);
    }, [graphData]);

    useEffect(() => {
        console.log('renderData :>> ', renderData);
        // 渲染数据
        logicflow && logicflow.render(Object.keys(renderData).length > 0 ? renderData : {});
    }, [logicflow, renderData]);
```

**Comment by towersxu** [comment]
如果是开发环境报错，测试环境没有报错，我猜测可能是打包的时候插件的方法被terser或者uglifyjs这些插件给压缩了。目前可以考虑打包的时候先不压缩这些插件，后续版本我们会考虑提供其他方案。
![image](https://user-images.githubusercontent.com/4093984/126097937-bc7af747-301d-4a7a-960f-8ef6156e4578.png)

https://segmentfault.com/a/1190000020484025

**Comment by YangsonHung** [comment]
是测试环境报错了，开发环境没问题

**Comment by towersxu** [comment]
嗯，我打错了，是测试环境报错，开发没有报错的情况。还是用上面的方法，将压缩忽略。
还有一种非常不推荐的方法，可以暂时先把extensions lib里面的文件，在index.html采用script标签方式引用，而不是import的方式，可以暂时跳过打包问题。

**Comment by YangsonHung** [comment]
我现在直接把Menu.js的ts转成js在index.html 里引入，注入全局。但是这样好麻烦，升级要换。项目里用的压缩是terser插件，由于一些原因，公司内部不给开配置。问下这个BUG什么时候修复？

**Comment by towersxu** [comment]
本月修复，会在1.0发布的时候统一修复

**Comment by fanqingxiang** [comment]
I didn't figure out the question. Any wrong with config like below:
`build: {
        chunkSizeWarningLimit: 2000,
        manify: 'terser',
        terserOptions: {
            compress: {
                defaults: false,
                keep_fnames: new RegExp("(DndPanel|Control|NodeResize|MiniMap|Snapshot)")
            },
            mangle: {
                keep_fnames: new RegExp("(DndPanel|Control|NodeResize|MiniMap|Snapshot)")
            }
        }
    },`
I rebuild the project and deploy it. Still I can't create an edge.

**Comment by xinxin93** [comment]
0.7.14之后这个问题已经解决
