### ISSUE TITLE
点击元素，弹窗Modal，每次visible设置为true，会自动将visible置为false，不明白为什么？

### ISSUE THREAD

**Issue by github16301147** [didi/LogicFlow#231]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
2. 期望的表现
3. 实际的表现

设置弹窗  visible 会自动置为false  导致弹窗一闪而过  或不弹出

**Comment by towersxu** [comment]
感觉不像是logicflow的问题，如确定有问题，请提供在线demo
