### ISSUE TITLE
[Bug report] 线条的双击事件难以触发

### ISSUE THREAD

**Issue by shifengshou2012** [didi/LogicFlow#232]
**问题描述**  
我的代码里，线条和节点都绑定了单击事件和双击事件，测试的过程中发现，线条的双击事件必须**非常快速**的点击才能触发，点击速度稍有迟缓，就会触发**两次单击事件**。与线条相比，节点的双击事件就很正常，与一般的操作体统的体验类似。

**环境信息描述**  
1. 系统类型(Windows)
2. 浏览器类型 （chrome87）
3. logicFlow @ 0.5.0

**Comment by towersxu** [comment]
一开始为了让双击不触发单击，所以加了个延迟判断。目前看起来还是直接使用浏览器自身的事件来区分单击还是双击较好。
