### ISSUE TITLE
希望点击连线的文本也能触发edge:click事件

### ISSUE THREAD

**Issue by meinaliao** [didi/LogicFlow#236]
因为如果在连线很短的情况下，连线可能会被文本覆盖很大一部分，这样会导致不容易选中连线（我想点击连线，但实际上点中了文本，导致没有触发edge:click事件）。用户反馈体验较差，希望点击文本的时候也能触发edge:click事件。
目前只有在点击连线的时候才会触发edge:click事件。

**Comment by towersxu** [comment]
你这种情况应该是文本允许被拖动的情况下出现，你可以关闭文本拖动。edgeTextDraggable
