### ISSUE TITLE
连线文本相对于连线的位置

### ISSUE THREAD

**Issue by meinaliao** [didi/LogicFlow#237]
能不能提供一个属性或者方法，能设置连线的文本默认放在连线的开始/居中/末尾位置

**Comment by towersxu** [comment]
已支持，可以通过重写getTextPosition方法来实现，记得要将属性customTextPosition设置为true. 参考示例https://github.hippor.com/#edge-text-position

**Comment by HanYuanShow** [comment]
![screenshot-1722309541397](https://github.com/user-attachments/assets/df4c24d9-1e22-48bb-9112-1fcfb40d0942)
我出现一个问题，按照demo来讲，不管移动1 ，2 节点，文本是固定不动的。相同的代码块，在我的工程中，在移动节点1 时候，文本位置是不动的。但是在移动下面的节点2的时候，文本会跟着 节点2 走，不管是x ,y轴，都会跟着走。  在触发一次连线的位置更新，文本位置又对了。 这是什么原因造成的，代码参考这个案例来的
