### ISSUE TITLE
连线文本位置计算问题

### ISSUE THREAD

**Issue by meinaliao** [didi/LogicFlow#239]
目前当拖动连线的时候，连线上的文本位置是会重新计算的。但是拖动节点的，连线的文本位置却不会自动重新计算。用户体验很差。

**Comment by xinxin93** [comment]
// 自定义边，实现文案在节点调整是动态调整逻辑修改为：连线文案在连线中最长线段的中间
class ConnectionModel extends PolylineEdgeModel {
  setAttributes() {
    this.customTextPosition = true; // 设置此属性，可以启动调整连线文案在连线中最长线段的中间
  }
}
 // 注册自定义连线
lf.register({
  type: 'connection',
  view: PolylineEdge,
  model: ConnectionModel,
})
// 设置默认连线为自定义连线
lf.setDefaultEdgeType('connection');

**Comment by LovermmM** [comment]
还没有解决吗？

**Comment by HanYuanShow** [comment]
![screenshot-1722309541397](https://github.com/user-attachments/assets/000151df-3f19-4c2b-b4d1-af7e5ddc93eb)
我出现一个问题，按照demo来讲，不管移动1 ，2 节点，文本是固定不动的。相同的代码块，在我的工程中，在移动节点1 时候，文本位置是不动的。但是在移动下面的节点2的时候，文本会跟着 节点2 走，不管是x ,y轴，都会跟着走，导致文本位置偏移了。 在触发一次连线的位置更新，文本位置又对了。 这是什么原因造成的，代码参考这个案例来的
