### ISSUE TITLE
边的起点可以从 由html节点内部元素开始吗？ 类似下图

### ISSUE THREAD

**Issue by ayershub** [didi/LogicFlow#250]
<img width="728" alt="ae068ab6db5fc55cfa3e2e1c225b25d" src="https://user-images.githubusercontent.com/13098077/127966320-0fae1299-8d75-49ee-8a2e-49125df2015d.png">

**Comment by towersxu** [comment]
可以的，你可以把锚点的位置设置到html内部即可，可以参考这个https://github.hippor.com/#html-card
