### ISSUE TITLE
节点文本颜色

### ISSUE THREAD

**Issue by apolloyyu** [didi/LogicFlow#251]
请问能不能自定义节点文本颜色，我看文档对于自定义节点只能修改fill和stoke，文本颜色字体大小只能在theme里面更改。

**Comment by apolloyyu** [comment]
实在不行，文本颜色按自定义的节点type来分类定制也行啊

**Comment by towersxu** [comment]
自定义节点view的时候，可以重写getTextStyle方法来重新设置自定义文本
