### ISSUE TITLE
使用SelectionSelect出现多次选框

### ISSUE THREAD

**Issue by xusong0621** [didi/LogicFlow#259]
**问题描述**  
1. 使用SelectionSelect后，打开this.logicFlow.openSelectionSelect() 选框功能出现多次选框，并且不消失
2. 打开this.logicFlow.openSelectionSelect()选框功能，右键功能失效。

**环境信息描述**  
![1051628243751_ pic_hd](https://user-images.githubusercontent.com/4715970/128495442-eb2f5b47-4ec2-48a1-b79a-b4a502459730.jpg)

本机信息：
1. mac pro
2. 浏览器类型 （chrome 版本 92.0.4515.107（正式版本） (x86_64)）

**Comment by towersxu** [comment]
请参考拖拽面板的选项，如果你没有关闭上一个选区，是可能出现多个选区的。
http://logic-flow.org/guide/extension/component-dnd-panel.html
