### ISSUE TITLE
[Bug report]自定义节点缩放部分，对节点缩放不生效，通过getAttributes获取到的宽高数值为NaN

### ISSUE THREAD

**Issue by harvest888** [didi/LogicFlow#260]
**问题描述**  
1.自定义节点缩放部分，对节点缩放不生效，通过getAttributes获取到的宽高数值为NaN
2.期望能够缩放且能拿到缩放值
![image](https://user-images.githubusercontent.com/76862107/128656112-adfab70c-0927-4448-85a5-e0cd37c1fb5d.png)

**环境信息描述**  
1. Windows
2. chrome93.0.4542.2
3. vue做的demo

**最简复现demo**  
demo：
1.拖选用户节点
![image](https://user-images.githubusercontent.com/76862107/128656498-3ce2cad5-82c1-49af-9295-c6aeed22ad18.png)
2.缩放后节点宽width,height,x,y为NaN
![image](https://user-images.githubusercontent.com/76862107/128656573-f37ace91-d166-42c6-a366-ecd651a9bfd8.png)
[fa-flow-design.zip](https://github.com/didi/LogicFlow/files/6951966/fa-flow-design.zip)

**Comment by GDUT-Rex** [comment]
你是不是设置了画布的宽度和长度为100%?

**Comment by harvest888** [comment]
> 你是不是设置了画布的宽度和长度为100%?

之前是将宽度和长度为100%，但是后面设置画布固定px后，还是同样的问题

**Comment by GDUT-Rex** [comment]
> > 你是不是设置了画布的宽度和长度为100%?
> 
> 之前是将宽度和长度为100%，但是后面设置画布固定px后，还是同样的问题

试试不设置数据看看，应该是初始化的时候，'px'和百分比进行数字运算会转换成NaN
