### ISSUE TITLE
[Bug report]The same observable object cannot appear twice in the same tree, trying to assign it to 'ROOT/text', but it already exists at 'edges/0/text'

### ISSUE THREAD

**Issue by cied68160** [didi/LogicFlow#263]
**问题描述**  
连线编辑文本是报错
The same observable object cannot appear twice in the same tree, trying to assign it to 'ROOT/text', but it already exists at 'edges/0/text'

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Windows)
2. 浏览器类型 （chrome91）

**最简复现demo**

**Comment by towersxu** [comment]
我没法复现这个问题，有在线示例吗？
