### ISSUE TITLE
[Bug report]画布关闭了文本编辑之后，双击连线的圆点会触发到文本编辑

### ISSUE THREAD

**Issue by GDUT-Rex** [didi/LogicFlow#264]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 设置`textEdit: false,`后，点击节点不会触发文本编辑，但是点击连线圆点会触发。
2. 期望的表现：点击连线圆点不会触发。
3. 实际的表现：点击连线圆点会触发。

![动画](https://user-images.githubusercontent.com/33365722/128806603-2892737a-8839-41f7-8967-fcaa0d5499f2.gif)

**最简复现demo**  
画布配置
```javascript
 new LogicFlow({
      container: document.querySelector('#container'),
      stopScrollGraph: true,
      stopZoomGraph: true,
      stopMoveGraph: true,
      textEdit: false,
      metaKeyMultipleSelected: false,
      grid: {
        type: 'dot',
        size: 20,
      },
      guards: {

      },
      keyboard: {
        enabled: true,
      },

    });
```

**Comment by towersxu** [comment]
由于 #9 新增了点击锚点，触发文本编辑。锚点的点击没有像节点一样被限制导致这个问题。修复办法是去掉锚点点击触发文本编辑。
