### ISSUE TITLE
火狐浏览器中不支持Snapshot导出图片、获取图片Base64编码[Bug report]

### ISSUE THREAD

**Issue by Jingney** [didi/LogicFlow#269]
**问题描述**  
1. 在火狐浏览器中，导出图片为空，getSnapshotBase64()返回乱码
2. 期望的表现：图片插件能够兼容火狐浏览器

**Comment by towersxu** [comment]
暂时只保证core包主要功能在各浏览器兼容，extension中的插件后续再保证各浏览器兼容性，目前你可以自己实现一个图片下载插件，也欢迎PR。

**Comment by towersxu** [comment]
此问题已在1.2.5版本中解决
