### ISSUE TITLE
有没有什么办法在拖拽到画板后， 先调用接口获取到Id， 再渲染节点？

### ISSUE THREAD

**Issue by ljmCoder** [didi/LogicFlow#272]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
拖拽的渲染钩子
2. 期望的表现
希望有拖拽前后的渲染钩子
3. 实际的表现
暂时没发现这样的钩子

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
2.windows
2. 浏览器类型 （chrome80 或者 IE11）
chrome 80

**最简复现demo**  
有没有什么办法在拖拽到画板后， 先调用接口获取到Id， 再渲染节点？

**Comment by ljmCoder** [comment]
或者有个什么其他的实现机制可以实现当前的功能效果？

**Comment by towersxu** [comment]
在一些业务场景下，期望新增的节点是去异步获取id。

不论我们提供的是在拖拽之前让你去后端获取id后再允许拖动节点进画布，还是拖动到节点进画布后，先不创建节点，而是等请求完成后再去创建节点，都会因为会打断用户的操作，导致体验不好。为了保证流程编辑的流程，logicflow内部都是提供的同步操作。

所以如果想要动态创建id, 我们需要换种思路。目前我想到的办法是：

监听node:add事件，然后再去发起请求，请求成功后，把触发这个事件的节点的id改掉。

但是需要注意的是，节点的id是不允许随便改的，因为可能有连线的sourceNodeId或者targetNodeId是节点的id. 如果直接改会出现问题。后续我们可以提供一个方法changeNodeId来允许修改id。目前你可以把这个节点删掉，然后重新创建一个一样的节点，创建的时候带上新的id.

或者把从后端拿到的id放到properties里面，把这个id看做是一个业务属性，把这个业务属性和图的id分离开。如果你们后端要求提交的数据格式，可以用adapter来处理。

**Comment by ljmCoder** [comment]
目前看来，此方案是可行的； 先删除，再增加一个一模一样的节点； 不过要是能提供，changeNodeId就更好了；

**Comment by towersxu** [comment]
http://logic-flow.org/api/logicFlowApi.html#changenodeid

**Comment by eyea** [comment]
> http://logic-flow.org/api/logicFlowApi.html#changenodeid

这个链接失效

**Comment by boyongjiong** [comment]
> > http://logic-flow.org/api/logicFlowApi.html#changenodeid
> 
> 这个链接失效

https://site.logic-flow.cn/docs/#/en/api/logicFlowApi?id=changenodeid 文档里搜一下就好啦
