### ISSUE TITLE
[Bug report]当有文本编辑时，再点击放大/缩小..功能时，文本编辑框就会出现错位的现场和一些我认为文档描述问题

### ISSUE THREAD

**Issue by zhuibo66** [didi/LogicFlow#274]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件：如图所示

![image](https://user-images.githubusercontent.com/69130137/129855369-0d5872a1-4cad-4027-81c5-fc9c79ddeccb.png)

2. 期望的表现：点击控制条的时候应该取消文本的编辑聚焦，同时我认为应该提供个方法，来取消编辑框的聚焦（目前我这边有个场景是这样的，就是双击节点的时候，在右侧出现属性面板，但是在打开面板的同时也触发了文本编辑，大概是这个需求），
3. 实际的表现：控制条放大/缩小按钮点击后，文本编辑框的位置不对

**关于文档的问题**

接触了LogicFlow好几天了，在读文档的过程中发现了，自我感觉这几处的描述不是很正确。

1、http://logic-flow.org/api/logicFlowApi.html#constructor
![image](https://user-images.githubusercontent.com/69130137/129856804-7e649a81-1319-42c6-88fa-76c45785c1a7.png)

这里我觉得描述应该，**允许按住meta键+鼠标点击进行多选元素**，但是同时发现了个问题，就是选中后放开meta键，也触发了meta键自己的功能（win系统下是弹出开始菜单），所以我觉得这个快捷键的功能是不是要换其他键来替代？

ps：关于meta键知识扫盲，如果使用的是windows，那么meta键表示的就是键盘上的win键（及键盘上有窗口图案的键），如果使用的是苹果电脑，meta键表示的是Cmd键（来源：https://zhidao.baidu.com/question/1881848553705566828.html）

2、http://logic-flow.org/api/baseEdgeModelApi.html  这块内容是空得

3、http://logic-flow.org/api/nodeApi.html#样式属性

![image](https://user-images.githubusercontent.com/69130137/129857950-6b462823-121b-4c72-bfee-37d0adb413fe.png)

我觉得这里的描述是不是这样：**属性取值内部已定义，即在LogicFlow实例化后的render方法中传入的data中声明的样式是没有作用的，如需要更改，可通过修改主题、自定义节点方式进行属性值的修改**

**Comment by towersxu** [comment]
文档错误欢迎PR，我们1.0版本的时候也会整体对问题进行升级。

**Comment by towersxu** [comment]
聚焦框的问题后面会修复，目前可以通过如下方法将节点的状态重置为非编辑状态。

```js
lf.graphModel.textEditElement?.setElementState(1)
```

**Comment by zhuibo66** [comment]
> 聚焦框的问题后面会修复，目前可以通过如下方法将节点的状态重置为非编辑状态。
> 
> ```js
> lf.graphModel.textEditElement?.setElementState(1)
> ```

哦吼，思路一致， lf.graphModel.setElementStateById(id,state)，
具体用法请查看：http://logic-flow.org/api/graphModelApi.html#setelementstatebyid

需要，注意的时，这两种用法，都是有个短暂取消聚焦的时间，所以用户体验上，你们懂得
