### ISSUE TITLE
如何检测polyline线的拖拽移动

### ISSUE THREAD

**Issue by ljmCoder** [didi/LogicFlow#275]
节点有拖拽移动监听事件，edge有移动事件吗，因为polyline不是可以移动得嘛，文档里面没有看到监听移动的事件。现在想做:线和节点移动，保存当前布局，有没有什么入口来做这个需求？

**Comment by ljmCoder** [comment]
我觉后期可以出一个线的拖拽api ， 就像节点一样有drag drop 之类的  ，  元素统一拥有同样的拖拽api  比较好， 希望能采纳！

**Comment by towersxu** [comment]
可以监听'edge:adjust'事件
