### ISSUE TITLE
Html节点使用vue组件$.mounted()，下载图片读不到vue组件配置的class样式

### ISSUE THREAD

**Issue by JokerYB** [didi/LogicFlow#278]
name: Html节点使用vue组件$.mounted()，下载图片读不到vue组件配置的class样式
about: 框架Bug反馈
title: "[Html节点使用vue组件$.mounted()，下载图片读不到vue组件配置的class样式]"
labels: ''
assignees: ''

问题描述
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：

问题触发的条件：自定义html节点
期望的表现： 下载正确的图片
实际的表现
![image](https://user-images.githubusercontent.com/89193201/130053476-63d23256-3379-42c6-b0c4-62937a44d438.png)
环境信息描述
至少包含以下部分：

Windows
浏览器类型 chrome
Vue 2
代码:
import { HtmlNode, HtmlNodeModel } from '@logicflow/core'
import GatewayNode from './../nodes/GatewayNode'
import Vue from 'vue'
const GatewayNodeClass = Vue.extend(GatewayNode)

export default function registerGateway(lf) {
lf.register(node.type, () => {
class Model extends HtmlNodeModel {
setAttributes() {
this.text.editable = false // 禁止节点文本编辑
// 设置节点宽高和锚点
const width = 70
const height = 70
this.width = width
this.height = height
this.anchorsOffset = [
[0, height / 2],
[0, -height / 2],
[width / 2, 0],
[-width / 2, 0]
]
}
constructor(data, graphModel) {
data.text = {
value: (data.text && data.text.value) || ''
}
super(data, graphModel)
}
}
class View extends HtmlNode {
shouldUpdate() {
const { properties: { nodeStatus }} = this.getAttributes()
if (this.currentNodeStatus) return false
this.currentNodeStatus = nodeStatus || 'dragging'
return true
}
// 重新setHtml方法，想html节点插入任何你想要插入的节点
setHtml(rootEl) {
if (!this.shouldUpdate()) return
const attributes = this.getAttributes()
const { properties } = attributes
const event = new GatewayNodeClass({
propsData: {
lf: lf,
properties,
nodeStatus: this.currentNodeStatus
}
}).$mount()
rootEl.appendChild(event.$el)
}
}

return {
  view: View,
  model: Model
}
})
}

<template>
<div class="gateway-view">
<div class="icon-view" :style="{ background: var(--theme-${node.theme}) }">
<svg-icon :icon-class="icon" class="icon" />
</div>
</div>
</template>

<style lang="scss" scoped> .gateway-view{ width: 100%; height: 100%; position: relative; display: flex; justify-content: center; align-items: center; .icon-view{ position: absolute; width: 70%; height: 70%; background: var(--theme-danger); border-radius: 5px; color: var(--theme-light); font-size: 30px; display: flex; justify-content: center; align-items: center; cursor: pointer; transform: rotate(45deg); *{ transform: rotate(-45deg); } } </style>

**Comment by towersxu** [comment]
参考 #421
