### ISSUE TITLE
[Bug report]自定义节点的锚点不能设置为空

### ISSUE THREAD

**Issue by cm971991** [didi/LogicFlow#286]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
基于https://github.hippor.com/#html-card 这个例子
自定义节点的model层的setAttributes函数中，锚点不能设置为空，this.anchorsOffset = null 或者 this.anchorsOffset = []，都会自动生成锚点
使用的场景是 默认生成一个没有锚点的节点，编辑节点弹窗去动态增加、减少锚点。
2. 期望的表现
this.anchorsOffset = [] 不生成锚点
3. 实际的表现
会生成默认锚点

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
Windows
2. 浏览器类型 （chrome80 或者 IE11）
chrome80 
**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
```js
 class HtmlCardModel extends HtmlNodeModel {
      setAttributes () {
        this.width = 300
        this.height = 140
        const { properties } = this
        if (properties.answers) {
          let preOffset = 20
          const sourceAnchor = properties.answers.map((answer) => {
            const text = answer.text
            const x = -150 + preOffset + (12 * text.length / 2) + 4
            preOffset += 12 * text.length + 10 + 12
            return { x: x, y: 60, id: answer.id }
          })
         this.anchorsOffset = []
        }
      }
```

**Comment by towersxu** [comment]
目前，想要自定义锚点为空，还是只有通过重写getAnchorsByOffset来实现。

```js
 class HtmlCardModel extends HtmlNodeModel {
       getAnchorsByOffset() {
           return []
        }
      }
```
