### ISSUE TITLE
双击连接线报错，页面卡死。

### ISSUE THREAD

**Issue by huailiangwu** [didi/LogicFlow#292]
[**问题描述**]
双击连接线报错，页面卡死。

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
2. 浏览器类型 （chrome80 或者 IE11）

**最简复现demo**  

<template>
	<div id="app">
		<div style="height: 100%">
			<div style="height: 100%">
				
				<div class="node-panel">
					<div
						class="node-item"
						@mousedown="methods.mouseDownHandle(item)"
						v-for="(item, index) in shapeList"
						:key="index"
					>
						<div class="node-item-icon" :class="item.class">
							<span class="node-label">{{ item.text }}</span>
						</div>
					</div>
				</div>
				
				<div id="graph" style="height: 100%"></div>
			</div>
		</div>
	</div>
</template>
<script>
	import { toRefs, reactive, onMounted } from "vue";
	import LogicFlow from "@logicflow/core";
	import "@logicflow/core/dist/style/index.css";
	export default {
		name: "App",
		components: {},
		setup() {
			onMounted(() => {
				methods.init();
				window.onkeydown = function () {
					let key = window.event.keyCode;
					if (key === 46) {
						methods.deleteNode();
					}
					console.log(key);
				};
			});

			const data = reactive({
				lf: null,
				logicFlowData: {
					nodes: {
						nodes: [
							{
								id: 50,
								type: "rect",
								x: 100,
								y: 150,
								text: "你好",
							},
							{
								id: 21,
								type: "circle",
								x: 300,
								y: 150,
							},
						],
						// 边
						edges: [
							{
								type: "polyline",
								sourceNodeId: 50,
								targetNodeId: 21,
							},
						],
					},
				},
				shapeList: [
					{ type: "rect", text: "矩形", class: "node-rect" },
					{ type: "diamond", text: "菱形", class: "node-diamond" },
					{ type: "circle", text: "圆形", class: "node-circle" },
					{ type: "ellipse", text: "椭圆", class: "node-ellipse" },
					{ type: "my-rect", text: "自定义", class: "node-rect" },
					// {type: 'chatBubble', text: 'chatBubble',class:'node-polygon'},
					// {type: 'text=1', text: 'text=1',class:'node-polygon'},
				],
				clickNodeId: "",
				clickEdgeId: "",
			});

			const methods = {
				init: () => {
					data.lf = new LogicFlow({
						container: document.querySelector("#graph"),
						stopScrollGraph: true,
						stopZoomGraph: true,
						width: 500,
						height: 500,
						grid: {
							type: "dot",
							size: 20,
						},
					});
					data.lf.render();
				},
				// 				/**
				// 				 * 拖拽
				// 				 * @param item 拖拽属性
				// 				 */
				mouseDownHandle: function (item) {
					//生成ID
					let id = new Date().getTime();
					console.log(item, id);
					data.lf.dnd.startDrag({
						id: id.toString(),
						type: item.type,
						text: item.text,
						properties: {},
					});
				},
			};

			return {
				...toRefs(data),
				methods,
			};
		},
	};
</script>

<style>
	.el-main {
		padding: 10px;
		margin: 0;
	}
	#app {
		height: 100%;
		margin: 0;
		padding: 0;
	}
	.node-panel {
		width: 70px;
		padding: 20px 0;
		background-color: white;
		box-shadow: 0 0 10px 1px rgb(228, 224, 219);
		border-radius: 6px;
		text-align: center;
		z-index: 101;
	}
	.node-item {
		margin-bottom: 20px;
	}
	.node-item-icon {
		width: 30px;
		height: 30px;
		margin-left: 20px;
		background-size: cover;
		text-align: center;
	}
	.node-label {
		font-size: 12px;
		margin-top: 5px;
		user-select: none;
	}
	.node-rect {
		width: 40px;
		height: 30px;
		border: 2px solid black;
	}
	.node-circle {
		width: 40px;
		height: 40px;
		border-radius: 50%;
		border: 2px solid black;
	}
	.node-ellipse {
		border: 2px solid black;
		border-radius: 60%;
		width: 40px;
		height: 30px;
	}
	.node-polygon {
		width: 40px;
		height: 40px;
		border: 2px solid black;
		transform: rotate(45deg);
	}
	.node-diamond {
		width: 40px;
		height: 40px;
		border: 2px solid black;
		transform: rotate(45deg);
	}
	/*css 设置*/
	.lf-menu-delete .lf-menu-item-icon {
		display: inline-block;
		width: 20px;
		height: 20px;
		background: url("./img/delete.jpg") no-repeat;
		background-size: 20px;
	}
</style>

>

**Comment by huailiangwu** [comment]
<div id="app">
		<div style="height: 100%">
			<div style="height: 100%">
				
				<div class="node-panel">
					<div
						class="node-item"
						@mousedown="methods.mouseDownHandle(item)"
						v-for="(item, index) in shapeList"
						:key="index"
					>
						<div class="node-item-icon" :class="item.class">
							<span class="node-label">{{ item.text }}</span>
						</div>
					</div>
				</div>
				
				<div id="graph" style="height: 100%"></div>
			</div>
		</div>
	</div>

**Comment by huailiangwu** [comment]
<div id="app">
		<div style="height: 100%">
			<div style="height: 100%">
				
				<div class="node-panel">
					<div
						class="node-item"
						@mousedown="methods.mouseDownHandle(item)"
						v-for="(item, index) in shapeList"
						:key="index"
					>
						<div class="node-item-icon" :class="item.class">
							<span class="node-label">{{ item.text }}</span>
						</div>
					</div>
				</div>
				
				<div id="graph" style="height: 100%"></div>
			</div>
		</div>
	</div>
</template>

**Comment by towersxu** [comment]
hello, 你这样贴我们不方便看，建议将最简单的示例项目放到你自己的github或者去[codeSandbox](https://codesandbox.io/)这类在线演示平台写示例。
