### ISSUE TITLE
[Bug report]动态修改内置节点的样式不生效，比如fill

### ISSUE THREAD

**Issue by Dave-SEO** [didi/LogicFlow#293]
```javascript
// 修改节点数据的参数
export type NodeAttribute = {
  id: string;
  type?: string;
  x?: number;
  y: number;
  text?: TextConfig;
  properties?: Record<string, unknown>;
};
lf.setNodeData(nodeData);
```

通过lf.setNodeData({id: 'xxx', properties: {fill:""}})无法修改，ts提示使用setProperties，但是setProperties也无法修改内置节点，
目前只能通过自定义节点的方式修改样式。
通过f12发现文档中渲染的矩形svg元素属性上有properties="[object Object]"可能是这个原因？

**Comment by towersxu** [comment]
不是这个原因。不生效可能是你自定义节点设置的样式问题，如果想要动态修改，需要在view中基于properties进行修改，不要在model中。

**Comment by Dave-SEO** [comment]
> 不是这个原因。不生效可能是你自定义节点设置的样式问题，如果想要动态修改，需要在视图中基于属性进行修改，不要在模型中。
我并不是要修改自定义节点的样式，是修改内置节点的样式，比如内置的矩形颜色，使用文档提供的setNodeData无法修改，必须要以自定义的方式进行修改，这样的话要多写代码，或者说有没有api可以直接修改内置节点的样式（内置节点指官方提供的矩形、菱形等）

**Comment by towersxu** [comment]
LogicFlow的核心是建立在自定义节点这个机制上的，我们不提供API去修改内置节点，是因为通过API修改的内容没有自定义属性去保存，这样修改了也没有意义。
