### ISSUE TITLE
 LogicFlow 是否支持 Vue、React 或者 Angular？

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#297]
LogicFlow是框架无关的，可以在任意前端框架中使用。目前我们提供了vue示例和react示例

vue示例地址

[https://github.com/xinxin93/logicflow_vue_demo](https://github.com/xinxin93/logicflow_vue_demo)

react示例地址

[https://github.com/didi/LogicFlow/tree/master/examples/src/pages/usage/bpmn](https://github.com/didi/LogicFlow/tree/master/examples/src/pages/usage/bpmn)

插件使用示例地址(原生js)

[https://github.com/didi/LogicFlow/tree/master/packages/extension/examples](https://github.com/didi/LogicFlow/tree/master/packages/extension/examples)

**Comment by hydra1983** [comment]
能提供 Angular Demo 吗？
