### ISSUE TITLE
[Bug report]右键编辑连接线报错，页面卡死

### ISSUE THREAD

**Issue by onemorecoconut** [didi/LogicFlow#301]
新建流程图时双击连接线或右键编辑时页面报错直接卡死
![image](https://user-images.githubusercontent.com/64244495/132180552-49b21871-984d-434f-93e9-2cf125317171.png)
但对已有的流程图进行编辑时却正常
![image](https://user-images.githubusercontent.com/64244495/132180846-6ad23ff5-5e0b-49bb-b293-893d3658a23b.png)

**Comment by towersxu** [comment]
请问有在线可运行示例吗？

**Comment by towersxu** [comment]
没有回应，从遇到的case看，有可能是在react hook里面用lf出现的问题，请保证页面lf只被初始化一次。
