### ISSUE TITLE
[Bug report]使用贝塞尔曲线作为边，当拖动节点时，贝塞尔曲线的位置被重置了

### ISSUE THREAD

**Issue by guozhenyi** [didi/LogicFlow#303]
**问题描述**  
使用贝塞尔曲线作为边连接两个节点，鼠标拖动修改贝塞尔曲线的控制点位置，然后移动任意节点的位置，贝塞尔曲线被重置了，变回了默认的路径。
但是稍微拖动一下控制点，发现控制点又跳回了之前设置的坐标位置。

**期望的表现**
贝塞尔曲线在节点拖动时，能正确绘制。

**实际的表现**
贝塞尔曲线被重置到了默认绘制路径。

在线demo:  https://codepen.io/guozhenyi/pen/abwBYdq

绘制两条贝塞尔曲线：
![111](https://user-images.githubusercontent.com/5993771/132278926-00e59b76-d497-48bf-8a06-1a95b891fbab.png)

拖动节点时，贝塞尔曲线被重置了：
![222](https://user-images.githubusercontent.com/5993771/132278949-96fe8a22-35ce-43bf-808f-eeba807641eb.png)

稍微拖动贝塞尔曲线的控制点，能发现其内部控制点坐标记录应该是正常的，但是绘制路径有问题：
![333](https://user-images.githubusercontent.com/5993771/132278961-e910c31d-483f-4a67-a050-179f89d5b062.png)

--End

**Comment by towersxu** [comment]
@guozhenyi 嗯，这个是一个问题，因为拖动节点后会重新计算这个节点的路径，导致两天线重复了。这里可以考虑贝塞尔曲线拖动的时候不重置两个控制点。欢迎PR，或者等几天我们的下个版本修复。

**Comment by guozhenyi** [comment]
@towersxu 我增加了一个PR，等待review哦。
