### ISSUE TITLE
[Bug report] MiniMap无法显示HTML节点

### ISSUE THREAD

**Issue by zengkaiz** [didi/LogicFlow#309]
**问题描述**  
MiniMap无法显示自定义的HTML节点，线和其他svg节点可以显示
![ff6ec49a01675c47fcdfb6a3903d097](https://user-images.githubusercontent.com/22042000/132812973-88704049-65d9-43e1-ac12-45d489e438c2.png)

**Comment by towersxu** [comment]
关于MiniMap使用时目前遇到2个问题（1、自定义节点在小地图上不显示；2、节点数据量比较大，占用画布范围比较广时，小地图定位偏差很大）
解决方案（仅供参考）
问题1：将__resetData返回的节点数据type转换为内置节点之一，并在__init中实例化LogicFlow加入自己想要的样式
问题2：小地图拖动时所参考的x轴与y轴的缩放比例不能只由__viewPortScale一个属性决定；修正缩放比例参数__viewPortScaleX， __viewPortScaleY，并在__setView中赋上对应的值，再到__drag中调整centerX 与 centerY 相应的缩放比例

**Comment by wangzhengbo** [comment]
也碰到这个需求了，自定义HTML节点在缩略图没法显示
