### ISSUE TITLE
[Bug report]在调整贝塞尔曲线的控制点时，连线文本没有跟随曲线移动位置

### ISSUE THREAD

**Issue by guozhenyi** [didi/LogicFlow#311]
**问题描述
使用贝塞尔曲线作为边连接两个节点，并且新建一条贝塞尔曲线。
当改变贝塞尔曲线的控制点位置时，连线上的文本没有跟随曲线的改变而移动位置。

**期望的表现
连线文本跟随贝塞尔曲线的路径改变而移动。

**实际的表现
连线文本没有跟随贝塞尔曲线的改变而移动位置，会导致文本离贝塞尔曲线很远。

在线demo: https://codepen.io/guozhenyi/pen/abwBYdq

新建一贝塞尔曲线并设置连线文本：
![c1](https://user-images.githubusercontent.com/5993771/133399573-39c2382d-6bb4-45b1-b94d-f29b2c855152.png)

移动贝塞尔曲线的控制点位置，连线文本没有跟随移动：
![c2](https://user-images.githubusercontent.com/5993771/133399625-f3333bbc-da0c-4a24-aeb7-2f3ecb433447.png)

移动贝塞尔另一个控制点位置，连线文本也没有跟随移动，并且连线文本距离贝塞尔曲线很远了：
![c3](https://user-images.githubusercontent.com/5993771/133399649-a8230a6e-5340-4d36-b2bb-e14ce21aca62.png)

--End

**Comment by towersxu** [comment]
嗯，看起来是有问题，能PR吗？我这边事情有点多，本月应该没时间去改了
