### ISSUE TITLE
需要支持泳道,泳池的流程图绘制组件

### ISSUE THREAD

**Issue by king200mb** [didi/LogicFlow#312]
需要支持泳道,泳池的流程图绘制组件,期望早日能支持.

**Comment by xiamengjun** [comment]
同问，这个有在规划中吗？

**Comment by relines** [comment]
同问。

**Comment by wumail** [comment]
简单版本
https://docs.logic-flow.cn/demo/dist/pool/
https://github.com/Logic-Flow/docs/tree/master/demo/pool
