### ISSUE TITLE
希望可以类似BPMN节点功能：两个节点可以粘连

### ISSUE THREAD

**Issue by aidening** [didi/LogicFlow#326]
**问题描述**  

1、希望可以实现两个节点可以粘连在一起的功能，类似bpmn的节点，可以给任务节点关联异常节点等等功能，详情参考附件 

2、演示动画
![需求动画](https://user-images.githubusercontent.com/45580373/136505097-4890f660-bf21-44b4-bb28-d797bcf99d15.gif)

**Comment by aidening** [comment]
如上面动画所示，两个节点直接，可以建立关联关系，可以把一个节点挂到另一个节点上

**Comment by towersxu** [comment]
这个可以支持，bpmn的边界事件。因为logicflow本身支持节点给移动的时候，添加规则使多个节点一起移动，所以边界事件可以用插件实现。稍后我补充一下示例。

**Comment by hsole** [comment]
我自己实现了一个，https://juejin.cn/post/7152716966115934222
