### ISSUE TITLE
编辑节点文本时 输入中文 最后输入的中文文本保存无效 会变成拼音

### ISSUE THREAD

**Issue by kilosangma** [didi/LogicFlow#336]
+ 编辑前
![1](https://user-images.githubusercontent.com/46205711/138018425-9808b653-4767-41e6-95de-8f74ec170b3f.png)
+ 双击编辑节点 使用拼音输入法
![2](https://user-images.githubusercontent.com/46205711/138018421-4aec524f-3734-448a-a0be-02dcdc003a1b.png)
+ 保存失败 变成了拼音
![3](https://user-images.githubusercontent.com/46205711/138018424-04de276d-9521-468e-aada-5190d1145547.png)

**Comment by towersxu** [comment]
没能复现这个问题，感觉像是输入法的问题，能提供更多信息吗？比如在线示例之类的

**Comment by kilosangma** [comment]
> 没能复现这个问题，感觉像是输入法的问题，能提供更多信息吗？比如在线示例之类的

好像是微软输入法的问题 用QQ拼音就没有这种问题 你可以用微软输入法试一下
