### ISSUE TITLE
The same observable object cannot appear twice in the same tree, trying to assign it to 'ROOT/text', but it already exists at 'edges/1/text'

### ISSUE THREAD

**Issue by 642315342** [didi/LogicFlow#342]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 如github代码所示 https://github.com/642315342/logic-flow-test
2. 在两个节点之前新建一条连线，可正常拖动该连线
3. 拖动连线无效，且报错 The same observable object cannot appear twice in the same tree, trying to assign it to 'ROOT/text', but it already exists at 'edges/1/text'

**最简复现demo**  
https://github.com/642315342/logic-flow-test
![image](https://user-images.githubusercontent.com/27815638/138425383-da5ada98-ffe8-4f33-bb9f-0c54636e339a.png)

**Comment by towersxu** [comment]
Resolved in https://github.com/didi/LogicFlow/issues/837
