### ISSUE TITLE
如何动态修改初始化的属性

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#348]
一般情况下，大多数初始化属性都是[editConfig](http://logic-flow.org/api/editConfigModelApi.html), 这个属性可以通过`lf. updateEditConfig`来实现动态修改。

还有一些不属于editConfig的属性，比如背景图这种。logicflow并没有提供直接动态修改的方法，因为没有想到应用场景。但是有一个迂回的方法，那就是重新设置options，然后强制触发画布的render。例如：

```ts
lf.options.background = {
  color: 'red'
}
lf.graphModel.transformMatrix.translate(1, 1)
```

**Comment by menghany** [comment]
1.X版本，此方法已经失效了，请问有可以替代的方案吗

**Comment by towersxu** [comment]
1.x有一些写法变了
上面的代码可以改成
```js
  lf.options.background = {
    backgroundColor: 'red'
  }
  lf.graphModel.transformModel.translate(1, 1)
```

**Comment by menghany** [comment]
> 
测试了一下，此方法貌似没有效果
https://codesandbox.io/s/0kfr3n

**Comment by towersxu** [comment]
非局部渲染模式下` lf.graphModel.transformModel.translate(1, 1)`已经无法触发view重新渲染了，采用重写render吧
https://codesandbox.io/s/logicflow-base25-forked-98s7i6?file=/step_25_customEdgeTextPosition/index.js:889-984

**Comment by menghany** [comment]
> 非局部渲染模式下` lf.graphModel.transformModel.translate(1, 1)`已经无法触发view重新渲染了，采用重写render吧 https://codesandbox.io/s/logicflow-base25-forked-98s7i6?file=/step_25_customEdgeTextPosition/index.js:889-984

Thx!
