### ISSUE TITLE
自定义html节点  写的图片节点  实现缩放

### ISSUE THREAD

**Issue by wyk123-cmk** [didi/LogicFlow#351]
方案一  节点是一张有自定义html节点绘制的图片   如何实现缩放
 this.lf.register(item.type, () => {
        class UmlModel extends HtmlNodeModel {
          setAttributes() {
            this.text.editable = false; // 禁止节点文本编辑 // 设置节点宽高和锚点
            const width = 100;
            const height = 100;
            this.width = width;
            this.height = height; // this.anchorsOffset = [ //   [width / 2, 0], //   [0, height / 2], //   [-width / 2, 0], //   [0, -height/2], // ]
          }
        }
        class UmlNode extends HtmlNode {
          imgAA() {
            alert("23432");
          }
          setHtml(rootEl) {
            const el = document.createElement("div");
            el.className = "uml-wrapper";
            const html = `
          <div>
            <div class="uml-body">
              <img  style="width:100%;height:100px;" src="${item.img}"/>
            </div>
          </div>
        `;
            el.innerHTML = html; // 需要先把之前渲染的子节点清除掉。
            rootEl.innerHTML = "";
            rootEl.appendChild(el);
          }
        }
        return {
          view: UmlNode,
          model: UmlModel,
        };
      });
     方案二  2.或者实现继承矩形  自定义节点  里面放svg图标  如何当矩形缩放时 图标也是相应的缩放  就是动态改变svg图的宽高
最后    要想实现图片节点的缩放   我是应该用方案一  还是方案2  更好实现呢
![dc13a8c475401a41eb799b5d87993dc](https://user-images.githubusercontent.com/67937752/139669854-4e7a715c-f11c-4463-b736-4794923ce4c9.png)

**Comment by towersxu** [comment]
已支持，请参考示例http://logic-flow.org/mvp/index.html
