### ISSUE TITLE
[Bug report]BPMN 节点缩放大小 + 文本自动换行出现报错

### ISSUE THREAD

**Issue by qiuguanyou** [didi/LogicFlow#352]
**用到的XML**  
`<bpmn:definitions id="Definitions_1hm04kd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance http://www.springmodules.org/schema/cache/springmodules-cache.xsd http://www.springmodules.org/schema/cache/springmodules-ehcache.xsd" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" targetNamespace="http://bpmn.io/schema/bpmn" exporter="bpmn-js (https://demo.bpmn.io)" exporterVersion="7.3.0"><bpmn:process id="Process_045dtvj" name="测试"><bpmn:documentation></bpmn:documentation><bpmn:userTask id="Activity_3ggi8cv" name="德哈卡德哈卡德哈卡德哈卡德哈卡德哈卡德哈卡德哈卡德哈卡德哈卡德哈卡德哈卡德哈卡"><nodeSize width="170" height="110"/></bpmn:userTask></bpmn:process><bpmndi:BPMNDiagram id="BPMNDiagram_1"><bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_045dtvj"><bpmndi:BPMNShape id="Activity_3ggi8cv_di" bpmnElement="Activity_3ggi8cv"><dc:Bounds x="225" y="160" width="100" height="80"/><bpmndi:BPMNLabel><dc:Bounds x="80" y="193" width="390" height="14"/></bpmndi:BPMNLabel></bpmndi:BPMNShape></bpmndi:BPMNPlane></bpmndi:BPMNDiagram></bpmn:definitions>`

**复现步骤**  
重新渲染 XML 后，再次拖拽缩放大小报错
![image](https://user-images.githubusercontent.com/24726904/139796004-d7185188-77d3-40d0-9bd4-d18436b7df51.png)

**Comment by towersxu** [comment]
请带上可运行的错误项目
