### ISSUE TITLE
[Bug report] 升级到0.7.3 ，node_modules 的代码不是最新的

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#357]
[Bug report] 升级到0.7.3 ，node_modules 的代码不是最新的，是删掉node_modules  ，在package.json中修改版本号，再npm install

**Comment by towersxu** [comment]
没明白是什么问题

**Comment by zoujpxyz2017** [comment]
edge:exchange-node 这个的修改，在npmjs上面发班了吗，我是说更新npm包后，这个事件没有回调
