### ISSUE TITLE
希望可以实现自定义节点（多边形）的缩放

### ISSUE THREAD

**Issue by wyk123-cmk** [didi/LogicFlow#362]
节点缩放  至自定义节点的使用    http://logic-flow.org/guide/extension/extension-node-resize.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E4%BD%BF%E7%94%A8
根据官方实例代码   无法实现矩形的缩放   示例代码不完整   没有体现 isSelected ? super.getControlGroup(this.getAttributes()) : "",  缩放的功能代码

希望可以实现想    三角形    五边形   的缩放

**Comment by towersxu** [comment]
多边形不支持直接缩放，但是可以参考http://logic-flow.org/mvp/index.html, 在矩形的基础上缩放。
