### ISSUE TITLE
希望可以能直接把画布缩放到想要的大小

### ISSUE THREAD

**Issue by liyang1345** [didi/LogicFlow#372]
可以提供一个方法，传入一个比例，直接缩小画布

**Comment by towersxu** [comment]
画布的缩放比例是logicflow内部的transformModel对象维护的。http://logic-flow.org/api/transformModelApi.html目前可以通过如下方法来控制。
```js
  lf.graphModel.transformMatrix.SCALE_X  = 0.6
  lf.graphModel.transformMatrix.SCALE_Y = 0.6
```

下个版本会扩展zoom方法，支持直接使用`lf.zoom(0.6)`
