### ISSUE TITLE
几个优化建议

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#374]
1、希望能够实现自动布局功能
2、希望可以触发节点选中，类似trigger("click")
3、希望能够实现框选的右键菜单
4、可以复制分支，或是框选后的节点和边

**Comment by zoujpxyz2017** [comment]
5、自定义撤销，重做功能

**Comment by towersxu** [comment]
1. 自动布局你可以试试d3-hierarchy
2. 有lf.select方法
3. 支持，缺少文档，你可以看看示例或者extension的源码，文档最近会全新重构
4. 支持，同三
5. 目前history缺少有不完善的地方问题，你可以关闭了。自己用自定义插件实现。
