### ISSUE TITLE
静默的时候会出现选中的状态，如何去除

### ISSUE THREAD

**Issue by lhs20210205** [didi/LogicFlow#377]
![1637224088(1)](https://user-images.githubusercontent.com/78574254/142379554-50a30713-a096-4f3a-b96b-6bf2d587b15b.jpg)

**Comment by towersxu** [comment]
静默模式是多个编辑状态的集合，但是可以被再次传入其它控制画布编辑的配置覆盖。

如下示例，虽然静默模式会隐藏锚点，但是如果config中传入了hideAnchors:false, 那么还是会显示锚点。
```js
  const lf = new LogicFlow({
    container: document.querySelector('#app'),
    hideAnchors: false,
    isSilentMode: true,
})
```
