### ISSUE TITLE
通过getGraphData()获取到绘图流程数据，有没有方法修改？

### ISSUE THREAD

**Issue by kanglixia** [didi/LogicFlow#379]
**问题描述**  
1、通过getGraphData()获取到绘图流程数据；
2、编辑数据
**3、根据编辑后的数据怎么更新流程图？有没有什么方法？**

![image](https://user-images.githubusercontent.com/34027633/142606527-745505c8-9678-4b7c-869f-c19cf1e76822.png)

**Comment by towersxu** [comment]
重新render就行，另外，如果只是修改单个节点，不用把整个图数据拿出来。可以看看logicflow官方文档和示例
