### ISSUE TITLE
xml模式无法给标签添加文本内容，只能添加子标签或者属性

### ISSUE THREAD

**Issue by LIUSHUAI2018** [didi/LogicFlow#383]
![image](https://user-images.githubusercontent.com/37928107/142763923-7041df0e-beb3-46a7-a321-e94c25f9cdca.png)
这个里面显示所有的属性只要不是对象，都会被加上-，但是
![image](https://user-images.githubusercontent.com/37928107/142764001-f538ec5b-34b9-487e-8c8f-a1c197c054d6.png)
这个解析时会将首字母为-的渲染为属性，这样就会存在一个漏洞无法出现内容为文本标签，例如<a>111</a>

**Comment by towersxu** [comment]
我们不会差异化处理，如果你觉得text需要特殊处理，可以提供一下相关的规范。如果只是你们自己项目的特殊需求，这个可能需要你们自己实现一个xml adapter就好了。
