### ISSUE TITLE
注册 BpmnAdapter 后无法渲染初始数据

### ISSUE THREAD

**Issue by wghglory** [didi/LogicFlow#393]
**问题描述**  
http://logic-flow.org/examples/#/extension/adapter 官网代码在本地测试，  注册 LogicFlow.use(BpmnAdapter); 后无法渲染初始数据。删除它才能渲染初始数据。

**最简复现demo** ：代码来源官网examples extension/adapter/index.tsx 
```ts
const data = {
  nodes: [
    {
      id: 10,
      type: 'rect',
      x: 150,
      y: 70,
      text: '矩形',
    },
  ],
};

let lf: LogicFlow;

export default function AdapterExample() {
  useEffect(() => {
    LogicFlow.use(BpmnAdapter); // 删掉这个才能显示

    lf = new LogicFlow({
      container: document.querySelector('#graph') as HTMLElement,
      stopScrollGraph: true,
      stopZoomGraph: true,
    });

    lf.render(data);
  }, []);

  return (
    <>
      <div id="graph" className="viewport"></div>
    </>
  );
}
```

**Comment by towersxu** [comment]
因为adapter的用处就是数据格式转换的，用的adapter，就必须使用adapter支持的这种数据格式了。BpmnAdapter需要你用bpmn格式的数据进行渲染

**Comment by wghglory** [comment]
> 因为adapter的用处就是数据格式转换的，用的adapter，就必须使用adapter支持的这种数据格式了。BpmnAdapter需要你用bpmn格式的数据进行渲染

我用了 bpmn xml 格式数据传进去，bpmnXmlAdapter 也无法正常加载。有demo渲染bpmn xml嘛？

**Comment by towersxu** [comment]
bpmnAdapter目前只兼容了bpmnElement这些元素，其它元素还不支持。建议参考bpmnAdapter编写你们自己项目的adapter

**Comment by yangyingnan** [comment]
解决了吗？我也遇到这个我问题了

**Comment by luohaijun123** [comment]
如何把这个初始的数据转换成bpmn格式的数据？

**Comment by luohaijun123** [comment]
踩了一天的坑，我来回答这个问题。只需要使用lf.renderRawData(data)就可以实现。
