### ISSUE TITLE
自定义拖拽面板内容怎么实现动态更新lf.setPatternItems

### ISSUE THREAD

**Issue by xiamengjun** [didi/LogicFlow#397]
lf.setPatternItems需要在lf.render(data)之前执行，但是目前我想实现在页面已经渲染之后，通过页面的某些过滤条件能够动态改变左边的拖拽面板的节点内容，但是发现再次调用lf.setPatternItems无效，请问目前有方案可实现吗？

**Comment by towersxu** [comment]
代码已修复，预计11月底发版

**Comment by pubdreamcc** [comment]
还需要多久呀，这边有个需求要用

**Comment by towersxu** [comment]
试试最新版本
