### ISSUE TITLE
如何修改节点的x,y坐标对应图形的位置，如圆形节点目前是对应在中心，我想修改到左边垂直居中的位置

### ISSUE THREAD

**Issue by xujunweb** [didi/LogicFlow#399]
**问题描述**  
我尝试了使用自定义节点继承基础Model后，在constructor里面直接修改this.x的值，但是这样会导致每次渲染都会往右偏一次。

**Comment by towersxu** [comment]
model中我们要求x,y必须表示节点的中心点。但是你可以再view中，渲染的时候，将渲染的图形基于你自己的需求进行偏移

**Comment by xujunweb** [comment]
> model中我们要求x,y必须表示节点的中心点。但是你可以再view中，渲染的时候，将渲染的图形基于你自己的需求进行偏移

我尝试过这个方法了，渲染的图形是可以偏移，但是选中的hover效果和连线的有效区域没办法跟着偏移
