### ISSUE TITLE
node事件当中使用undo事件，之后拖动节点坐标不会一直随节点变化而变化。

### ISSUE THREAD

**Issue by wakanuli** [didi/LogicFlow#401]
触发条件：
        将节点拖拽出自己定义的边界之外，执行undo事件或者手动控制按钮“上一步”，再拖动节点，节点的坐标保留拖出边界后的位置一直不变。

```
this.lf.on('node:drop', ({data}) => 
     if(data.x < 20) {
          this.lf.undo()
      }
)
```

**Comment by towersxu** [comment]
如果想要定义节点的边界，建议使用最新api [`lf.graphModel.addNodeMoveRules()`](http://logic-flow.org/api/graphModelApi.html#addnodemoverules)
