### ISSUE TITLE
边的动画可以实现吗， 就是边的流动效果那种类似的动画。

### ISSUE THREAD

**Issue by zheng1249938304** [didi/LogicFlow#403]
边的动画可以实现吗， 就是边的流动效果那种类似的动画。

**Comment by relines** [comment]
+1

**Comment by fun3c** [comment]
+1

**Comment by flxy1028** [comment]
应该可以通过自定义节点可以实现

**Comment by towersxu** [comment]
这个功能目前已支持，请参考http://logic-flow.org/guide/basic/edge.html#%E7%BB%99%E8%BE%B9%E5%BC%80%E5%90%AF%E5%8A%A8%E7%94%BB
