### ISSUE TITLE
关于锚点连线的问题

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#407]
目前可以设置手动修改连线，是否可以限制连线只能是从锚点为进线或出线，现在修改连线，进线或出线，有可能不是在锚点上的

**Comment by atmfans** [comment]
控制锚点进出线可以尝试设置连线时的校验规则
![image](https://user-images.githubusercontent.com/10792454/146352349-af1052ab-a6b5-4e81-81ba-3a2951586ec7.png)

**Comment by towersxu** [comment]
请参考自定义锚点示例，在1.1.3版本已支持控制是否允许锚点创建连线。
