### ISSUE TITLE
没有生成对应的xml

### ISSUE THREAD

**Issue by shindouhiro** [didi/LogicFlow#408]
**问题描述**  
没有生成对应的xml

**最简复现demo**  

![image](https://user-images.githubusercontent.com/8401237/144845470-af63c756-9ac8-4ef5-a5a5-5ae75d48f753.png)

![image](https://user-images.githubusercontent.com/8401237/144845094-c27a3969-1afe-4d62-85dd-2ed65f855d97.png)

**Comment by towersxu** [comment]
你的意思是应该这样？
```xml
<children girl="shiori">
  <boy>Yusuke</boy>
  <boy>Kairi</boy>
</children>
```

**Comment by shindouhiro** [comment]
是的
