### ISSUE TITLE
自定义锚点位置问题

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#410]
通过设置锚点位置
![image](https://user-images.githubusercontent.com/28721603/144954173-13261c23-fca1-48ad-80c9-d10136792231.png)
锚点会显示在左右两侧，不会压在线上，但是当拖拽线的时候，线会消失，实际上线还存在。

**Comment by towersxu** [comment]
没明白是什么问题，请详细描述一下？

**Comment by zoujpxyz2017** [comment]
ok
![image](https://user-images.githubusercontent.com/28721603/144993660-f7e3b603-6013-4e14-884b-7a9ed7713dcb.png)
这个是锚点偏移了的效果，
![image](https://user-images.githubusercontent.com/28721603/144993791-e093a173-2f76-4bbc-bb4a-ed02ec239fc2.png)
这是我拖动连线后的效果，连线没显示出来，实际是存在的 如下图：
![image](https://user-images.githubusercontent.com/28721603/144994030-8e050776-5c2c-4a8a-9b07-4ec97922aa8d.png)

**Comment by zoujpxyz2017** [comment]
![image](https://user-images.githubusercontent.com/28721603/144994466-a3dcc954-2547-45d5-ad5a-81b4b21a5ba7.png)

**Comment by zoujpxyz2017** [comment]
锚点不位移也有这种情况，因为只有水平上的锚点，当拖拽线在垂直锚点上，就会出现undefined的情况

**Comment by towersxu** [comment]
我这边没有复现这个问题，有在线示例吗？
