### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by Dollbug** [didi/LogicFlow#419]
**问题描述**  
![image](https://user-images.githubusercontent.com/25731736/145963947-7a37417a-2e17-467d-a361-e0fd35504ce7.png)

目前支持节点文案自适应么？特定需求场景下，节点文案长度不固定，需要实现根据节点文案的长度，来动态设置节点width

**Comment by towersxu** [comment]
这个功能logicflow不打算内置，你可以自己定义一个插件来实现，我们是可以动态修改节点的宽高的，请参考源码中的node-resize
