### ISSUE TITLE
【需求】使用直线模式时使连线终点箭头始终在节点的边缘

### ISSUE THREAD

**Issue by baozoulolw** [didi/LogicFlow#423]
使连线的锚点始终在节点的中心，但是箭头可以一直在节点边缘
类似效果 ：https://codesandbox.io/s/qosj0

**Comment by wumail** [comment]
通过重写边的Model中的updateStartpoint和updateEndPoint方法，其中startPoint不变，endPoint通过自行计算两节点中心连线与目标节点shape（或者包围盒border）的交点获得
