### ISSUE TITLE
isAllowConnectedAsSource使用

### ISSUE THREAD

**Issue by wakanuli** [didi/LogicFlow#424]
isAllowConnectedAsSource使用时，内部无法使用lf.getNodeEdges()

**Comment by GDUT-Rex** [comment]
> isAllowConnectedAsSource使用时，内部无法使用lf.getNodeEdges()

sourceNode上有graphModel可以调用getNodeEdges，应该能够满足大部分场景
![image](https://user-images.githubusercontent.com/33365722/146867799-ff701039-62b6-4abc-9941-3cb44ca76359.png)
