### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by Dollbug** [didi/LogicFlow#425]
自定义节点规则的validate函数，可否返回第三个参数，graphData，有些场景需要图的所有数据，比如判断当前流程图是否成环，成环不允许连接
![image](https://user-images.githubusercontent.com/25731736/146861155-748e2bd5-9cba-450d-9245-4293130c0330.png)

**Comment by GDUT-Rex** [comment]
有source和target的节点信息，可以通过它们去获取对应的连接线的数据，通过这些也可以判断出是否成环

**Comment by Dollbug** [comment]
> 有source和target的节点信息，可以通过它们去获取对应的连接线的数据，通过这些也可以判断出是否成环

只有两个节点的数据，判断不了吧

**Comment by GDUT-Rex** [comment]
> 通过节点ID去获取节点上的线的数据，有API可以去获取

**Comment by GDUT-Rex** [comment]
这里第三个参数应该传入当前logiflow实例会比较合适，这里可以用全局注入一个全局变量去调用对应的API 应该能够满足你的需求，我这边是保存的时候去校验而不是连线的时候去校验，你参考下吧

**Comment by towersxu** [comment]
> > 通过节点ID去获取节点上的线的数据，有API可以去获取，节点上有graphModel的实例可以调用获取其它数据
> > ![image](https://user-images.githubusercontent.com/33365722/146867539-9f307b60-6d58-4509-a7a5-c158015b4bdc.png)

嗯嗯，model中可以直接通过`this.graphModel获取整个graphModel对象`
