### ISSUE TITLE
使用文字自动换行后，导出图片时会出现文字错位

### ISSUE THREAD

**Issue by zmj6459** [didi/LogicFlow#428]
![error](https://user-images.githubusercontent.com/86214157/147331567-70c0e9d9-a132-43e2-9b5e-fc1c42f4c38c.png)

**Comment by towersxu** [comment]
和 #421 类似，导出的时候没有样式。

**Comment by zmj6459** [comment]
![微信图片_20211227095429](https://user-images.githubusercontent.com/86214157/147426850-b2b198d9-5829-4f78-bb38-3130f2e62a7f.png)
我是用主题的形式设置的autoWrap,如何导出图片的时候有样式？谢谢
