### ISSUE TITLE
扩展节点生成svg图。

### ISSUE THREAD

**Issue by hadoop835** [didi/LogicFlow#429]
我想
<img width="116" alt="1640588300(1)" src="https://user-images.githubusercontent.com/8055054/147443970-9e2139b5-9b0d-481c-884c-7d5f87121245.png">
类似这样的包含网关。
<img width="199" alt="1640588367(1)" src="https://user-images.githubusercontent.com/8055054/147444063-35293765-cba9-4881-b3b2-39a681df6ed8.png">
。不知道从何下手

**Comment by towersxu** [comment]
这个可以拆分为菱形和圆。在getShape中这样写即可。
```js
    return h(
      'g',
      {
        transform: `matrix(1 0 0 1 ${x - width / 2} ${y - height / 2})`,
      },
      h('polygon', {
        ...style,
        x,
        y,
        points,
      }),
      h('circle', {
       rx: x,
       ry: y,
       stroke: "blue"
      }),
    );
 
```
