### ISSUE TITLE
如何刷新画布

### ISSUE THREAD

**Issue by jjy8040** [didi/LogicFlow#431]
如何刷新画布

**Comment by towersxu** [comment]
重新render即可

**Comment by jjy8040** [comment]
重新render后右键失效

**Comment by towersxu** [comment]
右键菜单吗？你是怎么用的？

**Comment by jjy8040** [comment]
flow = (data) =>{
this.lf = new LogicFlow({
      container: document.querySelector("#logicFlow"),
      keyboard: {
        enabled: false,
      },
      width: "100%",
      height: "100%",
      grid: true,
      // isSilentMode: true
    });
    let w =
      window.innerWidth ||
      document.documentElement.clientWidth ||
      document.body.clientWidth;
    this.lf.setTheme({
      rect: {
        width: Math.ceil((136 / 1440) * w),
        height: Math.ceil((40 / 1440) * w),
        fill: "#fff",
        stroke: "#c8c8c8",
        radius: Math.ceil((20 / 1440) * w),
        strokeWidth: Math.ceil((1 / 1440) * w),
      },
      nodeText: {
        fontSize: Math.ceil((14 / 1440) * w),
        color: "#333",
      },
      line: {
        stroke: "#999999",
        strokeWidth: Math.ceil((1 / 1440) * w),
        hoverStroke: "#999999",
        selectedStroke: "#999999",
        outlineColor: "#999999",
      },
      polyline: {
        stroke: "#999999",
        strokeWidth: Math.ceil((1 / 1440) * w),
        hoverStroke: "#999999",
        selectedStroke: "#999999",
        outlineColor: "#999999",
      },
    });
    this.lf.register(action);
    let that = this;
    this.lf.setMenuConfig({
      nodeMenu: [
        {
          text: "删除",
          callback(node) {
            that.lf.deleteNode(node.id);
          },
        },
      ], // 覆盖默认的节点右键菜单
      edgeMenu: [
        {
          text: "删除",
          callback(edge) {
            that.lf.deleteEdge(edge.id);
          },
        },
      ], // 删除默认的边右键菜单
      graphMenu: [], // 覆盖默认的画布右键菜单，与false表现一样
    });
    this.lf.render(data);
}

每需要更换一次数据就重新调用一次函数

**Comment by towersxu** [comment]
把new LogicFlow放到函数外面把，render(data)可以在函数里面，调用多次
