### ISSUE TITLE
自定义Html节点，如何在选中框外面添加元素

### ISSUE THREAD

**Issue by MvCraK** [didi/LogicFlow#434]
目前svg节点支持在选中框外部添加额外元素。参考官方vue demo中的推送节点
![image](https://user-images.githubusercontent.com/20339028/147552584-ba3701b6-ff21-4ba9-a52f-9e935d1dc0fa.png)

但是自定义Html节点由于foreignObject的长宽限制，在选中框外部添加的元素直接超出区域不会渲染了。

**Comment by towersxu** [comment]
对于HTML节点，目前不支持。

**Comment by wangzhengbo** [comment]
我也想要这个功能

**Comment by MvCraK** [comment]
临时方案：手动设置外层包裹节点的宽高能搞定。
