### ISSUE TITLE
锚点连线校验

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#437]
**问题描述**  

设置了只有横向的两个锚点，但还是想做一层限制，如：左侧锚点只能是进线终点，右侧锚点只能是出线始点

**Comment by towersxu** [comment]
目前所有的锚点都可以拖出连线来，后续考虑锚点自定义时新增一个”是否允许拖出连线“的配置。

**Comment by towersxu** [comment]
目前已支连线校验到锚点级别。http://logic-flow.org/guide/basic/node.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E7%9A%84%E9%94%9A%E7%82%B9
