### ISSUE TITLE
setProperties方法无法覆盖原有数据

### ISSUE THREAD

**Issue by scorpionfeng** [didi/LogicFlow#441]
**问题描述**  

当调用setProperties方法时,更新对象数据 ,
原数据对象:
properties:{
default:{url: 'string', param: 'any', method: 'string', respType: 'string'}
}

新数据对象:
properties:{
  **request**:{url: 'string', param: 'any', method: 'string', respType: 'string'}
}
调用setProperties后,数据对象成为:
properties:{
default:{url: 'string', param: 'any', method: 'string', respType: 'string'},
request:{url: 'string', param: 'any', method: 'string', respType: 'string'}
}
期望为:
properties:{
request:{url: 'string', param: 'any', method: 'string', respType: 'string'}
}

**Comment by RexYao97** [comment]
自己封装一个设置方法，在设置request的同时把default设置为undefined

**Comment by towersxu** [comment]
可以直接拿到nodeModel，然后对properties进行赋值操作，然后手动调用setAttributes方法触发render。

```js
const nodeModel = lf.getNodeModelById('nodeid');
nodeModel.properties = {}
nodeModel.setAttributes()
```
