### ISSUE TITLE
节点分组功能

### ISSUE THREAD

**Issue by jc-p** [didi/LogicFlow#450]
节点可以实现分组；同时内部节点可以跨组节点拖拽
![image](https://user-images.githubusercontent.com/33076265/148341234-b9c1fa7b-f4f1-4589-ad47-25ca84e1df74.png)

**Comment by casual-y** [comment]
同求功能

**Comment by towersxu** [comment]
bpmn泳道前置功能，优先支持。#312

**Comment by towersxu** [comment]
@goodcto 你好，泳道前置是分组，分组会在1.1.0版本发布。目前在1.1.0-alpha.6版本已有分组功能，功能基本完善，你可以先写泳道功能，我们在春节后测试完全后会发布1.1.0。文档地址请参考https://github.com/didi/LogicFlow/blob/1.1.0-next/docs/guide/extension/component-group.md。示例地址为[https://codesandbox.io/s/logicflow-base24-vgvpf](https://codesandbox.io/s/logicflow-base24-vgvpf)

**Comment by towersxu** [comment]
1.1.0版本已上线分组功能
