### ISSUE TITLE
如何隐藏锚点？

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#454]
隐藏锚点存在多种情景，不同的情景使用的方式不一样。

1. 隐藏所有的锚点，这个时候就无法通过锚点拖出连线。一般禁止编辑的情况使用。

logicflow支持在初始化的时候传入隐藏锚点[配置](http://logic-flow.org/api/logicFlowApi.html#constructor)

```js
const lf = new LogicFlow({
    hideAnchor: true
})
```

2. 自定义类型节点不显示锚点，也不允许其他节点连接到此节点，例如group节点。
logicflow自定义节点支持重写锚点, 重写的时候返回空数组即可，
```js
class cNode extend BaseNodeModel {
   getAnchorsByOffset() {
     return [];
   }
}
```

3. 自定义类型节点不显示锚点，但是允许其他节点连接到此节点
这个时候用logicflow的自定义锚点的样式来实现，将锚点设置为不可见，但是任然存在节点上即可。
```js
class cNode extend BaseNodeModel {
     getAnchorStyle() {
        const style = super.getAnchorStyle();
        style.stroke = "transparent";
        style.fill = "none";
        style.hover.stroke = "transparent";
        return style;
      }
}
```

[codesandbox示例](https://codesandbox.io/s/reverent-haslett-dkb9n?file=/index.html:314-328)

**Comment by hongliangsam** [comment]
`class cNode extend BaseNodeModel {
   getDetaultAnchor() {
     return [];
   }
}`
示例2这个方法的名字写错了，应该是getDefaultAnchor，示例是getDetaultAnchor

**Comment by wenlongluis** [comment]
hideAnchor少了“s”应该是
```
const lf = new LogicFlow({
    hideAnchors: true
})
```

**Comment by 18534613246** [comment]
我想左侧显示锚点  右侧锚点隐藏怎么做啊

**Comment by zengqingcandy** [comment]
> 我想左侧显示锚点 右侧锚点隐藏怎么做啊
请问这个隐藏有做好不？怎么做啊
