### ISSUE TITLE
build之后上生产Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by liyuhan1229** [didi/LogicFlow#458]
检查了本地的Component引用没有问题，测试环境不会报错，打包部署之后就会出现这个问题。屏蔽了其他页面，只有引入logicfow这一个页面出问题

**Comment by towersxu** [comment]
LogicFlow是基于继承来实现自定义的，所有如果你项目中有继承LogicFlow, 请确保不要使用terser这类代码压缩工具，把LogicFlow再次压缩了。

![image](https://user-images.githubusercontent.com/4093984/126097937-bc7af747-301d-4a7a-960f-8ef6156e4578.png)

https://segmentfault.com/a/1190000020484025

**Comment by towersxu** [comment]
有人反馈webpack4 + uglifyjs1.3.0也会出现这个问题，后来把uglifyjs升级到2.2.0版本就没问题了。
