### ISSUE TITLE
调用changeEdgeType后，edge的targetAnchorId和sourceAnchorId丢失了

### ISSUE THREAD

**Issue by MvCraK** [didi/LogicFlow#462]
调用changeEdgeType后，edge的targetAnchorId和sourceAnchorId丢失了。

**Comment by towersxu** [comment]
参考：http://logic-flow.org/guide/basic/edge.html#%E4%BF%9D%E5%AD%98%E9%94%9A%E7%82%B9%E4%BF%A1%E6%81%AF， 需要保存锚点信息
