### ISSUE TITLE
1.x版本，圆形控件r半径配置无效

### ISSUE THREAD

**Issue by wsad123456pm** [didi/LogicFlow#473]
1.x版本，圆形控件r半径配置无效

 ![image](https://user-images.githubusercontent.com/22383837/150290742-df9c0e14-a16a-4615-9186-f1bc49de7c61.png)

**Comment by towersxu** [comment]
形状属性只支持在自定义节点时设置了。[自定义节点的形状属性](http://logic-flow.org/guide/basic/node.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E7%9A%84%E5%BD%A2%E7%8A%B6%E5%B1%9E%E6%80%A7)
