### ISSUE TITLE
[Bug report] 1.x的lf-graph加入了内联style

### ISSUE THREAD

**Issue by ycc3000** [didi/LogicFlow#479]
**问题描述**  

设置grid是true的情况下，0.7.x的网格宽度是可以随窗口宽度自适应的，1.x的lf-graph加入了内联style导致并不随窗口宽度自动调整

**Comment by towersxu** [comment]
能贴一下代码吗？内联style是如何写的这种。请在codesandbox中写下示例：https://codesandbox.io/s/logicflow-base14-dkb9n

**Comment by ycc3000** [comment]
dear,
就你这个示例就可以重现，随便拖动一下窗口宽度，就可以看到style
<img width="715" alt="1643008042(1)" src="https://user-images.githubusercontent.com/22928461/150737411-62046d6c-91d6-45be-b4e1-711e120d7cee.png">

**Comment by towersxu** [comment]
我明白你的问题了，现在是不传宽、高的时候，宽度和高度不是100%自适应是吧，我看看这个问题。
