### ISSUE TITLE
如何定义边界，防止可以不断的扩张图纸？

### ISSUE THREAD

**Issue by fanqieo** [didi/LogicFlow#482]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
现在拖拉一个节点，可以无限制拖拉下去，有办法限制下边界吗？
2. 期望的表现
比如屏幕左侧和上侧，元素只能拖动到屏幕边缘就可以了

**Comment by towersxu** [comment]
1. 可以禁止画布拖动
2. 节点移动的时候，可以添加校验规则，这个文档会在本周的1.1.0版本提供出来
