### ISSUE TITLE
设置width=100%和height=100%后,miniMap显示不正常

### ISSUE THREAD

**Issue by ziaochina** [didi/LogicFlow#487]
设置width=100%和height=100%后,miniMap显示不正常
![NGOD$_EF1A62`{14 L6L_8S](https://user-images.githubusercontent.com/4494312/151280999-63b6332b-e2cf-4893-9d39-6374b522c810.png)

**Comment by towersxu** [comment]
width和height只支持传入数字，不传默认为100%。http://logic-flow.org/api/logicFlowApi.html#constructor
