### ISSUE TITLE
丰富锚点连线事件

### ISSUE THREAD

**Issue by lixianyu-icon** [didi/LogicFlow#507]
**问题描述**  
我现在有这样一个需求，开始连线时，根据类型判断哪些节点是可以被连接的，并高亮显示，我看了一下事件api貌似没有合适的

**实现结果**  
锚点连线时可以支持开始连线，连线中，连线结束（目前连线结束可以使用edge:add）三个事件。

**Comment by towersxu** [comment]
https://codesandbox.io/s/logicflow-vue-rules-d4j86e 请参考此示例
