### ISSUE TITLE
连线轨迹支持所见所得

### ISSUE THREAD

**Issue by willardwang** [didi/LogicFlow#523]
**问题描述**  
连线能否所见即所得，目前拖动的时候是直虚线，释放的时候线的轨迹和拖动时的不一致。

![image](https://user-images.githubusercontent.com/3304388/157423615-0c0e9911-1d8b-4854-9031-e3635cf6946a.png)
![image](https://user-images.githubusercontent.com/3304388/157423634-ac8b62d3-e4fe-4568-9317-e253ec4e0a32.png)

**Comment by willardwang** [comment]
请问能支持吗，现代设计器基本都能支持

**Comment by towersxu** [comment]
这个涉及改动范围比较大，短期内不支持。

**Comment by willardwang** [comment]
@towersxu 谢谢回复以及团队的工作。个人认为这个功能对logicflow使用体验是个不小的提升，如果可能的话希望能支持

**Comment by wumail** [comment]
👀 #1354
