### ISSUE TITLE
Vue3如何自定义HTML节点

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#527]
参考示例[https://codesandbox.io/s/vue3-html-node-yyqwg4](https://codesandbox.io/s/vue3-html-node-yyqwg4?file=/src/components/node-red/nodes/VueHtmlNode.js)，利用vue3的createApp来实现。

目前更新properties的方法用的是`app._instance`, 此方法vue没有对外公开，但是没有在官方文档中翻到合适的API，先这样。

**Comment by yeyaolong** [comment]
这个解决方案在开发环境是正常使用的，但是使用vite打包后，app_instance会变为null，导致空指针异常

![本地开发](https://user-images.githubusercontent.com/10331296/200986940-1eb3c9b1-4e6b-4e60-8bb2-84f94d7a384b.png)

![发布到测试环境](https://user-images.githubusercontent.com/10331296/200986972-d6d606f9-91ef-4fa7-8dbb-899320c563bd.png)

> 参考示例[https://codesandbox.io/s/vue3-html-node-yyqwg4](https://codesandbox.io/s/vue3-html-node-yyqwg4?file=/src/components/node-red/nodes/VueHtmlNode.js)，利用vue3的createApp来实现。
> 
> 目前更新properties的方法用的是`app._instance`, 此方法vue没有对外公开，但是没有在官方文档中翻到合适的API，先这样。

**Comment by yeyaolong** [comment]
晚上又查了一下，发现其他人也有类似的问题，并且提了issue解决了：

https://github.com/didi/LogicFlow/issues/686
