### ISSUE TITLE
getNodeModelById无法调用

### ISSUE THREAD

**Issue by zqc11** [didi/LogicFlow#528]
我在onBindEvent中调用lf的函数时总是报这个错， 在调onBindEvent之前，已确保lf初始化 ，另外它们是在同一个vue文件中，我在console.log(lf.value)时，是有输出的，但一在onBindEvent中调用它的方法就出错。

![QQ截图20220314162549](https://user-images.githubusercontent.com/46465484/158133565-96584aa5-1739-4132-a3be-1e7a935043e5.png)
![QQ截图20220314162609](https://user-images.githubusercontent.com/46465484/158133600-767396fb-e32b-43a4-9372-1e0adce6cdea.png)
![QQ截图20220314162527](https://user-images.githubusercontent.com/46465484/158133653-4dad3f46-75cc-4c68-8a53-5506c67f5cdc.png)
![QQ截图20220314162454](https://user-images.githubusercontent.com/46465484/158133658-e269b15f-a77d-4795-9854-d78cdcf38aaa.png)

**Comment by towersxu** [comment]
看起来不是LogicFlow的问题，你在排查一下，比如先确认函数里面的lf.value在运行的时候内容是什么？

**Comment by zqc11** [comment]
console.log(lf.value)输出就是lf实例
![QQ截图20220314173606](https://user-images.githubusercontent.com/46465484/158145395-7a29b97f-6f76-4255-86e1-2e3742c667ad.png)

**Comment by zqc11** [comment]
问题找到了，lf没有提供getNodeModelById的方法，反倒是通过VScode的代码提示找到了一个getNodeModel方法，这个方法文档里没有，但效果完全一样，不知道是不是文档写错了
