### ISSUE TITLE
画布点击事件阻止了事件冒泡，导致非画布区的下拉框不能自动收起

### ISSUE THREAD

**Issue by lixianyu-icon** [didi/LogicFlow#529]
**画布点击事件阻止了事件冒泡，导致非画布区的下拉框不能自动收起**  

**最简复现demo**  
画布外有切换画布数据版本的下拉框，打开下拉框后点击画布元素或者画布，版本下框不能自动收起。

**Comment by towersxu** [comment]
将在1.1.8版本修复
