### ISSUE TITLE
不能动态修改 grid 类型和样式

### ISSUE THREAD

**Issue by yhlchao** [didi/LogicFlow#53]
version：0.2.7

**问题描述**
目前 grid 样式只能在初始化 LogicFlow 时设置，但不能动态修改。

**期望**
支持通过 API 动态设置 grid 的类型和样式

**Comment by towersxu** [comment]
logicflow有内置的强制对齐功能，这个功能要求流程图绘制和渲染的时候，始终保持gird大小一致，不然会因为强制对齐导致流程图错乱。
