### ISSUE TITLE
properties打印出来为proxy对象

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#530]
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/4093984/158331104-3dbc0f4f-dae1-4aae-8c01-f4a6f5b62438.png">

**Comment by towersxu** [comment]
在自定义model或者view的时候，如果直接通过`this.properties`在model中获取properties属性，会显示为Proxy对象。这是因为LogicFlow内部为了让properties发生变化后能实时更新流程图，所以把properties转换为响应式对象。如果要打印原生对象内容，可以使用model的getProperties方法获取。
```js
class UserTaskModel extends RectNodeModel {
  getNodeStyle() {
    const style = super.getNodeStyle();
    const properties = this.getProperties();
    if (properties.statu === 'pass') {
      style.stroke = "green";
    } else if (properties.statu === 'reject') {
      style.stroke = "red";
    } else {
      style.stroke = "rgb(24, 125, 255)";
    }
    return style;
  }
}
```

PS: proxy对象虽然打印出来无法看到属性，但是在控制台上继续展开也可以看到属性。同时，这些属性可以仍然可以正常的通过正常的属性操作符得到。上面的代码和下面的结果一致：
```js
class UserTaskModel extends RectNodeModel {
  getNodeStyle() {
    const style = super.getNodeStyle();
    if (this.properties.statu === 'pass') {
      style.stroke = "green";
    } else if (this.properties.statu === 'reject') {
      style.stroke = "red";
    } else {
      style.stroke = "rgb(24, 125, 255)";
    }
    return style;
  }
}
```

**Comment by yanbin2019** [comment]
statu这个属性是写在哪里的？

**Comment by towersxu** [comment]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/4093984/169232907-a1570915-3de2-4dd0-87f6-890655c8fe85.png">
