### ISSUE TITLE
[需求]两个节点，相距较远，超过了当前屏幕高度了，连线不能随着滚动条下滑而往下延伸

### ISSUE THREAD

**Issue by topperCao** [didi/LogicFlow#534]
两个节点，相距较远，超过了当前屏幕高度了，连线不能随着滚动条下滑而往下延伸

注：此场景较为常见，当流程图较长时，当前浏览器页面高度不足以支撑画布高度时，此时需要连接两个相距比较远的节点，

连线时连不了！

**Comment by towersxu** [comment]
1.1.9版本已支持
