### ISSUE TITLE
windows下启动开发模式

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#538]
windows 10环境
运行 npm run dev:core 报错，无法启动跳转打开index.html
报错如下：
![image](https://user-images.githubusercontent.com/28721603/159104027-9fd45c05-a3fa-44bf-9f27-202d9676a1e2.png)

是否和node版本有关，用的是16.6.0版本

**Comment by towersxu** [comment]
参考[developer.md](https://github.com/didi/LogicFlow/blob/master/developer.md)中的window运行指南试试
