### ISSUE TITLE
需要什么功能？

### ISSUE THREAD

**Issue by sunyongjian** [didi/LogicFlow#54]
可以反馈下项目中需要的，但是 LogicFlow 目前还不支持的能力。

**Comment by juzhiyuan** [comment]
Apache APISIX Dashboard 在实现插件编排，正在尝试自定义 插件元件 :)

**Comment by sunyongjian** [comment]
来自用户群 jiangnan，节点之间发生了位置调整， 比如 A -> B 的位置变成了 B -> A，那期望连线的锚点也可以根据最短路径做出调整。

**Comment by thomas-kala** [comment]
能否支持框选多个图形的功能？

**Comment by sunyongjian** [comment]
@thomas-kala 有的，更新下最新版本。用法还没有更新到文档，先看一下这个示例：https://github.com/didi/LogicFlow/blob/master/examples/src/pages/usage/bpmn/pattern.tsx

new LogicFlow 的时候传下参
`
      extraConf: {
        openSelectionMode: true,
      }
`

**Comment by sunyongjian** [comment]
DND  的全生命周期，都要对外暴露钩子，比如 dragOver，drop

**Comment by yanchangyou** [comment]
怎么让拖拽面板的元素失效， 一个流程只允许一个开始节点， 拖了一次， 不能再拖

**Comment by sunyongjian** [comment]
如何禁用文本编辑，又不会让双击事件失效。目前 editable 的参数会让双击失效

**Comment by yanchangyou** [comment]
获取当前选中的节点，或者边

**Comment by yanchangyou** [comment]
> Apache APISIX Dashboard 在实现插件编排，正在尝试自定义 插件元件 :)

实现什么效果？
我在做服务编排，在扩展使用场景，原理应该是一致的

**Comment by yanchangyou** [comment]
在画边的事件里面 添加text， 调用API报错
加个timeout，就可以， 这可以优化成注释那种最好了
`
            setTimeout(() => {
                var text = getMiddlePoint(event.data.pointsList);
                text.value = edgeText;
                // event.data.text = text;
                codeEditor.setEdgeData({ id: event.data.id, text: text });
            }, 100);
`

**Comment by 123geshuai** [comment]
1、A->B连线上的文本，初始化时居中，拖拽节点后位置不合理。
2、文本超长情况。

**Comment by tongtie** [comment]
可以实时渲染改变节点和线颜色的功能，现在我是通过重新初始化lf示例，`lf.render(data)`实现的，但这样会丢失图形的位置（图形移动过）和图形的缩放（目前是自己保存的）
补充下：现在是把节点该显示什么颜色放到了properties属性中，目前发现只有第一次加载的时候生效，后续修改properties中的内容，就不会自动变化颜色了。
代码这样：
`    class StartNodeModel extends CircleNodeModel {
      constructor(data, graphModel) {
        super(data, graphModel);
        const { properties } = data;
        if (Object.keys(statusColor).includes(properties.status)) {
          this.stroke = statusColor[properties.status];
        } else {
          this.stroke = '#FF6347';
        }
      }`

**Comment by littleinsz** [comment]
泳道

**Comment by littleinsz** [comment]
分组节点

**Comment by baihuayao** [comment]
1.自定义线（虚线、线上有操作按钮）
2.拖拽节点自动吸附

**Comment by amoalys** [comment]
1.每个节点的锚点都可以设置是否允许被连接

**Comment by amoalys** [comment]
锚点事件

**Comment by belongwqz** [comment]
自动布局，不用指定x和y坐标，节点之间自动排列，目前可以实现么？

**Comment by lx11573** [comment]
自动计算生成 x,y 坐标,节点自动排列, 溢出换行

**Comment by sunyongjian** [comment]
> 自动布局，不用指定x和y坐标，节点之间自动排列，目前可以实现么？
@belongwqz @lx11573 
关于自动排列这一点，应该是按照一定的布局自动排列 + 吸附节点。对于自动排列的逻辑有什么想法吗？
我们也会去调研一下，看选取几个布局支持一下。

**Comment by belongwqz** [comment]
> > 自动布局，不用指定x和y坐标，节点之间自动排列，目前可以实现么？
> > @belongwqz @lx11573
> > 关于自动排列这一点，应该是按照一定的布局自动排列 + 吸附节点。对于自动排列的逻辑有什么想法吗？
> > 我们也会去调研一下，看选取几个布局支持一下。
类似于x6的layout功能，指定了布局类型就自动排列那种。

**Comment by lx11573** [comment]
> > 自动布局，不用指定x和y坐标，节点之间自动排列，目前可以实现么？
> > @belongwqz @lx11573
> > 关于自动排列这一点，应该是按照一定的布局自动排列 + 吸附节点。对于自动排列的逻辑有什么想法吗？
> > 我们也会去调研一下，看选取几个布局支持一下。

最好可以内置两种及以上自动排列的选择, 指定优先排列等.

**Comment by Serendipity96** [comment]
> Apache APISIX Dashboard 在实现插件编排，正在尝试自定义 插件元件 :)
可以加下官方微信：logic-flow 交流下

**Comment by belongwqz** [comment]
建议：
1、实现类似于X6的to_json和from_json接口
2、提供浏览器引用的es5示例

**Comment by JefferyChensp** [comment]
1.节点和边能否提供通用的属性面板编辑功能？（目前可能需要开发者自己实现）
2.页面美化自动布局，类似processOn的一键美化功能，目前体验发现连线不太好对齐
![image](https://user-images.githubusercontent.com/42525845/118068244-9e95fb00-b3d4-11eb-9925-6dd492ac6e02.png)

**Comment by waihaolaoxu** [comment]
希望插件支持边的move拖动事件，目前我们的场景是单点保存拖动一个节点保存节点的坐标信息，拖动边的位置保存边的位置信息

**Comment by ss876079056** [comment]
希望可以支持图形旋转

**Comment by xcyapcc** [comment]
> 可以反馈下项目中需要的，但是 LogicFlow 目前还不支持的能力。

希望增加泳道功能

**Comment by asreday** [comment]
1.节点能额外的文本框或者html绑定当前节点，比如可能要在外框上面添加一个标题这样。
2.自动对齐。

**Comment by GDUT-Rex** [comment]
希望画布拖拽事件暴露API方法，而不是简单的设置开关来设置，希望能增加用户自定义组合按键触发，例如：ctrl+鼠标点击移动画布

**Comment by GDUT-Rex** [comment]
希望节点新增节点权限属性控制，例如不允许编辑、不允许拖拽、不允许缩放等。

**Comment by GDUT-Rex** [comment]
> 希望节点新增节点权限属性控制，例如不允许编辑、不允许拖拽、不允许缩放等。

textEdit:false 配置之后可以关闭全局node的文本编辑，可以更新下文档

**Comment by zengkaiz** [comment]
想实现这样一个自定义连线为虚线dottedLine，需要重写getEdge可能比较麻烦，麻烦看怎么支持一下

**Comment by lcoder** [comment]
支持自定义Text节点，类似：
![自定义text](https://raw.githubusercontent.com/lcoder/blogimg/master/images/20210811131035.png)。

用途，比如model数据的text文本很长，但是希望展示界面超过10个字溢出展示`...`。就可以通过自定义text来实现

**Comment by YangsonHung** [comment]
节点里面的text文字不支持换行，这个能支持下吗，用的是BpmnElement的元素

**Comment by jinhuang415** [comment]
可以支持国际化吗？现在右键菜单里面都是写死中文了，如果能支持国际化使用场景会更多一些

**Comment by saber999** [comment]
图形间可以互相包含吗

**Comment by cenglulu** [comment]
拖拽面板不止是单一的一列，实现分类像工具箱一样

**Comment by Erin1203** [comment]
支持框选功能，整体移动节点   vue版本的 我看到目前有 react

**Comment by lisha0839** [comment]
增加连线文本事件。连线及连线文本增加不同状态设置不同样式的例子

**Comment by kilosangma** [comment]
能不能再框选后 对框选的元素右击打开menu菜单 进行批量删除操作

**Comment by kilosangma** [comment]
> 能不能再框选后 对框选的元素右击打开menu菜单 进行批量删除操作

或者如何获取当前框选的节点的相关信息

**Comment by finalreturn** [comment]
设置zoom的值，当前貌似只有最小值和最大值

**Comment by TatsuyaLMinami** [comment]
导出图片的格式，能不能做成自定义的，现在只有png格式

**Comment by TatsuyaLMinami** [comment]
自动布局功能什么时候可以完善

**Comment by baozoulolw** [comment]
请问可以在拖动节点的时候自动把连线锚点换成最近的那一个吗

**Comment by xiuse-liutao** [comment]
请问下子流程应该怎么实现？

**Comment by caoliy3567** [comment]
请问有没有jquery的例子，不使用recet或者VUE的

**Comment by xiuse-liutao** [comment]
单个节点的宽高能设置成可以拖拽的吗

**Comment by Dogtiti** [comment]
考虑支持dmn吗？

**Comment by lty1601** [comment]
请问可以支持拖拽修改连线的终点吗 ？

**Comment by towersxu** [comment]
目前logicflow已支持上面提到的绝大部分功能，有特殊需求欢迎单独提issue或者进技术交流群沟通。

**Comment by kilosangma** [comment]
希望能以vue组件的形式实现html自定义节点 目前自定义节点的局限比较多

**Comment by towersxu** [comment]
> 希望能以vue组件的形式实现html自定义节点 目前自定义节点的局限比较多

这里有vue3的示例，vue2类型https://github.com/Logic-Flow/logicflow-node-red-vue3/tree/master/src/components/node-red/nodes

**Comment by kilosangma** [comment]
> > 希望能以vue组件的形式实现html自定义节点 目前自定义节点的局限比较多
> 
> 这里有vue3的示例，vue2类型https://github.com/Logic-Flow/logicflow-node-red-vue3/tree/master/src/components/node-red/nodes

感谢

**Comment by wangzhengbo** [comment]
希望能自定义id生成策略，目前的id太长了

**Comment by towersxu** [comment]
@wangzhengbo 目前支持的，可以通过`idGenerator`控制，也可以自定义节点的时候手动生成

**Comment by wangzhengbo** [comment]
> 请问idGenerator怎么用呢？文档没看到哦。我看了下源码，id是直接用uuid库生成的，没有暴露接口给外部来设置生成策略

**Comment by wangzhengbo** [comment]
> @wangzhengbo 目前支持的，可以通过`idGenerator`控制，也可以自定义节点的时候手动生成

看到idGenerator了。在1.2.0版本中。但1.2.0还没发布，预计什么时候能发布呢？

**Comment by wangzhengbo** [comment]
请问有API能动态修改节点的坐标吗？不是拖拽去改动，需要API来修改、

**Comment by towersxu** [comment]
@wangzhengbo api中有moveNode，idGenerator已经支持了

**Comment by towersxu** [comment]
锁定此issue, 有新功能需求请单独开issue，所有问题在一个issue中不利于搜索，也会打扰之前的同学。
