### ISSUE TITLE
lf.fitView() 方法不存在

### ISSUE THREAD

**Issue by doubleksk** [didi/LogicFlow#543]
**问题描述**  
"@logicflow/core": "^1.1.7",
"@logicflow/extension": "^1.1.7",
以上版本中 logicFlow实例不存在fitView这个方法

**Comment by towersxu** [comment]
这个要1.1.8才存在，预计3.25发布

**Comment by doubleksk** [comment]
> 这个要1.1.8才存在，预计3.25发布

噢噢，好的，谢谢了！
