### ISSUE TITLE
发现拖拽节点，节点文案同步移动不正确

### ISSUE THREAD

**Issue by chenweihan** [didi/LogicFlow#548]
官网上：http://logic-flow.org/usage/bpmn.html

拖拽一个节点到画布   比如 开始节点。 拖拽移动开始节点，下面的文案为什么不和图案同步移动？？？

这个低级错误不应该出现，兼容性问题？

![1648478353(1)](https://user-images.githubusercontent.com/1927864/160422852-2f858995-d2cc-4b07-8b4b-bd47a4ff2fce.png)

**Comment by towersxu** [comment]
嗯，感谢提出问题，目前官网示例用的是next版本1.1.9。所以不会影响其他人线上项目。我们会尽快修复这个问题。
