### ISSUE TITLE
菜单问题

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#551]
描述：
我通过在自定义节点和边中根据各节点的业务定义了不同的菜单，但是希望菜单还能够实时监听根据某个变量变化来显示或隐藏所有节点和边的菜单（因为静默模式没有支持菜单不显示）

**Comment by towersxu** [comment]
参考[菜单文档](http://logic-flow.org/guide/extension/component-menu.html#%E6%8C%87%E5%AE%9A%E4%B8%9A%E5%8A%A1%E7%8A%B6%E6%80%81%E8%AE%BE%E7%BD%AE%E8%8F%9C%E5%8D%95), 你可以自定义的时候自己控制this.menu
