### ISSUE TITLE
使用BpmnXmlAdapter转换下载出来的xml中isExecutable为false

### ISSUE THREAD

**Issue by Helloyqgao** [didi/LogicFlow#554]
使用BpmnXmlAdapter转换下载出来的xml中isExecutable为false，导致xml不可用

**Comment by towersxu** [comment]
目前对bpmn全功能支持还存在问题。你可以参考bpmnxmlAdapter自己实现插件。或者等到后续bpmn全功能版本。https://github.com/didi/LogicFlow/blob/8495858bd6096338ab97fca6832b085e99df57ee/packages/extension/src/bpmn-adapter/index.ts#L428

**Comment by towersxu** [comment]
试试[1.2.0-alpha.2](https://www.npmjs.com/package/@logicflow/core/v/1.2.0-alpha.2)版本
