### ISSUE TITLE
[bug?] 节点难对齐，拖动到”水平“后依然出现折线

### ISSUE THREAD

**Issue by yzwsm** [didi/LogicFlow#555]
**节点难对齐，拖动到”水平“后依然出现折线**
http://logic-flow.org/examples/#/extension/InserNodeInPolyline
这个case，在这种情况下，必现无法对齐
![image](https://user-images.githubusercontent.com/4781152/162353306-dfdce376-6533-4163-8078-751858200990.png)

step1：创建两个水平节点，并连线（此时连线对齐的）
step2：拖动其中一个节点，至图示位置
step3：再拖动还原，始终无法对齐（如果没有达成step2，则可以还原）

**Comment by towersxu** [comment]
看起来是因为两个圆中心没有对齐，但是你慢一点应该还是可以对齐。目前logicflow连线对齐还是不够智能，后面我们优化一下。

**Comment by cyt68** [comment]
> 看起来是因为两个圆中心没有对齐，但是你慢一点应该还是可以对齐。目前logicflow连线对齐还是不够智能，后面我们优化一下。

更新之后这个bug很明显，而且就算慢慢对齐也对不齐，而且从远往近拖动节点连线就会扭曲。。。老哥早点优化一波，👍🏻

**Comment by towersxu** [comment]
嗯，我仔细体验了一下，确实有这个问题，下个版本优化一下。

**Comment by BelinChung** [comment]
所以节点对齐的，有什么优化思路吗，或者跟bpmn一样，引入一个磁吸的能力？
