### ISSUE TITLE
自定义节点时，getDefaultAnchor()，返回空数组时报错。

### ISSUE THREAD

**Issue by maohui66661** [didi/LogicFlow#559]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
自定义节点时，getDefaultAnchor()，返回空数组
![image](https://user-images.githubusercontent.com/7902405/162600058-18daa300-40c9-40e7-8772-38ba1df5dec8.png)
3. 期望的表现
节点正常渲染，且没有锚点
5. 实际的表现
报错，无法正常渲染。
![image](https://user-images.githubusercontent.com/7902405/162600163-7516b340-000d-4b34-82f5-273172c109d7.png)

**Comment by towersxu** [comment]
如果节点锚点为空，那么不能有连线连接到这个节点。如果想要被连接，又不显示锚点，可以将锚点设置为隐藏。

**Comment by maohui66661** [comment]
可以单独对节点设置锚点隐藏吗？目前看api是对整个画布设置锚点隐藏。
