### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by cheeZzp** [didi/LogicFlow#562]
自定义的html节点无法进行节点properties的设置后，节点无法在画布上渲染。

https://codesandbox.io/s/vibrant-shaw-r2h5xf?file=/src/components/Lf.vue

**Comment by towersxu** [comment]
你的shouldUpdate逻辑错误，另外1.0版本可以不自定义shouldUpdate。https://codesandbox.io/s/condescending-panini-itro10?file=/src/components/registerNode.js:246-258
