### ISSUE TITLE
[Bug report] 节点移动操作的redo异常

### ISSUE THREAD

**Issue by han-feng** [didi/LogicFlow#563]
**问题描述**  
使用1.1.8以上版本时，发现节点移动操作undo后无法进行redo操作。

**最简复现demo**  
使用官方 [mvp demo](http://logic-flow.org/mvp/index.html) ，拖入一个节点，然后移动该节点两三次，点击一次undo，然后点击redo，发现redo操作无效。

**Comment by towersxu** [comment]
目前已修复
