### ISSUE TITLE
setProperties不支持将属性设置为undefined

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#564]
将properties中的name设置为"test"后，然后设置为undefined，不会触发节点的更新。因为
@action
  setProperties(properties): void {
    this.properties = {
      ...this.properties,
      ...formatData(properties),
    };
    this.setAttributes();
  }
中的formatData(properties),过滤掉了properties中value为undefined的entry.

formatData源码如下:
export const formatData = (data) => {
  try {
    return JSON.parse(JSON.stringify(data));
  } catch {
    return data;
  }
};

测试代码:
JSON.parse(JSON.stringify({a: 1, b: undefined})) 返回 {a: 1}

**Comment by wangzhengbo** [comment]
@towersxu 您好，这个bugfix好像没有在当前最新的正式版中修复？

**Comment by wangzhengbo** [comment]
@towersxu 请问下这个fix能合到目前的1.x版本中发布下吗？

**Comment by towersxu** [comment]
@wangzhengbo 没修复吗？我重新打开看看

**Comment by boyongjiong** [comment]
![image](https://github.com/didi/LogicFlow/assets/8553969/9adc837c-1690-4335-9557-e37541a0c78e)

如上面代码注释，cloneDeep 会导致内部其它逻辑出现问题，值置空，设置为 null 是否更合理些。

**Comment by Ari1c** [comment]
@boyongjiong 请问一下 1.2.27 版本中有修复掉吗？

**Comment by Ari1c** [comment]
向下兼容一下呗
