### ISSUE TITLE
[Bug report] lf.dnd.startDrag的文本节点，删除文字后文本框会残留无法删除

### ISSUE THREAD

**Issue by GGBeng1** [didi/LogicFlow#565]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
任何案例，使用 lf.dnd.startDrag的文本节点，删除文字后文本框会残留无法删除

**最简复现demo**  
任何案例codesandbox都可以复现
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/40552498/162865838-98c15189-1197-4edb-b199-774578bf3ba2.png">

**Comment by towersxu** [comment]
删除文字内容后，文本节点还在，如果想删除，可以直接删除节点即可（开启keyboard可以delete删除）。不能文字为空就把节点删除，因为还是存在先把文字内容删除后重新填写新的文本情况。
