### ISSUE TITLE
自定义HTML节点拖拽时会有残留的拖拽痕迹

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#566]
自定义HTML节点，设置了html的border，在拖拽时会有残留的拖拽痕迹，可能是竖线或者横线，颜色和html节点的边框颜色值一样。节点再次拖到痕迹上去可以抹去痕迹。用官方LogicFlow的examples中的html节点实例就可以复现， logicflow用的1.1.11版本。拖动节点快速左右上线移动，比较小的概率能复现。在我自己的项目中这个问题比较明显。

**Comment by towersxu** [comment]
我这里并没有复现，有具体复现效果吗？
![2](https://user-images.githubusercontent.com/4093984/163660054-f424dacb-2dae-4a1a-b534-b693b9a3c3b1.gif)

**Comment by wangzhengbo** [comment]
![logicflow-drag-bug](https://user-images.githubusercontent.com/5754985/163747023-6cc56781-fb15-401c-9ff0-f8063dd5d400.jpg)
使用官方仓库中examples下的 “自定义HTML节点“ 示例，往上拖拽右侧的节点，左侧的节点会自动往下滚动，滚动的时候留下了横向的线条。这个有时候好几次才能复现一次出来。

**Comment by wangzhengbo** [comment]
![canvas](https://user-images.githubusercontent.com/5754985/163747294-4501fc0a-6569-4f38-a8e4-cf038c3f68a5.png)
我们自己的项目中这个问题更明显

**Comment by towersxu** [comment]
我这边还是没有复现，请先排查一下是否是设备、操作系统、浏览器等引起的问题。

**Comment by wangzhengbo** [comment]
> 

因为我这边不是我一个人复现的。您有时间了可以多试几次。我用的Thinkpad T470, windows 10, Chrome 100.0.4896.60

**Comment by aweirdocc** [comment]
> > 
> 
> 因为我这边不是我一个人复现的。您有时间了可以多试几次。我用的Thinkpad T470, windows 10, Chrome 100.0.4896.60

你好，我也有同样的情况，你有解决了么？

**Comment by aweirdocc** [comment]
> > 
> 
> 因为我这边不是我一个人复现的。您有时间了可以多试几次。我用的Thinkpad T470, windows 10, Chrome 100.0.4896.60

你好，我也有同样的情况，你有解决了么？

**Comment by wangzhengbo** [comment]
> > > 
> > 
> > 
> > 因为我这边不是我一个人复现的。您有时间了可以多试几次。我用的Thinkpad T470, windows 10, Chrome 100.0.4896.60
> 
> 你好，我也有同样的情况，你有解决了么？

今天试了下没有复现。这个问题本身比较难复现

**Comment by aweirdocc** [comment]
> 
> 今天试了下没有复现。这个问题本身比较难复现

好的，这个问题再项目中出现的频率还是比较高，我目前是把边框背景用图片替换了，暂时没有出现了。

**Comment by hongliangsam** [comment]
<img width="924" alt="ac1f8ee97e6aa83897ec457c8e987df" src="https://user-images.githubusercontent.com/50320208/218626470-05b3243b-62c7-453b-900c-b20bfcd2adaf.png">
拖动画布，节点跟着移动有残影

版本	Windows 11 家庭中文版
版本	22H2
操作系统版本	22621.1194

Chrome
版本 110.0.5481.78（正式版本） （64 位）

Microsoft Edge
版本 110.0.1587.41 (正式版本) (64 位)

chrome和edge均发现此问题。

**Comment by hongliangsam** [comment]
`const lf = new LogicFlow({
    grid: {
      size: 20,
      visible: false,
      type: 'dot',
      config: {
        color: '#ababab',
        thickness: 1,
      },
    }
})`

暂时性解决方法：发现开启网格后就不会出现“拖动画布，节点跟着移动有残影”的问题，但网格开启后visible设置为false视觉上没有影响，拖动时候跟没有设置网格可能略有区别没那么平滑，算是个权宜之计。。

**Comment by hongliangsam** [comment]
> <img alt="ac1f8ee97e6aa83897ec457c8e987df" width="924" src="https://user-images.githubusercontent.com/50320208/218626470-05b3243b-62c7-453b-900c-b20bfcd2adaf.png">
> 
> 拖动画布，节点跟着移动有残影
> 版本 Windows 11 家庭中文版 版本 22H2 操作系统版本 22621.1194
> 
> Chrome 版本 110.0.5481.78（正式版本） （64 位）
> 
> Microsoft Edge 版本 110.0.1587.41 (正式版本) (64 位)
> 
> chrome和edge均发现此问题。

`const lf = new LogicFlow({
    grid: {
      size: 20,
      visible: false,
      type: 'dot',
      config: {
        color: '#ababab',
        thickness: 1,
      },
    }
})`

暂时性解决方法：发现开启网格后就不会出现“拖动画布，节点跟着移动有残影”的问题，但网格开启后visible设置为false视觉上没有影响，拖动时候跟没有设置网格可能略有区别没那么平滑，算是个权宜之计。。

**Comment by hongliangsam** [comment]
![image](https://user-images.githubusercontent.com/50320208/218628247-c0270d3b-0df9-4688-93c5-fbf682d6b779.png)

`const lf = new LogicFlow({
    grid: {
      size: 20,
      visible: false,
      type: 'dot',
      config: {
        color: '#ababab',
        thickness: 1,
      },
    }
})`

暂时性解决方法：发现开启网格后就不会出现“拖动画布，节点跟着移动有残影”的问题，但网格开启后visible设置为false视觉上没有影响，拖动时候跟没有设置网格可能略有区别没那么平滑，算是个权宜之计。。

**Comment by towersxu** [comment]
@hongliangsam 请问这个问题是所有的windows电脑都会出现还是个别电脑出现呢？

**Comment by hongliangsam** [comment]
> @hongliangsam 请问这个问题是所有的windows电脑都会出现还是个别电脑出现呢？

目前仅在我的电脑上发现，还在早期开发阶段，另一个同事的win10 22H2+chrome110.0.5481.78（正式版本） （64 位）没发现这个问题

**Comment by woshikey** [comment]
我的也有这情况，缩放的时候偶尔会出现

**Comment by woshikey** [comment]
/
![1691388114789](https://github.com/didi/LogicFlow/assets/42770876/221ff28d-a61d-4ada-9fa8-d148bd69f861)

**Comment by qingtian5266** [comment]
同样出现，safari 浏览器会有的，或者开f12内存不足时就会出现，也不知道咋解决哎

**Comment by qingtian5266** [comment]
> 同样出现，safari 浏览器会有的，或者开f12内存不足时就会出现，也不知道咋解决哎

![25381932381_165301379017_28a72cc567194e2b226f25fb879f0a38](https://github.com/user-attachments/assets/d8e9a6dc-87ec-4a62-8c02-f9a44b9f0e20)

**Comment by hongliangsam** [comment]
> 暂时性解决方法：发现开启网格后就不会出现“拖动画布，节点跟着移动有残影”的问题，同时网格开启后visible设置为false视觉上没有影响，拖动时候跟没有设置网格可能略有区别没那么平滑，算是个权宜之计。。

**Comment by hongliangsam** [comment]
> > 同样出现，safari 浏览器会有的，或者开f12内存不足时就会出现，也不知道咋解决哎
> 
> ![25381932381_165301379017_28a72cc567194e2b226f25fb879f0a38](https://private-user-images.githubusercontent.com/28749518/399423374-d8e9a6dc-87ec-4a62-8c02-f9a44b9f0e20.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzcyMjEsIm5iZiI6MTczNTYzNjkyMSwicGF0aCI6Ii8yODc0OTUxOC8zOTk0MjMzNzQtZDhlOWE2ZGMtODdlYy00YTYyLThjMDItZjlhNDRiOWYwZTIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA5MjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OWQxMTRmN2U5YjIyZjU2ZjY1MjE5M2EyZTc3OWIwODgxZTU5YTIwYThkZDFhMzNkYmQ5OWM2MGExZGY0M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lh1IYs-XtBWSW-VM15TvkZFYobuK7g-5f1J81tNcBwo)

你可以试试我的暂时性解决方法，我是1.0：发现开启网格后就不会出现“拖动画布，节点跟着移动有残影”的问题，同时网格开启后visible设置为false视觉上没有影响，拖动时候跟没有设置网格可能略有区别没那么平滑，算是个权宜之计。。
