### ISSUE TITLE
[功能需求] 支持国际化

### ISSUE THREAD

**Issue by THUzxj** [didi/LogicFlow#569]
包括：

1. console输出
2. extension menu文本
3. extension control文本
4. 其他一些message和标题等

十分感谢你们的贡献。我目前有开发英文GUI绘图软件的需求，这个框架十分合适。如果支持国际化该框架使用范围一定会更广泛，请予以考虑。

**Comment by towersxu** [comment]
感谢反馈，我们会讲国际化排上日程。目前extension建议自定义应该也能满足国际化。另外，也欢迎一起大家参与进来，给LogicFlow提PR，我们对PR持开放态度。

**Comment by THUzxj** [comment]
我可以尝试开发国际化相关功能，提供一个`t`函数根据key查找各语言翻译。但是想请问按现在的`core`与`extension`两个`package`并列的情形，若要共享国际化代码，是否可以且有必要添加一个与这两个`package`的新`package`？

**Comment by towersxu** [comment]
可以考虑一个新package，具体看你实现。需要注意目前core是umd格式，请不要把非中文的内容打包进行，国际化支持最好做成按需引入。

**Comment by towersxu** [comment]
@THUzxj 以发布到v1.2.0-alpha.2版本，您可以试试。
