### ISSUE TITLE
导出图片时考虑文本超出范围和图片居中

### ISSUE THREAD

**Issue by AK36** [didi/LogicFlow#573]
**问题描述**  

版本："@logicflow/core": "^1.1.6"  "@logicflow/extension": "^1.1.6"

当节点的名字过长时，导出图片会遮挡左边部分的文字，导致显示补全，应该是计算截图区域时没考虑节点名字的节点，只计算的节点所占区域；并且截图右侧空白区域大于左侧，应该是留白处理时没考虑居中

**最简复现demo**  

![flow-1649992324671](https://user-images.githubusercontent.com/18526128/163512566-2b11391c-3a93-436d-ba95-5758e4795a61.png)

**Comment by muyuanshan** [comment]
有一种解决方案，自定义节点的时候，可以设置换行和调整文字的位置，使图更加美观。
```
  class CustomCircleModel extends CircleNodeModel {
    constructor(data, graphModel) {
      if (!data.text) {
        data.text = "";
      }
      if (typeof data.text === "string") {
        data.text = {
          value: data.text,
          x: data.x,
          y: data.y + 100,
        };
      }
      super(data, graphModel);
    }
    setAttributes() {
      this.r = 30;
    }
    getTextStyle() {
      const style = super.getTextStyle();
      style.overflowMode = 'autoWrap'
      return style;
    }
  }
```
`style.overflowMode = 'autoWrap'` 和 `data.text `设置文案位置
![image](https://user-images.githubusercontent.com/51943988/228186288-14afeb7f-53da-44dd-ab7d-e6593689bd88.png)
