### ISSUE TITLE
@logicflow/extension": "^1.2.0-alpha.0", 这个版本，使用官网这个例子的时候，不能连线也没有报错，版本换回来就好了

### ISSUE THREAD

**Issue by yuanhaotian** [didi/LogicFlow#574]
![image](https://user-images.githubusercontent.com/36318960/163527684-ad890087-4fd1-4e1b-8dfd-bb39f5c8b0f5.png)

**Comment by towersxu** [comment]
我这边没有复现这个问题，如果是本地启动example，需要先build本地的core和extension，这样使用的就是本地build的版本，
