### ISSUE TITLE
使用API getSnapshotBase64 获取base64 报错 css文件出显跨域问题

### ISSUE THREAD

**Issue by lijunjie111** [didi/LogicFlow#575]
**问题描述**  
1. 使用API getSnapshotBase64 获取base64 报错 css文件出现跨域问题
版本 1.1.11  and 1.1.12 其他版本没有试

报错信息 下
![L1VzZXJzL2xpanVuamllL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9pRGluZ1RhbGsvMTU4OTYxNDM0MV92Mi9JbWFnZUZpbGVzLzE2NTAwMDQ5OTUzNjdfNDBCOEIyRDItMTEzOC00MDUyLTlDNjUtOUU3OUUxNEUzNUFGLnBuZw==](https://user-images.githubusercontent.com/98576530/163533274-5f4e8caf-9572-4feb-b38c-51a1596bfd78.png)

疑似诱因：
![lQLPDhtVed2ijxvNA_bNBWSwbRucFrBDBmECXLeWMwDIAA_1380_1014](https://user-images.githubusercontent.com/98576530/163559079-f0eb392c-8401-4c54-93c0-656935dd18ae.png)

**Comment by towersxu** [comment]
目前下载插件为了保证所有的html节点样式不错乱，会把全局css都加载到canvas中。如果全局css的canvas中存在跨域图片，则会出现这种情况。下个版本会增加忽略全局css和手动添加css的方法，来解决这个问题。

**Comment by pengzai530** [comment]
> 初步怀疑是因为目前下载插件为了保证所有的html节点样式不错乱，会把全局css都加载到canvas中。如果全局css的canvas中存在不允许跨域请求资源，则会出现这种情况。下个版本会增加忽略全局css和手动添加css的方法，来看是否解决这个问题。如果方便，请先帮我们定位一下具体是什么导致的报错。

遇到同样问题确实是因全局中包含跨域的css请求资源,在获取Document.styleSheets中包含跨域文件，cssrules的值就如同报错的图一样，遍历Document.styleSheets就抛出了异常

![image](https://user-images.githubusercontent.com/70130303/170873902-e138035d-2d15-4ac7-88ff-6b123b7f9fc5.png)

**Comment by towersxu** [comment]
在1.1.13版本之后提供了禁用全局css规则的方法。
```js
  lf.extension.snapshot.useGlobalRules = false
  lf.extension.snapshot.customCssRules = `
    .lf-node-text-auto-wrap-content{
      line-height: 1.2;
      background: transparent;
      text-align: center;
      word-break: break-all;
      width: 100%;
    }
    .lf-canvas-overlay {
      background: red;
    }
  `
```
