### ISSUE TITLE
[Bug report] 图上面输入的文字会莫名其妙的偏移位置

### ISSUE THREAD

**Issue by cyt68** [didi/LogicFlow#577]
**问题描述**  
最近更新了LogicFlow的最新版，但发现一个bug就是图上面输入的文字会莫名其妙的偏移位置（不知道如何稳定复现）

下面的”设置属性“本来是写在六边形正中间的

**最简复现demo**  
<img width="197" alt="image" src="https://user-images.githubusercontent.com/20410138/163549372-2536559c-a2dd-44a8-ad94-6fa4f18bc0cc.png">

**Comment by towersxu** [comment]
文本位置也是有文本的x,y来控制的。你可以看看是不是什么情况下影响了文本定位。
