### ISSUE TITLE
changeNodeId 方法发现有点问题

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#579]
changeNodeId 事件可以改变节点id，并且与之相关联边的sourceNodeId，targetNodeId也会发生改变，
但是遗漏了改变sourceAnchorId和targetAnchorId

**Comment by towersxu** [comment]
changeNodeId为什么要修改节点锚点上的id？修改节点的id并代表着修改锚点id。

**Comment by zoujpxyz2017** [comment]
边的sourceAnchorId 和  targetAnchorId 的值是 节点id_0 或节点id_1 ,节点id变了，这里的值也要变的的，边的sourceNodeId，targetNodeId的对应的变了，这应该是统一要变的哈。

**Comment by zoujpxyz2017** [comment]
> 节点

是修改边属性上的对应节点id

**Comment by zoujpxyz2017** [comment]
![image](https://user-images.githubusercontent.com/28721603/164414795-1d471f7f-0e90-441a-afb9-75c93919022d.png)

**Comment by towersxu** [comment]
目前看起来，锚点id的值和节点id的值关联不太合理，会误导使用者截取字符串来获取其所属节点。但是因为锚点id也是可以自定义，所以存在锚点和节点id在字符串上看起来没有关系的情况。如果截取字符串获取就会有问题。目前考虑在v1.2.0版本，锚点id将不再和节点id相关，提供其他方式去获取锚点所属的节点和其位置。
