### ISSUE TITLE
[建议] 给 GraphConfigData 类型添加 properties 属性，便于扩展

### ISSUE THREAD

**Issue by han-feng** [didi/LogicFlow#583]
实际使用中，很多情况下都需存储一些流程整体的属性数据。目前的数据结构仅提供了node和edge的属性扩展。

建议给 GraphConfigData 类型添加 properties 属性，并增加相应API。

**Comment by towersxu** [comment]
感谢提出！确实是一个好想法，可以再1.2.0版本新增。目前我们已经有了graphModel对象，只需要在这个对象上的setProperties方法进行扩展即可。如果您有精力，也欢迎PR。

**Comment by toyang** [comment]
确实，最近在用这个做bpmn流程图，Process元素需要输入一些name之类的属性，Process元素在图中没有节点，迫切需要这个特性，不知道现在这个已经实现了吗？
