### ISSUE TITLE
[Bug report] fitView(offset = 20)方法期望能改成fitView(offsetX = 20, offsetY = 20)

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#585]
**问题描述**  
fitView支持设置画布四周保留一定的间隙，但是在启用左侧拖拽面板的时候，水平和垂直方向的offset用一个值不太合适，期望能同时支持水平和垂直offset.

想要实现的效果是在排除左侧面板后的剩余画布空间内做fitView.

**Comment by towersxu** [comment]
感谢提出，是个很好的需求，目前计划在v1.2.0提供。如果您也精力，也欢迎PR。
