### ISSUE TITLE
[建议] 入门教程

### ISSUE THREAD

**Issue by chenweihan** [didi/LogicFlow#588]
首先该项目确实非常棒，能解决很多需求场景的实际问题,点赞。 我基于Vue3 学习LogicFlow完成了一个入门学习的开源项目，望能挂到README.md 介绍中的Vue的demo推荐列表，也算是为推广贡献点力量，让更多使用vue的人能尽快上手...

LogicFlow&vue3的demo实例 项目地址：https://gitee.com/copperpeas/logicflow-vue3

**Comment by towersxu** [comment]
厉害了，我们后面打算建一个演示栏目，是否可以把您的项目放进去呢？

**Comment by chenweihan** [comment]
可以啊，社区嘛，应该是多人参与...
