### ISSUE TITLE
[问题]流程中打回的线条必须要定位吗？如果不需要怎么处理？

### ISSUE THREAD

**Issue by zhengfs0** [didi/LogicFlow#589]
![MI0)(`4NTN4TJJSV~VBDAT8](https://user-images.githubusercontent.com/104049238/164145169-b0357a9e-4593-4a16-b382-05aa4f412718.png)

![@(Z~W 2Q YB3{@O~K8UD0)3](https://user-images.githubusercontent.com/104049238/164145200-0776e722-e8f2-4f0c-a246-26be3eb4857e.png)

如图，打回到前节点时，不写位置的话，线条重叠在一起了

![3 PSLRPTQR~A1S8`GHU%9~W](https://user-images.githubusercontent.com/104049238/164145294-681e8520-218b-47ff-a4d0-04a9a2bf2879.png)

**Comment by towersxu** [comment]
logicflow默认自身不带布局相关算法。看你的情况图本身不算复杂，可以自己算一下。
