### ISSUE TITLE
[提问]有类似传入json对象，生成流程图的例子或方法吗？

### ISSUE THREAD

**Issue by zhengfs0** [didi/LogicFlow#591]
如图，把logicflow定义为一个组件，使用者传入json对象，即可生成流程图。

![image](https://user-images.githubusercontent.com/104049238/164146422-374c9132-1f11-4c23-b512-e510206e539d.png)

![image](https://user-images.githubusercontent.com/104049238/164146596-a2977b94-9def-4289-9841-c66590745c85.png)

请问有没有类似的例子，传入的对象需要哪些字段数据，节点的位置x，y怎么处理

**Comment by towersxu** [comment]
这个你用vue和logicflow组合一下就好了。logicflow数据格式参考这里http://logic-flow.org/guide/start.html#%E7%BB%98%E5%88%B6%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E6%B5%81%E7%A8%8B%E5%9B%BE

**Comment by towersxu** [comment]
重复 #590

**Comment by ForeverCZ** [comment]
比如这个json数据就是后端返回的结构，这个坐标点x,y怎么处理呢，如何动态去自适应画布生成流程图？

**Comment by yuanhaotian** [comment]
你这个xy坐标，最后怎么处理？ @ForeverCZ
