### ISSUE TITLE
[Bug report] 边上的文本设置背景色后，不支持设置padding

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#592]
**问题描述**  
1. 问题触发的条件
    边的文本设置背景色，背景色矩形和文本之间没有保留间隙。setTheme中的edgeText配置使用了wrapPadding参数不起作用

2. 期望的表现
   背景色矩形和文本之间能配置间隙（类似于padding效果），效果更美观

**Comment by wangzhengbo** [comment]
LineText.tsx的
} else {
        // 计算文本中最长的一行的字节数
        let longestBytes = 0;
        rows && rows.forEach(item => {
          const rowByteLength = getBytesLength(item);
          longestBytes = rowByteLength > longestBytes ? rowByteLength : longestBytes;
        });
        // 背景框宽度，最长一行字节数/2 * fontsize + 2
        // 背景框宽度， 行数 * fontsize + 2
        const { width, height } = getSvgTextWidthHeight({ rows, fontSize, rowsLength });
        rectAttr = {
          ...backgroundStyle,
          x: x - 1,
          y: y - 1,
          width,
          height,
        };
      }
      return <Rect {...rectAttr} />;
部分
如果设置了left + right padding 分别为20，这里width设置成widtth + 10, x设置成x - 1 - (10  / 2)就行。上下padding是类似的处理。

**Comment by towersxu** [comment]
嗯，是的，也欢迎您提PR。

**Comment by wangzhengbo** [comment]
> 
好

**Comment by wangzhengbo** [comment]
> 嗯，是的，也欢迎您提PR。

这个仓库fork不了了，超出了数量限制。

**Comment by towersxu** [comment]
@wangzhengbo 不应该吧，我刚试了可以继续fork的。

**Comment by towersxu** [comment]
已发布在1.1.15版本， 使用方式为:
```js
class CustomPolylineModel extends PolylineEdgeModel {
  getTextStyle() {
    return {
      fontSize: 12,
      autoWrap: true,
      lineHeight: 1.5,
      background: {
        fill: '#ff00ff',
        wrapPadding: '5px,12px',
      }
    };
  }
}
```
