### ISSUE TITLE
[Bug report] SelectionSelect插件能支持拖拽选择多个节点和边，能不能支持隔着节点选择呢？

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#594]
**问题描述**  
SelectionSelect插件能支持拖拽选择多个节点和边，能不能支持隔着节点选择呢？
类似于文件管理器中按着Ctrl并点击文件或者文件夹来选择，这样可以选择不连续的节点或者边。

**Comment by towersxu** [comment]
目前已有点击按钮开启多选的功能，将API中的[multipleSelectKey](http://logic-flow.org/api/logicFlowApi.html#constructor)

**Comment by wangzhengbo** [comment]
> 目前已有点击按钮开启多选的功能，将API中的[multipleSelectKey](http://logic-flow.org/api/logicFlowApi.html#constructor)

多谢，很好用的功能。
