### ISSUE TITLE
[Feature Request] 删除、复制等方法增加中间件机制

### ISSUE THREAD

**Issue by ly525** [didi/LogicFlow#595]
目前 logic flow 提供了复制节点、删除节点、复制Line、删除Line的能力

在删除这种危险场景里，业务侧一般是希望可以进行二次确认的，是否可以考虑类似 iview、element、ant 的upload 组件的中，类似 beforeUpload 一样的拦截器注册/配置能力

支持传入一个promise，类似中间件模式，进行能力注入，可以做一些拦截等操作

**Comment by boyongjiong** [comment]
我理解菜单操作应该都可以自定义，应该可以按照自己的需要封装对应的方法。目前没有规划支持该功能，暂时将该 issue 关闭归档处理
