### ISSUE TITLE
[Bug report]当一个源节点有多个子节点时，删除某个子节点报错

### ISSUE THREAD

**Issue by maohui66661** [didi/LogicFlow#597]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
    当一个源节点有多个子节点时，且源节点与子节点之间有连线。当删除某个子节点时，报错。
    版本：1.1.14
3. 期望的表现
 正常删除某个节点与边。
5. 实际的表现
![image](https://user-images.githubusercontent.com/7902405/165269204-cc6de890-e8ee-414b-9aaf-3039e64b3bff.png)

**最简复现demo**  
demo：https://codesandbox.io/s/condescending-wilbur-wut0pp?file=/src/App.js
复现步骤：从左到右一次点击画布上方按钮，当执行到最后一步时报错。

**Comment by towersxu** [comment]
方法用错了。因为注册的时候没有区分节点和连线，所以边任然会显示出来。但是这里会被当做一个节点。
<img width="609" alt="image" src="https://user-images.githubusercontent.com/4093984/165270869-247f95b2-224a-4ca9-b162-114261243846.png">
