### ISSUE TITLE
BPMN添加泳道支持

### ISSUE THREAD

**Issue by sunnyguohua** [didi/LogicFlow#599]
BPMN是否可以添加泳道，实现效果参考：
https://online.visual-paradigm.com/diagrams/templates/business-process-diagram/pizza-order-process/

**Comment by towersxu** [comment]
对数据格式有什么要求吗？如果可以，请带上你需要最终的数据格式，以及数据格式中各字段含义。

**Comment by cyt68** [comment]
> 对数据格式有什么要求吗？如果可以，请带上你需要最终的数据格式，以及数据格式中各字段含义。

@towersxu 请问泳道现在支持了吗？

**Comment by gaofengbj** [comment]
数据格式应该是业务层面的， 其实就是实现那种组织架构图，在泳道内可以加入其他图形
<img width="506" alt="111" src="https://user-images.githubusercontent.com/1658100/212645124-0affd0ea-dcab-41f5-ad2f-9f82ff380739.png">
