### ISSUE TITLE
[Feature Request] 框选与拖动画布同时存在

### ISSUE THREAD

**Issue by duansheli** [didi/LogicFlow#600]
## 现有版本的方案 
默认是 左键 可以拖动画布   
左键也可以拖动节点  
当用户点击选区后 左键就变为框选 而非拖动画布 

但是 框选与拖动画布 只能二选一 

## 建议改进 
拖动画布 保持左键   
框选 使用右键  
这样的话 二者就可以同时存在

**Comment by towersxu** [comment]
在框选的时候禁止画布移动，在框选结束后开启移动就好了。
