### ISSUE TITLE
VUE框架中重复进入到Logicflow页，点击节点右键事件重复触发

### ISSUE THREAD

**Issue by tongtie** [didi/LogicFlow#61]
**问题描述**  
第一次进入到有默认数据的LogicFlow页，点击节点右键事件触发正常。
然后回退到其他页，再次进入到LogicFlow页，再次点击节点右键事件，就会多触发一次,
... 重复上述动作，每进入到LogicFlow页，右键事件触发次数多增加一次

![image](https://user-images.githubusercontent.com/2959046/110429458-f61e9e80-80e5-11eb-9dc4-f78bda98f355.png)

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
windows10和ubuntu14
2. 浏览器类型 （chrome80 或者 IE11）
chrome88（windows）和chrome87（ubuntu）

**最简复现demo**  
对首页提供的vue demo，进行了修改，可以复现此bug

https://github.com/tongtie/logicflow_vue_demo.git

1. 从首页点击LogicFlow按钮，进入到LogicFlow页
![image](https://user-images.githubusercontent.com/2959046/110429815-6f1df600-80e6-11eb-85fb-1a46f88798b7.png)
2. 在LogicFlow页，点击回退按钮，回退到首页
![image](https://user-images.githubusercontent.com/2959046/110429892-8826a700-80e6-11eb-8496-44486cd127a6.png)
3. 重复上述步骤，然后点击节点属性，发现触发了多次，并报错误（如问题描述中的图片所示）

感觉是Menu中的click事件多次注册导致。
前端新手，也有可能是vue框架结合Logicflow用的不对，没有写组件销毁啥的导致，请帮忙定位下，谢谢

**Comment by towersxu** [comment]
请升级到最新版再尝试，此问题应已修复。
