### ISSUE TITLE
能否支持动画呢，即提供一个路径，可以实现从开始到结束的一个动画流转

### ISSUE THREAD

**Issue by kangshifu1** [didi/LogicFlow#611]
**问题描述**  
1. 问题触发的条件
  设置一个基本流程
3. 期望的表现
  可以点击顶部的时候，触发一个可以定义一个动画
5. 实际的表现
目前不支持定义线的动态

**Comment by towersxu** [comment]
在边最新版本已支持动画。http://logic-flow.org/guide/basic/edge.html#%E7%BB%99%E8%BE%B9%E5%BC%80%E5%90%AF%E5%8A%A8%E7%94%BB
