### ISSUE TITLE
排他网关 内的判断数据会被放在properties 中以 #text 展现

### ISSUE THREAD

**Issue by ljjingone** [didi/LogicFlow#612]
**问题描述**  
排他网关 内的判断数据会被放在properties 中以 #text 展现
<bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">${operationType == 'agree'}</bpmn:conditionExpression>

**最简复现demo**  
xml数据
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
    xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
    xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
    xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
    xmlns:flowable="http://flowable.org/bpmn" 
    id="diagram_flowLeave" 
    targetNamespace="http://flowable.org/bpmn" 
    xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL bpmn0.xsd">
    <bpmn:process id="flowLeave" name="请假申请" isExecutable="true">
        <bpmn:startEvent id="Event_1c9ukkq">
            <bpmn:outgoing>Flow_05fy9wh</bpmn:outgoing>
        </bpmn:startEvent>
        <bpmn:userTask id="Activity_0sc2yuf" name="请假录入" flowable:formKey="{&#34;formId&#34;:&#34;1440945411354267648&#34;,&#34;readOnly&#34;:false,&#34;groupType&#34;:&#34;USERS&#34;}" flowable:candidateUsers="${startUserName},12345,userA">
            <bpmn:extensionElements>
                <flowable:operationList>
                    <flowable:formOperation id="1632387369558" label="提交" type="agree" showOrder="0" />
                </flowable:operationList>
                <flowable:variableList />
                <flowable:userCandidateGroups type="USERS" value="${startUserName},leaderHR,userA" />
                <flowable:copyItemList>
                    <flowable:copyItem id="" type="deptPostLeader" />
                </flowable:copyItemList>
            </bpmn:extensionElements>
            <bpmn:incoming>Flow_05fy9wh</bpmn:incoming>
            <bpmn:incoming>Flow_012hd4v</bpmn:incoming>
            <bpmn:outgoing>Flow_0pme0vr</bpmn:outgoing>
        </bpmn:userTask>
        <bpmn:sequenceFlow id="Flow_05fy9wh" sourceRef="Event_1c9ukkq" targetRef="Activity_0sc2yuf" />
        <bpmn:userTask id="Activity_1jw5u20" name="部门领导审批" flowable:formKey="{&#34;formId&#34;:&#34;1440945411354267648&#34;,&#34;readOnly&#34;:true,&#34;groupType&#34;:&#34;POST&#34;}" flowable:candidateGroups="selfDeptPost__1440964131539652608">
            <bpmn:extensionElements>
                <flowable:operationList>
                    <flowable:formOperation id="1632387389734" label="同意" type="agree" showOrder="0" />
                    <flowable:formOperation id="1632387393116" label="拒绝" type="refuse" showOrder="1" />
                </flowable:operationList>
                <flowable:variableList />
                <flowable:copyItemList />
                <flowable:deptPostList>
                    <flowable:deptPost id="selfDeptPost__1440964131539652608" type="selfDeptPost" postId="1440964131539652608" />
                </flowable:deptPostList>
            </bpmn:extensionElements>
            <bpmn:incoming>Flow_0pme0vr</bpmn:incoming>
            <bpmn:outgoing>Flow_1hbob37</bpmn:outgoing>
            <bpmn:outgoing>Flow_012hd4v</bpmn:outgoing>
        </bpmn:userTask>
        <bpmn:sequenceFlow id="Flow_0pme0vr" sourceRef="Activity_0sc2yuf" targetRef="Activity_1jw5u20" />
        <bpmn:userTask id="Activity_0olxatv" name="HR审批" flowable:formKey="{&#34;formId&#34;:&#34;1440945411354267648&#34;,&#34;readOnly&#34;:true,&#34;groupType&#34;:&#34;POST&#34;}" flowable:candidateGroups="deptPost__1440964221780103168">
            <bpmn:extensionElements>
                <flowable:variableList />
                <flowable:copyItemList />
                <flowable:deptPostList>
                    <flowable:deptPost id="deptPost__1440964221780103168" type="deptPost" deptPostId="1440964221780103168" />
                </flowable:deptPostList>
                <flowable:operationList>
                    <flowable:formOperation id="1632388147727" label="同意" type="agree" showOrder="0" />
                    <flowable:formOperation id="1641827181937" label="驳回到起点" type="rejectToStart" showOrder="1" />
                </flowable:operationList>
            </bpmn:extensionElements>
            <bpmn:incoming>Flow_1hbob37</bpmn:incoming>
            <bpmn:outgoing>Flow_0so810a</bpmn:outgoing>
        </bpmn:userTask>
        <bpmn:sequenceFlow id="Flow_1hbob37" name="同意" sourceRef="Activity_1jw5u20" targetRef="Activity_0olxatv">
            <bpmn:extensionElements>
                <flowable:customCondition type="operation" operationType="agree" />
            </bpmn:extensionElements>
            <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">${operationType == 'agree'}</bpmn:conditionExpression>
        </bpmn:sequenceFlow>
        <bpmn:endEvent id="Event_04byxr7">
            <bpmn:incoming>Flow_0so810a</bpmn:incoming>
        </bpmn:endEvent>
        <bpmn:sequenceFlow id="Flow_0so810a" name="同意" sourceRef="Activity_0olxatv" targetRef="Event_04byxr7">
            <bpmn:extensionElements>
                <flowable:customCondition type="operation" operationType="agree" />
            </bpmn:extensionElements>
            <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">${operationType == 'agree'}</bpmn:conditionExpression>
            
        </bpmn:sequenceFlow>
        <bpmn:sequenceFlow id="Flow_012hd4v" name="拒绝" sourceRef="Activity_1jw5u20" targetRef="Activity_0sc2yuf">
            <bpmn:extensionElements>
                <flowable:customCondition type="operation" operationType="refuse" />
            </bpmn:extensionElements>
            <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">${operationType == 'refuse'}</bpmn:conditionExpression>
        </bpmn:sequenceFlow>
    </bpmn:process>
    <bpmndi:BPMNDiagram id="BPMNDiagram_1">
        <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="flowLeave">
            <bpmndi:BPMNEdge id="Flow_012hd4v_di" bpmnElement="Flow_012hd4v">
                <di:waypoint x="430" y="300" />
                <di:waypoint x="430" y="270" />
                <di:waypoint x="270" y="270" />
                <di:waypoint x="270" y="300" />
                <bpmndi:BPMNLabel>
                    <dc:Bounds x="339" y="252" width="22" height="14" />
                </bpmndi:BPMNLabel>
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="Flow_0so810a_di" bpmnElement="Flow_0so810a">
                <di:waypoint x="640" y="340" />
                <di:waypoint x="702" y="340" />
                <bpmndi:BPMNLabel>
                    <dc:Bounds x="660" y="322" width="23" height="14" />
                </bpmndi:BPMNLabel>
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="Flow_1hbob37_di" bpmnElement="Flow_1hbob37">
                <di:waypoint x="480" y="340" />
                <di:waypoint x="540" y="340" />
                <bpmndi:BPMNLabel>
                    <dc:Bounds x="499" y="322" width="23" height="14" />
                </bpmndi:BPMNLabel>
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="Flow_0pme0vr_di" bpmnElement="Flow_0pme0vr">
                <di:waypoint x="320" y="340" />
                <di:waypoint x="380" y="340" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="Flow_05fy9wh_di" bpmnElement="Flow_05fy9wh">
                <di:waypoint x="168" y="340" />
                <di:waypoint x="220" y="340" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNShape id="Event_1c9ukkq_di" bpmnElement="Event_1c9ukkq">
                <dc:Bounds x="132" y="322" width="36" height="36" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Activity_0sc2yuf_di" bpmnElement="Activity_0sc2yuf">
                <dc:Bounds x="220" y="300" width="100" height="80" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Activity_1jw5u20_di" bpmnElement="Activity_1jw5u20">
                <dc:Bounds x="380" y="300" width="100" height="80" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Activity_0olxatv_di" bpmnElement="Activity_0olxatv">
                <dc:Bounds x="540" y="300" width="100" height="80" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Event_04byxr7_di" bpmnElement="Event_04byxr7">
                <dc:Bounds x="702" y="322" width="36" height="36" />
            </bpmndi:BPMNShape>
        </bpmndi:BPMNPlane>
    </bpmndi:BPMNDiagram>
</bpmn:definitions>

**Comment by ljjingone** [comment]
如图
![image](https://user-images.githubusercontent.com/24402187/168017621-4f175722-a3e0-443d-be83-c09af5017b52.png)

**Comment by wumail** [comment]
这样做会导致什么问题？

**Comment by wumail** [comment]
符合该插件的预期
