### ISSUE TITLE
二个节点间连多条线，会存在连线覆盖的情况

### ISSUE THREAD

**Issue by LeeScofield** [didi/LogicFlow#616]
![image](https://user-images.githubusercontent.com/28806015/168196151-79cfd823-ff1b-48a0-8094-87c9c560bbee.png)
像上面图片那样，有没有办法做到，二个点连多条线时，线只通过id ，不通过坐标相连时，能自动优化匹配锚点，现在是后面那条线把前面的覆盖了，看上去只有一条线。
下面是参数：
nodes: [
            {
              id: "1",
              type: "rect",
              x: 900,
              y: 100,
              text: "这是一个很长很长有点离谱的状态",
              properties:{
                text:'hello',
                type: 'ongoing'
              }
            },
            {
              id: "2",
              type: "rect",
              x: 300,
              y: 200,
              text: "节点2"
            }
          ],
          edges: [
            {
              sourceNodeId: "1",
              targetNodeId: "2",
              type: "bezier",
              text: "连线1",
             /* startPoint:{x:850,y:110},
              endPoint:{x:350,y:210}*/
            },
            {
              sourceNodeId: "2",
              targetNodeId: "1",
              type: "bezier",
              text: "连线2"
            }
          ]

**Comment by towersxu** [comment]
嗯，是一个可以优化的点，欢迎PR，可以考虑在获取跳转点的时候加一个随机值，这样曲线就不会重合了。

**Comment by LeeScofield** [comment]
随机不行， 要算坐标定下来，随机多条线会有线交叉的情况，还有拖拽以后锚点不能自适应，看着好难受
![image](https://user-images.githubusercontent.com/28806015/168199520-897f4816-72ec-41ea-87df-1f2d14ecb42b.png)

**Comment by towersxu** [comment]
连线交叉这个问题目前确是没有好的想法，这种情况目前我们建议考虑用https://github.com/d3/d3-hierarchy去自动布局。如果你有更好的想法，欢迎提出来。

**Comment by LeeScofield** [comment]
找到了  https://x6.antv.vision/zh/examples/gallery
