### ISSUE TITLE
[Bug report] setTheme部分有效部分无效

### ISSUE THREAD

**Issue by zqy233** [didi/LogicFlow#617]
**问题描述**  
版本为 "@logicflow/core": "^1.1.15"
使用`ls.setTheme`设置节点样式，宽高一直无效，但奇怪的是填充色边框色有效，这样就很奇怪，还是哪里写错了嘛

**最简复现demo**  
我是基于vue-cli直接创建的一个vue2项目，直接导入@logicflow/core，app.vue中代码如下
```vue
<template>
  <div>
    <div id="container"></div>
  </div>
</template>

<script>
import LogicFlow from "@logicflow/core"
import "@logicflow/core/dist/style/index.css"

export default {
  name: "home",
  mounted() {
    const data = {
      nodes: [
        {
          id: 50,
          type: "rect",
          x: 160,
          y: 150,
          text: "hello"
        }
      ]
    }
    const lf = new LogicFlow({
      container: document.querySelector("#container"),
      width: 700,
      height: 600,
      grid: {}
    })

    // 设置矩形主题
    lf.setTheme({
      rect: {
        width: 260, // 无作用
        height: 40, // 无作用
        fill: "#87CEFA", // 有作用
        stroke: "#1E90FF", // 有作用
        radius: 20 // 无作用
      }
    })

    lf.render(data)
  }
}
</script>

```

**Comment by zqy233** [comment]
试了下相同的代码，0.7.16版本是可以正常设置宽高的，之后的版本，宽高就无效了

**Comment by towersxu** [comment]
在1.0版本，logicflow将节点属性分为了样式属性和形状属性。width、height这种属于形状数据，不再支持主题中设置。http://logic-flow.org/guide/basic/node.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%80%E4%B8%AA%E4%B8%9A%E5%8A%A1%E8%8A%82%E7%82%B9

**Comment by zqy233** [comment]
> 在1.0版本，logicflow将节点属性分为了样式属性和形状属性。width、height这种属于形状数据，不再支持主题中设置。http://logic-flow.org/guide/basic/node.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%80%E4%B8%AA%E4%B8%9A%E5%8A%A1%E8%8A%82%E7%82%B9

感谢解答
