### ISSUE TITLE
[Bug report] 打开框选时点击鼠标右键会开始框选，选框无法正常消失

### ISSUE THREAD

**Issue by zhuqingguang** [didi/LogicFlow#618]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
   a. 打开框选
   b. 点击鼠标右键，会出现浏览器菜单，并开始框选
   c. 再次点击右键，出现菜单并结束框选
   d. 再在其他地方点一下右键，原来的选框不会消失
2. 期望的表现
   开启框选功能时，点击鼠标右键时不会触发框选或者不会弹出浏览器菜单。结束后选框能正常消失。

3. 实际的表现
 开启框选功能时，点击鼠标右键时会触发框选并弹出浏览器菜单。结束后选框不能正常消失。

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
https://codesandbox.io/s/logicflow-selection-m0bn4r?from-embed=&file=/examples/025_selection/index.js

**Comment by towersxu** [comment]
嗯，这里是一个问题，欢迎PR。

**Comment by zhuqingguang** [comment]
> 嗯，这里是一个问题，欢迎PR。

https://github.com/didi/LogicFlow/pull/647 已提PR
