### ISSUE TITLE
请问如何动态添加锚点？

### ISSUE THREAD

**Issue by FabricateDeng** [didi/LogicFlow#620]
想可以通过事件修改锚点数量和位置

**Comment by towersxu** [comment]
可以的。http://logic-flow.org/guide/basic/node.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E7%9A%84%E9%94%9A%E7%82%B9 getDefaultAnchor基于properties的内容动态改变返回结果就行。
