### ISSUE TITLE
关于edge 中文本不可以指定位置

### ISSUE THREAD

**Issue by zouk688** [didi/LogicFlow#628]
edge 中的文本的默认位置修改后保存在显示出来位置还在是在默认地方 "text":
{
"x":
165,
"y":
-238.94117647058832,
"value":
"xxxxx"
}   这里的X，Y 不管用

**Comment by towersxu** [comment]
请提供在线示例，我这边没有复现这个问题。https://codesandbox.io/s/logicflow-base25-forked-w4lejx?file=/step_25_customEdgeTextPosition/index.js。看你的描述感觉像是你数据问题。

**Comment by zouk688** [comment]
我这里没有办法用那个复现工具，都打不开
![image](https://user-images.githubusercontent.com/7833780/170273325-a0fb7cc4-5a6d-4bd6-804d-bc9b7df97ad4.png)
问题是这里的文本修改完位置后保存，在打开的时候这里的文本位置就变到其它位置了，不是我调整的位置
