### ISSUE TITLE
[功能需求] 如何自定义edge中文本菱形形状

### ISSUE THREAD

**Issue by XiaoBaiClassmate** [didi/LogicFlow#630]
![20220526153410](https://user-images.githubusercontent.com/39209286/170441144-cfc7c66e-68c0-41ce-be94-7e82218add32.png)

**Comment by towersxu** [comment]
这不是一个菱形节点吗？

**Comment by XiaoBaiClassmate** [comment]
@[towersxu](https://github.com/towersxu) 是的，我想自定义edge中文本样式为菱形，这点可以实现吗？我参考《基于React组件自定义边》里实现菱形，效果还不如默认配置的好~

**Comment by towersxu** [comment]
你可以参考源码，重写getText方法。

**Comment by XiaoBaiClassmate** [comment]
@towersxu 你好请问是重写`getTextStyle`方法吗？如果是的话，可能不太适合我。其实我就是想把edge中的文本样式`react` 替换`diamond`。
