### ISSUE TITLE
多次渲染内存泄漏，内存不释放且无法释放

### ISSUE THREAD

**Issue by lingyucao** [didi/LogicFlow#645]
项目默认约内存占200m,不间断渲染，内存达到1.5g回释放到1g多点，就不会释放了，再点会继续增加。浏览器会变慢直达无响应

**Comment by towersxu** [comment]
请问有示例吗？我们这边测试调用LogicFlow的组件销毁了，内存就会回收了。

**Comment by s-boaz** [comment]
> 我们有示例吗？我们这个测试逻辑流程的组件有不同，请尽快回收。

自定义html节点，deleteNode后，dom和内部的obj会被回收吗

**Comment by Panweitong** [comment]
我这边也遇到了这种情况，多次渲染后页面会很卡，直至卡死

**Comment by wumail** [comment]
> 我这边也遇到了这种情况，多次渲染后页面会很卡，直至卡死

需要具体看你的使用方式，看看页面或者组件是不是正常销毁的
