### ISSUE TITLE
连接线 不能使用backspace进行删除

### ISSUE THREAD

**Issue by qwertor-5678** [didi/LogicFlow#648]
操作地址：http://logic-flow.org/mvp/index.html 
os系统：macOS
问题描述：backspace可以删除框图形，但是删除不掉连接线。

**Comment by towersxu** [comment]
感谢提出。目前mvp在试用我们的开发版本，还有很多问题，你可以先试用正式版本。

**Comment by qwertor-5678** [comment]
操作地址：http://logic-flow.org/mvp/index.html
os系统：macOS
已测试，可以backspace可以删除 连接线，👍🏻

**Comment by RandallYin1** [comment]
@qwertor-5678  这个实例有源码吗？我的快捷键删除连线报一个错，想看看你的删除连线是怎么写的，我用的框架是vue
