### ISSUE TITLE
自定义onclick事件，需要按钮两次才能触发事件

### ISSUE THREAD

**Issue by ddw-327** [didi/LogicFlow#654]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
2. 期望的表现
3. 实际的表现

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 在任意在线编码平台，编写示例如[codesanbox](https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js。将其保存到自己空间，然后贴上链接。
2. 在自己github中创建一个最简单的示例，然后贴上github链接。
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by towersxu** [comment]
请提供在线可运行的示例，或者看看是否是这个issue相同的问题。https://github.com/didi/LogicFlow/issues/338

**Comment by ddw-327** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by ddw-327** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
