### ISSUE TITLE
节点拖拽时报错，版本1.1.18

### ISSUE THREAD

**Issue by johntangna** [didi/LogicFlow#655]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 节点拖拽改变大小时候
2. Uncaught (in promise) Error: The same observable object cannot appear twice in the same tree, trying to assign it to '/nodeHanlder', but it already exists at '/nodeHanlder'

**Comment by towersxu** [comment]
请提供在线示例

**Comment by johntangna** [comment]
好的，等稍晚一些

**Comment by johntangna** [comment]
已换版本
