### ISSUE TITLE
[new feature]建议 delete快捷键加入默认快捷键。

### ISSUE THREAD

**Issue by songyx** [didi/LogicFlow#656]
**问题描述**  

delete符合使用直觉，我是研究了两天才知道快捷键的事儿。还写了两句代码才增加了delete快捷键。
另外应该默认增加删除功能入口，新增提供了，删除也是必须的，否则没有形成用户操作习惯的闭环，操作demo时就很难受。

**Comment by towersxu** [comment]
目前我们更习惯backspace键删除。只要默认开启快捷键，就可以按这个键删除。
