### ISSUE TITLE
对齐线snapline自定义设置无效，guards无法触发beforeClone事件

### ISSUE THREAD

**Issue by Clayeee** [didi/LogicFlow#66]

**Comment by Clayeee** [comment]
### 问题描述

#### 克隆节点事件拦截失败
1. 初始化配置，开启快捷键，监听节点拷贝，节点删除事件并拦截。

![image](https://user-images.githubusercontent.com/34047473/110751956-89d7a280-827f-11eb-8521-7c170a9f42eb.png)

2. delete节点正常触发beforeDelete，ctrl+c， ctrl+v无法触发beforeClone

![image](https://user-images.githubusercontent.com/34047473/110752168-db802d00-827f-11eb-99fa-fb9a10eca490.png)

#### 自定义对齐线无效
1. 初始化配置，开启对齐线并设置对齐线自定义样式

![image](https://user-images.githubusercontent.com/34047473/110752288-08344480-8280-11eb-9150-b8e1697b9862.png)

2. 对齐线正常显示，单自定义样式失效

![image](https://user-images.githubusercontent.com/34047473/110752405-30bc3e80-8280-11eb-8359-ed9b5eddfad3.png)

### 问题版本
> 0.2.7，0.2.9

**Comment by yhlchao** [comment]
@Clayeee 

**问题1:**
fixed in #69 

**问题2:**
fixed in #65 

对齐线的样式的配置方式：
```ts
lf.setTheme({
   snapline: {
     stroke: '#1E90FF', // 对齐线颜色
     strokeWidth: 1, // 对齐线宽度
   },
 })
```
宽度应该是`strokeWidth`而不是`verticalLength`
