### ISSUE TITLE
[功能需求] 树状布局

### ISSUE THREAD

**Issue by ForeverCZ** [didi/LogicFlow#660]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
2. 期望的表现
通过数据驱动，动态添加一个子节点，子节点可以自适应位置，同时整个画布的节点，也能自适应位置。
4. 实际的表现
**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 在任意在线编码平台，编写示例如[codesanbox](https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js。将其保存到自己空间，然后贴上链接。
2. 在自己github中创建一个最简单的示例，然后贴上github链接。
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by towersxu** [comment]
建议考虑https://github.com/d3/d3-hierarchy或者[https://github.com/antvis/hierarchy](https://github.com/d3/d3-hierarchy)。
