### ISSUE TITLE
节点布局后，自定义锚点的edge位置信息不准确

### ISSUE THREAD

**Issue by Alan0827** [didi/LogicFlow#663]
**问题描述**  
节点布局后，自定义锚点的edge 位置信息不准确，希望帮忙给个简单的demo  😀

**最简复现demo**  
![image](https://user-images.githubusercontent.com/22651795/174758994-79f6e03c-6184-4278-bd88-0dc330c4b6ac.png)

https://codesandbox.io/s/logicflow-base17-forked-7jlkps?file=/step_17_customAnchor/index.js

**Comment by towersxu** [comment]
对dagre的布局功能不太了解，但是目前大多数布局算法不支持节点宽高不同。这个你可以看看是不是dagre也不支持。另外，我看这个已经标注`DEPRECATED`，建议考虑换成https://github.com/d3/d3-hierarchy或者https://github.com/antvis/hierarchy。

**Comment by Alan0827** [comment]
你好，谢谢回复！是的，考虑换了，但是我的意思是 节点坐标变动后，获取节点对应的锚点之间的连线坐标不准确，节点布局后，节点的锚点坐标是正确的，这个应该和用什么布局没有关系。

**Comment by Alan0827** [comment]
谢谢回复！通过测试，我发现重新渲染画布的时候（render或graphDataToModel），布局后节点的位置被重新改变了，靠边的节点都会有轻微的移动，锚点的edge 起终点坐标是准确的。我通过动态删除edge，添加edge重新弄了一下是可以的。示例：https://codesandbox.io/s/logicflow-base17-forked-7jlkps?file=/step_17_customAnchor/index.js
