### ISSUE TITLE
[Bug report]使用缩放 放大节点之后，再度修改边框虚线（strokeDasharray）之后报错

### ISSUE THREAD

**Issue by lengthy-daydream** [didi/LogicFlow#667]
报错信息：The same observable object cannot appear twice in the same tree, trying to assign it to '/nodeSize', but it already exists at '/nodeSize'
![image](https://user-images.githubusercontent.com/58502519/176334657-4c663d8b-f68b-43ff-b553-4be210343103.png)

**Comment by yanbin2019** [comment]
快捷样式组件（QuickStyle）代码：
<img width="633" alt="image" src="https://user-images.githubusercontent.com/58502519/176335699-42d6488f-dfda-49c6-965d-24f22553d45c.png">
页面使用组件（QuickStyle）代码：

<img width="826" alt="image" src="https://user-images.githubusercontent.com/58502519/176335827-e68079f4-60ff-43f1-9148-55c2a4e33e51.png">

**Comment by yanbin2019** [comment]
我定位了一下，好像是这个方法有问题：setProperties
但是页面会正常改变
<img width="591" alt="image" src="https://user-images.githubusercontent.com/58502519/176336791-f733aba2-0389-41c2-b4d3-ad6b9cbcd64d.png">
![image](https://user-images.githubusercontent.com/58502519/176336852-f19b163b-e1dc-450a-9a16-21645dd2049d.png)

**Comment by towersxu** [comment]
有codesandbox示例吗？我不确定这个问题是否已经修复过了。

**Comment by yanbin2019** [comment]
> 我有这个问题和盒子示例吗？

没有，这可能是vue3的问题，强制希望大佬能出一份vue3、ts、使用setup语法的示例
