### ISSUE TITLE
[Bug report]曲线拖动节点不随着改变，并报错

### ISSUE THREAD

**Issue by yanbin2019** [didi/LogicFlow#668]
直线和折线拖动正常，曲线拖动报错
![image](https://user-images.githubusercontent.com/58502519/176386885-f7d61d03-29fe-4eb2-8c07-fde6314fcd0b.png)
![image](https://user-images.githubusercontent.com/58502519/176386929-c5bc1736-b29c-4f61-bbfc-388b2bc3763e.png)

**Comment by yanbin2019** [comment]
我用官方自带的节点和边测试，也报这个错误
<img width="697" alt="image" src="https://user-images.githubusercontent.com/58502519/176388983-6edbe3d2-e16e-4cff-9236-7e63c23bc67e.png">
![image](https://user-images.githubusercontent.com/58502519/176389007-90ba0f8e-893e-4a02-80e9-b8d641c31e27.png)

**Comment by towersxu** [comment]
请提供在线codesandbox示例，我这边并没有复现这个问题
