### ISSUE TITLE
问题请求：重合连线如何禁用点击事件

### ISSUE THREAD

**Issue by bujiangjiuzhang** [didi/LogicFlow#670]

**Comment by bujiangjiuzhang** [comment]
![A_6ODSTFLFWKTAD(OAZPQTF](https://user-images.githubusercontent.com/33220627/176396146-1244c407-a877-49ea-9315-b6dfb34dbc27.png)
如上图所示，一个节点指向其他两个节点的连线如果有重合的地方，如红色框选处所示，如何可以做到两条线非重合部分可以触发点击事件而禁止重合部分触发呢（问题：重合之后点击重合部分只能触发其中一条线的点击事件，想要禁用重合部分的点击事件）

**Comment by towersxu** [comment]
通过监听edge:click，点击重合的连线，并没法发现触发两次事件。
