### ISSUE TITLE
[Bug report]vite环境build打包部署运行后 报错 LogicFlow.use is not a function

### ISSUE THREAD

**Issue by blurries** [didi/LogicFlow#671]
**问题描述**  
vite环境build打包部署运行后 报错 LogicFlow.use is not a function
<img width="551" alt="54f9b9dae75aacb3b28a45211e017f3" src="https://user-images.githubusercontent.com/16989791/176430006-0d0595eb-d8a0-47f1-8afd-beb853535bf5.png">
LogicFlow1.1.19版本
![image](https://user-images.githubusercontent.com/16989791/176431877-2bf48f11-e069-4c9b-ab43-27410ef45c2b.png)
工具栏加载不出来
试了其他版本，有些怪怪的(lll￢ω￢)
环境:基于vue-vben-admin项目
    "@logicflow/core": "^1.1.20",
    "@logicflow/extension": "^1.1.20",
    vite: ^2.9.1
    typescript: ^4.6.3

**最简复现demo**  
[vue-vben-admin](https://github.com/anncwb/vue-vben-admin)更新logicflow为1.1.20即可

**Comment by KeyToLove** [comment]
@towersxu  我试着看了下这个问题，从1.1.12 -> 1.1.20 中间有我提交了支持开发环境下提供未压缩版本代码的pr，修改了导出logiclofw的方式（额外以commonjs导出生成的umd产物），导致rollup打包后引入logicflow是引入的整个cjs模块，和之前的方式有差异；
在`examples`文件夹下webpack打包后没发现异常，应该是 [@rollup/plugin-commonjs](https://github.com/rollup/plugins/tree/master/packages/commonjs) 插件在处理logicflow上和webpack不一致 。
。

**Comment by towersxu** [comment]
嗯，我看看怎么处理一下

**Comment by towersxu** [comment]
此问题1.1.21版本已修复
