### ISSUE TITLE
请问node的文本编辑完成有回调钩子吗？

### ISSUE THREAD

**Issue by cyt68** [didi/LogicFlow#678]
请问node的文本编辑完成有回调钩子吗？
![image](https://user-images.githubusercontent.com/20410138/177151732-7053c37b-23cf-4c05-b780-558515a3ed35.png)

**Comment by towersxu** [comment]
text:update事件吧，你找一下事件文档

**Comment by cyt68** [comment]
> text:update事件吧，你找一下事件文档

好的
