### ISSUE TITLE
导出base64图片节点文本问题

### ISSUE THREAD

**Issue by zoujpxyz2017** [didi/LogicFlow#679]
![image](https://user-images.githubusercontent.com/28721603/177245018-b90a61dd-eeb2-4315-9e99-fe286e6b9669.png)
自定义节点中有设置节点文本换行，画布中显示正常，但是导出的图片中会截断文本

还有一种情况：如果节点文本没有换行，文本够长（10个中文字）时，导出时也是会截断文本

**Comment by towersxu** [comment]
此问题应该已经修复，请使用最新版本。
