### ISSUE TITLE
[Bug report]自定义节点中存在的BUG和问题

### ISSUE THREAD

**Issue by NiroNiro** [didi/LogicFlow#68]
1. 在继承自rect的自定义节点中, 设置radius不生效, 一直是直角
2. 在继承自circle的自定义节点中, 通过设置拖动添加节点时, 该自定义节点的图形一直停留在画布左上角(x=0,y=0), 但是锚点和文本却可以拖动, 查看该节点对应的x和y属性是正确的值, 但是图形显示的位置一直在左上角, 且无法改变

**Comment by towersxu** [comment]
可以贴一下怎么写的吗？

**Comment by towersxu** [comment]
可以贴一下怎么写的吗？
