### ISSUE TITLE
目前提供的vue3渲染html节点存在问题

### ISSUE THREAD

**Issue by Kabuda-czh** [didi/LogicFlow#686]
**问题描述**  
开发环境没有异常, build 之后的线上环境有异常
在渲染时无法解析 `app._instance` 参数, 从而无法设定 `props`
![image](https://user-images.githubusercontent.com/62021214/178654164-94ee66c8-f1ba-4db1-8f3d-28de602d12b9.png)

使用了模板项目 `pure-admin-thin`
`logicFlow` 版本: `1.1.21`

**最简复现demo**  
https://github.com/Kabuda-czh/pure-admin-thin
通过 pnpm install 下载, 直接 build 通过 Live Server 即可看到异常

**Comment by towersxu** [comment]
LogicFlow渲染HTML节点机制是在setHtml中给出参数rootEl, 然后让开发者把自定义的内容通过DOM操作的方式挂载到rootEl就可以实现自定义HTML节点。至于自定义的内容用vue、react还是原生写其实不关心。目前发现之前给出的利用vue3未对外暴露的`_instance`方式属性获取vue的实例在生产环境会是null, 因为需要去vue3看看是否由其他方式。

```js
import { HtmlNode, HtmlNodeModel } from "@logicflow/core";
import { createApp } from 'vue';
import VueNode from './VueNode.vue';
class VueHtmlNode extends HtmlNode {
  constructor (props) {
    super(props)
    this.app = createApp(VueNode)
  }
  setHtml(rootEl) {
    const node = document.createElement('div')
    const { model, graphModel } = this.props;
    const properties = model.getProperties();
    rootEl.appendChild(node)
    if (!this.isMounted) {
      this.app.mount(node)
     // _instance在生产环境为null, 所以这种方式不行。
      this.app._instance.emitsOptions['btn:click'] = (val) => {
        graphModel.eventCenter.emit('vue-node:click', {
          id: model.id,
          val
        })
      }
      this.isMounted = true
    } else {
      this.app._instance.props.properties = properties
    }
  }
}

```

**Comment by Kabuda-czh** [comment]
已经解决了
通过在`.ts`文件中, 声明ref创建app, 在`.vue`中expose对应方法即可
`xxx.ts`
```ts
class VueHtmlNode extends HtmlNode {
  app: App<Element>;
  isMounted: any;
  constructor(props: any) {
    super(props);
    const appRef = ref(null);
    this.app = createApp({
      render: () => h(VueNode, { ref: appRef }),
      mounted: () => {
        appRef.value.test(props.model.getProperties().datas);
      }
    });
  }
  setHtml(rootEl: HTMLElement) {
    const node = document.createElement("div");
    rootEl.appendChild(node);
    this.app.mount(node);
    this.isMounted = true;
  }
}
```
`.vue`
```vue
<script lang="ts" setup>
import { ref } from "vue";

// 声明该模板节点需要接收的数据类型
type TFlowProps = {
  xxx: xxx
};

// 声明props, 严格使用properties, 否则外部无法传入
// const props = defineProps({
//   properties: {
//     type: Object as () => TFlowProps,
//     default: () => ({})
//   }
// });

const properties = ref<TFlowProps>({
  
});

const test = (props: TFlowProps) => {
  properties.value = props;
};

defineExpose({
  test
});
</script>
```

**Comment by towersxu** [comment]
vue3如果通过h方式把vue组件创建为vnode，则可以通过`vnode.component.props`来进行更新props属性。参考代码如下：

```js
class VueHtmlNode extends HtmlNode {
  constructor (props) {
    super(props)
    this.isMounted = false // 用个属性来避免重复挂载
    this.r = h(VueNode, {
      properties: props.model.getProperties(),
      text: props.model.inputData,
      onBtnClick: (i) => {
        this.r.component.props.text = String(Number(this.r.component.props.text) + Number(i))
      }
    })
    this.app = createApp({
      render: () => this.r
    })
  }
  setHtml(rootEl) {
    if (!this.isMounted) {
      this.isMounted = true
      const node = document.createElement('div')
      rootEl.appendChild(node)
      this.app.mount(node)
    } else {
      this.r.component.props.properties = this.props.model.getProperties() // properties发生变化后，将properties作为props传给vue组件
    }
  }
  getText () {
    return null
  }
}
```

**Comment by psrheartache** [comment]
> 已经解决了 通过在`.ts`文件中, 声明ref创建app, 在`.vue`中expose对应方法即可 `xxx.ts`
> 
> ```ts
> class VueHtmlNode extends HtmlNode {
>   app: App<Element>;
>   constructor(props: any) {
>     super(props);
>     const appRef = ref(null);
>     this.app = createApp({
>       render: () => h(VueNode, { ref: appRef }),
>       mounted: () => {
>         appRef.value.test(props.model.getProperties());
>       }
>     });
>   }
>   setHtml(rootEl: HTMLElement) {
>     const node = document.createElement("div");
>     rootEl.appendChild(node);
>     this.app.mount(node);
>   }
> }
> ```
> 
> `.vue`
> 
> ```
> <script lang="ts" setup>
> import { ref } from "vue";
> 
> // 声明该模板节点需要接收的数据类型
> type TFlowProps = {
>   xxx: xxx
> };
> 
> // 声明props, 严格使用properties, 否则外部无法传入
> // const props = defineProps({
> //   properties: {
> //     type: Object as () => TFlowProps,
> //     default: () => ({})
> //   }
> // });
> 
> const properties = ref<TFlowProps>({
>   
> });
> 
> const test = (props: TFlowProps) => {
>   properties.value = props;
> };
> 
> defineExpose({
>   test
> });
> </script>
> ```

dalao方便留一个邮箱地址么， 有点疑问请教一下。
