### ISSUE TITLE
节点和背景同时有点击事件时，节点无法正常使用函数阻止冒泡[Bug report]

### ISSUE THREAD

**Issue by ouweicong** [didi/LogicFlow#689]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
2. 期望的表现
3. 实际的表现
4. 
在用lf.on('node:click', (args) => {
  console.log('node:click', args.position)
})给节点监听点击事件时，和背景同时有点击事件时，点击节点后会继续执行背景点击事件，如果使用e.stopPropagation()阻止冒泡，会导致另外的一些错误，希望官方添加阻止冒泡方法

**Comment by towersxu** [comment]
#694

**Comment by Myfyz** [comment]
> **问题描述** 请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
> 
> 1. 问题触发的条件
> 2. 期望的表现
> 3. 实际的表现
> 
> 在用lf.on('node:click', (args) => { console.log('node:click', args.position) })给节点监听点击事件时，和背景同时有点击事件时，点击节点后会继续执行背景点击事件，如果使用e.stopPropagation()阻止冒泡，会导致另外的一些错误，希望官方添加阻止冒泡方法

this.lf.on('node:click', (dataObject) => { dataObject.e.stopPropagation() }),这样写，就可以了，不要解构回调的参数对象，使用里面的 e 属性
