### ISSUE TITLE
创建group节点折叠后回显问题

### ISSUE THREAD

**Issue by waht123** [didi/LogicFlow#690]
因为group节点的坐标x，y是节点的中心点位置，折叠后获取的需要保存数据group节点并未有isFolded相关信息。结果展示以展开形式展示group的位置不是期望效果。当我采用事件去存放group节点的isFolded信息，回显创建折叠展示有问题，请问需要怎么处理这个呢

**Comment by towersxu** [comment]
参考这个示例，需要自定触发折叠。https://codesandbox.io/s/angry-rhodes-182d8n?file=/src/SelectGroup.js

**Comment by waht123** [comment]
按照你提供的模板我试了是可以正常折叠和展开展示了 ，但是坐标不对，我定位了下属性变化，展开和折叠分别是以左上角定点不变对左边x，y各自边折半重新计算的，但是初始化如果我之传入unfoldedWidth，foldedWidth等展开和折叠宽高的话，节点是监听不到的，如果我接管一个事件的整个节点的展开和折叠就失效了

**Comment by waht123** [comment]
![image](https://user-images.githubusercontent.com/39727546/179171070-f44ef08b-7909-4904-9b5c-4efc0ae49b76.png)
  // step 1
        if (isFolded) {
            this.x = this.x - this.width / 2 + this.foldedWidth / 2;
            this.y = this.y - this.height / 2 + this.foldedHeight / 2;
            this.unfoldedWidth = this.width;
            this.unfoldedHight = this.height;
            this.width = this.foldedWidth;
            this.height = this.foldedHeight;
        }
        else {
            this.width = this.unfoldedWidth;
            this.height = this.unfoldedHight;
            this.x = this.x + this.width / 2 - this.foldedWidth / 2;
            this.y = this.y + this.height / 2 - this.foldedHeight / 2;
        }
这块代码对于初始化是展开渲染的没问题，折叠回显在initNodeData中重新设置了 unfoldedWidth等值，但是会自定替换成折叠后的大小
