### ISSUE TITLE
分组节点缩放bug

### ISSUE THREAD

**Issue by ouweicong** [didi/LogicFlow#692]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件：对于分组节点缩小后，就算设置了子节点不能拉出分组，但只要分组节点缩小到比子节点小，子节点就能逃出分组节点

**最简复现demo**  
https://codesandbox.io/s/logicflow-base24-vgvpf?from-embed=&file=/step_24_group/index.js

**Comment by towersxu** [comment]
嗯，这是个问题，可以加一个在分组节点缩放时，不允许缩放到比子节点范围还小的功能。欢迎PR。

**Comment by towersxu** [comment]
已在1.1.29中修复，请使用新版圆角折线
