### ISSUE TITLE
创建group节点折叠后回显问题

### ISSUE THREAD

**Issue by waht123** [didi/LogicFlow#693]
跟据[https://github.com/didi/LogicFlow/issues/690](https://github.com/didi/LogicFlow/issues/690 )的问题，从实现看是有问题的，折叠组保存的x，y是计算过折叠后的坐标，当初次渲染折叠组时，width和height不应该是传递foldedWidth和foldedHeight尺寸么？开始以为程序内部会自己重新计算，单结果总会出现偏移

**Comment by towersxu** [comment]
请提供示例和复现步骤？我这边没有看出来坐标有什么问题。

**Comment by waht123** [comment]
1.你创建一个可缩放的组，
2.将组折叠的数据重绘
3.打开折叠的组
4.折叠组的位置已经不在原来的位置上了
目前我的做法是：初次渲染group，width和height判断properties是否有nodesize存在，其次从新计算group节点相对于展开情形下的位置去重绘，然后再执行节点的foldGroup（）函数，但是过程中计算x，y是会有误差的，期望能将原数据保存回显

**Comment by towersxu** [comment]
目前logicflow导出的数据不带有是否折叠，也就是折叠只是一个显示效果, 不支持回显，下个版本考虑将分组的折叠状态也保存到图数据中。我基于之前其他有回显需求的示例改了一下，参考这个示例就支持折叠后的分组回显了。https://codesandbox.io/s/angry-rhodes-182d8n?file=/src/index.js
