### ISSUE TITLE
动态获取图片

### ISSUE THREAD

**Issue by lydAndtry** [didi/LogicFlow#696]
能否动态获取图片在控制面板，并且拖拽到画布中，不是根据type去显示相应的组件，也就是能不能不需要封装成js文件啊？

**Comment by towersxu** [comment]
这个不支持，因为LogicFlow支持各种类型的自定义节点，可能会存在很多节点就特别复杂。所以还是觉得让开发者自己去基于需求实现拖拽面板中的组件。
