### ISSUE TITLE
如何创建选区

### ISSUE THREAD

**Issue by waht123** [didi/LogicFlow#697]
项目按文档引入了SelectionSelect，但是创建选区的效果没出来，事件selection:selected可以获取选中的节点数据，请问怎么创建选区呢

**Comment by towersxu** [comment]
请看文档，因为选区和画布的拖动时互斥的功能，因此需要写代码开启选区功能。

**Comment by waht123** [comment]
知道原因了 是因为angular 脚手架直接从js引入样式不生效导致的
