### ISSUE TITLE
[功能需求]addEdge添加连线时能否传入更多参数，比如起始和终点的锚点id

### ISSUE THREAD

**Issue by FabricateDeng** [didi/LogicFlow#700]
业务需求中有针对锚点id作判断的需要，发现addEdge生成的锚点id似乎是随机的（不确定），希望可以在添加时就传入指定的锚点id，辛苦大佬们

**Comment by towersxu** [comment]
你可以自定义锚点，然后重写getData在保存的时候把锚点信息也保存即可。
