### ISSUE TITLE
框选分组节点移动时，子节点连线会混乱bug

### ISSUE THREAD

**Issue by ouweicong** [didi/LogicFlow#702]
框选分组节点，若分组节点内有子节点并连线，框选整个分组节点后移动分组节点，子节点的连线会变得很混乱

**最简复现demo**  
https://codesandbox.io/s/logicflow-base20-forked-l7026r?file=/step_20_controlAndMinimap/index.js

**Comment by ouweicong** [comment]
还有，拉分组里的子节点时，碰到分组的边，子节点的连线也会混乱

**Comment by xuess** [comment]
这个解决了吗？
