### ISSUE TITLE
[Feature Requirement] 如何画一个直线？

### ISSUE THREAD

**Issue by ycc3000** [didi/LogicFlow#703]
**问题描述**  
求教，如何画一条直线，可以跟不要箭头的边一样的两头随意拖动，但做为节点来用？
我继承了RectResize，用 h('line', {...}) 来画，总是不尽人意，不能用两端来随意拖动而只能用四个角拖动，要不只能是斜线要不只能是横线或竖线。

**Comment by towersxu** [comment]
目前你只有继承baseNode, 然后全部都自己重新view来实现。
