### ISSUE TITLE
页面刷新后容器高度为0

### ISSUE THREAD

**Issue by XiaoBaiClassmate** [didi/LogicFlow#704]
示例代码
```
const container = ref(null)
onMounted(() => {
  lf.value = new LogicFlow({
    container: container.value,
    height: 800,
    grid: true,
  });
```

版本：1.1.22
复现步骤：页面刷新
效果：
```
<div class="lf-graph" style="height:0px"> </div> 
```

在版本1.1.16中，页面刷新后，高度是存在的。
在最新版中页面刷新高度就为0了

**Comment by towersxu** [comment]
logicflow会在页面没有高度或者宽度的时候去计算容器的宽高作为画布的宽高。建议将width和height都传进去。或者确保container对应的节点已经完全加载到DOM中后在去触发render。

**Comment by XiaoBaiClassmate** [comment]
@towersxu 你好，已确保container是存在的，但是我的问题是，明明在16版中，强制刷新页面后高度是存在的，但22版本强制刷新页面后就不行了。

**Comment by towersxu** [comment]
能提供一个可复现的demo吗？
