### ISSUE TITLE
Vue3.0下设置边 type:bezier 将引发报错 [Bug report]

### ISSUE THREAD

**Issue by Af4fun** [didi/LogicFlow#706]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
 当前依赖版本
![image](https://user-images.githubusercontent.com/21170789/180753820-95517377-877f-4f7f-8400-6b65b9f112ab.png)
基本代码（官网示例代码）：
```
lf.value = new LogicFlow({
      container: container.value,
      grid: true
  });
  lf.value.render({
      nodes: [
          {
              id: '1',
              type: 'rect',
              x: 100,
              y: 100,
              text: '节点1'
          },
          {
              id: '2',
              type: 'circle',
              x: 300,
              y: 200,
              text: '节点2'
          }
      ],
      edges: [
          {
              sourceNodeId: '1',
              targetNodeId: '2',
              type: 'bezier',
              text: '连线'
          }
      ]
  });
```
2. 期望的表现
能正确的拖拽
3. 实际的表现
![image](https://user-images.githubusercontent.com/21170789/180754285-173d1e56-820c-43b4-ba43-83050a0927ee.png)
![image](https://user-images.githubusercontent.com/21170789/180754322-3909f4f1-49a5-4cb7-912d-f7289beb7b02.png)

**Comment by towersxu** [comment]
logicflow在vue3中应该没有问题，请参考这个https://github.com/Logic-Flow/logicflow-node-red-vue3

**Comment by zguolee** [comment]
> logicflow在vue3中应该没有问题，请参考这个https://github.com/Logic-Flow/logicflow-node-red-vue3

是有问题的，这个例子没有问题是因为没有用ref，一旦lf用一个ref或者reactive保存，拖拽节点都会报错。
