### ISSUE TITLE
zIndex没有用

### ISSUE THREAD

**Issue by lydAndtry** [didi/LogicFlow#711]
使用置顶置底在编辑页面有作用，在渲染的时候是根据结点的顺序显示的，zIndex一样有数值增减

**Comment by towersxu** [comment]
LogicFlow初始化节点的时候在堆叠模式为[默认](http://logic-flow.org/api/graphModelApi.html#overlapmode)情况下不会去获取图数据中的zIndex。需要初始化lf的时候将堆叠模式设置为自增。
const lf = new LogicFlow({
   ...
})

https://github.com/didi/LogicFlow/blob/ce130220657dc92bb1b4c376a604a0d7d4a973d8/packages/core/src/model/node/BaseNodeModel.ts#L134-L154
