### ISSUE TITLE
LogicFlow案例分享

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#716]
## 描述
LogicFlow为了提供足够的扩展性，默认情况下并不会做过多的样式、交互上的效果。我们提供了足够多的API支持您去实现您们产品、UI的效果。 在不涉及公司信息安全的情况下，欢迎您把LogicFlow在您们项目中的实际效果分享出来。

## 你可以分享

1. 分享项目中的效果截图。
2. 分享自己用LogicFlow实现的开源项目github地址。
3. 分享使用了LogicFlow的网址。

## 我们还会做什么

1. 在收集到足够多的分享后，我们会从中选区一些用的多的效果做成内置插件。
2. 为后续提供案例展示模块收集素材。

**Comment by towersxu** [comment]
案例一：

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/4093984/181871689-da051aa4-93f3-49b9-b908-182b40091c11.png">

**Comment by guanalongaaa** [comment]
12

**Comment by hsole** [comment]
我把LogicFlow和自动布局、一键美化结合起来。


![autolayout](https://user-images.githubusercontent.com/42540018/191229478-b057a706-0b41-4641-807c-d9ba354eeefa.gif)

![QQ20220920-165532-HD](https://user-images.githubusercontent.com/42540018/191229682-f1d2787c-57b6-4d83-9b31-53fbe2efe5fd.gif)



https://hsole.github.io/layoutFlow/

https://github.com/hsole/layoutFlow

**Comment by hadoop835** [comment]
> 案例一
> 
> <img alt="image" width="1154" src="https://user-images.githubusercontent.com/4093984/181871689-da051aa4-93f3-49b9-b908-182b40091c11.png">

有源码地址吗

**Comment by chenweihan** [comment]
入门demo学习,请跳转:

Angular版本LogicFlow的入门DEMO实例请参考
    码云 https://gitee.com/copperpeas/logicflow-angular
    github https://github.com/chenweihan/logicflow-angular
Vue3LogicFlow的入门DEMO实例请参考((Vue2可参考))
    码云 https://gitee.com/copperpeas/logicflow-vue3
    github https://github.com/chenweihan/logicflow-vue3

**Comment by love666** [comment]
想要这种hover效果
![image](https://user-images.githubusercontent.com/34014343/231097266-17b1ac80-f5cf-42f7-b2ff-065208174bb1.png)
![image](https://user-images.githubusercontent.com/34014343/231097439-fec38598-a747-4dd2-b7db-05fb806c666f.png)

**Comment by sx1989827** [comment]
公司或组织：阿尔方斯
产品：基于人工智能的团队协作平台Teamlinker，
访问地址：[Teamlinker](https://team-linker.com/) [Teamlinker开源项目](https://github.com/sx1989827/Teamlinker)
截图：

<img width="1540" alt="Screenshot 2023-11-13 at 11 46 24" src="https://github.com/didi/LogicFlow/assets/5820929/f1b7f2d4-df72-4e97-999a-81eb3ed2f470">

**Comment by ijry** [comment]
产品：FinalMind在线脑图流程图工具
访问地址：[Teamlinker](https://team-linker.com/) [Teamlinker开源项目](https://github.com/sx1989827/Teamlinker)
截图：<img width="1200" alt="QQ20240102-120353@2x" src="https://github.com/didi/LogicFlow/assets/3102798/545c2c66-8daa-493e-8f32-241527ba1766">

**Comment by whki** [comment]
产品：RuleGo-Editor 规则引擎可视化编辑器
访问地址：https://editor.rulego.cc/
截图：
![image](https://github.com/didi/LogicFlow/assets/7507761/3319b594-ac36-4a0e-a47b-91b0fe41c63a)

**Comment by harry5257** [comment]
我看示例中有关于react版本的泳道图，能否加一下vue2版本的泳道图，谢谢

**Comment by wumail** [comment]
> 我看示例中有关于react版本的泳道图，能否加一下vue2版本的泳道图，谢谢

哪里的示例？泳道节点本身不依赖框架呀

**Comment by harry5257** [comment]
> > 我看示例中有关于react版本的泳道图，能否加一下vue2版本的泳道图，谢谢
> 
> 哪里的示例？泳道节点本身不依赖框架呀

![image](https://github.com/didi/LogicFlow/assets/86468351/6cf180a0-7fd3-47ff-97c9-3536ba3c338b)
在https://site.logic-flow.cn/demo/dist/pool示例中

**Comment by wumail** [comment]
> > > 我看示例中有关于react版本的泳道图，能否加一下vue2版本的泳道图，谢谢
> > 
> > 
> > 哪里的示例？泳道节点本身不依赖框架呀
> 
> ![image](https://private-user-images.githubusercontent.com/86468351/309975549-6cf180a0-7fd3-47ff-97c9-3536ba3c338b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTEyNDksIm5iZiI6MTcwOTYxMDk0OSwicGF0aCI6Ii84NjQ2ODM1MS8zMDk5NzU1NDktNmNmMTgwYTAtN2ZkMy00N2ZmLTk3YzktMzUzNmJhM2MzMzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAzNTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOTkxMDU5YTVhYmM4ZGM0MDY3ODk5ZjgwNjk4Mjg5ZGQxMGU0NDdlMGEwMzNiMjI2OGUzNjNkZmZlODZkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ki-oxyL03Ci1Gw5F9wJ3Ox9nnz-V1_FQl00opL6HbI) 在[https://site.logic-flow.cn/demo/dist/pool示例中](https://site.logic-flow.cn/demo/dist/pool%E7%A4%BA%E4%BE%8B%E4%B8%AD)

可以看这里的代码https://github.com/Logic-Flow/docs/tree/master/demo/pool/src/node，本质是一个Logicflow自定义节点，不依赖框架，可以在vue里使用，但是这个泳道功能并不完善，可以参考一下

**Comment by ByteTerminator** [comment]
@towersxu  你好，这个案例有源码吗，求分享。
![image](https://github.com/user-attachments/assets/3e77b937-e1c9-47f2-ae2d-e1c8eab36ec4)

**Comment by hlongc** [comment]
> 我把LogicFlow和自动布局、一键美化结合起来。
> 
> ![autolayout](https://user-images.githubusercontent.com/42540018/191229478-b057a706-0b41-4641-807c-d9ba354eeefa.gif) [ ![autolayout](https://user-images.githubusercontent.com/42540018/191229478-b057a706-0b41-4641-807c-d9ba354eeefa.gif) ](https://user-images.githubusercontent.com/42540018/191229478-b057a706-0b41-4641-807c-d9ba354eeefa.gif) [ ](https://user-images.githubusercontent.com/42540018/191229478-b057a706-0b41-4641-807c-d9ba354eeefa.gif)
> 
> ![QQ20220920-165532-HD](https://user-images.githubusercontent.com/42540018/191229682-f1d2787c-57b6-4d83-9b31-53fbe2efe5fd.gif) [ ![QQ20220920-165532-HD](https://user-images.githubusercontent.com/42540018/191229682-f1d2787c-57b6-4d83-9b31-53fbe2efe5fd.gif) ](https://user-images.githubusercontent.com/42540018/191229682-f1d2787c-57b6-4d83-9b31-53fbe2efe5fd.gif) [ ](https://user-images.githubusercontent.com/42540018/191229682-f1d2787c-57b6-4d83-9b31-53fbe2efe5fd.gif)
> 
> https://hsole.github.io/layoutFlow/
> 
> https://github.com/hsole/layoutFlow

这个有源码参考吗

**Comment by miniliupeng** [comment]
react项目中使用LogicFlow，支持一键美化（垂直布局、水平布局）、导出图片、上一步、下一步、拖拽线、连线认证、自定义react节点（支持react 16、react 17）：

![演示](https://github.com/user-attachments/assets/7efc69fa-2f4c-4de4-99b3-31bd9074a727)

github项目地址：https://github.com/miniliupeng/react-logic-flow
演示地址：http://minierpeng.top/react-logic-flow

**Comment by fuyuku** [comment]
有没有类似coze的工作流的
