### ISSUE TITLE
[Bug report]在使用bpmn中关于xml互相转换的一些bug

### ISSUE THREAD

**Issue by shaohua007** [didi/LogicFlow#718]
**问题描述**  
开发环境： Edge浏览器 , 对接后端flowable最新的流程引擎，采用bpmn2.0规范
1、 文件 packages\extension\src\bpmn-adapter\index.ts 中toXmlJson跟toNormalJson方法没有考虑Array的情况，Object.entries无法正确解析数组,，导致本来的对象数组例如
`{
    "bpmn2:extensionElements": {
        "flowable:taskListener": [
            {
                "event": "create",
                "flowable:field": {
                    "name": "taskType",
                    "stringValue": "Execute"
                }
            },
            {
                "event": "end",
                "flowable:field": {
                    "name": "taskType",
                    "stringValue": "Execute"
                }
            }
        ]
    }
}`
变成了下面的形式：
`{
    "bpmn2:extensionElements": {
        "flowable:taskListener": {
           0: {
                "-event": "create",
                "flowable:field": {
                    "-name": "taskType",
                    "-stringValue": "Execute"
                }
            },
            1: {
                "-event": "end",
                "flowable:field": {
                    "-name": "taskType",
                    "-stringValue": "Execute"
                }
            }
        }
    }
}`
造成的后果就是生成bpmn的xml总是少了元素

2、 文件 packages\extension\src\bpmn-adapter\index.ts   toXmlJson方法没有处理xml中的 #text节点（文本节点）
![image](https://user-images.githubusercontent.com/24848929/182822666-9f4ec0d4-0c80-4a3c-bc0a-d71757427db2.png)
这是做了处理后的

3、issue https://github.com/didi/LogicFlow/issues/325 并不能保证 incomming在outgoing之前，因为各浏览器差异，对象并不会按照先后顺序处理，所以需要在 packages\extension\src\bpmn-adapter\json2xml.ts 中修改，如下只是个人临时修改没来得及重构
![image](https://user-images.githubusercontent.com/24848929/182824036-8bc20ca0-36ee-414e-a722-6154caf71756.png)

先写这么多，还有些bug容我想想~

**Comment by towersxu** [comment]
目前BPMN支持不完善，如果遇到欢迎提测，我们将在v1.2.0中修复。

**Comment by wumail** [comment]
这些问题在最新的版本中都得到了修复，新的使用方式可以查阅文档的相关部分

**Comment by wumail** [comment]
这些问题在最新的版本中都得到了修复，新的使用方式可以查阅文档的相关部分

**Comment by youtiao66** [comment]
v1.2.22 仍然无法保证incoming和outgoing在其他元素之前。大家有遇到类似这类情况？
