### ISSUE TITLE
选择锚点，往空白处拖拽连线，拖拽够长以后松开鼠标，会发现整体画布自动不停往上移动，根本无法停下来

### ISSUE THREAD

**Issue by Loukai1991** [didi/LogicFlow#719]
现象：从图中任意节点，选取一个锚点，往下拖拽连线。拖拽到接近屏幕下边缘的时候，发现整个画布包含内容开始往上自动滚动(移动),根本停不下来，除非刷新页面。求助，会是什么原因导致的？
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/25781954/182832629-3e6d661f-adc4-4454-b997-0cb0b70c68b4.png">
使用的项目地址：https://github.com/Logic-Flow/logicflow-node-red-vue3
预览地址：https://codesandbox.io/s/logicflow-node-red-vue3-u2c3zk?file=/src/components/FlowChart.vue
截取录屏如下：

https://user-images.githubusercontent.com/25781954/182831922-57b8d6ed-1386-4038-8639-3ea6f78cd56e.mov

**Comment by towersxu** [comment]
感谢提出。这个是一个BUG，由于LogicFlow支持在拖动到边界时自动扩充画布来支持用户连接到可视区外部的节点。但是未处理好在可视化外取消连接的情况。目前已在1.1.23版本修复。
