### ISSUE TITLE
[Question] Do you have an English version documentation?

### ISSUE THREAD

**Issue by Mashiane** [didi/LogicFlow#721]
Good day

This is a very interesting find. Do you happen to have an English version of the documentation?

Thank you.

**Comment by towersxu** [comment]
Hi Mashiane
Thank you for your interest. But I don't have enough time to write English version document now. You can read our sourcecode.
We also looking for someone pull requests.

**Comment by wumail** [comment]
> Good day
> 
> This is a very interesting find. Do you happen to have an English version of the documentation?
> 
> Thank you.

Hi Mashiane,
It's been a long time, though, but we have an English-version document now, you could see that at https://docs.logic-flow.cn/docs/#/en/guide/start. We hope it helps!
