### ISSUE TITLE
[question] 自定义node 回显锚点关联问题

### ISSUE THREAD

**Issue by baimaopp** [didi/LogicFlow#722]
如何根据 自定义edge保存的sourceAnchorId 和 targetAnchorId 来回显edge而不是根据startPoint endPoint显示和关联

有时候进行 重做 的时候会改变自定义node的位置，导致锚点关联出问题

**Comment by towersxu** [comment]
请参考http://logic-flow.org/guide/basic/edge.html#%E4%BF%9D%E5%AD%98%E9%94%9A%E7%82%B9%E4%BF%A1%E6%81%AF
里面的示例
