### ISSUE TITLE
[Feature request] 实现连线校验：两节点之间，同方向只能有一条连线

### ISSUE THREAD

**Issue by houxg** [didi/LogicFlow#724]
## 问题
我们的场景要求两节点之间，同方向只能有一条连线，目前按照[官方示例](http://logic-flow.org/guide/basic/node.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%9E%E6%8E%A5%E8%A7%84%E5%88%99%E6%A0%A1%E9%AA%8C)是没法实现的。

## 期望
validate方法增加LogicFlow实例参数，以方便遍历全部edge做校验

**Comment by towersxu** [comment]
可以实现，校验函数是你自己写的，你可以再校验函数中通过graphModel拿到所有的连线和节点
