### ISSUE TITLE
分组节点在只读模式下，还能通过拉大拉小，和按钮的放大缩小

### ISSUE THREAD

**Issue by ouweicong** [didi/LogicFlow#726]
分组节点在只读模式下，还能通过拉大拉小，和按钮的放大缩小

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
https://codesandbox.io/s/logicflow-base24-forked-t3p6nb?file=/step_24_group/index.js

**Comment by towersxu** [comment]
group是否允许调整是受到resizable、foldable属性控制，在自定义的分组的时候，可以基于静默模式来设置。

```js
  initNodeData(data) {
    super.initNodeData(data);
    this.foldable = !this.graphModel.editConfigModel.isSilentMode;
  }
```

**Comment by ouweicong** [comment]
好的，谢谢
