### ISSUE TITLE
[Bug report] 鼠标hover状态BUG

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#727]
问题描述 
1、问题触发的条件：
    getTextStyle() 的 overflowMode 设置为 ellipsis 或 autowrap 时鼠标向上hover超出矩形范围一段距离才会取消状态。
    其他前置条件：Text编辑框被置顶，左对齐；文本被输入。
    正常情况：overflowMode 设置为 default 时无任何异常。

2、期望的表现：
    无论如何调整文本编辑框，鼠标hover的触发范围受限于矩形范围内。

3、实际的表现：
![hoverBug](https://user-images.githubusercontent.com/18308819/185018506-3f8885d3-f3cb-470d-ba6d-6f0c35e61e7e.gif)

最简复现demo
codesanbox：https://codesandbox.io/s/young-frost-dx1491?file=/src/group.js

**Comment by towersxu** [comment]
因为你把文本的位置向上偏移了一半的高度，所以出现这种情况。这样改就没问题了。https://codesandbox.io/s/reverent-hertz-xubfeg?file=/src/group.js
