### ISSUE TITLE
继承htmlNode的节点中svg图标显示异常

### ISSUE THREAD

**Issue by MuniniD** [didi/LogicFlow#728]
我在编写一个自定义的节点，继承HtmlNode，里面使用到了一个editorjs的富文本编辑器，在编辑器弹出的工具栏中的svg图标都比正常情况下变粗了，这是什么问题？下图中白色背景方框就是工具栏
"vite": "^2.8.0"
"vue": "^3.2.25"
"@logicflow/core": "^1.1.23",
"@logicflow/extension": "^1.1.23",
"@editorjs/editorjs": "^2.25.0",

![image](https://user-images.githubusercontent.com/56426939/185305646-e995ac79-f6c0-4b2d-be0f-cf6f7d8fefc1.png)

**Comment by towersxu** [comment]
您好，因为没有可运行示例，没法定位你的问题，建议你看看是不是CSS影响了。

**Comment by CN-Haoling** [comment]
看了下应该是画布的css入侵了svg css ，在svg外面套一个 storke：none就行
