### ISSUE TITLE
删除节点后还能获取到节点信息

### ISSUE THREAD

**Issue by Damon99999** [didi/LogicFlow#732]
**问题描述**  
1. 问题触发的条件
通过lf.deleteNode('id');删除节点

2. 期望的表现
删除后不再获取到节点信息

3. 实际的表现
还可以通过getNodeModelById(nodeId: string): BaseNodeModel获取该节点信息
也可以通过lf.getGraphRawData()获取到节点信息

**Comment by towersxu** [comment]
您好，我用最新版本测试没有复现这个问题，请提供可运行示例。
