### ISSUE TITLE
[Bug report] Resize扩展的鼠标hover状态BUG

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#733]
**问题描述**  
1. 问题触发的条件:
    使用 RectResize 扩展时，节点类的 autoToFront 设置为 false，两个该节点相交且 zIndex 相同
    
2. 期望的表现
    鼠标点击选中一个节点时，应该能选中该节点的 resize 扩展锚点。

3. 实际的表现
    鼠标点击选中一个节点时，在相交区域可能hover到另一个节点（视节点的先后摆放顺序而定），导致无法选中扩展的 resize 锚点。
    **该问题仅在最新版本中出现（目前发现1.1.22以上），codesanbox 中默认的 1.1.0-alpha.0 版本无法复现该问题**

![hover](https://user-images.githubusercontent.com/18308819/185556227-a3496204-142e-4314-9f3a-70d182c1277a.gif)

**最简复现demo**  
codesanbox: https://codesandbox.io/s/competent-paper-90nomi?file=/src/group.js:55-68

**Comment by towersxu** [comment]
autoToFront表示控制节点选中时是否自动置顶，默认为true。我看你示例将其设置为false, 那表示那个节点在上面是受到节点自身zIndex控制，相同是谁后添加谁在上面。所以是没有问题的。

**Comment by gh565923562** [comment]
> autoToFront表示控制节点选中时是否自动置顶，默认为true。我看你示例将其设置为false, 那表示那个节点在上面是受到节点自身zIndex控制，相同是谁后添加谁在上面。所以是没有问题的。

我这是个分组节点，所以autoToFront必须设为false，我看在原始版本即使这样设置也不会有问题

**Comment by towersxu** [comment]
你可以通过model的isHover等状态属性自己控制zIndex。

**Comment by gh565923562** [comment]
> 在 getNodeStyle 中根据 isHovered 或 isSelected 使用 setZIndex 也做不到，因为它们的类型相同，且isHovered的边界判断非常敏感，而isSelected的判断有问题，设置就一起设置了

**Comment by towersxu** [comment]
设置zIndex可以再setAttributes中，样式相关的设置才在getNodeStyle中
