### ISSUE TITLE
[Bug report]   分组-拖动分组允许子元素一起移动，子元素错位异常

### ISSUE THREAD

**Issue by destinyhand** [didi/LogicFlow#735]
分组，允许子元素自由拖动。
添加全局移动规则，分组元素拖动允许子元素一起移动。  子元素位置严重错位

代码地址：
https://codesandbox.io/s/logicflow-base24-forked-ijc3zm?file=/step_24_group/index.js
![GIF 2022-8-19 15-57-01](https://user-images.githubusercontent.com/28997856/185573928-19a1bb89-f10a-41e1-9b90-75f1bc1cd08b.gif)

**Comment by towersxu** [comment]
#734
