### ISSUE TITLE
[Bug report] HTML节点 getResizeShape() 与  setHtml()  渲染方式不兼容

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#744]
**问题描述**  
1. 问题触发的条件
    HtmlResize.view 使用 getResizeShape() 后，调用 setHtml() 会报错

2. 期望的表现
    希望暴露接口，让用户可以通过逻辑控制采用  getResizeShape() 的渲染方式，还是 setHtml() 的渲染方式

3. 实际的表现
    只能单独使用  getResizeShape()  或  setHtml() 渲染节点

**最简复现demo**  
codesanbox: https://codesandbox.io/s/cocky-bartik-fvkrf7?file=/src/HtmlImageNode.js

**Comment by gh565923562** [comment]
已解决

**Comment by 1372798452** [comment]
能否给个示例
