### ISSUE TITLE
Group分组组件的properties属性里面添加object类型的数据 点击展开按钮的时候 报错[Bug report]

### ISSUE THREAD

**Issue by inshuang** [didi/LogicFlow#745]
![This is an image](https://myoctocat.com/assets/images/base-octocat.svg)
![1661412043715](https://user-images.githubusercontent.com/34765914/186601730-5f468c34-35a8-451e-80c5-f18ba600eb34.jpg)
![1661412043715](https://user-images.githubusercontent.com/34765914/186602138-0cae63dc-0ff6-4891-9428-2dc3922d5e98.jpg)
分组组件的properties属性里面添加object类型的数据 然后点击展开按钮的时候 报错
![1661412471510](https://user-images.githubusercontent.com/34765914/186602456-754e0cc4-61bc-4e1c-b56d-1384d9f56288.jpg)
数据的格式

**Comment by towersxu** [comment]
请提供可运行的在线示例，目前我的示例中并没有复现这个问题。https://codesandbox.io/s/logicflow-base24-forked-qsu3v3?file=/step_24_group/index.js
