### ISSUE TITLE
配置edgeAnimation点击边动画没有生效

### ISSUE THREAD

**Issue by GengZiwei** [didi/LogicFlow#746]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件   animation 开启了edge动画 配置了style中的edgeAnimation  点击边有动画效果但是没有生效主题配置,
2. 期望的表现。 配置edgeAnimation 动画生效
3. 实际的表现   只有默认的动画生效

https://codesandbox.io/s/quizzical-jepsen-3v1mjz?file=/src/index.js

**Comment by hsole** [comment]
可以试试用自定义边加动画效果，主题的动画不太灵活。http://logic-flow.org/guide/basic/edge.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8D%E5%90%8C%E8%8A%82%E7%82%B9%E8%BF%9E%E6%8E%A5%E7%9A%84%E8%BE%B9%E7%9A%84%E8%A7%84%E5%88%99

**Comment by GengZiwei** [comment]
@hsole 谢谢🙏
