### ISSUE TITLE
在节点properties 中设置数组类型的数据时生成 bpmn xml 格式会出现<0></0> <1></1> 这样的标签

### ISSUE THREAD

**Issue by jieying1314** [didi/LogicFlow#747]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
2. 期望的表现
3. 实际的表现

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 在任意在线编码平台，编写示例如[codesanbox](https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js。将其保存到自己空间，然后贴上链接。
2. 在自己github中创建一个最简单的示例，然后贴上github链接。
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by chen476026986** [comment]
这是Bpmn-adapter中index.js的toNormalJson，toXmlJson没有识别数组，引起的，可以使用自定义的adapter，修改这两个函数可以解决

**Comment by chen476026986** [comment]
修改后如下
`function toXmlJson(json) {
    var xmlJson = {};
    Object.entries(json).forEach(function (_a) {
        var _b = __read(_a, 2), key = _b[0], value = _b[1];
        if(typeof value==='string'){
            if (key.indexOf('-') === 0) { // 如果本来就是“-”开头的了，那就不处理了。
                xmlJson[key] = value;
            } else {
                let obj={}
                obj['-#text']=value
                xmlJson[key] = obj;
            }
        }else if(typeof value==='object'){
            if(Array.isArray(value)){
                xmlJson[key] =value.map(item=>{
                    return toXmlJson(item)
                })
            }else{
                xmlJson[key] = toXmlJson(value);
            }
        }else{
            xmlJson[key] = toXmlJson(value);
        }
    });
    return xmlJson;
}
function toNormalJson(xmlJson) {

    var json = {};
    Object.entries(xmlJson).forEach(function (_a) {
        var _b = __read(_a, 2), key = _b[0], value = _b[1];
        if (typeof value === 'string') {
            if (key.indexOf('-') === 0) { // 如果本来就是“-”开头的了，那就不处理了。
                json[key.substr(1)] = value;
            }
            else {
                let obj={}
                obj['#text']=value
                json[key] = obj;
            }
        }
        else if (typeof value === 'object') {
            if(Array.isArray(value)){
                json[key]=value.map(item=>{
                    return toNormalJson(item)
                })
            }else{
                json[key] = toNormalJson(value);
            }

        }
        else {
            json[key] = value;
        }
    });
    return json;
}`

**Comment by wumail** [comment]
#1107

**Comment by wumail** [comment]
#1107

**Comment by wumail** [comment]
> **问题描述** 请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
> 
> 1. 问题触发的条件
> 2. 期望的表现
> 3. 实际的表现
> 
> **最简复现demo** 一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
> 
> 1. 在任意在线编码平台，编写示例如[codesanbox]([https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js。将其保存到自己空间，然后贴上链接。](https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js%E3%80%82%E5%B0%86%E5%85%B6%E4%BF%9D%E5%AD%98%E5%88%B0%E8%87%AA%E5%B7%B1%E7%A9%BA%E9%97%B4%EF%BC%8C%E7%84%B6%E5%90%8E%E8%B4%B4%E4%B8%8A%E9%93%BE%E6%8E%A5%E3%80%82)
> 2. 在自己github中创建一个最简单的示例，然后贴上github链接。
> 3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

#1107

**Comment by wumail** [comment]
该问题在最新的版本中已得到修复
