### ISSUE TITLE
图形上任意点都可以作为连接点和终点

### ISSUE THREAD

**Issue by toyang** [didi/LogicFlow#748]
**问题描述**  
目前每个图形上都有锚点作为连线的起始点，能否实现图形上任一点都可以作为连线的起始点呢？意思就是取消锚点，任意一点都可以作为连线（edge）的起始点连接到target的任意一点。目前文档上没看到相关的描述

**Comment by towersxu** [comment]
这个功能暂时不支持，目前连线不能没有起点和终点。你可以尝试自定义一个节点，节点的外观是连线。
