### ISSUE TITLE
[Bug report]Grrop分组组件里面能不能获取里面子组件node 跟edge相对分组组件框的相对定位啊

### ISSUE THREAD

**Issue by inshuang** [didi/LogicFlow#752]
**问题描述**  
 
1.  把分组组件注册为像node一样的基础组件的时候 通过控制面板拖拽到画布中 原本定义好在分组组件里面的子元素的位置会混乱 
2.希望子元素能相对分组元素定位 用于模板组件场景

**Comment by towersxu** [comment]
不能直接获取，你可以基于分组的坐标和子节点的坐标计算。
