### ISSUE TITLE
体验问题（关于边上插入节点功能）

### ISSUE THREAD

**Issue by Damon99999** [didi/LogicFlow#754]
**问题描述**  
“边上插入节点”这个功能经常不能正常插入，需要用户对齐很久才能正确插入。就是用起来比较麻烦，而且有概率客户对半天也没插入成功。（尤其是边没有在网格的点上面的时候，更难对齐）

**希望实现**  
能将对其范围变大，当节点移入边上放开鼠标就可以顺利插入节点，无需客户去慢慢对齐（希望大佬关注并帮忙解决一下，万分感谢）

**Comment by soom-lupulus** [comment]
同样的感触，很不好对齐，希望尽快解决
