### ISSUE TITLE
edge可自定义箭头问题

### ISSUE THREAD

**Issue by Damon99999** [didi/LogicFlow#755]
**问题描述**  
![企业微信截图_16620888193733](https://user-images.githubusercontent.com/38937194/188052367-d3b04f8b-82d5-4b93-b61e-372bd6a78c8e.png)
我们的UI设计需求希望可以自定义箭头样式（比如可以传入一个svg的icon来代替当前的箭头，或者其他方式也可以）

**希望实现**  
通过开发者可以自定义箭头
![企业微信截图_16620888996044](https://user-images.githubusercontent.com/38937194/188052504-e52a0d3b-c708-4dc4-80b5-ab723151ed6f.png)

**Comment by towersxu** [comment]
1.1.27版本已支持，文档请参考http://logic-flow.org/guide/basic/edge.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AE%AD%E5%A4%B4
