### ISSUE TITLE
[Bug report] 撤销/回退操作后，导致节点文本偏移

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#756]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
     复现步骤：(版本core/extension: 1.1.26)
    ① 右键在画布任意位置创建3个节点
    ② 编辑每个节点中的文字
    ③ 使用[Backspace]删除任意一个节点
    ④ 使用[Ctrl+Z]回退操作步骤，发现坐标修正导致文本偏移

2. 期望的表现
   撤销/回退操作不会导致文本和节点位置发生偏移

3. 实际的表现
   撤销/回退操作导致文本和节点位置不正确
  
![offset](https://user-images.githubusercontent.com/18308819/188530243-81cb6608-f72b-4fe4-9f1a-f058a1c8981c.gif)

**最简复现demo**  
codesanbox:  https://codesandbox.io/s/async-voice-ohg51j?file=/src/index.js

**Comment by towersxu** [comment]
你提供的示例无法复现这个问题。

**Comment by gh565923562** [comment]
> 



> 你提供的示例无法复现这个问题。

可以复现啊，就像我上面这个gif截图的操作一样，先右键创建多个节点，然后输入文字，删除任一节点后，在执行回退（ctrl+z）操作，就能看到文本区域都发生了相对grid size的偏移

**Comment by gh565923562** [comment]
> 你提供的示例无法复现这个问题。

版本使用1.1.26

**Comment by towersxu** [comment]
创建节点是text为空会有问题，这个下版本修复。
