### ISSUE TITLE
拖拽一个继承Group的自定义节点进画布会报错

### ISSUE THREAD

**Issue by hellomarker** [didi/LogicFlow#757]
**问题描述**  
拖拽一个继承Group的自定义节点，移进画布不放手会一直触发报错。
![image](https://user-images.githubusercontent.com/14882781/188822707-7785bac3-b830-487d-aef3-36593b9e092d.png)

在官方demo上做的demo，修改了开始节点为group，拖开始节点进画布就会触发报错
https://codesandbox.io/s/logicflow-base24-forked-qy2wih?file=/step_24_group/index.js

**Comment by wuqinglaoxingxing** [comment]
我遇到了同样问题
