### ISSUE TITLE
[Bug report] 导出图片插件无法导出html图片

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#758]
**问题描述**  
1. 问题触发的条件
    画布创建一个html节点，html节点采用url的方式存放图片，使用 [Snapshot] 插件导出画布图片

2. 期望的表现
    正常的图片显示

3. 实际的表现
    无法正确解析URL路径，html节点图片渲染失败

![exportBug](https://user-images.githubusercontent.com/18308819/188843256-715ae165-18d6-45fd-bd6d-d46a69176548.gif)

**最简复现demo**  
codesanbox：https://codesandbox.io/s/gifted-greider-4hbcl9?file=/src/htmlImg.js:740-744

**Comment by towersxu** [comment]
duplicated #477
