### ISSUE TITLE
[Bug report] 连接2个节点时，从一个节点的锚点拖动时，如果在画布空白处释放，没有触发相应的事件

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#759]
连接2个节点时，从一个节点的锚点拖动时，如果在画布空白处释放，没有触发相应的事件（最好能有个drag:end事件）。

**Comment by wangzhengbo** [comment]
我觉得有个anchor:dargabort事件可能合适些

**Comment by towersxu** [comment]
能说一下这个功能具体应用场景吗？加太多用不到的功能会增加项目的维护难度和代码体积。

**Comment by wangzhengbo** [comment]
> 能说一下这个功能具体应用场景吗？加太多用不到的功能会增加项目的维护难度和代码体积。

默认节点锚点都隐藏，从一个锚点拖拽出来的时候，其它能连接的锚点才显示。如果中途放弃连接，其它显示的锚点要隐藏。
目前实现上面的效果碰到的问题。需要知道是放弃连接了，然后做一些处理。

目前我在安装依赖后执行的postinstall中修改logicflow的代码来实现了这样的功能。但是框架能支持是更好

**Comment by towersxu** [comment]
已在1.1.28支持

**Comment by wangzhengbo** [comment]
> 已在1.1.28支持

多谢，新版本已经用，不用在postinstall中去修改logicflow源码了。目前碰到一个小问题（在节点mouse enter时，框架会将isShowAnchor设置为true，mouse leave时将isShowAnchor设置为false；如果一个节点没有mouse enter的时候，我的业务代码将isShowAnchor设置为true了，但是节点mouse enter/leave后，isShowAnchor会被框架重置为false），不过这个小问题我绕开了（在mouse leave后，业务代码重新设置节点的isShowAnchor为true）

**Comment by towersxu** [comment]
嗯，这个小问题是有点难受，我先打开issue，后面尽快处理一下。
