### ISSUE TITLE
自定义节点创建svg元素

### ISSUE THREAD

**Issue by amoalys** [didi/LogicFlow#76]
使用 Logic Flow 提供的 h 方法来创建 SVG 元素。对于复杂的元素，可不可以支持导入svg文件,不用一个标签一个标签创建。

**Comment by yhlchao** [comment]
谢谢建议，我们正在思考创建 SVG 的语法糖，如果你对这方面有新的想法，欢迎继续向我们提交 issue～

**Comment by amoalys** [comment]
我想问一下哈：1.两个节点间连接一条线后，随意拖动那条线的边，那个箭头有时会消失。2.自定义两个节点，使用svg生成的两张图片，通过get anchors()自定义了几个锚点，锚点之间连接后随意拖动线条，靠近图片的线条会变细。3.如果直接在自定义节点的model里面设置this.points几个值后有了锚点，然后建立连线后，拖动连接线条会报错。4.polyline情况下，线条产生的边，可以分段或者禁止它是否可以拖动吗？

**Comment by amoalys** [comment]
@yhlchao

**Comment by towersxu** [comment]
目前有html节点，复杂元素可以使用html节点来实现。
