### ISSUE TITLE
[Bug report] 编辑文本时，会触发快捷键的回调

### ISSUE THREAD

**Issue by soom-lupulus** [didi/LogicFlow#760]
**问题描述**  
1. 问题触发的条件
在编辑文本时，会触发个别快捷键的回调（backspace，space等并不会触发，但是配置的英文字母就会触发，截图配置的e为快捷删除）
2. 期望的表现
编辑状态下不会触发快捷键的回调；
提供一个取消边的选中状态的方法（目前只能取消node节点的）；
3. 实际的表现
![convert](https://user-images.githubusercontent.com/61748548/189043536-a8c50ef1-ff4b-4eac-8b1d-c0975e8b1d3e.gif)

**Comment by towersxu** [comment]
1. 英文字符触发自定义快捷键的问题将在1.1.27版本修复。
2. 取消边的选中状态的方法，可以使用clearSelectElements方法。
