### ISSUE TITLE
分组组件放到控制面板再拖拽的时候报错[Bug report]

### ISSUE THREAD

**Issue by inshuang** [didi/LogicFlow#762]
group组件放到控制面板的时候 起初是没有设置id的 拖入后 会自动匹配一个id 之前的版本这个没报错 最新的版本会报错 建议不对分组组件加id验证
![image](https://user-images.githubusercontent.com/34765914/189074990-1685dd8f-ed1b-440f-8c5a-a7f778399a4f.png)

**Comment by towersxu** [comment]
#757
