### ISSUE TITLE
双击节点只触发一次点击监听事件

### ISSUE THREAD

**Issue by ouweicong** [didi/LogicFlow#765]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
节点注册点击监听事件node:click，快速双击节点同一位置，只触发一次监听事件（已经禁用文本编辑）

3. 期望的表现
能触发2次监听事件
5. 实际的表现

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 在任意在线编码平台，编写示例如[codesanbox](https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js。将其保存到自己空间，然后贴上链接。
2. 在自己github中创建一个最简单的示例，然后贴上github链接。
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by towersxu** [comment]
这个需求有点怪，为什么需要触发两次事件？

**Comment by ouweicong** [comment]
我这边想实现一个节点单击事件和双击事件，单击和双击各进行不同的操作

**Comment by towersxu** [comment]
你是期望触发dbclick的时候不触发click？

**Comment by ouweicong** [comment]
是的

**Comment by towersxu** [comment]
在开发的时候，我们也纠结双击是否需要触发一次单击。最终因为在原生DOM的事件里面双击会触发单击，为了尽力与原生DOM保持一致，我们还是选择了双击会触发一次单击。如果你项目的确需要区分双击和单击，可以参考这里https://stackoverflow.com/questions/1067464/need-to-cancel-click-mouseup-events-when-double-click-event-detected

**Comment by ouweicong** [comment]
感谢
