### ISSUE TITLE
自定义HTML节点内的button需要选中才能点击[Bug report]

### ISSUE THREAD

**Issue by G-guo** [didi/LogicFlow#767]
引用 #763 @towersxu 回复
 
不是方法的问题，是点击没选中节点的按钮连 setData 都没有调用

**Comment by towersxu** [comment]
感谢提出，这里是有问题，将在下个版本修复。原因是节点内通过mouseup来模拟了click，但是因为在默认堆叠模式下，节点点击会将被点击的节点置顶，而置顶的节点会修改移动DOM的位置，从而出现节点内部绑定的事件无法被触发。

**Comment by towersxu** [comment]
已修复
