### ISSUE TITLE
是否有支持自定义默认边样式

### ISSUE THREAD

**Issue by makabaka29** [didi/LogicFlow#769]
您好，
我想要在新建的节点上默认拉出的边为line类型，但是目前默认的边样式为polyline。
我在文档的主题样式中没有找到类似的设置，请问是否有能够实现该功能的方法或设置？

**Comment by towersxu** [comment]
目前定义边的默认类型有3中方式：
1. 初始化的时候传入edgeType
2. 使用api setDefaultEdgeType
3. 在1.1.26版本提供的[edgeGenerator](https://github.com/didi/LogicFlow/pull/739)
目前文档确实没有专门拿出一块来说明，稍后我补一下 。

**Comment by makabaka29** [comment]
> 

ok 感谢您的回复，问题解决了
