### ISSUE TITLE
文本多的位置能否增加多样性

### ISSUE THREAD

**Issue by z308790037** [didi/LogicFlow#77]
**问题描述**  
目前看文本只能居中。能否增加靠上左右下，或者根据position自定义

**Comment by towersxu** [comment]
文本自己的x,y就是偏移量。比如这种就是自定义开始节点的时候，设置y偏移35.

**Comment by towersxu** [comment]
![image](https://user-images.githubusercontent.com/4093984/111438283-074b5900-873f-11eb-84f5-a61fbb1a1070.png)

**Comment by sunyongjian** [comment]
@z308790037 看能不能满足需求~
