### ISSUE TITLE
getDefaultAnchor 设置默认锚点方法[Bug report]

### ISSUE THREAD

**Issue by inshuang** [didi/LogicFlow#771]
![ae351e67ff143c71ab28838ca083643](https://user-images.githubusercontent.com/34765914/189827568-06cf462a-0805-4ff9-8452-5cee9fe156a5.png)
![4004a5e243a026d829edfd2589feb53](https://user-images.githubusercontent.com/34765914/189827613-194f0888-2581-449f-905f-63c2feaf42ad.png)
getDefaultAnchor方法里面添加type属性 再给锚点添加校验规则 拖拽锚点的时候 校验规则打印出来的值是node的信息 而非锚点的信息
官方给出的示例中 得到是锚点的信息
![26064059ba9a240627e5d97d29fb4d2](https://user-images.githubusercontent.com/34765914/189827989-a353a917-b9cc-48ef-9d78-741c0ded7a0e.png)

**Comment by towersxu** [comment]
请仔细看一下validate的参数

**Comment by inshuang** [comment]
解决 少写参数的问题 感谢
