### ISSUE TITLE
自定义锚点边数据丢失

### ISSUE THREAD

**Issue by superchangme** [didi/LogicFlow#772]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 参考官网例子自定义节点的锚点
http://logic-flow.org/guide/basic/node.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E7%9A%84%E9%94%9A%E7%82%B9。 需要在用户操作了锚点连线之后，我将边的数据信息sourceNodeId,sourceAnchorId,targetNodeId,targetAnchorId保存了起来。当数据更新时。将保存的边信息存放在edge属性，调用lf.render函数渲染。
2. 期望的表现：期望渲染正常
3. 实际的表现：存在多条边的信息时，边的关系会错乱

**最简复现demo**  
```
 // 已有边
  let edges = lf.getNodeOutgoingEdge(Out_Node_Id)

edges = edges.filter(t=>过滤逻辑).map(t=>{
          return {
            id: uuid(),
            sourceNodeId: t.sourceNodeId,
            sourceAnchorId: t.sourceAnchorId,
            targetNodeId: t.targetNodeId,
            targetAnchorId: t.targetAnchorId,
            type: "bezier"
          }
     })
 lf.render({
          nodes,
          edges
        });
```

**Comment by towersxu** [comment]
为什么边的数据不保留pointsList和startPoint、endPoint？LogicFlow是基于这些数据来绘制连线的

**Comment by superchangme** [comment]
> 为什么边的数据不保留pointsList和startPoint、endPoint？LogicFlow是基于这些数据来绘制连线的
因为数据是动态的，用户可以把1中间某个锚点删除

**Comment by towersxu** [comment]
这个功能我们暂时不打算支持，如果你们不存储连线和锚点这些位置数据，只有自己去计算合适的位置数据了。
