### ISSUE TITLE
[Bug report] 自定义节点svg渐变渲染，导出图片时颜色填充丢失

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#780]
**问题描述**  
1. 问题触发的条件
节点采用自定义svg渐变渲染，使用默认的 Snapshot 插件导出图片，无法导出渐变色，填充色丢失

2. 期望的表现
希望canvas渲染的图片和用户看见的效果保持一致

3. 实际的表现
渐变效果丢失
![gradientNode](https://user-images.githubusercontent.com/18308819/191151366-5507b65b-5500-4797-b7ae-7b452fa184f9.gif)

**最简复现demo**  
codesanbox:  https://codesandbox.io/s/distracted-stitch-90r1pm?file=/src/index.js

**Comment by muyuanshan** [comment]
在 SVG 中，冒号用于分隔属性名和属性值。如果在fill属性的属性值中包含了冒号，例如fill="url(#gradient:myGradient)"，那么这个冒号会被解释为属性值的一部分，而不是分隔符，这可能会导致浏览器无法正确解析属性值，从而无法正确绘制 SVG 图形。
所以在例子中的，这个地方把冒号去掉就可以了。
![image](https://user-images.githubusercontent.com/51943988/226892710-2090807a-981b-450a-9f97-a48b8a872af0.png)
