### ISSUE TITLE
在edge:add 事件中通过changeEdgeId修改Id后，不出现箭头

### ISSUE THREAD

**Issue by kmprof** [didi/LogicFlow#788]
**问题描述**  
在edge:add事件中通过changeEdgeId修改Id后，不出现箭头，anchor:drop事件中修改通用也不出现
**dmeo**
可以在这个[案例](https://codesandbox.io/s/logicflow-base4-lx1n1?from-embed=&file=/step4/index.js)上修改
![image](https://user-images.githubusercontent.com/69748518/191645607-28570e0b-b111-49c6-9a31-613fc2b49721.png)

**Comment by towersxu** [comment]
确实是个bug，应该是前几个版本增加了自定义箭头没有考虑到changeEdgeId api，我们本周尽快修复。
