### ISSUE TITLE
使用react-dnd拖拽，如果将页面的客户端坐标转换画布本地坐标？急急急

### ISSUE THREAD

**Issue by chengjiashuai** [didi/LogicFlow#790]
类似于antv X6的clientToLocal()方法

**Comment by towersxu** [comment]
在lf.graphModel.transformModel中有`HtmlPointToCanvasPoint`和`CanvasPointToHtmlPoint`

**Comment by chengjiashuai** [comment]
HtmlPointToCanvasPoint试了一下，并不能解决我的问题，我的目的是想要把react-dnd拖放的浏览器坐标转换成画布坐标

**Comment by towersxu** [comment]
getPointByClient也不行吗？

**Comment by chengjiashuai** [comment]
解决了，多谢
