### ISSUE TITLE
group isAllowAppendIn 建议多暴露一个鼠标的参数

### ISSUE THREAD

**Issue by waht123** [didi/LogicFlow#800]
存在的情况如下,画布节点过多的时候,拖动节点从组上划过的时候并不期望触发当前组的事件,期望是在节点被拖拽到目标组的时候再触发,这时需要鼠标当前状态来区分用户的行为

**Comment by towersxu** [comment]
拖动的时候触发这个方法主要是让分组做出高亮的提示，现在这样有什么问题吗？

**Comment by waht123** [comment]
但是我们怎么捕捉用户的意图呢 ,是想拖进当前分组还是从当前组上划过,只有拖拽结束(鼠标弹起的时候)才能正确感知用户的意图

**Comment by towersxu** [comment]
为什么需要判断划过？目前的思路是拖动节点到分组上面后，分组判断这个节点能被添加进来就做出高亮，不能就不高亮。

**Comment by waht123** [comment]
其实我是想要一个能监听1.能添加到组内的节点时做一些节点信息的更改 2.反之移除时做相应的更改信息 3.组内拖拽时不做信息更改(目前在组内拖拽节点是拖拽中是能捕捉当前节点的信息,鼠标moseup的时候是删除了当前节点从新走了一次添加), 
这个时候我需要知道用户的意图以及节点是否能被添加,不能被添加的节点再手动将其移除到组外展示避免视觉错误

**Comment by towersxu** [comment]
没有看明白，你的意思是需要节点被添加和移除分组的事件？

**Comment by waht123** [comment]
对的对的

**Comment by towersxu** [comment]
这个可以有，我们后续版本会添加。

**Comment by waht123** [comment]
3q

**Comment by boyongjiong** [comment]
已发新版本，可以更新尝试一下，我先关闭此 issue
