### ISSUE TITLE
feature: 小地图支持设置宽高等参数

### ISSUE THREAD

**Issue by afuryboy** [didi/LogicFlow#802]
**问题描述**  
希望logic-flow的小地图miniMap可以支持自定义配置地图的宽高、位置（目前只支持left\top不太方便）、以及header和关闭icon的显影。

**Comment by towersxu** [comment]
小地图目前功能还不够，后续版本会逐步提供这些功能。

**Comment by wangzhengbo** [comment]
+1，希望能支持设置小地图的高宽，小地图里面预览矩形的高宽

**Comment by xinxin93** [comment]
> 
    添加下面css隐藏 header和关闭icon 
    .lf-mini-map-header, .lf-mini-map-close {
      display: none;
    }
    .lf-mini-map {
      padding-top: 0;
    }
