### ISSUE TITLE
[Bug report]提供获取节点所处路径所有节点API

### ISSUE THREAD

**Issue by cxx-iloveyou** [didi/LogicFlow#806]
问题：如何一次性获取到节点一个宗族的节点？似乎目前没有这样的API

场景：自定义了条件分支（类似树结构），小分支上要插入其他节点，无法一次性获取他的父节点，祖父节点，曾祖父节点.....，必须一层一层获取，以及一次性获取到他的子节点，孙子节点，曾孙子节点......。我需要判断他插入的节点是否是在条件分支里插入的

期望：可以提供获取祖宗节点的API和获取子孙节点 的API

**Comment by towersxu** [comment]
这个不支持。由于logicflow本身不限制图的结构，所以不是所有的都是树这种有宗族结构。这个时候提供这种API就不通用。你可以通过edges自己算一下。
