### ISSUE TITLE
新需求：希望节点数据里加上Anchor的数据

### ISSUE THREAD

**Issue by isCopyman** [didi/LogicFlow#808]
![image](https://user-images.githubusercontent.com/25970108/194832282-5ddd0e59-41d2-4093-9005-7c1d326fdfee.png)
![image](https://user-images.githubusercontent.com/25970108/194832309-ed883cd8-7b6c-4c0f-8ac8-53f8786a9712.png)
目前拿到的graphdata里是没有节点的anchor数据的，如图2

**Comment by towersxu** [comment]
请参考http://logic-flow.org/guide/basic/edge.html#%E4%BF%9D%E5%AD%98%E9%94%9A%E7%82%B9%E4%BF%A1%E6%81%AF
