### ISSUE TITLE
[需求] 希望能增加节点属性，能使单个节点定制自身的gridsize

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#811]
1. 业务场景
   需要让自定义节点能够定制自身的移动尺寸，便于更流畅的计算移动边距，及特定场景的拖拽体验（该类型节点不需要对齐）

2、现有状态及期待
![image](https://user-images.githubusercontent.com/18308819/194987478-28b764d2-3f4d-4fb7-a628-d58479823955.png)
    现在只能根据创建画布对象时的全局 grid.size 去对齐，无法实现特定场景需求，希望能增加节点属性，如果该节点gridsize存在，则以及该值替代全局gridsize执行对齐

**Comment by towersxu** [comment]
这个目前不考虑支持，你可以尝试去掉grid自己监听node:drop事件，在节点移动后算一下这个节点位置是否对齐，没对齐就移动一下。
