### ISSUE TITLE
[需求]自定义的背景图片无法随着画布缩放而缩放

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#812]
1. 问题描述
    在 backgroundImage 中自定义设置的图片无法随着画布的缩放而缩放，希望自动化或提供相应的方法，能够根据画布缩放比去设置图片缩放比。

**Comment by towersxu** [comment]
这个需求感觉有点不合理，因为有的人给的背景图就像我们桌面背景一样，这个时候缩放了不好看。你们自己项目需要的话，可以考虑自己监听缩放比，然后用css缩放。
