### ISSUE TITLE
[需求] focusOn 或者 translate 平移的动画过渡

### ISSUE THREAD

**Issue by GengZiwei** [didi/LogicFlow#813]
页面视图需要进行预览展示流程，执行focusOn或者translate 进行定位展示过于生硬，是否可以提供给个过渡到效果。

**Comment by towersxu** [comment]
你试试自己强制给画布所属的dom节点加一个transform css.

**Comment by GengZiwei** [comment]
对lf-drag-able 的class下面设置transition-timing-function跟transition-duration就有了

**Comment by GengZiwei** [comment]
跟matrix一起
