### ISSUE TITLE
node宽度不够时，锚点定位异常

### ISSUE THREAD

**Issue by zhaoyang-bupt** [didi/LogicFlow#817]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
resize node宽度较小时，polyline的自定义锚点定位异常，定位错误

复现步骤：
1.连接到左边的锚点
![image](https://user-images.githubusercontent.com/84660716/195751406-b394981a-44fc-41ec-a168-cea11f018f0a.png)
2.连接后的效果
![image](https://user-images.githubusercontent.com/84660716/195751527-7c7f88b4-d159-4ba1-9f29-a9d1e9b7efee.png)
3.将edge往上移动一点发现，实际连接到了第3个锚点
![image](https://user-images.githubusercontent.com/84660716/195751603-324e1b74-e8dc-40c5-93d6-17a09bd44b47.png)
PS：将测试的node宽度拉大一点，再重复上述步骤，就没有如上问题
![image](https://user-images.githubusercontent.com/84660716/195751741-8bb973b5-4d0b-40af-8dfa-d8fc4c2b9fd9.png)

代码： https://codesandbox.io/s/unruffled-nash-dqq3h2?file=/src/index.js

**Comment by zhanglei518** [comment]
请问这个bug近期有修复计划嘛，
