### ISSUE TITLE
[Bug report] NodeResize 最大/最小值设定后，极限拖拽不流畅

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#819]
**问题描述**  
1. 问题触发的条件
节点缩放 NodeResize 设置放大缩小的最大（maxWidth、maxHeight）最小值（minWidth、minHeight）后，在拖拽放大/缩小到接近某一轴（x / y）的极限时，另一轴无法再拖拽，影响用户体验。

2. 期望的表现
希望拖拽到最大/最小设置的极限设定时，再次拖拽能向极限值适应，拖拽更加流程

**Comment by DymoneLewis** [comment]
您好，您反馈的问题已于1.2.27版本处理完成，辛苦升版本试一下
