### ISSUE TITLE
[Bug] updateEditConfig更改isSilentMode状态问题

### ISSUE THREAD

**Issue by promiseMIMI** [didi/LogicFlow#826]
**问题描述**
`updateEditConfig({
   isSilentMode:  true,
 })`
更改isSilentMode为false之后，编辑节点text，点击空白区域无法更改为非编辑模式（编辑框一直都在）
![1dff5bb3e2ef10a6a0bedc25a3f85c0](https://user-images.githubusercontent.com/34825137/197524008-414b1128-39ab-47fb-a76b-f385321f6b7a.jpg)

**复现地址**https://codesandbox.io/s/bitter-glade-8tqzxd?file=/src/App.js:1221-1233

**Comment by towersxu** [comment]
这是一个BUG，将于下个版本解决。目前你可以通过自定义监听点击空白区域来解决这个问题。

```js
lf.on('graph:transform,node:click,blank:click', () => {
    if (lf.graphModel.textEditElement) {
      lf.graphModel.textEditElement.setElementState(1);
    }
  });
```

**Comment by promiseMIMI** [comment]
> 这是一个BUG，将于下个版本解决。目前你可以通过自定义监听点击空白区域来解决这个问题。
> 
> ```js
> lf.on('graph:transform,node:click,blank:click', () => {
>     if (lf.graphModel.textEditElement) {
>       lf.graphModel.textEditElement.setElementState(1);
>     }
>   });
> ```
这样还存在个问题，监听history:change不会被触发
![image](https://user-images.githubusercontent.com/34825137/197678321-cd3665b0-134a-4cf3-aeb0-223dc74e6818.png)
