### ISSUE TITLE
[Bug report] 在initNodeData()中动态创建的对象无法在render()方法中生效

### ISSUE THREAD

**Issue by gh565923562** [didi/LogicFlow#828]
**问题描述**  
1. 问题触发的条件
   在节点 initNodeData() 方法中使用 addNode() 等方法动态创建其他节点对象；使用 render() 方法对该节点数据进行渲染，动态创建的对象无法添加到 graphModel.nodes 中。
2. 问题原因
   render() 方法渲染数据时，会在之前的 graphModel 中创建动态对象，但返回的是新的graphModel
3. 希望的表现
   render() 中先构建出新的graphModel对象，然后在新的对象中执行所有节点的构造

**Comment by towersxu** [comment]
你是什么需求需要在initNodeData中创建其他节点呢？

**Comment by gh565923562** [comment]
![Mark](https://user-images.githubusercontent.com/18308819/197696369-1f4ad912-5bed-4a66-9864-1bd165602488.gif)

如图，创建一个标记对象，对象中由可拖拽的标记点，但数据中只记载一个node信息，点是只提供坐标动态生成的。
可能我这是比较特殊的业务需求，但我觉得在渲染时应该是能支持动态创建的，我现在的业务已经通过 graph:rendered 事件来处理了

**Comment by towersxu** [comment]
目前看来这个需求相对比较特殊，所以不内置到logicflow里面。目前在graph:rendered中来处理有什么问题吗？如果没有我觉得这样也行。

**Comment by gh565923562** [comment]
主要是会产生不必要的性能开销，如果这种节点比较多，要再生成一次哪个点，并且重新计算连线，大数据下可能性能比较吃紧。

**Comment by towersxu** [comment]
可以尝试写个adapter, 在数据渲染前把额外节点给加上。
