### ISSUE TITLE
小地图插件改版

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#829]
**问题描述**  
目前小地图插件存在如下问题：
1. 直接复用用户创建的节点和连线，性能消耗过大。
2. #802 
3. 无限移动画布后会出现视口丢失。
4. #839
5. #903

**Comment by yangmi0829** [comment]
1. 拖拽创建节点时initNodeData和setAttributes会触发多次，移动节点也会触发
2. 希望支持特殊字符，设置小地图位置左上/左下/右上/右下。

**Comment by wangzhengbo** [comment]
请问下这个改版有预估的发布时间吗？

**Comment by qingshansuiyun** [comment]
小地图的右上角自带的关闭icon点击后不能更新外部flag变量，能否提供当前小地图是否显示的api，或者有其它更好的解决方法？
