### ISSUE TITLE
可缩放节点，在节点缩放后，连线不跟着锚点走[Bug report]

### ISSUE THREAD

**Issue by 1126783699** [didi/LogicFlow#831]
**问题描述**  
使用官网提供的示例，在自己创建的vue3最简单的helloworld项目下，添加demo代码，运行后操作缩放节点，出现连线不跟着锚点走的问题
![image](https://user-images.githubusercontent.com/51231376/198174665-773338ec-9788-481c-8c9b-66d1b5891d4b.png)

**最简复现demo**  
demo：
[HelloWorld.zip](https://github.com/didi/LogicFlow/files/9875122/HelloWorld.zip)

**Comment by 1126783699** [comment]
邮件已收到，我会尽快查看的哈！

**Comment by wumail** [comment]
本周将发版的1.2.10中修复了该问题，烦请升级版本后重试～

**Comment by wumail** [comment]
> 邮件已收到，我会尽快查看的哈！

本周将发版的1.2.10中修复了该问题，烦请升级版本后重试～
