### ISSUE TITLE
请问怎么获取Selection区域的坐标和大小？

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#832]
在多选节点后创建的Selection，现在需要在它上使用邮件创建菜单。需要知道Selection区域的x, y坐标和size，有内置的API能实现吗？

**Comment by wangzhengbo** [comment]
document.querySelector('.lf-multiple-select').style中是可以拿到

**Comment by towersxu** [comment]
目前没有API，selection是通过计算所有的节点坐标+宽高算出来的，你可以使用同样的方式计算。
