### ISSUE TITLE
多选节点目前不支持ctrl，只支持meta, alt, shift

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#836]
目前多选节点只支持multipleSelectKey设置为meta, alt, shift，但是项目有需求要求使用ctrl快捷键。看logicflow源码中注释说ctrl会触发contextmenu，没有看到哪里使用了ctrl来触发contextmenu

**Comment by wangzhengbo** [comment]
我修改源码，改成ctrl，发现ctrl是可以用的，没有碰到其它副作用。请问代码中下面的注释中提到的原因是啥情况？

  /**
   * 多选按键, 支持meta(cmd)、shift、alt
   * 不支持ctrl，ctrl会触发contextmenu
   */
  multipleSelectKey?: string;

**Comment by towersxu** [comment]
这个是浏览的默认行为，你可以任何按下ctrl + 左键，都表现出点击鼠标右键的表现。为了不影响这个默认行为，所以才没有支持ctrl。

**Comment by wangzhengbo** [comment]
> 这个是浏览的默认行为，你可以任何按下ctrl + 左键，都表现出点击鼠标右键的表现。为了不影响这个默认行为，所以才没有支持ctrl。因为如果支持了，多选会触发节点的右键点击事件，如果我们基于右键点击做了线上菜单这类操作，就会出现多选时也出现菜单。

我试了没碰到这种情况哦。Chrome下按住Ctrl + 左键点击节点，没有触发节点的contextmenu事件。

**Comment by wangzhengbo** [comment]
Mac上确实是这样的

**Comment by wangzhengbo** [comment]
我想在Mac上支持meta，Windows上支持ctrl（Windows上没有ctrl + 点击触发上下文菜单的问题）。但是LogicFlow限制不能用ctrl，请问这个限制能放开吗？

**Comment by towersxu** [comment]
这样的话确实可以放开，下个版本我加一下这个功能。

**Comment by towersxu** [comment]
FIXED https://github.com/didi/LogicFlow/pull/870
