### ISSUE TITLE
[Bug report] 多节点框选和画布拖拽不能同时启用问题

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#838]
目前多节点框选和画布拖拽不能同时启用，只能启用一个，通过开关来回切换。
可以考虑左键拖拽是框选节点，右键拖拽是拖拽画布，或者反过来，左键拖拽是拖拽画布，右键拖拽是框选节点吗？
这样2个功能就能同时启用，不会冲突

**Comment by towersxu** [comment]
不确定这种交互的效果怎么样，有见过什么产品用的是这个效果吗？

**Comment by wangzhengbo** [comment]
> 不确定这种交互的效果怎么样，有见过什么产品用的是这个效果吗？

暂时没见过有哪个产品这么用。但是相比框选和拖拽不能同时启用，这个方案还是可以接受的。

**Comment by towersxu** [comment]
这个暂时不考虑内置支持，你可以参考现有的选区插件，自己实现一个右键拖拽框选的功能。

**Comment by terralian** [comment]
> 不确定这种交互的效果怎么样，有见过什么产品用的是这个效果吗？

只是说产品的话，效果可以看看
- Xmind（左键框选，中键滚动，右键单击菜单，不放画布拖拽）
- excalidraw（左键框选，中键画布拖拽，右键菜单）

不同鼠标按键支持不同功能对操作的灵活度提升很大，需求感觉还挺普遍的，希望未来可以加入Feature
