### ISSUE TITLE
关于Mini Map不支持自定义HTML Node的问题

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#839]
目前Mini Map不支持自定义HTML Node，请问是否可以考虑使用Snapshot插件,  生成图片渲染在Mini Map部分来修复这个问题呢？
请问这个方案可行吗？

**Comment by towersxu** [comment]
小地图会准备改版，修改内容在issue #829 中，目前计划改成和其他的库一个，只显示节点的轮廓，不显示节点的具体内容。

**Comment by wangzhengbo** [comment]
> 小地图会准备改版，修改内容在issue #829 中，目前计划改成和其他的库一个，只显示节点的轮廓，不显示节点的具体内容。

请问改版大概什么时候能完成，有排期吗？

**Comment by towersxu** [comment]
@wangzhengbo 目前我们也有自己业务上的事情，只有利用业余时间做，所以时间不确定。你要是项目比较紧急，可以看看minimap的源码自己实现一个插件。

**Comment by wangzhengbo** [comment]
> @wangzhengbo 目前我们也有自己业务上的事情，只有利用业余时间做，所以时间不确定。你要是项目比较紧急，可以看看minimap的源码自己实现一个插件。

好的，多谢！

**Comment by wangzhengbo** [comment]
> 目前Mini Map不支持自定义HTML Node，请问是否可以考虑使用Snapshot插件, 生成图片渲染在Mini Map部分来修复这个问题呢？ 请问这个方案可行吗？

目前的版本是支持自定义HTML Node的，因为我没有开始history功能，导致增加节点后缩略图没有显示添加的节点（Mini Map目前是通过监听history:change事件来触发刷新）。

感觉这里可以在Mini Map文档备注下，开启Mini Map后history选项不能设置为false。或者Mini Map中做下优化，不依赖history来监听变化。
