### ISSUE TITLE
连线上的文字拖拽功能貌似存在问题

### ISSUE THREAD

**Issue by assassinfym** [didi/LogicFlow#842]
LogicFlow提供在初始化的时候，支持edge的Text拖拽  edgeTextDraggable，这个功能没有问题，但是因为特殊场景，只支持指定类型的(自定义)edge的文字允许拖拽

我自定义了一个连线（基于Polyline，去掉了无用代码）
class PolylineCustomModel extends PolylineEdgeModel {
    initEdgeData(data){
        if(!data.id){
            data.id = "link-" + uuidv4();
        }
        
        this.text.draggable = true;
        super.initEdgeData(data);
    }

    setAttributes() {
        this.offset = 20;
    }
    getEdgeStyle() {
        const style = super.getEdgeStyle();
        const { properties } = this;
        style.stroke = "#1890FF";
        style.strokeWidth = 2
        return style;
    }
    getTextStyle() {
        return super.getTextStyle();
    }
    getOutlineStyle() {
        return super.getOutlineStyle();
    }
}

export default {
    type: "PolylineCustomModel",
    view: PolylineEdge,
    model: PolylineCustomModel
};

其中    initEdgeData  我增加了 this.text.draggable = true; ，支持这种自定义的连线可以拖拽文字，但是添加了以后会出现 连线的箭头消失了(如下图)
initEdgeData(data){
        if(!data.id){
            data.id = "link-" + uuidv4();
        }
        //这句代码 ，比如去掉才正常，改成false也不行
        this.text.draggable = true;
        super.initEdgeData(data);
}
![image](https://user-images.githubusercontent.com/15188754/199147789-ea3a9730-a452-4abd-8194-af6f0bc9c667.png)

我的组件版本 
![image](https://user-images.githubusercontent.com/15188754/199169767-d560b795-da65-4f86-b230-bc11e55a5a66.png)

我不确定是我使用上的问题，还是这部分逻辑处理存在缺陷

**Comment by towersxu** [comment]
能提供一个在线示例吗？
