### ISSUE TITLE
getBpmnId存在问题

### ISSUE THREAD

**Issue by assassinfym** [didi/LogicFlow#843]
开发环境 Electron +Vue 基于NodeJS模式 （Web环境没问题）
xxxxxx\node_modules\@logicflow\extension\cjs\bpmn\getBpmnId.js
xxxxxx\node_modules\@logicflow\extension\cjs\bpmn-adapter\bpmnIds.js

两个文件中，关于ids的引用在Nodejs模式存在问题
原先的方式
![image](https://user-images.githubusercontent.com/15188754/199171856-20993cb8-dffe-40d7-82a1-a8bb5932ad96.png)
需要修改成：
![image](https://user-images.githubusercontent.com/15188754/199172002-7e413710-793b-4a21-87a5-73fcf2e5af53.png)

目前我是临时修改了node_modules下的文件解决，不确定这块是哪里配置有问题，或者是程序bug

目前是最新的1.1.30版本

**Comment by jasmine-song** [comment]
#1243

**Comment by wumail** [comment]
现在已经替换ids
