### ISSUE TITLE
初始化流程图时控制台报错

### ISSUE THREAD

**Issue by 15738848982** [didi/LogicFlow#845]
![image](https://user-images.githubusercontent.com/117069643/199687586-e61d5d3d-21de-4be1-832d-ec583adc7a17.png)

**Comment by towersxu** [comment]
请问有在线示例吗？最好带上你初始化传入的数据。

**Comment by 15738848982** [comment]
{"nodes":[{"id":"3d291a4941cc42f9869998a762f7f598","type":"endNode","x":500,"y":582,"properties":{"toolId":"-2","jobId":null,"name":"end","nodeId":27942,"toolCHName":"结束节点"}},{"id":"c3103da2aeb142bdb17e50404b35d0be","type":"startNode","x":500,"y":35,"properties":{"toolId":"-1","jobId":null,"name":"start","nodeId":27941,"toolCHName":"开始节点"}},{"id":"2d16fb479e8746438e7ae7e01f68083b","type":"choose data","x":500,"y":157,"properties":{"toolId":"62","instanceId":"467743952494133888","background":"#61D0B0","name":"选择文件夹","nodeId":27943,"toolCHName":null}},{"id":"1c32c950dd84467688efdc4deb88ae65","type":"QC","x":501,"y":252,"properties":{"toolId":"75","instanceId":"467744153405489792","background":"#F6CD76","name":"QC","nodeId":27944,"toolCHName":"质控"}},{"id":"352394a03495462b87fe80e03ada9225","type":"PT","x":501,"y":358,"properties":{"toolId":"103","instanceId":"468078822181307008","background":"#F9AEC7","name":"PT","nodeId":27945,"toolCHName":"拟时序"}},{"id":"ecb4bd6ffe0b4cb482a61b62512cfe26","type":"ORA","x":501,"y":476,"properties":{"toolId":"99","background":"#F9AEC7","name":"ORA","nodeId":27946,"toolCHName":null}},{"id":"b11017a2856c46f48cae288a048025c0","type":"ORA","x":209,"y":473,"properties":{"toolId":"99","background":"#F9AEC7","name":"ORA","nodeId":27950,"toolCHName":null}},{"id":"dadcedd3121d40678dd1a9b6590e2b8e","type":"DR_CL","x":214,"y":256,"properties":{"toolId":"77","background":"#F6CD76","name":"DR_CL","nodeId":27961,"toolCHName":"降维"}},{"id":"8a7ba1bd431e489c81b5bdd8ce9aef42","type":"DEG","x":211,"y":362,"properties":{"toolId":"79","nodeId":27964,"name":"DEG","background":"#F9AEC7","toolCHName":"差异表达"}},{"id":"a62d7cc3a7cb46f18f03942cab495ca0","type":"CCC","x":213,"y":135,"properties":{"toolId":"101","nodeId":27972,"name":"CCC","background":"#F9AEC7","toolCHName":"细胞通讯"}}],"edges":[{"id":"7ec4d4218c02471ab3f5e873d293c298","type":"polyline","sourceNodeId":"c3103da2aeb142bdb17e50404b35d0be","targetNodeId":"2d16fb479e8746438e7ae7e01f68083b","startPoint":{"x":500,"y":70},"endPoint":{"x":500,"y":122},"properties":{},"pointsList":[{"x":500,"y":70},{"x":500,"y":100},{"x":500,"y":100},{"x":500,"y":92},{"x":500,"y":92},{"x":500,"y":122}]},{"id":"44fcc645720149ac9a396524d4f6b9ac","type":"polyline","sourceNodeId":"2d16fb479e8746438e7ae7e01f68083b","targetNodeId":"1c32c950dd84467688efdc4deb88ae65","startPoint":{"x":500,"y":192},"endPoint":{"x":501,"y":217},"properties":{},"pointsList":[{"x":500,"y":192},{"x":500,"y":222},{"x":"500.5","y":222},{"x":"500.5","y":187},{"x":501,"y":187},{"x":501,"y":217}]},{"id":"d1af7ff3fc3449688a61f82b25d40bf4","type":"polyline","sourceNodeId":"1c32c950dd84467688efdc4deb88ae65","targetNodeId":"352394a03495462b87fe80e03ada9225","startPoint":{"x":501,"y":287},"endPoint":{"x":501,"y":323},"properties":{},"pointsList":[{"x":501,"y":287},{"x":501,"y":317},{"x":501,"y":317},{"x":501,"y":293},{"x":501,"y":293},{"x":501,"y":323}]},{"id":"2331e8896bed4a6287a21a42e3d96434","type":"polyline","sourceNodeId":"352394a03495462b87fe80e03ada9225","targetNodeId":"ecb4bd6ffe0b4cb482a61b62512cfe26","startPoint":{"x":501,"y":393},"endPoint":{"x":501,"y":441},"properties":{},"pointsList":[{"x":501,"y":393},{"x":501,"y":423},{"x":501,"y":423},{"x":501,"y":411},{"x":501,"y":411},{"x":501,"y":441}]},{"id":"727783553b744ac5817c3907657b53cc","type":"polyline","sourceNodeId":"ecb4bd6ffe0b4cb482a61b62512cfe26","targetNodeId":"3d291a4941cc42f9869998a762f7f598","startPoint":{"x":501,"y":511},"endPoint":{"x":500,"y":547},"properties":{},"pointsList":[{"x":501,"y":511},{"x":501,"y":541},{"x":"500.5","y":541},{"x":"500.5","y":517},{"x":500,"y":517},{"x":500,"y":547}]},{"id":"e9ceda5583214a4db37fd20dff334eb2","type":"polyline","sourceNodeId":"352394a03495462b87fe80e03ada9225","targetNodeId":"b11017a2856c46f48cae288a048025c0","startPoint":{"x":501,"y":393},"endPoint":{"x":209,"y":438},"properties":{},"pointsList":[{"x":501,"y":393},{"x":501,"y":408},{"x":209,"y":408},{"x":209,"y":438}]},{"id":"de92b757b0d84a9783a6830fd5d7fd14","type":"polyline","sourceNodeId":"b11017a2856c46f48cae288a048025c0","targetNodeId":"3d291a4941cc42f9869998a762f7f598","startPoint":{"x":209,"y":508},"endPoint":{"x":500,"y":547},"properties":{},"pointsList":[{"x":209,"y":508},{"x":209,"y":517},{"x":500,"y":517},{"x":500,"y":547}]},{"id":"3c9f18dc83a44723823fced36f34a6ea","type":"polyline","sourceNodeId":"2d16fb479e8746438e7ae7e01f68083b","targetNodeId":"dadcedd3121d40678dd1a9b6590e2b8e","startPoint":{"x":500,"y":192},"endPoint":{"x":214,"y":221},"properties":{},"pointsList":[{"x":500,"y":192},{"x":500,"y":222},{"x":357,"y":222},{"x":357,"y":191},{"x":214,"y":191},{"x":214,"y":221}]},{"id":"09e600902754431484d349db731825f0","type":"polyline","sourceNodeId":"dadcedd3121d40678dd1a9b6590e2b8e","targetNodeId":"352394a03495462b87fe80e03ada9225","startPoint":{"x":214,"y":291},"endPoint":{"x":501,"y":323},"properties":{},"pointsList":[{"x":214,"y":291},{"x":214,"y":293},{"x":501,"y":293},{"x":501,"y":323}]},{"id":"0cf768222cf042dd8b907b8f6e361135","type":"polyline","sourceNodeId":"1c32c950dd84467688efdc4deb88ae65","targetNodeId":"8a7ba1bd431e489c81b5bdd8ce9aef42","startPoint":{"x":501,"y":287},"endPoint":{"x":211,"y":327},"properties":{},"pointsList":[{"x":501,"y":287},{"x":501,"y":297},{"x":211,"y":297},{"x":211,"y":327}]},{"id":"6740369d134948508c4aef51de30032d","type":"polyline","sourceNodeId":"8a7ba1bd431e489c81b5bdd8ce9aef42","targetNodeId":"b11017a2856c46f48cae288a048025c0","startPoint":{"x":211,"y":397},"endPoint":{"x":209,"y":438},"properties":{},"pointsList":[{"x":211,"y":397},{"x":211,"y":427},{"x":210,"y":427},{"x":210,"y":408},{"x":209,"y":408},{"x":209,"y":438}]},{"id":"263d4c40213d451e95e77cb860687ed3","type":"polyline","sourceNodeId":"c3103da2aeb142bdb17e50404b35d0be","targetNodeId":"a62d7cc3a7cb46f18f03942cab495ca0","startPoint":{"x":500,"y":70},"endPoint":{"x":213,"y":100},"properties":{},"pointsList":[{"x":500,"y":70},{"x":500,"y":100},{"x":356.5,"y":100},{"x":356.5,"y":70},{"x":213,"y":70},{"x":213,"y":100}]},{"id":"c7944594e9e4482893101809861252a8","type":"polyline","sourceNodeId":"a62d7cc3a7cb46f18f03942cab495ca0","targetNodeId":"dadcedd3121d40678dd1a9b6590e2b8e","startPoint":{"x":213,"y":170},"endPoint":{"x":214,"y":221},"properties":{},"pointsList":[{"x":213,"y":170},{"x":213,"y":200},{"x":213.5,"y":200},{"x":213.5,"y":191},{"x":214,"y":191},{"x":214,"y":221}]}]}


以上是流程图完整的数据，之后就直接给render赋值了，页面流程图可以正常操作，就是控制台报错了。

**Comment by towersxu** [comment]
你这些节点都是自定义节点，我无法复现，能提供codesandbox示例吗？

**Comment by 15738848982** [comment]
不好意思官方，我刚刚对比了一下其他数据发现node节点多了一个字段导致的控制台报错问题，现在不报错了。感谢感谢感谢
