### ISSUE TITLE
如何实现粘贴节点到鼠标所处位置

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#847]
画布鼠标移动事件blank:mousemove不支持，但是文档中说了是支持的。看了源代码，确实没支持blank:mousemove事件。

**Comment by wangzhengbo** [comment]
API文档: http://logic-flow.org/api/eventCenterApi.html#%E7%94%BB%E5%B8%83%E4%BA%8B%E4%BB%B6

源码：
eventMap() {
    return {
      onMouseEnter: this.dragEnter,
      onMouseOver: this.dragEnter, // IE11
      onMouseMove: this.onDragOver,
      onMouseLeave: this.onDragLeave,
      // onMouseOut: this.onDragLeave, // IE11
      onMouseUp: this.onDrop,
    };
  }

onDragOver = (e) => {
    e.preventDefault();
    if (this.fakerNode) {
      const { x, y } = this.clientToLocalPoint({ x: e.clientX, y: e.clientY });
      this.fakerNode.moveTo(x, y);
      const nodeData = this.fakerNode.getData();
      this.lf.setNodeSnapLine(nodeData);
      this.lf.graphModel.eventCenter.emit(EventType.NODE_DND_DRAG, { data: nodeData });
    }
    return false;
  }

只处理了EventType.NODE_DND_DRAG事件，没有emit mousemove事件。

**Comment by wangzhengbo** [comment]
现在需要支持ctrl + c复制节点，ctrl + v粘贴节点到鼠标所处的位置，所以需要通过blank:mousemove获取鼠标在画布中的坐标

**Comment by wangzhengbo** [comment]
blank:mousedown支持，但是blank:mouseup不支持

**Comment by towersxu** [comment]
这个需求只有你自己在项目中全局获取鼠标位置（例如在body中监听）或者在渲染logicflow的父级监听。然后使用（http://logic-flow.org/api/logicFlowApi.html#getpointbyclient）API将鼠标位置转换为logicflow画布内的坐标。
