### ISSUE TITLE
[Bug report]1.0.4 导入json数据且完全覆盖当前编排数据

### ISSUE THREAD

**Issue by wakanuli** [didi/LogicFlow#852]
导入json数据且完全覆盖当前编排数据时：
导入前：右键menu展示正常；
导入后：右键仅且只有选中状态，无menu展示。但是右键节点事件“node:contextmenu”有正常触发；

![企业微信截图_937f95a2-f882-4a7e-9629-e01c99a12b92](https://user-images.githubusercontent.com/93758404/200457724-4f2dd1eb-2467-48b0-b0de-4254ade66b11.png)

![image](https://user-images.githubusercontent.com/93758404/200457832-ad992ec6-9747-4e71-9797-98ee8b601dcb.png)

**Comment by towersxu** [comment]
建议用最新版本试试,如果还有问题麻烦带上示例提个issue
