### ISSUE TITLE
新增一个节点后拖动节点，自定义边的getEdge方法里面调用了graphModel.getNodeModelById()会报错[Bug report]

### ISSUE THREAD

**Issue by huzhigao** [didi/LogicFlow#856]
自定义边：
![image](https://user-images.githubusercontent.com/20855389/200732203-51d65321-2376-4e29-b605-056210ac1c54.png)
报错：
![image](https://user-images.githubusercontent.com/20855389/200732315-12e93604-abae-4dd2-8819-707cadd09d77.png)

**Comment by towersxu** [comment]
没看出哪里有问题，请提供codesandbox示例
