### ISSUE TITLE
[Feature] 希望框架能将计算MultipleSelectTool的style的方法export出来

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#857]
代码中想在通过lf.selectElementById() API多选节点后，同步获取到lf-multiple-select元素的style(left, top, width, height, 目前主要想拿到left, top), 
目前在调用lf.selectElementById()后，不能同步拿到lf-multiple-select的style。而通过获取dom并拿dom节点style的方式，需要等待MultipleSelectTool重新render，需要异步才能拿到lf-multiple-select dom更新后的style。

**Comment by towersxu** [comment]
能说一下你需要用style做什么呢？目前你可以通过拿到所有的节点自己计算。

**Comment by wangzhengbo** [comment]
> 能说一下你需要用style做什么呢？目前你可以通过拿到所有的节点自己计算。

现在有个复制粘贴功能，ctrl + c批量复制选中的节点，ctrl + v粘贴节点到鼠标指针所在位置，粘贴完成后，新生成的节点需要自动选中。如果连续2次ctrl + v粘贴，那么粘贴出来的2批节点位置会完全重叠。所以需要在lf.selectElementById() API多选节点后，通过获取lf-multiple-select dom的坐标信息，并在必要的时候节点通过调用moveNodes api，做下小距离的偏移。

本来是想从logicflow源码中把计算逻辑拷贝出来，但是发现关联的代码有些多，而且这样处理也不合适。

**Comment by towersxu** [comment]
你可以自定义ctrl + v，粘贴的时候判断这个位置是否有节点了，有就把新增的节点偏移一下。

**Comment by wangzhengbo** [comment]
> 你可以自定义ctrl + v，粘贴的时候判断这个位置是否有节点了，有就把新增的节点偏移一下。

单个节点发复制粘贴可以这样处理。多个节点复制粘贴，我目前是对比的粘贴前后的多选框的位置。
