### ISSUE TITLE
[Bug report] multipleSelectKey多选问题

### ISSUE THREAD

**Issue by yyang-git** [didi/LogicFlow#858]
开启multipleSelectKey选中两个元素会出现多选框，而多选框内其他的元素就无法选中了

**Comment by towersxu** [comment]
这个就是multipleSelectKey的功能，选择多个就是让多个节点一起操作。

**Comment by wangzhengbo** [comment]
> 这个就是multipleSelectKey的功能，选择多个就是让多个节点一起操作。

最近也碰到这个问题。可能您没太理解他的意思。比如从左到右依次有A, B, C 3个节点，选择A和C节点后，多选窗口会遮住B节点，这个时候想把B也多选，只能把A,C节点生成的多选框拖拽走，不遮住B后，就可以选择B了。

但目前来看，多选框会生成一个大的矩形，覆盖选择的所有节点，不太好处理目前这个问题。
有些流程图框架，在多选的时候，只是将每个被选中的节点单独标记为选中状态（就像目前大选一个节点一个），不会在顶层生成一个大的矩形遮罩层，就不会有类似的问题。
