### ISSUE TITLE
[Improvment] EventType.NODE_DND_ADD事件希望能在回调中访问到event对象

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#860]
目前在从工具栏拖拽生成一个节点后，会触发EventType.NODE_DND_ADD事件，这个时候想拿到鼠标在画布上的坐标，但是拿不到event对象。

LogicFlow源码this.lf.graphModel.eventCenter.emit(EventType.NODE_DND_ADD, { data: nodeData }); 只有nodeData, 没有event对象.

**Comment by towersxu** [comment]
这个可以，欢迎你PR

**Comment by towersxu** [comment]
FIXED https://github.com/didi/LogicFlow/pull/869
