### ISSUE TITLE
[Improvment]锚点连线问题

### ISSUE THREAD

**Issue by huzhigao** [didi/LogicFlow#861]
![image](https://user-images.githubusercontent.com/20855389/201019970-0d623f5a-bd35-4dd3-ac30-9a12744f545c.png)
源码里面锚点连线支持重写不

**Comment by towersxu** [comment]
目前支持重新样式。如果有更多需求可以支持，能给一下你希望重新成什么样式吗？最好给一下UI设计图，我们需要评估一下这个需求是否合理。

**Comment by huzhigao** [comment]
https://user-images.githubusercontent.com/20855389/201331362-b742c285-d571-442a-92dd-1f8bec634bcb.mp4

锚点连线希望做成视频中那样的效果，跟自定义边保持一致

**Comment by wumail** [comment]
👀 #1354
