### ISSUE TITLE
[Bug report]自定义边里面调用graphModel.getNodeModelById(),lf.changeNodeId()后会报错

### ISSUE THREAD

**Issue by huzhigao** [didi/LogicFlow#864]
codesanbox地址：https://codesandbox.io/s/beautiful-benji-lr4cg4?file=/src/index.js:1255-1267

**Comment by towersxu** [comment]
目前是不支持这样调用，请问是什么情况需要在这里调用这些api？

**Comment by huzhigao** [comment]
想在自定义边的getEdge方法里面通过graphModel.getNodeModelById获取开始节点的x坐标和y坐标，然后跟边的开始和结束坐标来比较判断边是从哪个锚点连出来的

**Comment by DymoneLewis** [comment]
可以从model.sourceAnchorId属性获取到边的起始锚点，辛苦看下是否满足诉求呢

**Comment by huzhigao** [comment]
getEdge() {
    const { model } = this.props
    const { targetNode } = model
}
现在getEdge方法里面可以取到targetNode，但在用lf.changeNodeId改变targetNode的id后，targetNode会变成undefined，麻烦看下

**Comment by DymoneLewis** [comment]
确实有这个问题，这边排查下原因

**Comment by boyongjiong** [comment]
已发版 2.0.1，请升级后使用，如有问题再新建 issue 关联此 issue，先关闭本 issue
