### ISSUE TITLE
[Bug report]节点缩放有几率导致节点上的边出现位置错误

### ISSUE THREAD

**Issue by yyang-git** [didi/LogicFlow#875]
codesanbox： https://codesandbox.io/s/logicflow-base26-forked-bvxmi5?file=/package.json
![1668389898606](https://user-images.githubusercontent.com/26850479/201558015-f6008319-8190-45ba-aa31-4a4cf7733b91.jpg)

**Comment by BJQ888** [comment]
我是通过缩小网格间距，来避免这个问题，grid：{size:0.5,visible:false}

**Comment by chengjiashuai** [comment]
@towersxu 我现在的项目也有这个问题，请问什么时候可以修复，或者有什么解决方法可以参考吗

**Comment by wumail** [comment]
本周将发版的1.2.10中修复了该问题，烦请升级版本后重试～
