### ISSUE TITLE
[Bug report] 画布开启Selection Select插件后，Mac上触发不了画布的右键菜单，Windows上没问题

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#876]
https://github.com/didi/LogicFlow/pull/647  这里merge的改动增加了代码：
wrapper.oncontextmenu = function prevent(ev: PointerEvent) {
        ev.preventDefault();
};

在Mac上ctrl + 点击画布时会触发wrapper.oncontextmenu（windows上画布右击不会触发wrapper.oncontextmenu），
由于使用了ev.preventDefault();，导致画布的onContextMenu事件没有触发。

**Comment by towersxu** [comment]
没能复现这个问题，目前选区是在最上面新增一个区域覆盖下面所有的节点，来实现拖动选区而不是拖动节点。如果你想对选区有更多想法，欢迎自定义插件，给我们PR。

**Comment by JarringBye** [comment]
怎么解决了，没想到这个一年前的问题现在还在，怎么就不能复现而把这个问题关闭呢
