### ISSUE TITLE
业务中需要用到拖拽时的节点样式和拖拽结束后生成的节点求样式不一样的情况，建议支持拖拽中的节点添加样式相关API

### ISSUE THREAD

**Issue by ChengDale** [didi/LogicFlow#878]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
2. 期望的表现
3. 实际的表现

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 在任意在线编码平台，编写示例如[codesanbox](https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js。将其保存到自己空间，然后贴上链接。
2. 在自己github中创建一个最简单的示例，然后贴上github链接。
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by towersxu** [comment]
你可以自定义一个专门用于拖拽的节点，然后兼容dnd:drop，判断新增的是这个专门用于拖拽的节点，就删除这个节点，然后在同样位置新增一个你需要的节点。

**Comment by ChengDale** [comment]
> 你可以自定义一个专门用于拖拽的节点，然后兼容dnd:drop，判断新增的是这个专门用于拖拽的节点，就删除这个节点，然后在同样位置新增一个你需要的节点。

如果结点种类多的话，这样会很麻烦的
我现在的做法是在properties里增加字段，监听面板添加节点，拖拽、拖拽完成事件，然后改变该字段值，然后改变样式
另外，发现一个bug。触发node:dnd-drag事件时不可以改变properties的东东
