### ISSUE TITLE
希望能增加节点最外层(或者自定义层)的类名方法

### ISSUE THREAD

**Issue by ZhangMingZhao1** [didi/LogicFlow#880]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/29058747/201868362-36b9fd3a-609f-4353-bfc0-80bb6bd76df4.png">

一个自定义节点的创建层级有.lf-node.lf-node-default ->.lf-node-content->.getShape()创建的节点 & 文字g节点 ，用getNodeStyle设置的class类名，只能设置最内层的形状节点。 

如果想用类名的方式批量获取一些svg dom，做一些隐藏，移动，动画等效果，现状只能获取到最内层的形状节点，效果会有一些问题，希望能增加一个定义最外层svg容器类名的方法，来操作整体的节点。

**Comment by towersxu** [comment]
嗯，现在确实有这个问题，欢迎PR
