### ISSUE TITLE
[Improvment]删除节点双击事件不生效

### ISSUE THREAD

**Issue by huzhigao** [didi/LogicFlow#881]
执行
const { eventCenter } = this.lf.graphModel
eventCenter.off('node:dbclick', () => {
  console.log('node:click off')
})
回调函数未执行，节点仍然可以双击
![image](https://user-images.githubusercontent.com/20855389/202143544-429796db-7859-455c-a716-e5ed17a466f2.png)

**Comment by towersxu** [comment]
请问什么情况下你可以删除node:dbclick事件呢？

**Comment by huzhigao** [comment]
是不支持删除node:dbclick事件么，希望可以加上这个功能
