### ISSUE TITLE
[Bug report]奇怪的边框

### ISSUE THREAD

**Issue by zyh374892663** [didi/LogicFlow#882]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件：自定义node时，继承了htmlModel
2. 期望的表现：hover或selected时，应用自定义node样式
3. 实际的表现：
![image](https://user-images.githubusercontent.com/33707926/202347046-1c7ff982-e523-49a0-85bb-9e10ec9cac96.png)

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 在任意在线编码平台，编写示例如[codesanbox](https://codesandbox.io/s/logicflow-template-7i2c3?file=/src/index.js。将其保存到自己空间，然后贴上链接。
2. 在自己github中创建一个最简单的示例，然后贴上github链接。
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）
```tsx
const StartNode = (props) => {
    const classNames = useStatus(props.model);

    return <div className={cc(["logic-flow-base logic-flow-start-node", classNames])}>{props.children}</div>;
};

function StartNodeModel(ParentClass) {
    return class extends ParentClass {
        setAttributes() {
            this.width = 120;
            this.height = 60;
            this.text.editable = true;
        }
        getConnectedTargetRules() {
            const rules = super.getConnectedTargetRules();
            const notAsTarget = {
                message: "起始节点不能作为边的终点",
                validate: () => false,
            };
            rules.push(notAsTarget);
            return rules;
        }
        getAnchorStyle(anchorInfo) {
            const style = super.getAnchorStyle(anchorInfo);
            style.fill = "white";
            style.hover.fill = "transparent";
            style.hover.stroke = "transpanrent";
            style.className = "lf-hide-default";
            return style;
        }
        getDefaultAnchor() {
            const { height, x, y, id } = this;
            return [
                {
                    x,
                    y: y + height / 2,
                    type: "bottom",
                    edgeAddable: true,
                    id: `${id}_0`,
                },
            ];
        }
    };
}

const customStartNode: CustomNode = {
    type: NodeTypes.StartNode,
    viewHOC: nodeView(StartNode),
    modelHOC: StartNodeModel,
};

export default customStartNode;

```

**Comment by zyh374892663** [comment]
期望去除白色和黄色边框，应该怎么配置呢？

**Comment by zyh374892663** [comment]
继承Diamond没有该问题

**Comment by towersxu** [comment]
默认的HTML节点并不存在边框，你看看是不是自己项目中存在样式影响了。

**Comment by zyh374892663** [comment]
> 默认的HTML节点并不存在于旁边的框内，你看是不是自己的项目存在于样式影响了。
我将内部内容全部删除后，依然会出现该边框，且该边框贯穿了连接点，应该不是项目样式原因
![image](https://user-images.githubusercontent.com/33707926/203459562-754ca6ff-180a-464f-84a3-52f7571fe489.png)

**Comment by ljmCoder** [comment]
> > 默认的HTML节点并不存在于旁边的框内，你看是不是自己的项目存在于样式影响了。
> > 我将内部内容全部删除后，依然会出现该边框，且该边框贯穿了连接点，应该不是项目样式原因
> > ![image](https://user-images.githubusercontent.com/33707926/203459562-754ca6ff-180a-464f-84a3-52f7571fe489.png)

针对这个foreignobject元素， 查看下你当前的前端框架是否有:focus的设置 
![image](https://github.com/didi/LogicFlow/assets/41459781/e1ea830a-9b05-4b4b-b3ce-3d99cd5b888c)
可能是这块的影响.
