### ISSUE TITLE
是否可以对patch-package进行支持

### ISSUE THREAD

**Issue by zyh374892663** [didi/LogicFlow#883]
当不满足业务需求时，会涉及到修改源码，并记录补丁，是否可以支持patch-package，或有其他方式可以记录补丁并在安装时进行打补丁

**Comment by zyh374892663** [comment]
@towersxu

**Comment by towersxu** [comment]
这个可以有，欢迎PR

**Comment by boyongjiong** [comment]
这个是啥东西啊，感觉很奇怪，patch-package 就是用户在自己项目中打补丁吧。这玩意儿需要我们支持什么呢？

之前是只提供 umd 包，我理解没办法修改代码。目前 2.0.0 版本提供了 umd/esm/cjs 三种类型的产物，应该是支持打补丁了。欢迎升级尝试
