### ISSUE TITLE
请问下如何在添加节点或者渲染节点的时候展示不同样式的边

### ISSUE THREAD

**Issue by yyqxjwxy** [didi/LogicFlow#888]
我们的业务需求是在添加或者渲染节点的时候要根据两个节点之间的关系展示不同的边样式例如不同的边颜色实现虚线：

**Comment by towersxu** [comment]
还是基于properties控制业务属性的思路，你可以监听边创建事件，然后通过此边的两个节点数据，动态设置边的properties。这样你就可以在model的getEdgeStyle中基于properties自定义不同的样式了。
