### ISSUE TITLE
增加修改连接线的交互功能

### ISSUE THREAD

**Issue by zyh374892663** [didi/LogicFlow#889]
是否可以增加修改连接线的交互功能，用来修改出入口的连接点例如：
![20221117174246](https://user-images.githubusercontent.com/33707926/202411942-34ddfaac-fb9b-4159-9a4e-17b7a2fb742b.gif)

**Comment by towersxu** [comment]
初始化配置中有一个`adjustEdgeStartAndEnd `, 你可以看看是否符合你的要求。
