### ISSUE TITLE
[Bug report]继承PolylineEdge，重写render时无法调用 super.render

### ISSUE THREAD

**Issue by zyh374892663** [didi/LogicFlow#890]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件：期望在折线的基础上进行扩展功能。保留折线调整能力，添加修改连接线功能。
2. 期望的表现：调用super.render正常渲染polyline，在polyline选中时切换另一条polyline进行拖动修改连接线
3. 实际的表现：报错
![image](https://user-images.githubusercontent.com/33707926/202426543-7f4aac30-8799-49d9-b6fe-50969d3560c2.png)

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
```js
class CustomPolylineEdgeView extends PolylineEdge {
    getEndArrow() {
        const { model } = this.props;
        let { stroke, strokeWidth } = this.getArrowStyle();
        let fill = "#000";
        if (model.isSelected) {
            fill = stroke ="#2e7de5";
        }
        const pathAttr = {
            fill,
            stroke,
            strokeWidth
        };
        return h('path', {
            ...pathAttr,
            d: 'M 0 0 -10 -5 -10 5 z'
        });
    }
    componentDidMount(): void {
        console.log(super.render);
        
    }
    render(): h.JSX.Element {
        return (
            <>
                {super.render()}
            </>
        );
    }
}
```

**Comment by towersxu** [comment]
可以试试参考https://github.com/didi/LogicFlow/blob/master/packages/extension/src/materials/curved-edge/index.ts 重写连线。
