### ISSUE TITLE
增加初始化lf实例时给插件透传参数的功能。

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#892]
目前对于一些插件的设置还是以静态方法或静态属性的方式支持，这样会出现一个页面多个设计器共用插件配置的情况。例如小地图的要支持设置宽高的参数，目前的写法是

```js
import { LogicFlow } from '@logicflow/core'
import { MiniMap } from '@logicflow/extension'

MiniMap.setOption({
  width: 300,
  height: 180
})

const lf = new LogicFlow({
   plugins: [ MiniMap ]
})
```

在`1.2.0`正式版本, 将支持插件参数传入到LogicFlow构造函数中

```js
import { LogicFlow } from '@logicflow/core'
import { MiniMap } from '@logicflow/extension'

const lf = new LogicFlow({
   plugins: [ MiniMap ],
   pluginsOptions: { 
      miniMap: {
         width: 200,
         height: 80
      }
   }
})
```

**Comment by wangzhengbo** [comment]
const lf = new LogicFlow({
   plugins: [
    [
      MiniMap, {
         width: 200,
         height: 80
      }
    ] 
  ]
})
用这种语法格式呢？是不是要简洁一些？babel plugin，eslint rule等的配置就是采用这种数组格式。


这里pluginsOption中的miniMap的跟插件的name对应起来的吧？
const lf = new LogicFlow({
   plugins: [ MiniMap ],
   pluginsOption: { 
      miniMap: {
         width: 200,
         height: 80
      }
   }
})

**Comment by towersxu** [comment]
@wangzhengbo 嗯，你的方案看起来更好。就用这个方案，欢迎PR。

**Comment by ChengDale** [comment]
更喜欢原作者的，表意明确一下

**Comment by wumail** [comment]
Logicflow.use新增了一个入参
``` ts
use(extension: Extension, props?: any): void;
```
第二个参数为对应插件内部需要的参数
