### ISSUE TITLE
[Bug report] 多选节点后不能取消选中某个节点

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#894]
多选10个节点后，想取消选中某一个节点，目前做不到。
或者画布4个角落和中间分别有一个节点，多选角落的4个节点后，还想同时选择中间的节点，也做不到。

因为目前多选后，会生成一个覆盖当前所选节点的矩形区域作为遮照层，导致了上面了问题。
Windows文件管理器里面的文件多选，就不会有上面的问题，这种多选方式易用性更好。

请问下，LogicFlow是否会考虑支持类似Windows文件管理器的多选方式呢？

**Comment by towersxu** [comment]
这个你可以试试能不能自定义插件来实现，欢迎PR

**Comment by wangzhengbo** [comment]
> 这个你可以试试能不能自定义插件来实现，欢迎PR

设置选项disabledTools: ['multipleSelect']是可以支持这个功能（不显示遮罩层），不过多选节点后，拖动其中一个，其它被选中的没有一起移动。我提了PR，支持了此功能。

**Comment by towersxu** [comment]
这个需要再考虑一下，能否做成draw.io那样，拖动选中的节点，所有选中的都一起移动一下。同时为了不影响之前的功能，是否可以做成一个新的插件，而不是在原插件上修改？
