### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by babydada** [didi/LogicFlow#899]
导出 Snapshot
lf.getSnapshot();

报错
"SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules"
 Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at Snapshot.getClassRules

**Comment by towersxu** [comment]
这个问题一般是全局样式中css内部有跨域影响导致的，可以使用自定义下载css来解决这个问题。http://logic-flow.org/guide/extension/snapshot.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8B%E8%BD%BDcss
