### ISSUE TITLE
Error in mounted hook: "Error: 找不到bpmn:sequenceFlow对应的边。“

### ISSUE THREAD

**Issue by 15982153332** [didi/LogicFlow#900]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件:将绘制的流程导出xml格式，再导入渲染，提示Error in mounted hook:"Error: 找不到bpmn:sequenceFlow对应的边。“边。
2. 期望的表现：正常渲染流程
3. 实际的表现："Error: 找不到bpmn:sequenceFlow对应的边。“

**最简复现demo**  
demoxml：
<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_13jbrfh" targetNamespace="http://bpmn.io/schema/bpmn" exporter="bpmn-js (https://demo.bpmn.io)" exporterVersion="7.3.0">
<bpmn:process id="Process_1v5ht41" isExecutable="false">
<bpmn:startEvent id="28ec6a87-faf8-47be-bd16-e9747087085a" backgroundColor="#FFFFFF">
<bpmn:outgoing>7b8dacf1-7f4e-42d1-bba5-e6d9dafa1cf3</bpmn:outgoing>
</bpmn:startEvent>
<bpmn:sendTask id="5552299d-f44f-4b72-bb99-492fd052675d">
<bpmn:incoming>7b8dacf1-7f4e-42d1-bba5-e6d9dafa1cf3</bpmn:incoming>
<bpmn:outgoing>bd2ebf36-68fe-430d-921b-d15db1349786</bpmn:outgoing>
</bpmn:sendTask>
<bpmn:receiveTask id="5b867246-800e-4362-9de2-2aabf857b55a">
<bpmn:incoming>bd2ebf36-68fe-430d-921b-d15db1349786</bpmn:incoming>
</bpmn:receiveTask>
<bpmn:sequenceFlow id="7b8dacf1-7f4e-42d1-bba5-e6d9dafa1cf3" sourceRef="28ec6a87-faf8-47be-bd16-e9747087085a" targetRef="5552299d-f44f-4b72-bb99-492fd052675d"/>
<bpmn:sequenceFlow id="bd2ebf36-68fe-430d-921b-d15db1349786" sourceRef="5552299d-f44f-4b72-bb99-492fd052675d" targetRef="5b867246-800e-4362-9de2-2aabf857b55a"/>
</bpmn:process>
<bpmndi:BPMNDiagram id="BPMNDiagram_1">
<bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1v5ht41">
<bpmndi:BPMNEdge id="7b8dacf1-7f4e-42d1-bba5-e6d9dafa1cf3_di" bpmnElement="7b8dacf1-7f4e-42d1-bba5-e6d9dafa1cf3">
<di:waypoint x="420" y="200"/>
<di:waypoint x="420" y="250"/>
<di:waypoint x="430" y="250"/>
<di:waypoint x="430" y="300"/>
</bpmndi:BPMNEdge>
<bpmndi:BPMNEdge id="bd2ebf36-68fe-430d-921b-d15db1349786_di" bpmnElement="bd2ebf36-68fe-430d-921b-d15db1349786">
<di:waypoint x="430" y="440"/>
<di:waypoint x="430" y="470"/>
<di:waypoint x="605" y="470"/>
<di:waypoint x="605" y="270"/>
<di:waypoint x="780" y="270"/>
<di:waypoint x="780" y="300"/>
</bpmndi:BPMNEdge>
<bpmndi:BPMNShape id="28ec6a87-faf8-47be-bd16-e9747087085a_di" bpmnElement="28ec6a87-faf8-47be-bd16-e9747087085a">
<dc:Bounds x="400" y="130" width="40" height="40"/>
</bpmndi:BPMNShape>
<bpmndi:BPMNShape id="5552299d-f44f-4b72-bb99-492fd052675d_di" bpmnElement="5552299d-f44f-4b72-bb99-492fd052675d">
<dc:Bounds x="380" y="330" width="100" height="80"/>
</bpmndi:BPMNShape>
<bpmndi:BPMNShape id="5b867246-800e-4362-9de2-2aabf857b55a_di" bpmnElement="5b867246-800e-4362-9de2-2aabf857b55a">
<dc:Bounds x="730" y="330" width="100" height="80"/>
</bpmndi:BPMNShape>
</bpmndi:BPMNPlane>
</bpmndi:BPMNDiagram>
</bpmn:definitions>

**Comment by towersxu** [comment]
logicflow不是开箱即用的流程图框架，需要你自己注册对应的节点和边。
