### ISSUE TITLE
自定义问题节点---菱形宽高不知道怎么设置

### ISSUE THREAD

**Issue by pikachuWorld** [didi/LogicFlow#902]
**问题描述**  
关于菱形实现效果图如下，但是官网的例子都是矩形，其他的都实现了，唯独这个菱形没有实现
<img width="655" alt="屏幕快照 2022-11-24 23 00 54" src="https://user-images.githubusercontent.com/21151422/203814894-79600b94-8f9d-4298-8fcb-813a7a5572b1.png">
下面我的代码 ，我看棱形svg还是多边形实现的，宽高怎么改小呀？

<img width="625" alt="屏幕快照 2022-11-24 22 53 46" src="https://user-images.githubusercontent.com/21151422/203815511-90cbc38c-235e-4d11-ad3d-b012674369d0.png">

**Comment by shanquanyaoyue** [comment]
```js
setAttributes() {
    this.rx = 85;
    this.ry = 85;
}
```

**Comment by pikachuWorld** [comment]
> ```js
> setAttributes() {
>     this.rx = 85;
>     this.ry = 85;
> }
> ```
找到问题了我之前继承类不对,应该继承多边形PolygonNodeModel
class DiamondTaskModel extends PolygonNodeModel {
    setAttributes () {
      
        this.rx = 25;
        this.ry = 25;
}
}
