### ISSUE TITLE
[Feature] 支持调整边连接的节点

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#905]
画布中一条边连接了A、B 2个节点，想动态调整边连接到A、C 2个节点，也就是通过拖拽边的尾端动态调整连接到目标节点C，请问目前是否支持？如果不支持，是否有计划考虑支持呢？

**Comment by shanquanyaoyue** [comment]
adjustEdgeStartAndEnd设置为true

**Comment by wangzhengbo** [comment]
> 

多谢，我试下
