### ISSUE TITLE
通过自定义的箭头，如何自适应线的变化角度？

### ISSUE THREAD

**Issue by aweirdocc** [didi/LogicFlow#906]
线在挪动位置的时候，想要箭头也随着适应转动。
![image](https://user-images.githubusercontent.com/74596152/204200573-a53be406-6cba-4f1c-9467-1d5fb30ccb94.png)

![image](https://user-images.githubusercontent.com/74596152/204190701-b5f1f052-e685-4bc1-87af-e565e9e00f0a.png)

**Comment by towersxu** [comment]
你是如何自定义的呢？如果使用我们新的自定义箭头API，应该不会有这个问题。因为最终对应的是svg的markerEnd。
