### ISSUE TITLE
希望在dnd-panel添加自定义事件，例如doubleClick

### ISSUE THREAD

**Issue by shanquanyaoyue** [didi/LogicFlow#907]
dnd-panel可能有额外场景，例如双击快速在中间位置添加节点，或其他一些事件，使得dnd-panel功能更强一些

**Comment by shanquanyaoyue** [comment]
或支持icon和label类型是ReactNode，优点1：可对其事件进行扩展。优点2：icon不再局限base64，可通过交互修改icon样式，UI扩展性更强

**Comment by shanquanyaoyue** [comment]
https://github.com/didi/LogicFlow/pull/909

**Comment by shanquanyaoyue** [comment]
https://github.com/didi/LogicFlow/pull/910

**Comment by towersxu** [comment]
感谢PR， 最近可能没时间对功能测试，会晚点发版。
