### ISSUE TITLE
properties添加业务属性数组对象 出现xx，tree的报错

### ISSUE THREAD

**Issue by kzhzjdyw888** [didi/LogicFlow#908]
**问题描述**  
properties添加业务属性数组对象 出现xx，tree的报错

![Uploading a5bb0e044348af244b62a74f3ab2142.jpg…]()
![Uploading fb694e9164952f9e78d3a81b4360f4a.png…]()

**Comment by towersxu** [comment]
请确认properties中的内容为“纯”对象，不能是响应式对象。可以先将传入properties的内容JSON.stringify, JSON.parse试试。
