### ISSUE TITLE
groupModel分组折叠按钮换成好看一点背景有没有例子

### ISSUE THREAD

**Issue by pikachuWorld** [didi/LogicFlow#914]
1. 期望的表现

➕ ➖展开收起想换好看一点背景,官网有没有现成demo例子可以参考一下不知道怎么替换,按照之前步
按照  骤3: 自定义节点view
http://logic-flow.org/guide/basic/node.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%80%E4%B8%AA%E4%B8%9A%E5%8A%A1%E8%8A%82%E7%82%B9
返回h报错
2. 实际的表现
<img width="443" alt="屏幕快照 2022-11-30 21 20 13" src="https://user-images.githubusercontent.com/21151422/204807433-78bccb96-12e4-490c-81ab-e60d13bcf7ec.png">

<img width="129" alt="屏幕快照 2022-11-30 21 20 25" src="https://user-images.githubusercontent.com/21151422/204807421-f3111bef-f916-4fea-b6db-17d2f34ed35e.png">

**Comment by towersxu** [comment]
参考自定义节点，你可以基础group节点再次自定义
