### ISSUE TITLE
[Improvment] 边的选择应该适当的增加热区，降低选中边的难度

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#920]
实际效果：
边线条在比较细的情况下，要选中边很困难，鼠标指定必须悬浮在边上才能点击选中，这样操作起来有些困难。
将边的线条加粗可以增加选中的容易程度，但是太粗的边，效果不好看。

期望的效果：
边的周围能设置透明背景（比如边是20px粗，那么中间2px是带颜色的，边上18px是透明的），这样在视觉上，边
只有2px粗细，但是实际的粗细是20px，能增加可点击的热区，更好的让用户选中。

**Comment by towersxu** [comment]
目前应该是有的，源码中的appendWidth，你看看

**Comment by wangzhengbo** [comment]
> 目前应该是有的，源码中的appendWidth，你看看

多谢！试了可以用。
