### ISSUE TITLE
分组节点开启resizable后如何设置手动调整的最大宽和最大高？

### ISSUE THREAD

**Issue by Liu-Peter** [didi/LogicFlow#923]
分组节点开启resizable后如何设置手动调整的最大宽和最大高？

**Comment by towersxu** [comment]
分组是基础NodeResize开发，可以参考http://logic-flow.org/guide/extension/extension-node-resize.html#%E8%AE%BE%E7%BD%AE%E6%94%BE%E5%A4%A7%E7%BC%A9%E5%B0%8F%E7%9A%84%E6%9C%80%E5%A4%A7%E6%9C%80%E5%B0%8F%E5%80%BC
