### ISSUE TITLE
logicFlow有销毁实例的方法吗？官网没找到

### ISSUE THREAD

**Issue by y-zhangbo** [didi/LogicFlow#924]
logicFlow集成到antd Modal弹窗组件中，查看画布节点均正常。但是刷新浏览器后，再次打开，发现画布网格丢失、渲染组件样式也错乱，怀疑是实例占用内存导致的

**Comment by towersxu** [comment]
目前没有发现logicFlow内存泄露的问题，你这个看起来像是你自己代码中可能存在问题，建议再排查一下。如果有可复现的示例，欢迎带上示例提PR
