### ISSUE TITLE
getSnapshot 方法 自定义的HTML节点（使用的VUE） 里面的图片无法导出

### ISSUE THREAD

**Issue by XM-GO** [didi/LogicFlow#925]
导出的节点显示如下，图片不显示
![2e18729045155236b18053cca5ef5b0](https://user-images.githubusercontent.com/93296511/206099803-359acaa6-bc53-4221-b9cb-124a094a45f2.png)

**Comment by towersxu** [comment]
目前确是有这个问题，只有HTML节点中的图片是url地址，导出的时候就会不生效。你可以先将url地址转换为base64格式的图片，这样就会没有问题。
