### ISSUE TITLE
[Bug report] 开启adjustEdgeStartAndEnd功能后，调整边连接的节点时校验问题

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#926]
将adjustEdgeStartAndEnd配置设置为true后，可以调整边连接的节点，碰到如下2个问题：

1. 在调整的时候如果违反了sourceRules或者targetRules中定义的约束条件，没有抛出connection:not-allowed事件，而正常的方式连接2个节点违反了约束时，会抛出connection:not-allowed事件。（业务代码中需要监听connection:not-allowed事件，拿到错误信息并提示给用户）

2. 有时候一个节点可以连接的前序或者后续节点，除了有节点类型限制外，还有数量限制。比如起始节点后面只能连一个节点，不能连多个。如果起始节点A已经连接了节点B的情况下，需要调整边，改成连接到C，这个时候在sourceRules或者targetRules的rule的validate函数中，只能拿到起始节点，锚点，结束节点，锚点的信息，并不清楚是边的修改操作。如果完全当成是添加一条新的边来校验，A -> C是校验通不过的，因为已经有A -> B了，违反了A之后只能有一个后续节点的约束。
期望在rule的validate函数中能提供参数，标识如果校验通过，将会删除的边的相关信息。

**Comment by towersxu** [comment]
嗯，确实有这个问题，也感谢PR。这个问题有点复杂，我们需要再确认一下，晚点合并。

**Comment by towersxu** [comment]
@wangzhengbo #936 这个PR应该是为了解决上面的第2点问题对吧？

**Comment by towersxu** [comment]
@wangzhengbo #936 这个PR应该是为了解决上面的第2点问题对吧？

**Comment by towersxu** [comment]
@wangzhengbo #936 这个PR应该是为了解决上面的第2点问题对吧？
```js
initNodeData(data) {
    super.initNodeData(data);

    const onlyOneOutgoing = {
      message: "节点类型A只允许一个目标节点",
      validate: (sourceNode, targetNode, sourceAnchor, targetAnchor, adjustInfo) => {
        return targetNode.type === "circle";
      },
    };
    this.sourceRules.push(circleOnlyAsTarget);
  }
```
节点的`isAllowConnectedAsSource`增加的adjustInfo这个参数存在一定的解释成本，毕竟最常用的可能还是新建连线而不是调整连线。

**Comment by towersxu** [comment]
@wangzhengbo #936 这个PR应该是为了解决上面的第2点问题对吧？有个这个PR后，实现上面的需求代码应该如下：
```js
initNodeData(data) {
    super.initNodeData(data);

    const onlyOneOutgoing = {
      message: "节点类型A只允许一个目标节点",
      validate: (sourceNode, targetNode, sourceAnchor, targetAnchor, adjustInfo) => {
        const edges = this.graphModel.getNodeOutgoingEdge()
        if (edges.length >= 1 && edges.indexOf(adjustInfo.edgeIndex) !== 0) return false
        return true
      },
    };
    this.sourceRules.push(circleOnlyAsTarget);
  }
```
这里有一点问题，adjustInfo中的adjustSourcePoint看起来不是必须的，是否只传edgeId就可以，这样相比adjustInfo会减少很多解释成本。

**Comment by wangzhengbo** [comment]
> @wangzhengbo #936 这个PR应该是为了解决上面的第2点问题对吧？有个这个PR后，实现上面的需求代码应该如下：
> 
> ```js
> initNodeData(data) {
>     super.initNodeData(data);
> 
>     const onlyOneOutgoing = {
>       message: "节点类型A只允许一个目标节点",
>       validate: (sourceNode, targetNode, sourceAnchor, targetAnchor, adjustInfo) => {
>         const edges = this.graphModel.getNodeOutgoingEdge()
>         if (edges.length >= 1 && edges.indexOf(adjustInfo?.edgeIndex) !== 0) return false
>         return true
>       },
>     };
>     this.sourceRules.push(circleOnlyAsTarget);
>   }
> ```
> 
> 这里有一点问题，adjustInfo中的adjustSourcePoint看起来不是必须的，是否只传edgeId就可以，这样相比adjustInfo会减少很多解释成本。

@towersxu 确实是这样的，我代码中的校验可以去掉adjustSourcePoint依赖。那adjustInfo类型改成这样行不行？
```typescript
adjustInfo?: {
            edgeId: string;
}
```

**Comment by towersxu** [comment]
@wangzhengbo 要不就直接传edgeId?参数说明一下这个在开启`adjustEdgeStartAndEnd`后会传入。然后带上这个issue

**Comment by wangzhengbo** [comment]
> @wangzhengbo 要不就直接传edgeId?参数说明一下这个在开启`adjustEdgeStartAndEnd`后会传入。然后带上这个issue

可以

**Comment by oe** [comment]
遇到同样问题了, 还准备动手再提个PR的..

请问啥时候发版呢?

**Comment by towersxu** [comment]
已发布到1.2.0-next.2
