### ISSUE TITLE
请教：如何关闭双击节点时默认会出现的updateText的那个事件？

### ISSUE THREAD

**Issue by yangyjxm** [didi/LogicFlow#927]
如何可以关闭双击节点时默认会出现的updateText的那个事件？就是节点下方会出现编辑框的事件。因为我自定义了双击事件了，这个编辑框和我定义的事件有点重复了。

**Comment by towersxu** [comment]
可以直接配置节点不开启双击编辑，http://logic-flow.org/api/logicFlowApi.html
