### ISSUE TITLE
[Bug report]自定义react节点要点 2 下才能删除节点

### ISSUE THREAD

**Issue by yoyooyooo** [didi/LogicFlow#933]
**问题描述**  
点一下后按删除没用，要再点一下按删除才能删掉节点，点一下的时候也没触发node:delete事件

**最简复现demo**  
[codesanbox](https://codesandbox.io/s/thirsty-sea-clxqek?file=/src/box.css)

**Comment by Spongebobo** [comment]
我也遇到同样的问题了。
删除后，撤销也无效。需要先点击一下画布，才能撤销。
我猜测应该是选中状态还在，无法撤销

**Comment by yoyooyooo** [comment]
> 我也遇到同样的问题了。 删除后，撤销也无效。需要先点击一下画布，才能撤销。 我猜测应该是选中状态还在，无法撤销

我怀疑是和foreignObject内部的自定义html第一次没触发事件
