### ISSUE TITLE
[Bug report]：缩放分组时锚点未跟随移动

### ISSUE THREAD

**Issue by wakanuli** [didi/LogicFlow#938]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/93758404/206956227-7f1ffebd-2f58-4bc4-9b7e-ef28aa28fb0e.png">
控制右上角定位点向左缩小分组时，分组两侧锚点未同步

**Comment by towersxu** [comment]
确认一下是否是自定义的锚点位置不在边上？

**Comment by wakanuli** [comment]
将官网示例锚点去掉透明化就能复现

**Comment by towersxu** [comment]
去掉透明化是什么意思呢？能否提供codesandbox示例？

**Comment by towersxu** [comment]
可以参考这个示例https://codesandbox.io/s/logicflow-base24-forked-c0tsud?file=/step_24_group/MyGroup.js
