### ISSUE TITLE
拖拽连线的时候怎么保持连线的起点和终点不变？

### ISSUE THREAD

**Issue by camellieeee** [didi/LogicFlow#939]
折线的时候，拖拽两个节点间的连线，有什么方式可以保持锚点不变吗？也就是连线起点和终点不变。

**Comment by wyd2015** [comment]
同问，这个虽然说拖拽线条时线的源锚点和目标锚点id不会发生变化，但视图上却会连接到其他（最上方或最下方）锚点，api翻了一遍没找到可以控制的地方

**Comment by towersxu** [comment]
@camellieeee 初始化参数中有个adjustEdgeStartAndEnd，这个参数设置为true则可以让和锚点相连的线段不能调整。
