### ISSUE TITLE
[Request feature] Mode readonly and on change event?

### ISSUE THREAD

**Issue by nbao** [didi/LogicFlow#941]
Hi,
Can I ask you a question, please?
There is a configuration variable to tell logicFlow in read-only mode, that the visitor cannot move or edit the text?
I use CDN!
is there onchange event ? when I change text or move node, i just want to get data and save in hidden field, if yes can you show me some exemple please.
Thanks

**Comment by towersxu** [comment]
You can use `isSilentMode` as read-only mode. 
And  about logic-flow event docs you can see http://logic-flow.org/api/eventCenterApi.html#%E8%8A%82%E7%82%B9%E4%BA%8B%E4%BB%B6
