### ISSUE TITLE
[Bug report]选中节点后删除，发现要点击两次，才能删除。

### ISSUE THREAD

**Issue by Spongebobo** [didi/LogicFlow#942]
第一次点击，删除无效。
![image](https://user-images.githubusercontent.com/22763696/207753478-1f6a8aa2-e902-40c1-ad57-e42c1a88eb9a.png)
第二次点击后出现蓝色边框，这个时候删除有效。
![image](https://user-images.githubusercontent.com/22763696/207753609-c6c7dba8-9d65-4156-9cd7-89ab4a727ef4.png)

**Comment by towersxu** [comment]
此问题已在1.2.1版本修复

**Comment by Echonessy** [comment]
有解决吗

**Comment by wumail** [comment]
> 有解决吗

目前只有解决办法

**Comment by Echonessy** [comment]
已解决
```
 useEffect(() => {
    try {
      const selectedElement = document.querySelector(
        '.lf-node-selected foreignObject',
      ) as HTMLElement;
      selectedElement?.focus();
    } catch (e) {}
  }, [activeId?.current]);
```
