### ISSUE TITLE
[Improvment] 希望能支持优化布局排版的功能，类似自动布局的能力

### ISSUE THREAD

**Issue by Spongebobo** [didi/LogicFlow#946]
![image](https://user-images.githubusercontent.com/22763696/207816027-2d888242-2bb8-4650-80cc-822dba1fee19.png)

连完线后，比较乱，希望能有各功能自动布局，更加美观。

**Comment by towersxu** [comment]
目前我们并没有找到完美的布局方案，你可以参考这篇文章，寻找符合你们自己要求的布局算法。https://juejin.cn/post/7145653979119091720
