### ISSUE TITLE
[Bug report]连线时，调用edgeModel.points和edgeModel.pointsList不准确问题

### ISSUE THREAD

**Issue by shanquanyaoyue** [didi/LogicFlow#948]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件 打开`minimap`，并拖动画布。两个节点连线时，触发了`minimap render`时，订阅的 `history:change`事件，该事件触发了 `__setView`函数，该函数内部执行了`__resetData`函数，函数内部根据在拿到画布偏移量后，对`edge.startPoint`、`edge.endPoint`、`edge.pointsList`等数据进行变更，导致数据不一致。
2. 期望的表现 连线时，`edge.startPoint`、`edge.endPoint`、`edge.pointsList`等数据不再变更
3. 实际的表现 `edge.startPoint`、`edge.endPoint`、`edge.pointsList`等数据发生变更，数据有误，且多次执行 `CustomPolylineModel`中`initEdgeData`，函数内部`this`数据不一致

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
![1RPR}1%0TWHVL%FN8Y}% OV](https://user-images.githubusercontent.com/111632046/207837309-6169dd9c-07b2-4e46-b9fc-2814c59340d6.png)

**Comment by shanquanyaoyue** [comment]
https://codesandbox.io/s/logicflow-base25-forked-vmwt55?file=/step_25_customEdgeTextPosition/index.js
先拖动画布，后新增节点并连线，log信息中可观察到

**Comment by shanquanyaoyue** [comment]
![20221215185555_rec_](https://user-images.githubusercontent.com/111632046/207841832-4494f979-0093-4121-8350-f827907021f6.gif)

**Comment by towersxu** [comment]
因为这里的连线是小地图中的连线，后面可以考虑在小地图中不显示连线。
