### ISSUE TITLE
[Bug report] 调整边连接的节点时如果做了取消可能还会触发edge:exchange-node事件

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#950]
选中边后，会显示边2端的锚点，通过拖拽锚点可以修改边连接的节点。但是如果用户在拖拽过程中想放弃修改：
1. 在画布空白处释放，此时会还原边的位置，不会触发edge:exchange-node事件；
2. 在原锚点处释放，此时会删除原边，创建新边，触发edge:exchange-node事件(此时原边和新边实际上连接的2个完全一样的节点和一样的节点上的锚点)，在用户看来没有做任何修改，此时的逻辑处理应该和在画布空白处释放做一样的处理更合理；

**Comment by towersxu** [comment]
感谢PR，已合并到master
