### ISSUE TITLE
[Bug report]LogicFlow  的H5端(移动端，mobile)的 不支持touch事件

### ISSUE THREAD

**Issue by zhuangxiaohui** [didi/LogicFlow#955]
**问题描述**  
1. 问题触发的条件
   H5端 不支持touch事件
2. 期望的表现
    H5端 能 移动画出的图
3. 实际的表现
     H5端 不能 移动画出的图

**Comment by towersxu** [comment]
目前LogicFlow不支持移动端，主要是目前内部还是主要用的mousedown、mouseup这些事件。后续版本可以考虑支持。

**Comment by zhuangxiaohui** [comment]
什么时候支持啊，比较急了

**Comment by towersxu** [comment]
@zhuangxiaohui 短期内应该支持不了，建议看看其他开源项目。

**Comment by jackshang** [comment]
现在2.3还是不支持touch事件 和 移动画出的图 吗？
