### ISSUE TITLE
[Bug report]拖拽元素到顶部，继续拖拽出现异常

### ISSUE THREAD

**Issue by chenweihan** [didi/LogicFlow#956]
官网demo地址  http://logic-flow.org/usage/bpmn.html
选择2个用户任务，当拖拽一个往上到顶部，继续拖拽，另一个直接往下了，有点不符合操作。 

期望：拖到顶部就OK了，拖拽画布往上留白后，又可以继续拖拽。

**Comment by towersxu** [comment]
这个是默认开启的自动扩展画布范围功能，配置是autoExpand。可以通过设置为false来关闭这个功能。
