### ISSUE TITLE
[Bug report] node:click事件有延迟

### ISSUE THREAD

**Issue by viewhang** [didi/LogicFlow#96]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件：点击节点的响应事件有延迟
2. 期望的表现：点击完立马有效果
3. 实际的表现：点击完有0.5秒左右延迟

**环境信息描述**  
至少包含以下部分：
windows10 chrome  89.0.4389.90

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
[官方文档示列代码](http://logic-flow.org/usage/approve.html#%E5%88%9B%E5%BB%BA%E5%AE%A1%E6%89%B9%E8%8A%82%E7%82%B9)
![screen](https://user-images.githubusercontent.com/26957298/113080340-5a2a1380-9209-11eb-9af5-e7846071261c.gif)

**Comment by ouzhou** [comment]
确实很慢

**Comment by towersxu** [comment]
此问题已修复
