### ISSUE TITLE
[Bug report] 文档：边上插入节点 InsertNodeInPolyline示例无法显示并且报错 TypeError: Cannot read properties of null (reading 'x')

### ISSUE THREAD

**Issue by yj-liuzepeng** [didi/LogicFlow#960]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件  文档示例无法显示 [边上插入节点 InsertNodeInPolyline](http://logic-flow.org/guide/extension/extension-insert-node-in-polyline.html#%E5%8A%9F%E8%83%BD)
2. 期望的表现 正常显示，没有报错
3. 实际的表现 无法显示，报错 **TypeError: Cannot read properties of null (reading 'x')**

**最简复现demo**  
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/75007029/209498880-a26b74b1-a221-4ec0-b5d3-21c2fabf7221.png">
__

**Comment by towersxu** [comment]
感谢[PR](https://github.com/didi/LogicFlow/pull/961)，已合并。
