### ISSUE TITLE
[Feature Request] 创建了一个group，当组里的一个节点拖动时，如何让整个组一起动？

### ISSUE THREAD

**Issue by aweirdocc** [didi/LogicFlow#962]
目前我是通过绑定事件去移动的组里的节点的，但效果不是很好，还有其它实现方法吗？

**Comment by aweirdocc** [comment]
![image](https://user-images.githubusercontent.com/74596152/209639373-2e69ba7e-7aed-4633-8ef4-9568b5748713.png)
例如这样的结构

**Comment by towersxu** [comment]
不确定你的需求。你试试看看能不能将属于分组的节点设置为不允许移动操作，然后直接移动整个分组。要是不行，就需要你自己参考group插件源码，重新写一个新的分组插件了。
