### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by readwarf** [didi/LogicFlow#963]
after run `npm run build` at the top and install to local at `master` branch (v1.1.31).
will show this error with extension
Can't resolve 'lodash-es'

please add `lodash-es` to `package.json` to avoid this error

**Comment by towersxu** [comment]
Hello, Do you use package @logicflow/core? In @logicflow/core, we only support umd modules which not need lodash-es. So can you give a example project to help us find the real problem?

**Comment by readwarf** [comment]
Yes, I use both of @logicflow/core and @logicflow/extension.
the @logicflow/extension package build and there is `import { throttle } from 'lodash-es';` at `packages/extension/es/components/mini-map/index.js` at line 12.

https://github.com/didi/LogicFlow/blob/master/packages/extension/src/components/mini-map/index.ts#L1

I use this with nuxtjs project. and `packages/extension/package.json` has module entry `"module": "es/index.js",`

(besides older version v1.1.30 doesn't has this problem because it doesn't require `lodash-es` at all.
https://github.com/didi/LogicFlow/blob/%40logicflow/extension%401.1.30/packages/extension/src/components/mini-map/index.ts
)
