### ISSUE TITLE
[Bug report] 2个组件，如何再组件一渲染的时候加载组件二

### ISSUE THREAD

**Issue by z-lionel** [didi/LogicFlow#966]
现在是想一个如图的组合结构，通过官方示例这样去组合去移动。数据结构如下。
现在是想通过修改properties里面的answers动态调节按钮的个数。
现在是大的组件里面的initNodeData 方法里面 this.graphModel.addNode去添加按钮，
问题是需要通过settimeout做个延迟才会渲染，请问有什么更好的方法达到这个效果

```
  properties: {
        title: "你好",
        answers: [
          { id: "1", text: "否定" },
          { id: "2", text: "肯定" },
          { id: "3", text: "默认" }
        ]
      }

```

```
    logicflow.graphModel.addNodeMoveRules((model, deltaX, deltaY) => {
      if (model.isGroup && model.children) {
        // 如果移动的是分组，那么分组的子节点也跟着移动。
        logicflow.graphModel.moveNodes(model.children, deltaX, deltaY, true);
      }
      return true;
    });

```

![image](https://user-images.githubusercontent.com/37678805/210042234-c9f516a6-9350-4cff-8a9e-71f87bea7301.png)

**Comment by towersxu** [comment]
logicflow思路是数据中的节点就对应着真实看到的节点，所以不建议出现显示A节点的时候自动在图上显示B节点。你这种情况建议直接用一个节点来实现，可以在自定义节点的getShape时判断answer来做处理。

**Comment by z-lionel** [comment]
> logicflow思路是数据中的节点就对应着真实看到的节点，所以不建议出现显示A节点的时候自动在图上显示B节点。你这种情况建议直接用一个节点来实现，可以在自定义节点的getShape时判断answer来做处理。

请问A节点的getShape方法里面能渲染自定义的B节点类型吗？
