### ISSUE TITLE
开启adjustEdge配置后，拖动边能否像拖动节点一样，以网格作为最小移动单位

### ISSUE THREAD

**Issue by chengjiashuai** [didi/LogicFlow#967]
边上插入节点功能体验：
现在移动边后，如果边不在网格线上，由于节点是以网格为最小移动单位，就会导致节点怎么移动都无法插入到边上

**Comment by towersxu** [comment]
此功能已在1.2版本优化，现在会在拖动节点到边时，节点中心只要靠近(10px之内)连线就会实现节点插入到边上。
