### ISSUE TITLE
请问如何动态修改连线的位置

### ISSUE THREAD

**Issue by z-lionel** [didi/LogicFlow#971]
如下面两张图，demo是官方提供的，现在我动态删除了个锚点，我可以找到这个锚点的连线动态删除
但是原来的连线需要修改位置，有什么方法可以修改？或者有什么更好的实现方式？

![image](https://user-images.githubusercontent.com/37678805/210315653-cf7851f8-0c73-4170-ab03-c0da0fdd760a.png)

![image](https://user-images.githubusercontent.com/37678805/210316073-1be1dd19-4d74-4218-9856-38a13100c6f6.png)

**Comment by towersxu** [comment]
连线位置只有自己计算连线开始坐标和结束坐标了
