### ISSUE TITLE
angular版本demo，官方没有参考demo，现在他来了

### ISSUE THREAD

**Issue by chenweihan** [didi/LogicFlow#972]
抽空做了一个angular版本的demo入门版本   github https://github.com/chenweihan/logicflow-angular

**Comment by towersxu** [comment]
这个好！请问有时间参考[https://github.com/hsole/layoutFlow](https://github.com/hsole/layoutFlow)，用github pages做一个可在线演示的效果吗？然后可以带上截图和在线地址更新到LogicFlow的readme中

**Comment by chenweihan** [comment]
No problem

**Comment by chenweihan** [comment]
github pages 的地址：https://chenweihan.github.io/logicflow-angular/bpmn

![image](https://user-images.githubusercontent.com/1927864/211807908-92714aa2-a0b1-4a2f-a6fa-2a3a590a0e68.png)

项目地址：https://github.com/chenweihan/logicflow-angular

因个人没有流程图开发的需求，纯感兴趣弄弄，项目使用场景不够复杂，图标也没有美化，只能算是angular版本入门级别。但是参考demo后，自己修改是完全没有问题的。

**Comment by towersxu** [comment]
感谢提供示例！

**Comment by wumail** [comment]
#884
