### ISSUE TITLE
[Bug report] 在调整边连接的节点后，偶现新的边不能被点击选择

### ISSUE THREAD

**Issue by wangzhengbo** [didi/LogicFlow#974]
在调整边连接的节点后，偶现新的边不能被点击选择。在AdjustPoint.tsx中，onDragStart的时候会设置edgeModel.isHitable = false;，
onDragEnd的时候会设置edgeModel.isHitable = true;
偶尔出现不能被选择，所以我怀疑有如下可能：
1. onDragEnd中的edgeModel.isHitable = true没有执行到; 
或者
2. edgeModel.isHitable = true执行了，但是edge没有重新render，还是处于isHitable=false的状态。
看源码没看出来有啥问题，而且也没找到复现的规律，并不是很容易复现。

另外AdjustPoint.tsx中对edgeModel.isHitable的修改没看明白有什么意图，去掉这个处理就可以避免出现边不能拖拽的问题。

**Comment by wangzhengbo** [comment]
lf-edge.pointer-none {
   pointer-events: auto !important;
}
目前我是通过覆写css避免这个问题的。

**Comment by towersxu** [comment]
我试了一下，这里的 edgeModel.isHitable 可以去掉。以前这里应该为什么加这个我也记不清了，有可能是通过设置 obserable 属性isHitable，强制触发edge的渲染。欢迎PR把这个去掉，并在注释中带上此issue。
