### ISSUE TITLE
分组节点出现节点收起失败的问题

### ISSUE THREAD

**Issue by waht123** [didi/LogicFlow#975]
判断节点是否可以移入时是没问题的,但当开启了group内部节点不能移出的api isRestrict后,当不能移入的节点存在组内时,鼠标弹起的最后一次结果是false,会导致已存在group内部的节点被移出了

**Comment by towersxu** [comment]
可以提供一个示例吗？目前看描述并不能清楚的知道是什么问题

**Comment by waht123** [comment]
![20220803_185346 00_00_00-00_00_31](https://user-images.githubusercontent.com/39727546/210550839-ad204cad-73f6-48b9-8db5-0718b81bcd48.gif)

**Comment by waht123** [comment]
我们可以简单的任务名为逻辑的节点为不可移入的节点,当组外的逻辑节点移入不到组内是可行的,同样的代码在组内的名为逻辑的节点移动是满足不可以移出组外的,但是鼠标弹起的瞬间isAllowAppendIn返回的最后一次结果是false,导致节点被移出了

**Comment by towersxu** [comment]
我这边无法复现这个问题，请问可以提供codesandbox示例吗？
