### ISSUE TITLE
[Bug report]调整连线接入连出点，text不跟随连线调整位置

### ISSUE THREAD

**Issue by shanquanyaoyue** [didi/LogicFlow#982]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件 组件连线后，连线有text内容，位置为连线居中，修改连线接入点或连出点
2. 期望的表现 text跟随连线位置进行调整
3. 实际的表现 text在原有位置，当连线调整后才变更text位置

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
https://codesandbox.io/s/logicflow-base25-forked-ww984i?file=/step_25_customEdgeTextPosition/index.js

**Comment by towersxu** [comment]
感谢PR，已合并到master
