### ISSUE TITLE
鼠标移入是否可以显示文字全部？

### ISSUE THREAD

**Issue by Oliwans** [didi/LogicFlow#984]
nodeText的主题设置overflowMode: 'ellipsis'后，可以正常显示单行省略...的效果，是否支持鼠标移入节点或鼠标移入文字显示文字全称？

**Comment by towersxu** [comment]
这个暂时不考虑，因为文字的长度不定，太长了直接显示也不美观。如果有显示全部的需求，可以考虑自定义节点，通过isHovered属性来处理。例如鼠标移动到节点上弹出一个popover这类。
<img width="152" alt="image" src="https://user-images.githubusercontent.com/4093984/211988646-2259b957-c6a3-406d-b6cf-ec3ff12906ec.png">

**Comment by ZhangMingZhao1** [comment]
@Oliwans 

原生dom title标签 以tool tip的形式提示显示全文，这种效果满不满足你们的需求，如下图：

<img width="310" alt="image" src="https://user-images.githubusercontent.com/29058747/212069765-7742a7f3-7428-4125-931d-060752bfa5fc.png">
#992

**Comment by towersxu** [comment]
已发布到[v1.2.0-next.2](https://www.npmjs.com/package/@logicflow/core/v/1.2.0-next.2)
