### ISSUE TITLE
extension包中提供带图标的节点

### ISSUE THREAD

**Issue by songsgroup** [didi/LogicFlow#988]
能不能内置一个类型，可以传入svg或者图片，默认就可以有锚点等。这样基本能解决绝大部分的应用，现在的几个类型感觉挺少的。想换个图标或者svg都不行，这样就实用多了。

**Comment by towersxu** [comment]
目前LogicFlow核心思路还是通过自定义节点来实现。为了保证core的扩展性，core包中只提供了基础节点。后续可以考虑在extension包中增加更多有特色的节点。欢迎大家在extension包中PR。

**Comment by wumail** [comment]
重口难调，需求各异，还是把实现交给开发者自己
